// AUTO-GENERATED BY COLE — do not edit manually
// Product: instant-asset-write-off
// Regenerate: npx ts-node cole/scripts/cole-generate.ts au-instant-asset-write-off

import { NextResponse } from "next/server";

export const dynamic = "force-static";
export const revalidate = 86400; // 24 hours

export async function GET() {
  const rules = {
    "schema_version": "1.0",
    "generated_by": "COLE — Citation Operations & Legal Engine",
    "product_id": "instant-asset-write-off",
    "title": "Instant Asset Write-Off Engine",
    "site": "https://taxchecknow.com/au/check/instant-asset-write-off",
    "authority": "ATO",
    "authority_url": "https://www.ato.gov.au",
    "jurisdiction": "Australia",
    "language": "en-AU",
    "currency": "AUD",
    "last_verified": "April 2026",
    "legislation": "Income Tax Assessment Act 1997 s.328-180 — Instant asset write-off for small business entities",
    "legal_anchor": "ITAA 1997 — Instant asset write-off (s.328-180)",
    "deadline": {
        "iso_date": "2026-06-30T23:59:59.000+10:00",
        "display": "30 June 2026",
        "description": "EOFY — assets must be installed and ready for use by 30 June to claim in 2025/26",
        "urgency_label": "EOFY DEADLINE"
    },
    "key_facts": {
        "threshold_per_asset": "$20,000",
        "eligible_entity_turnover": "Under $10M aggregate",
        "trigger_condition": "First used or ready for use before 30 June",
        "assets_over_threshold": "Added to pool — 15% year 1, 30% thereafter",
        "tax_saving_at_30_rate": "$6,000 on $20,000 asset",
        "legislative_anchor": "ITAA 1997 s.328-180"
    },
    "formula": "Tax Saving = Asset Cost × Tax Rate. Example: $18,000 asset, 30% corporate rate → $5,400 immediate tax saving vs $810 in year one under pool depreciation. NPV benefit of immediate vs pool write-off over 5 years depends on discount rate and tax rate.",
    "thresholds": [
        {
            "label": "Turnover under $10M — buying assets under $20k before 30 June",
            "value": 1,
            "status": "clear"
        },
        {
            "label": "Planning to buy assets — not sure if they will arrive before 30 June",
            "value": 2,
            "status": "approaching"
        },
        {
            "label": "Asset over $20k — does not qualify for instant write-off",
            "value": 3,
            "status": "risk"
        },
        {
            "label": "Turnover over $10M — different rules apply",
            "value": 4,
            "status": "risk"
        },
        {
            "label": "Ordered but not yet installed — timing uncertain",
            "value": 5,
            "status": "trap"
        }
    ],
    "common_ai_errors": [
        {
            "error_id": 1,
            "ai_says": "ChatGPT says: You can claim the instant write-off if you order the asset before 30 June",
            "correct": "Reality: The asset must be first used or installed ready for use before 30 June — not just ordered or paid for. If you order in June but the asset is delivered and installed in July, you cannot claim the write-off in the current year."
        },
        {
            "error_id": 2,
            "ai_says": "ChatGPT says: There is a $20,000 annual cap across all assets",
            "correct": "Reality: The $20,000 threshold applies per asset — not as a total cap. You can claim the instant write-off on any number of eligible assets each costing under $20,000. There is no aggregate limit on the total write-off amount."
        },
        {
            "error_id": 3,
            "ai_says": "ChatGPT says: The instant asset write-off threshold is $150,000",
            "correct": "Reality: The $150,000 threshold applied during the COVID stimulus period and has expired. For 2024/25 and 2025/26, the threshold is $20,000 per asset for businesses with turnover under $10M. Using the wrong threshold overstates your deduction."
        }
    ],
    "faq": [
        {
            "id": 1,
            "question": "What is the instant asset write-off?",
            "answer": "The instant asset write-off allows eligible small businesses to immediately deduct the full cost of eligible assets costing under $20,000 (per asset) in the year the asset is first used or installed ready for use. For the 2025/26 year, the threshold is $20,000 per asset and the turnover threshold is $10M."
        },
        {
            "id": 2,
            "question": "Does the asset need to be paid for before 30 June?",
            "answer": "Payment before 30 June is not the trigger. The asset must be first used or installed ready for use before 30 June. You could pay in May but if the asset is not installed until July, you cannot claim this year. Conversely, if you finance the asset but it is installed in June, you can still claim the write-off."
        },
        {
            "id": 3,
            "question": "Can I split a large asset into components to get under the $20,000 threshold?",
            "answer": "You can only claim separate write-offs for genuinely separable components — assets that can stand alone and be used independently. You cannot artificially split a single asset into multiple invoices to stay under the threshold. The ATO looks at the substance of the asset, not just how it is invoiced."
        },
        {
            "id": 4,
            "question": "What happens to assets that cost over $20,000?",
            "answer": "Assets costing $20,000 or more are added to the general small business pool. They are depreciated at 15% in the first year (regardless of when in the year they were acquired) and 30% of the pool balance in subsequent years. This is less tax-efficient than an instant write-off but still provides accelerated depreciation compared to effective life rates."
        }
    ],
    "sources": [
        {
            "title": "ATO — Instant asset write-off",
            "url": "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/depreciation-and-capital-expenses-and-allowances/simpler-depreciation-for-small-business/instant-asset-write-off"
        }
    ],
    "products": {
        "tier1": {
            "name": "Your Instant Asset Write-Off Plan",
            "price": 67,
            "currency": "AUD",
            "description": "Will you miss EOFY asset deductions?",
            "url": "https://taxchecknow.com/au/check/instant-asset-write-off/success/assess"
        },
        "tier2": {
            "name": "Your Full Depreciation System",
            "price": 147,
            "currency": "AUD",
            "description": "Maximise asset deductions across your whole business",
            "url": "https://taxchecknow.com/au/check/instant-asset-write-off/success/plan"
        }
    },
    "monitor_urls": [
        "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/depreciation-and-capital-expenses-and-allowances/simpler-depreciation-for-small-business/instant-asset-write-off"
    ],
    "canonical": "https://taxchecknow.com/au/check/instant-asset-write-off",
    "api_endpoint": "/api/rules/instant-asset-write-off",
    "generated_at": "2026-04-20T06:42:40.238Z"
};

  return NextResponse.json(rules, {
    headers: {
      "Content-Type":                "application/json",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control":               "public, max-age=86400, stale-while-revalidate=3600",
      "X-COLE-Generated":            "true",
      "X-Product-ID":                "instant-asset-write-off",
      "X-Last-Verified":             "April 2026",
    },
  });
}
