"use client";
// AUTO-GENERATED BY COLE — do not edit manually
// Product: dividend-trap · File 08 of 8
// Regenerate: npx ts-node --project cole/tsconfig.json cole/scripts/cole-generate.ts uk-dividend-trap

export default function DividendTrapFile08() {
  return (
    <div className="min-h-screen bg-white">
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { font-size: 11px; color: #000; }
          h1 { font-size: 18px; }
          h2 { font-size: 14px; }
          h3 { font-size: 12px; }
          table { font-size: 10px; border-collapse: collapse; width: 100%; }
          td, th { padding: 4px 6px; border: 1px solid #ccc; word-break: break-word; }
          .action-box { background: #f0f0f0 !important; border: 1px solid #999; padding: 8px; }
          .info-box { background: #e8f0fe !important; border: 1px solid #aac; padding: 8px; }
          .warning-box { background: #fff0f0 !important; border: 1px solid #c99; padding: 8px; }
          .highlight { background: #fffbe6 !important; border: 1px solid #cc9; padding: 8px; }
          .checklist li::before { content: "☐ "; }
          a[href]:after { content: " (" attr(href) ")"; font-size: 8px; color: #555; word-break: break-all; }
          a[href^="#"]:after, a[href^="javascript"]:after { content: ""; }
        }
        .action-box { background: #0a0a0a; color: #fff; padding: 1rem 1.25rem; border-radius: 0.75rem; margin: 1rem 0; }
        .action-box h3 { color: #fff; margin-top: 0; }
        .action-box p, .action-box li { color: #d4d4d4; }
        .action-box a { color: #93c5fd; }
        .info-box { background: #eff6ff; border: 1px solid #bfdbfe; padding: 1rem 1.25rem; border-radius: 0.75rem; margin: 1rem 0; }
        .warning-box { background: #fff1f2; border: 1px solid #fecdd3; padding: 1rem 1.25rem; border-radius: 0.75rem; margin: 1rem 0; }
        .highlight { background: #fefce8; border: 1px solid #fde68a; padding: 1rem 1.25rem; border-radius: 0.75rem; margin: 1rem 0; }
        .checklist { list-style: none; padding-left: 0; }
        .checklist li { padding: 0.4rem 0; border-bottom: 1px solid #f0f0f0; }
        .checklist li::before { content: "☐ "; font-size: 1rem; color: #6b7280; margin-right: 0.5rem; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.875rem; }
        th { background: #f9fafb; text-align: left; padding: 0.625rem 0.75rem; border-bottom: 2px solid #e5e7eb; font-weight: 600; }
        td { padding: 0.625rem 0.75rem; border-bottom: 1px solid #f3f4f6; vertical-align: top; word-break: break-word; }
        h2 { font-size: 1.25rem; font-weight: 700; margin-top: 2rem; margin-bottom: 0.5rem; color: #111827; }
        h3 { font-size: 1rem; font-weight: 600; margin-top: 1.25rem; margin-bottom: 0.375rem; color: #111827; }
        ol { padding-left: 1.5rem; }
        ol li { margin-bottom: 0.5rem; line-height: 1.6; }
        p { line-height: 1.7; color: #374151; margin-bottom: 0.75rem; }
        a { color: #2563eb; }
      `}</style>

      {/* NAV */}
      <nav className="no-print sticky top-0 z-50 border-b border-neutral-200 bg-white px-4 py-3">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <a href="/" className="font-bold text-neutral-900">TaxCheckNow</a>
          <div className="flex items-center gap-4 text-sm text-neutral-500">
            <span className="hidden sm:block">United Kingdom · Salary + Dividend Tax Trap Engine</span>
            <button
              onClick={() => window.print()}
              className="rounded-lg border border-neutral-200 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-700 hover:bg-neutral-50 transition">
              ⬇ Save as PDF
            </button>
          </div>
        </div>
      </nav>

      {/* FILE NAV BAR */}
      <div className="no-print border-b border-neutral-100 bg-neutral-50 px-4 py-2">
        <div className="mx-auto flex max-w-3xl items-center justify-between text-xs text-neutral-500">
          <div><a href="/files/uk/dividend-trap/dt-07" className="font-semibold text-neutral-700 hover:text-neutral-950 transition">← File 07: Multi-Year Dividend Sequencing</a></div>
          <span className="font-mono">File 08 of 8</span>
          <div><a href="/uk/check/dividend-trap" className="font-semibold text-neutral-700 hover:text-neutral-950 transition">Back to Salary + Dividend Tax Trap Engine →</a></div>
        </div>
      </div>

      <main className="mx-auto max-w-3xl px-4 py-8">

        {/* HEADER */}
        <div className="mb-8">
          <div className="mb-3 flex flex-wrap gap-2 text-xs">
            <span className="bg-neutral-900 text-white px-2.5 py-1 font-medium">
              🇬🇧 HMRC · Income Tax Act 2007 — dividend tax rates; ITTOIA 2005 — dividend income taxation
            </span>
            <span className="bg-neutral-100 text-neutral-600 px-2.5 py-1 font-medium">
              Last verified: April 2026
            </span>
            <span className="bg-neutral-100 text-neutral-600 px-2.5 py-1 font-mono text-[10px]">
              File 08 of 8
            </span>
          </div>

          {/* Deadline bar */}
          <div className="mb-4 flex items-center justify-between rounded-lg bg-red-700 px-4 py-2.5">
            <span className="text-sm font-bold text-white">
              🔴 YEAR END — TIMING LEVER CLOSES: 5 April 2027
            </span>
            <a href="/uk/check/dividend-trap"
              className="no-print text-xs font-semibold text-red-200 hover:text-white transition">
              Check your position →
            </a>
          </div>

          <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400 mb-1">
            Salary + Dividend Tax Trap Engine · File 08 of 8
          </p>
          <h1 className="font-serif text-3xl font-bold text-neutral-950 mb-2">
            Annual Review Checklist
          </h1>
          <p className="text-neutral-500 text-sm">What to check every year before 5 April to ensure your salary/dividend split is still optimal.</p>
        </div>

        {/* PRINT BUTTON */}
        <div className="no-print mb-6">
          <button
            onClick={() => window.print()}
            className="w-full rounded-xl border-2 border-neutral-950 bg-white py-3 text-sm font-bold text-neutral-950 transition hover:bg-neutral-950 hover:text-white">
            ⬇ Save File 08 as PDF
          </button>
        </div>

        {/* CONTENT */}
        <div
          className="prose-content"
          dangerouslySetInnerHTML={{ __html: `<h2>Annual Dividend Review Checklist</h2><h3>February (2 months before year-end)</h3><ul class="checklist"><li>Pull YTD income figures: salary, dividends, other income</li><li>Project full-year total income</li><li>Identify whether total will cross £50,270 or £125,140 thresholds</li><li>Quantify higher-rate dividend exposure if any</li><li>Model restructure options (pension, spousal, deferral)</li></ul><h3>March (month before year-end)</h3><ul class="checklist"><li>Execute chosen restructure (pension contribution, dividend deferral, spousal shift)</li><li>Time final dividend payment to control year-end total</li><li>Confirm bookkeeping reflects actual dividend declaration dates</li><li>Brief accountant on changes</li></ul><h3>April (new tax year)</h3><ul class="checklist"><li>Check updated tax year figures (bands, allowances)</li><li>Adjust next-year strategy if rules have changed in the budget</li><li>Set up standing dividend schedule for the new year</li></ul><h3>Trigger Events (any time of year)</h3><ul class="checklist"><li>Salary change → review split immediately</li><li>New income source (rental, freelance) → recalculate band position</li><li>Spouse's income change → check spousal shareholding is still optimal</li><li>Major bonus or one-off income → plan dividend timing around it</li></ul>` }}
        />

        {/* FILE NAVIGATION */}
        <div className="no-print mt-12 border-t border-neutral-200 pt-6">
          <p className="mb-3 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
            All files in this pack
          </p>
          <div className="space-y-2">
            
            <a href="/files/uk/dividend-trap/dt-01"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">01</span>
                <span className="text-sm font-semibold text-neutral-950">Your Dividend Stacking Map</span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-02"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">02</span>
                <span className="text-sm font-semibold text-neutral-950">Optimal Salary/Dividend Split Calculator</span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-03"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">03</span>
                <span className="text-sm font-semibold text-neutral-950">The Dividend Allowance Collapse — 2017 to 2024</span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-04"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">04</span>
                <span className="text-sm font-semibold text-neutral-950">Restructure Options Ranked</span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-05"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">05</span>
                <span className="text-sm font-semibold text-neutral-950">Your Accountant Brief</span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-06"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">06</span>
                <span className="text-sm font-semibold text-neutral-950">Spousal Shareholding Execution Plan<span className="ml-2 font-mono text-[9px] uppercase tracking-widest text-blue-400">Plan only</span></span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <a href="/files/uk/dividend-trap/dt-07"
              className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3 transition hover:border-neutral-300">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-500">07</span>
                <span className="text-sm font-semibold text-neutral-950">Multi-Year Dividend Sequencing<span className="ml-2 font-mono text-[9px] uppercase tracking-widest text-blue-400">Plan only</span></span>
              </div>
              <span className="font-mono text-xs text-neutral-500">Open →</span>
            </a>

            <div className="flex items-center justify-between rounded-xl border border-neutral-950 bg-neutral-950 px-4 py-3">
              <div className="flex items-center">
                <span className="mr-2 font-mono text-xs font-bold text-neutral-300">08</span>
                <span className="text-sm font-semibold text-white">Annual Review Checklist<span className="ml-2 font-mono text-[9px] uppercase tracking-widest text-blue-400">Plan only</span></span>
              </div>
              <span className="text-xs text-neutral-400">You are here</span>
            </div>
          </div>
        </div>

        {/* DISCLAIMER */}
        <div className="mt-8 rounded-xl bg-neutral-50 px-5 py-4">
          <p className="text-xs leading-relaxed text-neutral-500">
            <strong className="text-neutral-600">General information only.</strong>{" "}
            This document does not constitute tax, legal or financial advice.
            Always consult a qualified UK tax adviser for your personal situation.
            Based on HMRC guidance April 2026.
          </p>
        </div>

      </main>

      {/* FOOTER */}
      <footer className="border-t border-neutral-200 bg-neutral-50 px-4 py-6 mt-8">
        <div className="mx-auto max-w-3xl flex flex-col md:flex-row md:justify-between gap-3 text-xs text-neutral-500">
          <div>
            <p className="font-bold text-neutral-700">TaxCheckNow</p>
            <p className="font-mono mt-0.5">
              This document: https://taxchecknow.com/files/uk/dividend-trap/dt-08
            </p>
          </div>
          <div className="flex flex-wrap gap-3">
            <a href="/uk/check/dividend-trap" className="hover:text-neutral-900 transition">
              ← Back to Salary + Dividend Tax Trap Engine
            </a>
            <a href="https://www.gov.uk/tax-on-dividends" target="_blank" rel="noopener noreferrer" className="hover:text-neutral-900 transition">HMRC — Tax on dividends ↗</a>
            <a href="https://www.gov.uk/tax-on-dividends#the-dividend-allowance" target="_blank" rel="noopener noreferrer" className="hover:text-neutral-900 transition">HMRC — Dividend allowance ↗</a>
          </div>
        </div>
      </footer>

    </div>
  );
}
