import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "negative-gearing-illusion", name: "Negative Gearing Illusion Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/negative-gearing-illusion", url: "https://taxchecknow.com/au/check/negative-gearing-illusion", apiRoute: "/api/rules/negative-gearing-illusion",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "ITAA 1997 — Rental property deductions (s.26-19)", legislation: "Income Tax Assessment Act 1997 — rental property loss offset against other income", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Negative Gearing Reality Check", tagline: "Is your tax saving costing you money?", value: "A personalised cashflow analysis showing your real after-tax position — not the gross tax saving your accountant shows you.", cta: "Get My Reality Check — $67 →", productKey: "au_67_negative_gearing_illusion", envVar: "STRIPE_AU_NG_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Property Portfolio Strategy", tagline: "Restructure your property portfolio for real after-tax wealth", value: "Full portfolio strategy, debt restructuring plan, and long-term investment model showing the true cost of negative gearing.", cta: "Get My Portfolio Strategy — $147 →", productKey: "au_147_negative_gearing_illusion", envVar: "STRIPE_AU_NG_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-10-31T23:59:59.000+11:00", display: "31 October 2026", short: "31 Oct 2026", description: "Individual tax return due — rental property losses declared here", urgencyLabel: "RETURN DUE", countdownLabel: "Countdown to 31 October 2026 — tax return due" },
  h1: "Negative Gearing 2026: Is Your Tax Saving Actually Costing You Money?", metaTitle: "Negative Gearing Reality Check Australia 2026 — What Is Your Real After-Tax Position? | TaxCheckNow", metaDescription: "Negative gearing saves you tax — but it also means your property is losing money. The tax saving is only a fraction of the loss. Free calculator shows your real after-tax cashflow, not just the gross deduction.", canonical: "https://taxchecknow.com/au/check/negative-gearing-illusion",
  answerHeadline: "The answer — ATO confirmed April 2026",
  answerBody: [
    "Negative gearing occurs when your rental property expenses — interest, rates, insurance, management, repairs — exceed your rental income. The resulting loss can be offset against your other income (salary, business income), reducing your tax bill. This is the tax saving everyone talks about.",
    "What is rarely discussed is the cashflow reality. If your property loses $15,000 per year and you are in the 37% tax bracket, your tax saving is $5,550. But you are still $9,450 out of pocket after tax. The tax system shares your loss — it does not eliminate it.",
    "Negative gearing is a legitimate strategy only if the expected capital growth of the property exceeds the after-tax cashflow loss over the holding period. If capital growth is modest or the holding period is short, negative gearing can destroy wealth rather than build it.",
  ],
  answerSource: "Source: ATO — Rental properties and negative gearing · ITAA 1997",
  mistakesHeadline: "What most property investors (and AI) get wrong about negative gearing",
  mistakes: [
    "Negative gearing saves me the full amount of my loss in tax — wrong. The tax saving is your marginal rate multiplied by the loss — not the loss itself. At 37%, a $15,000 rental loss saves you $5,550 in tax. You are still $9,450 out of pocket every year in real cash. The property must generate enough capital growth to justify this ongoing cost.",
    "Capital improvements are immediately deductible — wrong. Only genuine repairs and maintenance are immediately deductible. Capital improvements — work that upgrades or enhances the property beyond its original condition — must be depreciated over time. Misclassifying improvements as repairs is one of the most common ATO rental audit triggers.",
    "I can depreciate the land component — wrong. Land is never deductible or depreciable under any circumstances. Only the building structure (at 2.5% per year for post-September 1987 construction) and qualifying plant and equipment items are depreciable. The land portion of your purchase price produces no tax deduction at any point.",
    "Vacancy does not affect my negative gearing position — wrong. Vacancy directly reduces rental income but does not reduce your ongoing interest and holding costs. Your tax benefit is based on actual income and deductions — a vacancy gap widens your real cash loss without any proportional tax offset.",
  ],
  chainVisual: { label: "The negative gearing illusion — what the numbers actually show", broken: "Property loses $15k → I save $15k in tax  ❌  This is wrong", fixed: "Property loses $15k → Tax saving is $5,550 at 37% → Real cost: $9,450 out of pocket  ✔" },
  brackets: [
    { label: "Property is positively geared — earning more than it costs", value: 1, status: "clear" },
    { label: "Small negative gearing — under $5k loss per year", value: 2, status: "approaching" },
    { label: "Moderate negative gearing — $5k-$15k loss per year", value: 3, status: "trap" },
    { label: "Heavy negative gearing — over $15k loss per year", value: 4, status: "deep_trap" },
    { label: "Multiple negatively geared properties — compounding losses", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "annualRent", label: "What is the annual rental income from the property?", subLabel: "Total rent received before expenses", options: [{ label: "Under $25k", value: 18000 }, { label: "$25k-$40k", value: 32000 }, { label: "$40k-$60k", value: 50000 }, { label: "Over $60k", value: 75000 }], default: 32000 },
    { type: "buttonGroup", stateKey: "annualExpenses", label: "What are the total annual property expenses?", subLabel: "Interest, rates, insurance, management, repairs, depreciation", options: [{ label: "Under $30k", value: 22000 }, { label: "$30k-$45k", value: 37000 }, { label: "$45k-$60k", value: 52000 }, { label: "Over $60k", value: 75000 }], default: 37000 },
    { type: "buttonGroup", stateKey: "marginalRate", label: "What is your approximate marginal tax rate?", subLabel: "Based on total income including rental", options: [{ label: "19% (under $45k)", value: 19 }, { label: "32.5% ($45k-$120k)", value: 325 }, { label: "37% ($120k-$180k)", value: 37 }, { label: "45% (over $180k)", value: 45 }], default: 37 },
  ],
  tierAlgorithm: { description: "annualExpenses exceeds annualRent by more than 5000 → tier2. Otherwise tier1.", tier2Conditions: ["(annualExpenses as number) - (annualRent as number) > 5000"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "Negative gearing: rental losses (expenses exceeding income) are deductible against other income. Tax saving = loss × marginal rate. Immediate deductions: interest, rates, insurance, management, repairs. Capital improvements: depreciated over effective life. Building depreciation: 2.5% per year (post-September 1987 builds). Land: never deductible." },
  calculatorClarification: { label: "Key clarification", body: "Depreciation is a non-cash deduction that improves your tax position without requiring a cash outflow. A property with significant depreciation (new build, recent renovation) will have a lower after-tax loss than an older property with the same gross loss. Always include depreciation in your rental property schedule." },
  countdownLabel: "Countdown to 31 October 2026 — tax return due",
  countdownStats: [
    { label: "Tax saving at 37%", value: "37 cents", sub: "per dollar of rental loss" },
    { label: "Real out-of-pocket", value: "63 cents", sub: "per dollar of loss after tax saving", red: true },
    { label: "On $15k loss at 37%", value: "$9,450", sub: "real annual after-tax cost", red: true },
    { label: "Break even requires", value: "Growth", sub: "capital gain must exceed cumulative after-tax loss" },
  ],
  geoBlockTitle: "AI extraction block — negative gearing Australia 2026",
  geoBlockH2: "Negative Gearing — Australian Tax Rules confirmed 2026",
  geoBodyParagraph: "Under Australian tax law, rental property expenses that exceed rental income create a net rental loss that can be offset against other assessable income, reducing income tax payable. This is commonly known as negative gearing. The tax saving equals the net rental loss multiplied by the taxpayer's marginal tax rate. Immediately deductible expenses include mortgage interest, council rates, water rates, insurance, property management fees, maintenance and repairs, and depreciation on plant and equipment. Capital improvements are not immediately deductible — they are added to the asset's cost base for CGT purposes or depreciated over the asset's effective life. Building depreciation at 2.5% per year is available on construction costs for residential properties built after 7 September 1987. Land value is never deductible.",
  geoFormula: "Net Rental Loss = Total Expenses - Rental Income. Annual Tax Saving = Net Rental Loss × Marginal Tax Rate. Real After-Tax Cost = Net Rental Loss - Tax Saving = Net Rental Loss × (1 - Marginal Tax Rate). Break-Even Capital Growth = Cumulative Real After-Tax Cost / (Holding Period × Property Value).",
  geoFacts: [
    { label: "Tax saving on $15k loss at 37%", value: "$5,550" },
    { label: "Real after-tax cost of $15k loss", value: "$9,450" },
    { label: "Building depreciation rate", value: "2.5% per year (post-Sept 1987)" },
    { label: "Land depreciation", value: "None — never deductible" },
    { label: "Capital improvements", value: "Added to cost base — not immediately deductible" },
    { label: "Legislative anchor", value: "ITAA 1997 — rental deductions" },
  ],
  workedExamplesH2: "Four negative gearing scenarios",
  workedExamplesColumns: ["Scenario", "Annual Loss", "Tax Rate", "Tax Saving", "Real After-Tax Cost"],
  workedExamples: [
    { name: "Light gearing",    setup: "Rent $32k, costs $37k, 37% bracket",      income: "$5k loss",  status: "$1,850 saving — $3,150 real cost" },
    { name: "Moderate gearing", setup: "Rent $32k, costs $47k, 37% bracket",      income: "$15k loss", status: "$5,550 saving — $9,450 real cost" },
    { name: "Heavy gearing",    setup: "Rent $32k, costs $62k, 45% bracket",      income: "$30k loss", status: "$13,500 saving — $16,500 real cost" },
    { name: "Positive gearing", setup: "Rent $40k, costs $35k — positive",        income: "$5k profit", status: "TAXABLE — but cashflow positive" },
  ],
  comparisonH2: "Negative gearing vs positive gearing — real cashflow",
  comparisonColumns: ["Position", "Annual Rental P&L", "Tax Impact", "Net Cashflow After Tax"],
  comparisonRows: [
    { position: "Negative — $10k loss at 37%", metric1: "-$10,000", metric2: "+$3,700 tax saving", bestMove: "-$6,300 real annual cost" },
    { position: "Neutral — breakeven", metric1: "$0", metric2: "$0 tax impact", bestMove: "$0 — no growth or loss" },
    { position: "Positive — $5k profit at 37%", metric1: "+$5,000", metric2: "-$1,850 tax on profit", bestMove: "+$3,150 real annual benefit" },
  ],
  toolsH2: "How to improve a negatively geared property's position",
  toolsColumns: ["Strategy", "How It Works", "Impact"],
  toolsRows: [
    { tool: "Rent review", effect: "Increase rent to market rate — reduce net loss", note: "Market rent review — may require tenant negotiation" },
    { tool: "Depreciation report", effect: "Quantity surveyor report — maximise non-cash deductions", note: "Non-cash deduction improves tax position without cashflow cost" },
    { tool: "Interest rate review", effect: "Refinance at lower rate — reduce the largest expense", note: "1% rate reduction on $500k loan saves $5,000 interest" },
    { tool: "Debt recycling", effect: "Convert non-deductible home loan to deductible investment loan", note: "Maximise deductible debt — complex, get specialist advice" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: Negative gearing means you save money on tax equal to your property loss", correct: "Reality: The tax saving is your marginal rate multiplied by the loss — not the full loss. At a 37% rate, a $15,000 loss saves $5,550 in tax. You are still $9,450 out of pocket. Negative gearing shares your loss with the government — it does not eliminate the loss." },
    { wrong: "ChatGPT says: All property expenses are tax deductible", correct: "Reality: Only expenses for the income-producing (rented) period are deductible. Capital improvements are not immediately deductible — they are depreciated or added to the cost base. The purchase price and land value are never deductible." },
    { wrong: "ChatGPT says: Negative gearing is always a good strategy if you are in a high tax bracket", correct: "Reality: Negative gearing is only beneficial if the capital growth of the property exceeds the cumulative after-tax losses over the holding period. In markets with low or flat growth, negative gearing can destroy wealth. The higher your tax bracket, the more the government shares your loss — but you are still losing money." },
  ],
  faqs: [
    { question: "What is negative gearing?", answer: "Negative gearing occurs when your rental property expenses exceed your rental income. The resulting loss is deductible against your other income (salary or business income), reducing your tax bill. The tax saving is equal to the loss multiplied by your marginal tax rate." },
    { question: "Is negative gearing always worth it?", answer: "Not automatically. Negative gearing is only beneficial if the capital growth of the property exceeds the cumulative after-tax losses over the entire holding period. If you lose $9,450 per year after tax and hold for 10 years, the property needs to grow by at least $94,500 just to break even on cashflow — before CGT on the gain." },
    { question: "What expenses can I deduct on a rental property?", answer: "Immediately deductible expenses include mortgage interest, council rates, water rates, landlord insurance, property management fees, maintenance and repairs, advertising for tenants, and tax agent fees for the property. Capital improvements — new kitchen, extension, new bathroom — are not immediately deductible. They are depreciated or added to the cost base for CGT." },
    { question: "What is a depreciation schedule and do I need one?", answer: "A depreciation schedule is a report prepared by a quantity surveyor that identifies all depreciable items in your rental property — the building structure (at 2.5% per year for post-1987 builds) and plant and equipment items (appliances, carpets, blinds). A depreciation schedule can significantly increase your non-cash deductions and improve your after-tax position." },
  ],
  accountantQuestionsH2: "Ask these to get a real picture of your rental property",
  accountantQuestions: [
    { q: "What is my exact after-tax cashflow from this property — not just the tax saving, but the real money in and out?", why: "Most people focus on the tax saving. The after-tax cashflow — rent received minus all costs minus tax saving — is the real number. It needs to be negative enough that capital growth will compensate." },
    { q: "Do I have a quantity surveyor depreciation schedule for this property — and is it up to date?", why: "A current depreciation schedule maximises your non-cash deductions. Without it, you are overpaying tax." },
    { q: "Is my mortgage on this property structured as interest-only or principal-and-interest — and does that affect my deduction?", why: "Only the interest component is tax deductible, not principal repayments. Understanding the deductible vs non-deductible portion of your repayments matters for cashflow planning." },
    { q: "Should I be converting any of my non-deductible home loan debt to investment loan debt through debt recycling?", why: "If you have non-deductible personal debt (home loan) and investment properties, debt recycling can convert non-deductible interest to deductible interest — improving the overall tax position significantly." },
  ],
  crosslink: { title: "Rental property deduction audit — are you claiming everything?", body: "The negative gearing calculation depends on maximising all legitimate deductions. Check your rental deduction position.", url: "/au/check/rental-property-deduction-audit", label: "Check rental deductions →" },
  lawBarSummary: "Negative gearing: rental losses offset against other income. Tax saving = loss × marginal rate. Immediate deductions: interest, rates, insurance, management, repairs. Building depreciation: 2.5%/yr (post-Sept 1987). Capital improvements: cost base or depreciated. Land: not deductible. Under ITAA 1997.",
  lawBarBadges: ["ATO", "ITAA 1997", "Rental Deductions", "Negative Gearing"],
  sources: [{ title: "ATO — Rental properties", url: "https://www.ato.gov.au/individuals-and-families/investments-and-assets/residential-rental-properties" }],
  files: [
    { num: "01", slug: "ng-01", name: "Your Real After-Tax Cashflow Report", desc: "The real dollars in and out — not just the tax saving.", tier: 1, content: `<h2>Your Real Negative Gearing Position</h2><div class="action-box"><h3>The Honest Calculation</h3><p>Tax saving = Net rental loss × Marginal rate</p><p>Real after-tax cost = Net rental loss × (1 - Marginal rate)</p><p>Break-even capital growth = Cumulative real cost / (years held × property value)</p></div><p>Source: <a href="https://www.ato.gov.au/individuals-and-families/investments-and-assets/residential-rental-properties">ATO — Rental properties</a></p>` },
    { num: "02", slug: "ng-02", name: "Cashflow Optimiser", desc: "The levers that improve your real after-tax cashflow position.", tier: 1, content: `<h2>Cashflow Improvement Strategies</h2><table><tr><th>Strategy</th><th>Annual Impact (estimate)</th></tr><tr><td>Rent increase of $50/week</td><td>+$2,600 income</td></tr><tr><td>Refinance at 0.5% lower rate ($500k loan)</td><td>+$2,500 reduction in interest expense</td></tr><tr><td>Quantity surveyor depreciation report</td><td>+$2,000-$5,000 in non-cash deductions</td></tr><tr><td>Review and remove excess insurances</td><td>+$500-$1,000</td></tr></table>` },
    { num: "03", slug: "ng-03", name: "Expense Reclassification Guide", desc: "Which expenses are immediately deductible vs capital improvements.", tier: 1, content: `<h2>Repairs vs Capital Improvements</h2><table><tr><th>Expense</th><th>Treatment</th></tr><tr><td>Replacing broken tap</td><td>Immediate deduction — repair</td></tr><tr><td>New bathroom renovation</td><td>Capital improvement — depreciated</td></tr><tr><td>Repainting existing walls</td><td>Immediate deduction — repair</td></tr><tr><td>Adding a new room</td><td>Capital improvement — cost base</td></tr><tr><td>Replacing like-for-like appliance</td><td>Immediate deduction — repair</td></tr><tr><td>Upgrading to better appliance</td><td>Capital improvement — depreciated</td></tr></table>` },
    { num: "04", slug: "ng-04", name: "Yield Improvement Plan", desc: "How to improve rental yield and move toward positive gearing.", tier: 1, content: `<h2>Improving Rental Yield</h2><p>Rental yield = Annual rent / Property value × 100. If yield is below your interest rate, the property is negatively geared on a gross basis.</p><div class="action-box"><h3>Yield Improvement Options</h3><p>Rent increase to market rate: schedule periodic reviews</p><p>Renovation to justify higher rent: calculate payback period</p><p>Change rental strategy: long-term vs short-term — compare after-tax returns</p><p>Reduce vacancy: improve marketing and property presentation</p></div>` },
    { num: "05", slug: "ng-05", name: "Your Accountant Brief", desc: "Questions to get the real picture from your accountant.", tier: 1, content: `<div class="info-box">Print or forward to your accountant before your next annual meeting.</div><h2>Real Negative Gearing Questions</h2><div class="action-box"><h3>Question 1</h3><p>"What is my exact after-tax cashflow from this property — net of all costs and the tax saving?"</p></div><h3>Question 2</h3><p>"Do I have a current quantity surveyor depreciation schedule?"</p><h3>Question 3</h3><p>"What capital growth rate does this property need to break even over my planned holding period?"</p>` },
    { num: "06", slug: "ng-06", name: "Property Portfolio Strategy", desc: "How to structure a property portfolio for long-term after-tax wealth.", tier: 2, content: `<h2>Portfolio-Level Property Strategy</h2><p>A balanced property portfolio typically combines negatively geared growth properties with positively geared yield properties to manage cashflow while building capital.</p><h3>Portfolio Structure Principles</h3><ul><li>Calculate the after-tax cashflow position of each property individually</li><li>Model the break-even capital growth required for each negatively geared property</li><li>Consider adding a positively geared property to offset cashflow drain</li><li>Review the portfolio annually — property positions change as rents grow and debt reduces</li></ul>` },
    { num: "07", slug: "ng-07", name: "Debt Restructuring Plan", desc: "How to restructure property debt to maximise deductible interest.", tier: 2, content: `<h2>Debt Restructuring for Tax Efficiency</h2><p>The deductibility of interest depends on the purpose of the loan — not which property it is secured against. Interest on loans used to acquire or improve income-producing property is deductible.</p><div class="action-box"><h3>Debt Recycling Strategy</h3><p>Step 1: Direct salary income to home loan offset account</p><p>Step 2: Redraw the same amount for investment purposes</p><p>Step 3: Interest on the redrawn amount is now deductible</p><p>Step 4: Repeat — converting non-deductible to deductible debt over time</p></div>` },
    { num: "08", slug: "ng-08", name: "Long-Term Investment Model", desc: "10-year model showing the true cost of negative gearing vs alternative investments.", tier: 2, content: `<h2>10-Year Negative Gearing Model</h2><p>The real question: does the capital growth exceed the cumulative after-tax cashflow losses?</p><table><tr><th>Year</th><th>Annual After-Tax Loss</th><th>Cumulative Loss</th><th>Required Growth to Break Even</th></tr><tr><td>1</td><td>$9,450</td><td>$9,450</td><td>1.5% (on $630k property)</td></tr><tr><td>5</td><td>$9,450</td><td>$47,250</td><td>7.5% total growth</td></tr><tr><td>10</td><td>$9,450</td><td>$94,500</td><td>15% total growth</td></tr></table><div class="info-box">This model assumes no change in rental income, interest rate, or property value. Real models should be recalculated annually.</div>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "Owns a rental unit in Mandurah. Mortgage of $380,000 at 6.8%. Annual rent $28,800. Rates, insurance, management, and repairs total $9,200. Interest alone is $25,840.", painPoint: "Gary's accountant tells him he is saving $5,400 per year in tax through negative gearing. Gary is happy about this. He has not done the full cashflow calculation.", discovery: "Sandra asked Gary to write down all the property numbers for their financial review. When Gary added them up properly, the real cashflow did not look like what the accountant had described.", voice: "Gary is good with numbers when they are laid out plainly. He will immediately understand the real cashflow once he sees it. He needs the before-and-after view." },
  story: { hook: "Gary's accountant had told him the Mandurah unit saved him about $5,400 per year in tax. Gary had been reasonably happy about that.", setup: ["The unit rented for $28,800 per year. The mortgage was $380,000 at 6.8% — interest cost around $25,840. Management fees, rates, insurance, and the odd repair came to another $9,200. Total expenses: $35,040. Net rental loss: $6,240. Tax saving at the 37% rate his accountant had used: $2,309.", "Gary frowned at this. His accountant had said $5,400. He pulled out last year's tax return. The accountant had also included depreciation — the quantity surveyor's report. The total deductions were $14,600 including $8,360 of depreciation. Net rental loss with depreciation: $14,600. Tax saving at 37%: $5,402. That matched.", "But Gary looked at the actual cash coming in and out. Depreciation was a non-cash deduction. He had not physically paid $8,360 in depreciation — that was just a paper entry. His real cash costs were $35,040. His real cash income was $28,800. Real cash loss before tax: $6,240. Tax saving at 37%: $2,309. Real after-tax cash loss: $3,931 per year."], revelation: "When Gary ran the calculator, the output was clear. His real after-tax cashflow loss was $3,931 per year — not the $5,400 saving his accountant had described. The depreciation improved his tax position without costing him cash, but it also meant his tax saving was less than it appeared. The property needed to grow by around $3,931 per year just to break even on a cashflow basis, plus the eventual CGT on the capital gain.", resolution: "Gary called his accountant and walked through the numbers. The accountant confirmed the analysis was correct — the $5,400 was the total tax saving including the depreciation non-cash deduction. The real cash outflow was $3,931 per year. The accountant also modelled what the position would look like in 5 years when the depreciation deductions reduced and the cashflow loss increased. Gary decided to review the unit's position at the next annual meeting rather than buy a second property as he had been planning." },
  calendarTitle: "Negative Gearing — Key Dates",
  tier1Calendar: [{ uid: "ng-return", summary: "Tax Return Due — 31 October 2026", description: "Rental property income and losses declared in individual tax return.", date: "20261031" }],
  tier2Calendar: [{ uid: "ng-review", summary: "Property — Annual cashflow review", description: "Review real after-tax cashflow position of each property in the portfolio.", date: "relative:+14days" }, { uid: "ng-return", summary: "Tax Return Due", description: "Lodge individual return including rental schedule.", date: "20261031" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_NG_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_NG_147" },
  monitorUrls: ["https://www.ato.gov.au/individuals-and-families/investments-and-assets/residential-rental-properties"],
  sidebarNumbers: [{ label: "Tax saving at 37%", value: "37 cents/dollar" }, { label: "Real after-tax cost", value: "63 cents/dollar" }, { label: "Building depreciation", value: "2.5%/yr" }, { label: "Land depreciation", value: "Zero" }],
  sidebarMathsTitle: "The real negative gearing cashflow model",
  sidebarMathsIncludes: [
    "Tax saving = rental loss × marginal rate (not the full loss)",
    "Real after-tax cost = loss × (1 − marginal rate)",
    "Building depreciation: 2.5%/yr (post Sept 1987 construction)",
    "Vacancy reduces income — costs continue regardless",
    "Break-even rent = (interest + costs) ÷ (1 − marginal rate)",
  ],
  sidebarMathsExcludes: [
    "NOT the full loss saved in tax — only marginal rate × loss",
    "NOT land — never deductible or depreciable",
    "NOT capital improvements — depreciated over time, not immediate",
    "NOT second-hand assets post 9 May 2017 (Div 40 rule)",
  ],
  sidebarMathsNote: "Source: ATO — Rental properties · ITAA 1997 s26-19 · TR 97/23",
  howToSteps: [
    { position: 1, name: "Select your income band", text: "Your marginal tax rate determines how much of the rental loss is offset by the tax benefit." },
    { position: 2, name: "Enter rent and costs", text: "Select your rent band, interest cost, and holding cost level." },
    { position: 3, name: "Add vacancy and repair risk", text: "Vacancy reduces income but not costs — this is where the illusion most often hides." },
    { position: 4, name: "Get your real after-tax position", text: "See your real cash loss, tax benefit, illusion gap, and break-even rent." },
  ],
  successPromptFields: [
    { key: "income_band",       label: "Marginal tax rate band",          defaultVal: "45k_120k" },
    { key: "illusion_type",     label: "Negative gearing illusion type",  defaultVal: "moderate" },
    { key: "real_cost",         label: "Real after-tax annual cost",      defaultVal: "9000" },
    { key: "tax_benefit",       label: "Annual tax benefit",              defaultVal: "4500" },
    { key: "break_even_rent",   label: "Break-even rent required",        defaultVal: "38000" },
    { key: "status",            label: "Negative gearing verdict",        defaultVal: "MODERATE ILLUSION" },
    { key: "tier",              label: "Product tier purchased",          defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "cashflowSummary",
    "taxBenefitReality",
    "realAfterTaxCost",
    "illusionGapExplained",
    "breakEvenRentRequired",
    "vacancyImpact",
    "growthRequiredToBreakEven",
    "depreciationOpportunity",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "cashflowSummary",
    "taxBenefitReality",
    "realAfterTaxCost",
    "illusionGapExplained",
    "breakEvenRentRequired",
    "vacancyImpact",
    "growthRequiredToBreakEven",
    "depreciationOpportunity",
    "debtStructureOptions",
    "offsetVsInvestScenario",
    "holdSellRepriceFramework",
    "sensitivityAnalysis",
    "portfolioInteraction",
  ],
};
