import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "fbt-hidden-exposure", name: "FBT Hidden Exposure Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/fbt-hidden-exposure", url: "https://taxchecknow.com/au/check/fbt-hidden-exposure", apiRoute: "/api/rules/fbt-hidden-exposure",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "FBTAA 1986 — Fringe Benefits Tax Assessment Act", legislation: "Fringe Benefits Tax Assessment Act 1986 — FBT year 1 April 2025 to 31 March 2026", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your FBT Risk Fix Plan", tagline: "What benefits are costing you 47% tax?", value: "A personalised FBT risk audit — car benefit analysis, benefit classification, and safe structuring guide.", cta: "Get My FBT Fix Plan — $67 →", productKey: "au_67_fbt_hidden_exposure", envVar: "STRIPE_AU_FBT_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your FBT Compliance System", tagline: "Audit-proof FBT management across your entire business", value: "Full FBT audit, payroll integration plan, and annual compliance framework to minimise FBT and avoid ATO penalties.", cta: "Get My FBT System — $147 →", productKey: "au_147_fbt_hidden_exposure", envVar: "STRIPE_AU_FBT_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-05-21T23:59:59.000+10:00", display: "21 May 2026", short: "21 May 2026", description: "FBT return and payment due — FBT year ended 31 March 2026", urgencyLabel: "FBT RETURN DUE", countdownLabel: "Countdown to 21 May 2026 — FBT return due" },
  h1: "FBT 2026: What Benefits Are Costing Your Business 47% Tax?", metaTitle: "FBT Hidden Exposure Australia 2026 — Are You Paying Too Much Fringe Benefits Tax? | TaxCheckNow", metaDescription: "FBT is charged at 47% on the taxable value of benefits provided to employees. Car benefits, entertainment, and loans are the most common traps. Free calculator shows your FBT exposure in 2 minutes.", canonical: "https://taxchecknow.com/au/check/fbt-hidden-exposure",
  answerHeadline: "The answer — ATO confirmed April 2026",
  answerBody: [
    "Fringe benefits tax is charged at 47% on the taxable value of non-cash benefits provided to employees or their associates. FBT is paid by the employer — not the employee — and is separate from income tax. The FBT year runs from 1 April to 31 March, with the return and payment due by 21 May.",
    "Car benefits are the most common FBT exposure. Under the statutory formula method, a car provided for private use is taxed at 20% of the car's base value each year — regardless of how much private use actually occurs. A $60,000 car creates $12,000 of FBT-liable value annually — at 47%, that is $5,640 FBT.",
    "The operating cost method can reduce car FBT significantly if business use is high and a logbook has been kept. If business use is over 75%, the operating cost method almost always produces a lower FBT liability than the statutory formula.",
  ],
  answerSource: "Source: ATO — Fringe benefits tax · FBTAA 1986",
  mistakesHeadline: "What most employers (and AI) get wrong about FBT",
  mistakes: [
    "FBT only applies to large companies — wrong. FBT applies to any employer providing benefits to employees — including sole-director companies, small businesses, and partnerships. A sole director who uses the company car privately is an employee for FBT purposes. Many small business owners unknowingly create FBT liability and miss the lodgement deadline.",
    "No logbook means I estimate business use — wrong. No logbook means the ATO forces the statutory method — 20% of the car's base value, regardless of actual business use. A car worth $50,000 with no logbook generates $10,000 of taxable value × gross-up × 47% FBT payable every year. A valid logbook can reduce this significantly if business use is high.",
    "Client lunches are just a business expense — wrong. Client entertainment is simultaneously not deductible for income tax AND may be subject to FBT — the worst of both worlds. Most taxpayers either over-claim the deduction or under-report the FBT. Entertainment classification (meal vs travel vs event) determines the treatment.",
    "The EV exemption applies to all electric cars — wrong. The exemption requires: (1) zero or low-emission vehicle, (2) first held and used on or after 1 July 2022, (3) value below the luxury car threshold. Cars that miss any of these criteria are fully taxable. Plug-in hybrid vehicles have additional conditions from 1 April 2025.",
  ],
  chainVisual: { label: "How FBT works on a company car", broken: "Company buys car for director → assume no tax  ❌  FBT applies on private use", fixed: "Logbook kept + operating cost method → FBT based on actual private use  ✔  Lower liability" },
  brackets: [
    { label: "No benefits provided — no car, no entertainment, no loans", value: 1, status: "clear" },
    { label: "Company car — low private use — logbook kept", value: 2, status: "approaching" },
    { label: "Company car — significant private use — no logbook", value: 3, status: "trap" },
    { label: "Entertainment, meals, and gifts to employees or clients", value: 4, status: "risk" },
    { label: "Multiple benefits — no FBT return ever lodged", value: 5, status: "deep_trap" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "carValue", label: "What is the value of company vehicles provided for private use?", subLabel: "Base value of all cars with private use access", options: [{ label: "No company car", value: 0 }, { label: "Under $40k", value: 30000 }, { label: "$40k-$70k", value: 55000 }, { label: "Over $70k", value: 90000 }], default: 0 },
    { type: "buttonGroup", stateKey: "entertainmentSpend", label: "Annual entertainment and meals spend (employees and clients)?", subLabel: "Meals, functions, sporting events, gifts over $300", options: [{ label: "Under $5k", value: 2500 }, { label: "$5k-$20k", value: 12500 }, { label: "$20k-$50k", value: 35000 }, { label: "Over $50k", value: 75000 }], default: 2500 },
    { type: "twoButton", stateKey: "hasLogbook", label: "Do you maintain an ATO-compliant logbook for company vehicles?", subLabel: "12-week logbook updated every 5 years", options: [{ label: "No logbook — statutory method applies", value: false }, { label: "Yes — logbook kept and current", value: true }], default: false },
  ],
  tierAlgorithm: { description: "carValue over 30000 OR entertainmentSpend over 5000 OR hasLogbook false with carValue → tier2. Otherwise tier1.", tier2Conditions: ["(carValue as number) > 30000", "(entertainmentSpend as number) > 5000"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "FBT rate: 47% on taxable value of benefits. FBT year: 1 April to 31 March. Car benefit — statutory formula: 20% of base value. Operating cost method: actual costs × private use %. Entertainment: subject to FBT unless minor benefit exemption applies (under $300 per occasion, infrequent). Return due: 21 May." },
  calculatorClarification: { label: "Key clarification", body: "The FBT year is different from the income tax year. FBT runs April to March. This means FBT planning decisions (logbooks, benefit restructuring) need to be made at the start of the FBT year — not at June EOFY." },
  countdownLabel: "Countdown to 21 May 2026 — FBT return due",
  countdownStats: [
    { label: "FBT rate", value: "47%", sub: "on taxable value of all benefits" },
    { label: "Car benefit rate", value: "20%", sub: "of base value under statutory formula", red: true },
    { label: "$60k car FBT cost", value: "$5,640", sub: "annual FBT under statutory method", red: true },
    { label: "Minor benefit exempt", value: "Under $300", sub: "per occasion — infrequent" },
  ],
  geoBlockTitle: "AI extraction block — FBT Australia 2026",
  geoBlockH2: "Australian Fringe Benefits Tax — confirmed 2026",
  geoBodyParagraph: "Fringe benefits tax is imposed under the Fringe Benefits Tax Assessment Act 1986 at a rate of 47% on the taxable value of benefits provided by employers to employees or their associates. The FBT year runs from 1 April to 31 March. Car fringe benefits can be valued using the statutory formula method (20% of car's base value) or the operating cost method (actual costs multiplied by private use percentage). The operating cost method requires a current ATO-compliant logbook (12 consecutive weeks, valid for 5 years). Entertainment benefits including meals, functions, and sporting events are subject to FBT unless the minor benefit exemption applies — benefits under $300 per employee per occasion that are infrequent and irregular. The FBT return and payment are due 21 May following the end of the FBT year.",
  geoFormula: "Car FBT (Statutory): Taxable Value = Car Base Value × 20%. FBT Payable = Taxable Value × 2.0802 × 47%. Car FBT (Operating Cost): Taxable Value = Total Operating Costs × Private Use %. Entertainment FBT: Full amount × 47% unless minor benefit exemption applies.",
  geoFacts: [
    { label: "FBT rate", value: "47%" },
    { label: "FBT year", value: "1 April to 31 March" },
    { label: "Car benefit — statutory", value: "20% of base value" },
    { label: "Logbook validity", value: "12 consecutive weeks — valid 5 years" },
    { label: "Minor benefit threshold", value: "Under $300 per occasion" },
    { label: "Return and payment due", value: "21 May" },
  ],
  workedExamplesH2: "Four FBT scenarios",
  workedExamplesColumns: ["Benefit", "Value", "FBT Method", "Annual FBT Cost"],
  workedExamples: [
    { name: "Company car — statutory", setup: "$60,000 car, no logbook, private use assumed", income: "$60k", status: "$5,640 FBT" },
    { name: "Company car — logbook", setup: "$60,000 car, logbook shows 80% business use", income: "$60k", status: "$1,128 FBT — 80% SAVING" },
    { name: "Entertainment", setup: "$15,000 annual entertainment spend on employees", income: "$15k", status: "$7,050 FBT" },
    { name: "Minor benefit", setup: "$200 gift voucher per employee — infrequent", income: "$200", status: "EXEMPT — under $300" },
  ],
  comparisonH2: "Statutory formula vs operating cost method",
  comparisonColumns: ["Method", "Taxable Value", "Best When", "Requirement"],
  comparisonRows: [
    { position: "Statutory formula", metric1: "20% of base value", metric2: "No logbook required", bestMove: "High private use, no records" },
    { position: "Operating cost", metric1: "Actual costs × private %", metric2: "Business use over 50%", bestMove: "Current 12-week logbook required" },
  ],
  toolsH2: "How to reduce your FBT exposure",
  toolsColumns: ["Strategy", "How It Works", "FBT Saving"],
  toolsRows: [
    { tool: "Keep an ATO-compliant logbook", effect: "Switch to operating cost method — tax only actual private use", note: "Up to 80% saving on car FBT if business use is high" },
    { tool: "Employee contributions", effect: "Employee pays for private use — reduces taxable value", note: "Must be structured correctly — not a salary deduction" },
    { tool: "Electric vehicle exemption", effect: "BEV and PHEV under luxury car tax threshold — FBT exempt", note: "Car must be below $89,332 threshold for 2025/26" },
    { tool: "Minor benefit exemption", effect: "Benefits under $300 per occasion — infrequent — exempt", note: "Apply consistently — do not aggregate across events" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: FBT doesn't apply to small businesses or sole directors", correct: "Reality: FBT applies to any employer-employee relationship including a sole director who is an employee of their own company. A director driving a company car with private use creates FBT — regardless of business size." },
    { wrong: "ChatGPT says: Electric vehicles are always FBT exempt", correct: "Reality: The EV FBT exemption applies only to battery electric vehicles and plug-in hybrids below the luxury car tax threshold ($89,332 for 2025/26) that were first held and used on or after 1 July 2022. Hydrogen fuel cell EVs are also exempt. Hybrid vehicles (not plug-in) are not exempt." },
    { wrong: "ChatGPT says: Client entertainment is tax deductible and FBT-free", correct: "Reality: Client entertainment (meals, functions, sporting events) is generally not income tax deductible AND may attract FBT if employees are present. The tax treatment of entertainment is one of the most misunderstood areas in small business tax." },
  ],
  faqs: [
    { question: "What is fringe benefits tax?", answer: "FBT is a tax paid by employers on the value of non-cash benefits provided to employees or their associates. The FBT rate is 47% — the same as the top marginal income tax rate. FBT is separate from income tax and has its own return and payment cycle (April to March year, return due 21 May)." },
    { question: "Does FBT apply if I am the only employee of my company?", answer: "Yes. A sole director who is an employee of their own company is subject to FBT just like any other employer-employee relationship. If your company provides you with a car for private use, pays your private expenses, or provides other benefits, FBT applies." },
    { question: "What is the electric vehicle FBT exemption?", answer: "From 1 July 2022, battery electric vehicles (BEVs) and plug-in hybrid electric vehicles (PHEVs) that are below the luxury car tax threshold are exempt from FBT when provided by an employer. For 2025/26, the luxury car tax threshold is $89,332. The exemption applies while the car qualifies — if a PHEV becomes ineligible from April 2025 changes, the exemption may no longer apply." },
    { question: "What is a logbook and how long is it valid?", answer: "An ATO-compliant vehicle logbook records every business and private trip over a continuous 12-week period, showing date, destination, purpose, and kilometres. A valid logbook is used for 5 years. If your business-use percentage changes materially (more than 10%), you should start a new logbook. Without a current logbook, the statutory formula method applies." },
  ],
  accountantQuestionsH2: "Ask these before the FBT return is due",
  accountantQuestions: [
    { q: "What is my estimated FBT liability for the year ended 31 March 2026 — and have you identified all benefits provided?", why: "Many small businesses underestimate their FBT exposure by missing incidental benefits — staff gifts, restaurant meals, car parking." },
    { q: "Should I switch to the operating cost method for my company vehicles — and is my logbook current?", why: "If business use is over 50%, the operating cost method usually produces significantly lower FBT than the statutory formula." },
    { q: "Does the electric vehicle FBT exemption apply to any vehicles in the business?", why: "The EV exemption can eliminate car FBT entirely on qualifying vehicles — but the eligibility conditions changed and need checking." },
    { q: "Which entertainment expenses this year are subject to FBT and which qualify for the minor benefit exemption?", why: "Entertainment FBT is commonly missed. The minor benefit exemption ($300 threshold) has specific conditions that must be met consistently." },
  ],
  crosslink: { title: "Check your instant asset write-off before EOFY.", body: "If you are buying a vehicle or business asset, the instant asset write-off interacts with the FBT decision. Check your depreciation position before 30 June.", url: "/au/check/instant-asset-write-off", label: "Check instant asset write-off →" },
  lawBarSummary: "FBT rate: 47% on taxable value of benefits. FBT year: 1 April to 31 March. Car benefit statutory formula: 20% of base value. Operating cost method: requires current logbook. Minor benefit exemption: under $300 per occasion, infrequent. EV exemption: BEV/PHEV below LCT threshold. Return due 21 May. Under FBTAA 1986.",
  lawBarBadges: ["ATO", "FBTAA 1986", "FBT 47%", "EV Exemption"],
  sources: [{ title: "ATO — Fringe benefits tax", url: "https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/fringe-benefits-tax" }],
  files: [
    { num: "01", slug: "fbt-01", name: "Your FBT Exposure Estimate", desc: "Estimated FBT liability across cars, entertainment, and other benefits.", tier: 1, content: `<h2>Your FBT Position</h2><div class="action-box"><h3>FBT Calculation — Cars (Statutory)</h3><p>FBT = Car Base Value × 20% × 2.0802 × 47%</p><p>Example: $60,000 car → $60,000 × 20% × 2.0802 × 47% = $11,731 × 47% = $5,634</p></div><p>Source: <a href="https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/fringe-benefits-tax">ATO — Fringe benefits tax</a></p>` },
    { num: "02", slug: "fbt-02", name: "FBT Risk Checklist", desc: "Every benefit type and whether it triggers FBT.", tier: 1, content: `<h2>FBT Benefit Checklist</h2><table><tr><th>Benefit</th><th>FBT Status</th></tr><tr><td>Company car — private use</td><td>FBT applies — statutory or operating cost</td></tr><tr><td>Electric vehicle (BEV/PHEV under threshold)</td><td>Exempt since 1 July 2022</td></tr><tr><td>Car parking near CBD</td><td>FBT applies if eligible parking space</td></tr><tr><td>Meals — restaurant with clients AND employees</td><td>FBT applies — entertainment</td></tr><tr><td>Staff gift under $300 — infrequent</td><td>Exempt — minor benefit</td></tr><tr><td>Loan to employee below benchmark rate</td><td>FBT applies on interest shortfall</td></tr></table>` },
    { num: "03", slug: "fbt-03", name: "Car Method Optimiser", desc: "Compare statutory formula vs operating cost for your vehicles.", tier: 1, content: `<h2>Which Method Is Better for Your Car?</h2><p>The operating cost method is better when business use is high. Use this comparison:</p><table><tr><th>Business Use %</th><th>Statutory FBT ($60k car)</th><th>Operating Cost FBT (approx)</th></tr><tr><td>25% business</td><td>$5,640</td><td>$4,230 — marginal saving</td></tr><tr><td>50% business</td><td>$5,640</td><td>$2,820 — significant saving</td></tr><tr><td>75% business</td><td>$5,640</td><td>$1,410 — major saving</td></tr><tr><td>90% business</td><td>$5,640</td><td>$564 — 90% saving</td></tr></table><div class="info-box">Operating cost method requires a current ATO-compliant 12-week logbook.</div>` },
    { num: "04", slug: "fbt-04", name: "Safe Benefit Structuring Guide", desc: "How to provide benefits in a way that minimises or eliminates FBT.", tier: 1, content: `<h2>FBT-Safe Benefit Structures</h2><ul><li><strong>Electric vehicles:</strong> Provide a BEV or PHEV under $89,332 — zero FBT</li><li><strong>Minor gifts:</strong> Keep under $300 per employee per occasion — exempt</li><li><strong>Work-related items:</strong> Laptops, phones, tools — portable electronic devices exempt once per year</li><li><strong>Employee contributions:</strong> Have employees contribute to private use costs — reduces taxable value</li><li><strong>Salary packaging:</strong> Novated lease structures can shift FBT and income tax advantages</li></ul>` },
    { num: "05", slug: "fbt-05", name: "Your Accountant Brief", desc: "FBT questions to take to your next meeting.", tier: 1, content: `<div class="info-box">Print or forward to your accountant before the FBT return is due.</div><h2>FBT Questions</h2><div class="action-box"><h3>Question 1</h3><p>"What is our total FBT liability for the year ended 31 March 2026?"</p></div><h3>Question 2</h3><p>"Should we switch to operating cost method for the company vehicles?"</p><h3>Question 3</h3><p>"Which entertainment expenses triggered FBT this year?"</p>` },
    { num: "06", slug: "fbt-06", name: "Full FBT Audit Report", desc: "Complete FBT audit across all benefit types in the business.", tier: 2, content: `<h2>Full FBT Audit — All Benefit Categories</h2><p>A comprehensive FBT audit covers every benefit type provided to employees and directors during the FBT year.</p><h3>Audit Categories</h3><ul><li>Car fringe benefits — all vehicles with private access</li><li>Car parking benefits — employer-provided or reimbursed</li><li>Loan benefits — company loans at below-benchmark rates</li><li>Entertainment — meals, functions, sporting events</li><li>Property benefits — goods provided at below-market value</li><li>Residual benefits — any other non-cash benefit</li></ul>` },
    { num: "07", slug: "fbt-07", name: "Payroll Integration Plan", desc: "How to integrate FBT management into payroll systems.", tier: 2, content: `<h2>FBT and Payroll Integration</h2><p>FBT is most efficiently managed when benefits are captured at the payroll level rather than reconstructed at return time.</p><div class="action-box"><h3>Payroll System Actions</h3><p>Tag all non-cash benefits in the payroll system as they occur</p><p>Capture employee contributions immediately</p><p>Flag reportable fringe benefits on payment summaries</p><p>Maintain logbook records in the same system as vehicle costs</p></div>` },
    { num: "08", slug: "fbt-08", name: "Annual FBT Compliance Framework", desc: "A year-round system to manage FBT obligations and minimise exposure.", tier: 2, content: `<h2>Annual FBT Compliance Calendar</h2><table><tr><th>Month</th><th>Action</th></tr><tr><td>April</td><td>FBT year starts — review benefit arrangements</td></tr><tr><td>May (prior year)</td><td>Lodge FBT return and pay liability</td></tr><tr><td>June</td><td>Mid-year review of car log books and benefit accruals</td></tr><tr><td>October</td><td>Logbook validity check — update if 5 years elapsed</td></tr><tr><td>February-March</td><td>Final FBT year benefit review — quantify all benefits</td></tr><tr><td>March 31</td><td>FBT year ends</td></tr></table>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "Company owns a dual-cab ute used for inspection visits to the Rockingham investment property. Gary also uses it for personal trips most weekends. No logbook has ever been kept.", painPoint: "Gary has never lodged an FBT return. He assumed the ute was a work vehicle and FBT did not apply to him. His accountant has never raised it.", discovery: "Gary's accountant mentioned in passing that private use of a company vehicle attracts FBT. Gary nodded but later realised he had no idea what the liability might be or whether he needed to file anything.", voice: "Gary is not interested in the technical detail. He wants to know: does he owe FBT, how much, and what does he need to do before 21 May." },
  story: { hook: "The ute had been in the company name for four years. Gary used it for everything — inspecting the Rockingham property, picking up materials, weekend trips down to Mandurah with Sandra.", setup: ["He had not thought of it as a taxable benefit. It was a work vehicle. That was how it had always felt. The company needed a vehicle, he drove it, that was the end of the analysis.", "When his accountant mentioned FBT in passing at their September meeting, Gary had assumed it did not apply to him. Small setup, retired bloke, one vehicle. Surely there was a threshold.", "There was not. When Gary looked into it properly, the statutory formula method applied 20% of the ute's $62,000 purchase price regardless of how much business driving he actually did. The number came out at $12,400 of taxable value. At 47% FBT, that was $5,828 per year — for four years."], revelation: "The calculator showed Gary's estimated FBT liability for the current year at $5,828 and flagged that a logbook had never been kept. Without a logbook, the statutory method applied and there was no way to reduce the liability. It also showed that if Gary had maintained a logbook showing 70% business use, his liability would have been $1,748 — a difference of $4,080 per year.", resolution: "Gary called his accountant the next day. The news was that prior years would need to be reviewed — FBT returns had not been lodged. His accountant advised voluntary disclosure to the ATO to reduce penalties. Going forward, Gary started a logbook immediately. He also asked whether switching to an electric ute would eliminate the FBT issue entirely. It would — if the vehicle was under the luxury car tax threshold. That conversation was added to the agenda for their next meeting." },
  calendarTitle: "FBT — Key Dates",
  tier1Calendar: [{ uid: "fbt-return", summary: "FBT Return Due — 21 May 2026", description: "FBT return and payment for FBT year ended 31 March 2026 due 21 May.", date: "20260521" }],
  tier2Calendar: [{ uid: "fbt-audit", summary: "FBT — Conduct annual benefit audit", description: "Review all benefits provided during FBT year ended 31 March.", date: "relative:+7days" }, { uid: "fbt-return", summary: "FBT Return Due — 21 May 2026", description: "Lodge and pay FBT return.", date: "20260521" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_FBT_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_FBT_147" },
  monitorUrls: ["https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/fringe-benefits-tax"],
  sidebarNumbers: [{ label: "FBT rate", value: "47%" }, { label: "Car benefit rate", value: "20% of value" }, { label: "Minor benefit", value: "Under $300" }, { label: "Return due", value: "21 May" }],
  sidebarMathsTitle: "FBT — what triggers it and what doesn't",
  sidebarMathsIncludes: [
    "Car with private use — statutory: 20% of base value",
    "Car with logbook — operating cost: actual private use %",
    "Meals/entertainment over $300/person — taxable at 47%",
    "Loans below ATO benchmark rate — interest shortfall taxable",
    "Housing, property, expense reimbursements — if private benefit",
  ],
  sidebarMathsExcludes: [
    "NOT minor benefits under $300/occasion — infrequent only",
    "NOT work-related portable devices — one per employee",
    "NOT eligible EVs (post 1 Jul 2022, under LCT threshold)",
    "NOT work-only car use — if genuinely no private access",
  ],
  sidebarMathsNote: "Source: ATO — FBT · FBTAA 1986 · s8, s9, s40, s58P",
  howToSteps: [
    { position: 1, name: "Select benefit types", text: "Select all benefits provided — car, meals, loans, reimbursements, housing." },
    { position: 2, name: "Answer routing questions", text: "Private use, logbook, EV status, entertainment type — each routes to correct treatment." },
    { position: 3, name: "Get benefit-by-benefit exposure", text: "See each benefit classified as high/medium/low risk with the specific ATO rule." },
    { position: 4, name: "Get your fix plan", text: "Receive classification memo, method comparison, record gaps, and accountant questions." },
  ],
  successPromptFields: [
    { key: "benefit_types",   label: "Benefit types provided",           defaultVal: "car" },
    { key: "high_risks",      label: "Number of high-risk benefits",     defaultVal: "1" },
    { key: "status",          label: "FBT exposure verdict",             defaultVal: "HIGH FBT EXPOSURE" },
    { key: "strongest_risk",  label: "Strongest FBT risk trigger",       defaultVal: "No logbook — statutory method applies" },
    { key: "record_quality",  label: "Record quality",                   defaultVal: "some" },
    { key: "tier",            label: "Product tier purchased",           defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "fbtExposureSummary",
    "benefitByBenefitClassification",
    "carMethodComparison",
    "entertainmentTreatment",
    "evExemptionAnalysis",
    "minorBenefitExemptions",
    "recordGapsList",
    "strongestRiskTrigger",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "fbtExposureSummary",
    "benefitByBenefitClassification",
    "carMethodComparison",
    "entertainmentTreatment",
    "evExemptionAnalysis",
    "minorBenefitExemptions",
    "recordGapsList",
    "annualFBTWorkflow",
    "entertainmentPolicySettings",
    "evidenceTemplates",
    "payrollReportingFlags",
    "remediationPlan",
    "strongestRiskTrigger",
  ],
};
