import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "division-7a-loan-trap", name: "Division 7A Loan Trap Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/division-7a-loan-trap", url: "https://taxchecknow.com/au/check/division-7a-loan-trap", apiRoute: "/api/rules/division-7a-loan-trap",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "ITAA 1936 — Division 7A", legislation: "Income Tax Assessment Act 1936 — Division 7A (Loans to shareholders and associates)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Division 7A Loan Fix Plan", tagline: "Is your director loan about to become taxable income?", value: "A personalised Div 7A audit — minimum repayment calculation, loan compliance check, and risk classification.", cta: "Get My Div 7A Fix Plan — $67 →", productKey: "au_67_division_7a_loan_trap", envVar: "STRIPE_AU_DIV7A_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Division 7A Loan Restructure System", tagline: "Restructure your loans before ATO deems them dividends", value: "Full loan restructure plan, multi-year repayment strategy, and tax-efficient structuring to exit the Div 7A trap.", cta: "Get My Div 7A System — $147 →", productKey: "au_147_division_7a_loan_trap", envVar: "STRIPE_AU_DIV7A_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-06-30T23:59:59.000+10:00", display: "30 June 2026", short: "30 Jun 2026", description: "EOFY — minimum Div 7A repayments must be made before 30 June each year", urgencyLabel: "EOFY DEADLINE", countdownLabel: "Countdown to 30 June 2026 — Div 7A minimum repayments due" },
  h1: "Division 7A 2026: Is Your Director Loan About to Become Taxable Income?", metaTitle: "Division 7A Loan Trap Australia 2026 — Is Your Director Loan a Deemed Dividend? | TaxCheckNow", metaDescription: "Under Division 7A, loans from a company to a shareholder or associate become deemed dividends unless properly documented and repaid. The minimum repayment must be made before 30 June each year. Free calculator shows your risk in 2 minutes.", canonical: "https://taxchecknow.com/au/check/division-7a-loan-trap",
  answerHeadline: "The answer — ATO confirmed April 2026",
  answerBody: [
    "Under Division 7A of ITAA 1936, if a private company lends money to a shareholder or their associate without a complying loan agreement, the loan is treated as an unfranked dividend — fully taxable at the shareholder's marginal rate. This applies even if the loan was never intended to be a dividend and even if the company never formally declared one.",
    "To avoid the deemed dividend, loans must be documented with a written agreement before the company's lodgement day, charged at the ATO benchmark interest rate (currently 8.27% for 2025/26), and repaid with minimum annual repayments over a maximum of 7 years (25 years for loans secured by a registered mortgage over real property).",
    "The most common trap: directors draw cash from their company without paperwork, the balance accumulates over years, and at tax time the accountant discovers the entire amount is a deemed dividend. On a $200,000 loan at a 47% marginal rate, that is $94,000 in unexpected tax.",
  ],
  answerSource: "Source: ATO — Division 7A · ITAA 1936",
  mistakesHeadline: "What most people (and AI) get wrong about Division 7A",
  mistakes: [
    "It's just a loan — I'll pay it back later — wrong. Division 7A does not care about your intention to repay. If a complying loan agreement is not in place before lodgement day, the loan is reclassified as an unfranked deemed dividend on that date — retroactively. You cannot fix it after lodgement day by repaying the money.",
    "The deadline is 30 June — wrong. The critical deadline is lodgement day — the earlier of the date the company return is due and the date it is actually lodged. Many taxpayers who lodge early accidentally trigger Division 7A earlier than they expected. 30 June is the minimum repayment deadline, not the agreement deadline.",
    "Small withdrawals don't matter — wrong. The ATO specifically targets repeated small drawings from private companies because they are a common way owners extract profits tax-free. Even $5,000 withdrawals across a year can accumulate into a significant deemed dividend if not documented.",
    "I used the money for the business so it's fine — wrong. The use of the funds is irrelevant for Division 7A purposes. Even if the money went back into a related business, the company-to-shareholder payment is still caught unless it is properly documented as a complying loan.",
  ],
  chainVisual: { label: "How Division 7A works — the trap and the fix", broken: "Draw cash from company → no paperwork → deemed dividend at 47%  ❌", fixed: "Written loan agreement + benchmark interest + minimum repayments  ✔  Loan stays as loan" },
  brackets: [
    { label: "No outstanding loans from the company", value: 1, status: "clear" },
    { label: "Loan with written agreement — repayments on track", value: 2, status: "approaching" },
    { label: "Loan exists — not sure if agreement is in place", value: 3, status: "trap" },
    { label: "Missed minimum repayment last year", value: 4, status: "deep_trap" },
    { label: "Drawings taken without any documentation", value: 5, status: "deep_trap" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "loanBalance", label: "What is the current loan balance from your company?", subLabel: "Total amount drawn from company and not repaid", options: [{ label: "Under $50k", value: 25000 }, { label: "$50k-$150k", value: 100000 }, { label: "$150k-$300k", value: 225000 }, { label: "Over $300k", value: 400000 }], default: 100000 },
    { type: "buttonGroup", stateKey: "loanStatus", label: "What is the status of the loan agreement?", subLabel: "Written Div 7A loan agreement in place?", options: [{ label: "Written agreement in place", value: "compliant" }, { label: "Not sure if agreement exists", value: "unsure" }, { label: "No agreement — informal drawings", value: "none" }, { label: "Agreement but missed repayments", value: "missed" }], default: "unsure" },
    { type: "twoButton", stateKey: "securedByProperty", label: "Is the loan secured by a registered mortgage over real property?", subLabel: "Secured loans can have 25-year repayment terms", options: [{ label: "No — unsecured loan", value: false }, { label: "Yes — secured by property", value: true }], default: false },
  ],
  tierAlgorithm: { description: "loanStatus unsure, none, or missed → tier2. loanBalance over 150000 → tier2. Otherwise tier1.", tier2Conditions: ["(loanBalance as number) > 150000", 'loanStatus === "none"', 'loanStatus === "missed"', 'loanStatus === "unsure"'], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "Division 7A: company loans to shareholders or associates are deemed dividends unless a written loan agreement exists before lodgement day, charged at ATO benchmark rate (8.27% in 2025/26), with minimum annual repayments over maximum 7 years (25 years if secured by real property mortgage). Missed minimum repayment = deemed dividend for that year's shortfall." },
  calculatorClarification: { label: "Key clarification", body: "The benchmark interest rate changes annually. For 2025/26 it is 8.27%. Your minimum repayment must be calculated using the correct rate for each year of the loan. Using the wrong rate means your repayments may be insufficient — creating a deemed dividend for the shortfall." },
  countdownLabel: "Countdown to 30 June 2026 — minimum repayments due",
  countdownStats: [
    { label: "Benchmark rate 2025/26", value: "8.27%", sub: "interest rate for Div 7A loans" },
    { label: "Max loan term (unsecured)", value: "7 years", sub: "secured by property: 25 years" },
    { label: "On $200k at 47%", value: "$94,000", sub: "deemed dividend tax if no agreement", red: true },
    { label: "Repayment deadline", value: "30 June", sub: "minimum repayment due each EOFY", red: true },
  ],
  geoBlockTitle: "AI extraction block — Division 7A Australia 2026",
  geoBlockH2: "Division 7A Loan Rules — confirmed 2026",
  geoBodyParagraph: "Under Division 7A of the Income Tax Assessment Act 1936, loans made by a private company to a shareholder or their associate are treated as unfranked dividends unless specific conditions are met. To avoid deemed dividend treatment, a written loan agreement must be in place before the company's lodgement day, the loan must be charged interest at no less than the ATO benchmark interest rate (8.27% for 2025/26), and minimum annual repayments must be made. The maximum loan term is 7 years for unsecured loans and 25 years for loans secured by a registered mortgage over real property. A missed minimum repayment results in a deemed dividend equal to the shortfall for that income year. The deemed dividend is unfranked, meaning no franking credits offset the tax liability.",
  geoFormula: "Minimum Annual Repayment = Loan Balance × (Benchmark Rate / (1 - (1 + Benchmark Rate)^(-n))) where n = remaining loan term in years. Deemed Dividend = Full loan balance if no agreement, or annual shortfall if minimum repayment missed.",
  geoFacts: [
    { label: "Benchmark interest rate 2025/26", value: "8.27%" },
    { label: "Maximum loan term (unsecured)", value: "7 years" },
    { label: "Maximum loan term (secured by real property)", value: "25 years" },
    { label: "Agreement deadline", value: "Before company lodgement day" },
    { label: "Missed repayment consequence", value: "Deemed dividend for shortfall amount" },
    { label: "Legislative anchor", value: "ITAA 1936 — Division 7A" },
  ],
  workedExamplesH2: "Four Division 7A scenarios",
  workedExamplesColumns: ["Scenario", "Loan Balance", "Status", "Tax Risk", "Action"],
  workedExamples: [
    { name: "Clean loan", setup: "Written agreement, repayments on track, correct interest rate", income: "$100k", status: "COMPLIANT" },
    { name: "No agreement", setup: "Director drew $180k over 3 years — no paperwork", income: "$180k", status: "$84,600 DEEMED DIVIDEND TAX" },
    { name: "Missed repayment", setup: "Agreement exists but $12k minimum missed last June", income: "$12k", status: "$5,640 DEEMED DIVIDEND TAX" },
    { name: "Property secured", setup: "$350k loan secured by registered mortgage — 25yr term", income: "$350k", status: "MANAGEABLE — LONG TERM" },
  ],
  comparisonH2: "Loan types and Division 7A treatment",
  comparisonColumns: ["Loan Type", "Max Term", "Agreement Required", "Consequence If Not Compliant"],
  comparisonRows: [
    { position: "Unsecured loan", metric1: "7 years", metric2: "Yes — before lodgement day", bestMove: "Deemed unfranked dividend" },
    { position: "Secured by real property", metric1: "25 years", metric2: "Yes — registered mortgage", bestMove: "Deemed unfranked dividend" },
    { position: "No agreement — informal drawings", metric1: "None", metric2: "N/A — already non-compliant", bestMove: "Full balance deemed dividend" },
    { position: "Unpaid trust entitlement", metric1: "7 years", metric2: "Sub-trust or Div 7A loan", bestMove: "Deemed dividend if not addressed" },
  ],
  toolsH2: "How to fix a Division 7A problem",
  toolsColumns: ["Fix", "How It Works", "Best For"],
  toolsRows: [
    { tool: "Formalise the loan agreement", effect: "Convert informal drawings to complying Div 7A loan", note: "Must be done before lodgement day — timing critical" },
    { tool: "Declare a dividend", effect: "Use franking credits to offset tax on deemed dividend", note: "Company must have sufficient franking account balance" },
    { tool: "Pay a salary or bonus", effect: "Company pays salary — deductible, reduces loan balance", note: "Company gets deduction, director pays income tax" },
    { tool: "Secured loan restructure", effect: "Register mortgage — extend term to 25 years", note: "Reduces annual minimum repayment significantly" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: You can avoid Division 7A by repaying the loan before the end of the financial year", correct: "Reality: The loan agreement must be in place before the company's lodgement day — not just the end of the financial year. If you repay the loan after lodgement day without a proper agreement, it is still a deemed dividend. Timing of the agreement, not just the repayment, is critical." },
    { wrong: "ChatGPT says: Division 7A only applies to loans — not to use of company assets", correct: "Reality: Division 7A also applies to payments and the use of company property. If a shareholder uses a company car, holiday house, or other asset without paying market rate, that use can also constitute a deemed dividend under Division 7A." },
    { wrong: "ChatGPT says: If my company has franking credits, a Division 7A deemed dividend is tax-free", correct: "Reality: Division 7A deemed dividends are specifically unfranked. Franking credits cannot be attached to a deemed dividend. The full amount is included in the shareholder's assessable income without any franking credit offset." },
  ],
  faqs: [
    { question: "What is Division 7A?", answer: "Division 7A is a section of ITAA 1936 that prevents private company profits from being distributed to shareholders tax-free through loans, payments, or use of assets. If a company lends money to a shareholder (or their associate) without a complying loan agreement, the ATO treats the loan as an unfranked dividend — taxable at the shareholder's marginal rate." },
    { question: "What is the ATO benchmark interest rate?", answer: "The ATO sets a benchmark interest rate for Division 7A loans each year. For 2025/26 it is 8.27%. Div 7A loans must charge interest at no less than this rate. If the rate is lower than the benchmark, the difference may be treated as an additional deemed dividend." },
    { question: "What is the minimum repayment?", answer: "Each year you must make a minimum principal and interest repayment calculated using the benchmark interest rate and remaining loan term. Missing the minimum repayment — even partially — results in a deemed dividend equal to the shortfall for that year. The ATO provides a minimum repayment calculator on its website." },
    { question: "What if I cannot afford to repay the loan?", answer: "If cash repayment is not possible, options include: declaring a fully-franked dividend to offset the loan balance (if the company has franking credits), paying a salary or bonus to reduce the balance, or restructuring the loan as a property-secured facility to extend the term to 25 years. Get advice before the lodgement deadline." },
    { question: "Does Division 7A apply to trust entitlements?", answer: "Yes — unpaid present entitlements (UPEs) from a trust to a private company can also trigger Division 7A. If a trust distributes income to a corporate beneficiary but does not actually pay the entitlement, the ATO may treat it as a loan from the company back to the trust, subject to Division 7A." },
  ],
  accountantQuestionsH2: "Ask these before 30 June",
  accountantQuestions: [
    { q: "What is my current loan balance from the company — and is a complying Division 7A agreement in place?", why: "Many directors do not know their loan balance. If no agreement exists, the full balance may be a deemed dividend in this financial year." },
    { q: "What is the minimum repayment I need to make before 30 June — and has it been calculated correctly using the 2025/26 benchmark rate?", why: "Missing the minimum repayment — or using the wrong rate — creates a deemed dividend for the shortfall." },
    { q: "Does the company have sufficient franking credits to declare a fully-franked dividend to offset or eliminate the loan?", why: "If the company has accumulated franking credits, a fully-franked dividend can offset the tax on the deemed dividend, reducing the cash impact." },
    { q: "Are there any trust entitlements owed to the company that might create a Division 7A exposure?", why: "Unpaid trust entitlements to a corporate beneficiary can create a secondary Division 7A loop that many accountants miss." },
    { q: "Should we restructure the loan as a property-secured facility to extend the term and reduce minimum repayments?", why: "A 25-year secured loan has much lower minimum repayments than a 7-year unsecured loan on the same balance. If you own property, this is often the most practical fix." },
  ],
  crosslink: { title: "Running a family trust? Check your trust distribution position.", body: "Unpaid trust entitlements to a company can trigger Division 7A. Check your trust structure.", url: "/au/check/small-business-cgt-concessions", label: "Check your business structure →" },
  lawBarSummary: "Division 7A: company loans to shareholders or associates are deemed unfranked dividends unless written loan agreement in place before lodgement day, benchmark interest rate charged (8.27% in 2025/26), and minimum repayments made. Max term 7 years unsecured, 25 years secured by real property. Under ITAA 1936 Division 7A.",
  lawBarBadges: ["ATO", "ITAA 1936", "Division 7A", "Benchmark Rate 8.27%"],
  sources: [{ title: "ATO — Division 7A", url: "https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/income/dividends-and-franking/division-7a-dividends" }],
  files: [
    { num: "01", slug: "d7a-01", name: "Your Division 7A Risk Assessment", desc: "Your loan compliance status and deemed dividend risk calculation.", tier: 1, content: `<h2>Your Div 7A Position</h2><div class="action-box"><h3>The Risk Calculation</h3><p>No agreement = full balance is deemed dividend</p><p>Missed repayment = shortfall is deemed dividend</p><p>Deemed dividend is unfranked — taxed at marginal rate</p></div><p>Source: <a href="https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/income/dividends-and-franking/division-7a-dividends">ATO — Division 7A</a></p>` },
    { num: "02", slug: "d7a-02", name: "Minimum Repayment Calculator", desc: "Calculate the exact minimum repayment due before 30 June.", tier: 1, content: `<h2>Minimum Repayment Calculation</h2><p>The minimum annual repayment depends on your loan balance, the ATO benchmark rate, and the remaining loan term.</p><div class="action-box"><h3>2025/26 Benchmark Rate: 8.27%</h3><p>Unsecured 7-year loan of $100,000:</p><p>Approximate minimum repayment: $19,808 per year</p><p>Use the ATO's online calculator for your exact amount.</p></div><table><tr><th>Loan Balance</th><th>7yr Unsecured (approx)</th><th>25yr Secured (approx)</th></tr><tr><td>$50,000</td><td>$9,904/yr</td><td>$4,540/yr</td></tr><tr><td>$100,000</td><td>$19,808/yr</td><td>$9,080/yr</td></tr><tr><td>$200,000</td><td>$39,616/yr</td><td>$18,160/yr</td></tr></table>` },
    { num: "03", slug: "d7a-03", name: "Loan Compliance Template Guide", desc: "What a complying Division 7A loan agreement must contain.", tier: 1, content: `<h2>Division 7A Loan Agreement — Required Elements</h2><ul class="checklist"><li>Names of lender (company) and borrower (shareholder/associate)</li><li>Loan amount and date</li><li>Interest rate — must be at least ATO benchmark rate</li><li>Loan term — maximum 7 years (25 years if secured by real property)</li><li>Minimum repayment schedule</li><li>Security details if applicable</li><li>Signatures of both parties</li><li>Date — must be before company lodgement day</li></ul><div class="warning-box"><strong>Critical:</strong> The agreement must be in place BEFORE the company's lodgement day. A backdated or late agreement does not protect against deemed dividend treatment.</div>` },
    { num: "04", slug: "d7a-04", name: "Risk Classification Summary", desc: "Your Division 7A risk level and the priority actions.", tier: 1, content: `<h2>Risk Classification</h2><table><tr><th>Situation</th><th>Risk Level</th><th>Action Required</th></tr><tr><td>Agreement in place, repayments on track</td><td>Low</td><td>Annual minimum repayment check</td></tr><tr><td>Agreement exists, missed one repayment</td><td>Medium</td><td>Deemed dividend for shortfall — declare and pay</td></tr><tr><td>No agreement — informal drawings</td><td>Critical</td><td>Formalise before lodgement day immediately</td></tr><tr><td>Drawings accumulated over multiple years</td><td>Critical</td><td>Restructure — specialist advice required</td></tr></table>` },
    { num: "05", slug: "d7a-05", name: "Your Accountant Brief", desc: "Print and take to your next meeting — Div 7A questions your adviser must answer.", tier: 1, content: `<div class="info-box">How to use: print or forward to your accountant before EOFY.</div><h2>Client Div 7A Status</h2><div class="action-box"><h3>Question 1</h3><p>"What is my current loan balance from the company — and is a complying agreement in place?"</p></div><h3>Question 2</h3><p>"What is the minimum repayment I need to make before 30 June?"</p><h3>Question 3</h3><p>"Should we restructure as a property-secured loan to extend the term?"</p>` },
    { num: "06", slug: "d7a-06", name: "Full Loan Restructure Plan", desc: "All options to fix a non-compliant Division 7A loan.", tier: 2, content: `<h2>Loan Restructure Options</h2><table><tr><th>Option</th><th>How It Works</th><th>Tax Impact</th></tr><tr><td>Formalise as Div 7A loan</td><td>Written agreement + benchmark interest + repayments</td><td>No deemed dividend — loan stays as loan</td></tr><tr><td>Fully-franked dividend</td><td>Company declares dividend, offsets loan balance</td><td>Tax offset by franking credits</td></tr><tr><td>Salary or bonus</td><td>Company pays wage — deductible, reduces balance</td><td>Income tax at marginal rate — company deduction</td></tr><tr><td>Property-secured facility</td><td>Extend to 25-year term — reduce annual repayment</td><td>Lower minimum repayment — manageable cashflow</td></tr></table>` },
    { num: "07", slug: "d7a-07", name: "Multi-Year Repayment Strategy", desc: "Model your loan repayment over the full term.", tier: 2, content: `<h2>Multi-Year Repayment Model</h2><p>Planning your Division 7A repayments over the full loan term reduces surprises and helps with cashflow planning.</p><div class="action-box"><h3>Strategy Considerations</h3><p>Pay more than the minimum when cashflow allows — reduces balance faster</p><p>Coordinate repayment timing with dividend or salary payments from the company</p><p>Review the benchmark rate each year — it changes annually</p><p>If the company has franking credits building up, consider a franked dividend strategy to accelerate the paydown</p></div>` },
    { num: "08", slug: "d7a-08", name: "Tax Minimisation Structuring Plan", desc: "Use franked dividends and salary to exit the Division 7A loan tax-efficiently.", tier: 2, content: `<h2>Tax-Efficient Exit Strategy</h2><p>Exiting a large Division 7A loan requires careful planning across multiple income years to minimise tax.</p><h2>The Optimal Approach</h2><ol><li>Quantify the full loan balance and accrued interest</li><li>Assess the company's franking account balance</li><li>Model: franked dividend vs salary repayment vs property security</li><li>Spread the repayment/exit across 2-3 income years to avoid bracket creep</li><li>Time larger payments in lower-income years (e.g. post-retirement)</li></ol>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "$3.4M SMSF. Owns a small Pty Ltd used for investment property management. Has been drawing money from the company account for years to cover personal expenses.", painPoint: "Gary and Sandra use the company account like a personal account. The accountant set up a loan years ago. Gary is not sure if the paperwork is current or whether the repayments are being made correctly.", discovery: "Gary's accountant mentioned Division 7A at their annual meeting but did not go into detail. Gary came home, googled it, and got three different explanations. He needed the plain English version.", voice: "Gary does not want theory. He wants to know: is his loan going to create a tax bill, and what does he need to do before 30 June." },
  story: { hook: "Gary had been drawing money from his company account for as long as he could remember. Small amounts mostly — $3,000 here, $5,000 there. The accountant had set up a loan years ago.", setup: ["The company was a simple structure. He and Sandra owned it. It held one investment property in Rockingham and managed a few smaller assets. When they needed money for personal things — a holiday, some house repairs, helping Jess with her first car — they had transferred it from the company account. The accountant had always sorted it in the annual accounts.", "At their last meeting in September, the accountant had said something about Division 7A and the benchmark rate going up. Gary had nodded. He had not really followed the detail. The accountant was good — he trusted her. But he had not asked the follow-up questions he probably should have.", "After the meeting Gary looked at the company account online. The loan balance was showing $87,000. He had not realised it had grown that much. He typed Division 7A into Google that evening."], revelation: "When Gary ran the calculator, it flagged the $87,000 balance as medium-to-high risk. The key question was whether the loan agreement was still current and whether the minimum repayments had been made every June. Gary realised he did not actually know the answer to either question. He assumed his accountant had handled it — but he had never specifically confirmed it.", resolution: "Gary called the accountant the next morning and asked directly: is the Div 7A agreement current, and have the minimum repayments been made for 2024/25? The answer was yes on both counts — but the 2025/26 minimum repayment of $19,800 was due before 30 June and had not been scheduled yet. They set up the transfer that week. Gary also asked whether restructuring the loan as a property-secured facility would reduce the annual minimum — it would, by about $11,000 a year. That conversation was scheduled for August." },
  calendarTitle: "Division 7A — Key Dates",
  tier1Calendar: [{ uid: "d7a-repayment", summary: "Division 7A — Minimum repayment due", description: "Minimum Div 7A loan repayment must be made before 30 June each year to avoid deemed dividend.", date: "20260630" }],
  tier2Calendar: [{ uid: "d7a-review", summary: "Division 7A — Review loan agreement and repayment", description: "Confirm agreement is current and minimum repayment calculated correctly.", date: "relative:+14days" }, { uid: "d7a-repayment", summary: "Division 7A — Minimum repayment due by 30 June", description: "Make minimum repayment before EOFY.", date: "20260630" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_DIV7A_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_DIV7A_147" },
  monitorUrls: ["https://www.ato.gov.au/businesses-and-organisations/income-deductions-and-concessions/income/dividends-and-franking/division-7a-dividends"],
  sidebarNumbers: [{ label: "Benchmark rate 2025/26", value: "8.27%" }, { label: "Max term unsecured", value: "7 years" }, { label: "Max term secured", value: "25 years" }, { label: "Repayment deadline", value: "30 June" }],
  sidebarMathsTitle: "Division 7A — the rules that decide everything",
  sidebarMathsIncludes: [
    "Agreement: written, signed BEFORE lodgement day",
    "Lodgement day: earlier of due date or actual lodge date",
    "Repayments: minimum amount before 30 June every year",
    "Interest: at ATO benchmark rate (8.27% for 2025-26)",
    "Terms: unsecured max 7 years, secured max 25 years",
  ],
  sidebarMathsExcludes: [
    "NOT fixed by repaying after lodgement day",
    "NOT covered by franking credits — unfranked dividend",
    "NOT the same as 30 June — lodgement day is earlier",
    "NOT exempt because it was used for business",
  ],
  sidebarMathsNote: "Source: ATO — Division 7A · ITAA 1936 s109D · ATO guidance 2025-26",
  howToSteps: [
    { position: 1, name: "Select your relationship", text: "Shareholder, associate, or trust linked to a private company — Division 7A only applies to connected parties." },
    { position: 2, name: "Select transaction type", text: "Cash withdrawal, private expense, asset use, debt forgiveness, or trust UPE — each has different rules." },
    { position: 3, name: "Check lodgement day and agreement", text: "The critical question — has lodgement day passed without a complying agreement?" },
    { position: 4, name: "Get your Division 7A verdict", text: "Compliant / at risk / deemed dividend — with specific action steps and accountant questions." },
  ],
  successPromptFields: [
    { key: "transaction_type",    label: "Division 7A transaction type",    defaultVal: "loan" },
    { key: "has_agreement",       label: "Written loan agreement in place",  defaultVal: "false" },
    { key: "is_deemed_dividend",  label: "Deemed dividend triggered",        defaultVal: "false" },
    { key: "status",              label: "Division 7A verdict",              defaultVal: "HIGH RISK" },
    { key: "strongest_risk",      label: "Strongest risk trigger",           defaultVal: "No complying loan agreement" },
    { key: "income_year",         label: "Income year of loan",              defaultVal: "current_year" },
    { key: "tier",                label: "Product tier purchased",           defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "division7aStatus",
    "loanClassification",
    "lodgementDayRisk",
    "agreementGapSummary",
    "minimumRepaymentRequired",
    "deemedDividendExposure",
    "remediationChecklist",
    "evidenceRequired",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "division7aStatus",
    "loanClassification",
    "lodgementDayRisk",
    "agreementGapSummary",
    "minimumRepaymentRequired",
    "deemedDividendExposure",
    "remediationChecklist",
    "evidenceRequired",
    "restructuringBlueprint",
    "repaymentSchedule",
    "upeAndTrustInteraction",
    "privateUseRemediation",
    "multiYearCompliancePlan",
  ],
};
