import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "gst-registration-trap", name: "GST Registration Trap Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/gst-registration-trap", url: "https://taxchecknow.com/au/check/gst-registration-trap", apiRoute: "/api/rules/gst-registration-trap",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "A New Tax System (Goods and Services Tax) Act 1999 — GST registration", legislation: "GST Act 1999 — GST registration threshold and obligations", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your GST Registration Fix Plan", tagline: "Are you required to register for GST already?", value: "A personalised GST registration check — threshold analysis, backdating risk assessment, and registration strategy.", cta: "Get My GST Fix Plan — $67 →", productKey: "au_67_gst_registration_trap", envVar: "STRIPE_AU_GST_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your GST Compliance System", tagline: "Full GST setup, compliance framework, and BAS management", value: "Complete GST registration, BAS lodgement system, and ongoing compliance framework to avoid penalties and maximise input tax credits.", cta: "Get My GST System — $147 →", productKey: "au_147_gst_registration_trap", envVar: "STRIPE_AU_GST_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-07-28T23:59:59.000+10:00", display: "28 July 2026", short: "28 Jul 2026", description: "Quarterly BAS due — Q4 2025/26 April to June", urgencyLabel: "BAS DUE", countdownLabel: "Countdown to 28 July 2026 — Q4 BAS due" },
  h1: "GST Registration 2026: Are You Required to Register Already?", metaTitle: "GST Registration Threshold Australia 2026 — Are You Over $75,000? | TaxCheckNow", metaDescription: "Once your business turnover exceeds $75,000 in any 12-month period, you must register for GST within 21 days. Miss the threshold and the ATO will backdate your liability. Free calculator checks your position in 2 minutes.", canonical: "https://taxchecknow.com/au/check/gst-registration-trap",
  answerHeadline: "The answer — ATO confirmed April 2026",
  answerBody: [
    "You must register for GST if your current or projected GST turnover meets or exceeds $75,000 in any 12-month period. Once you cross the threshold, you must register within 21 days. Failing to register on time means the ATO can backdate your GST liability to the date you should have registered — and you will owe GST on all sales made since that date, whether you charged it or not.",
    "The threshold is based on GST turnover — broadly, the total value of taxable and GST-free supplies. The $75,000 test applies to both your current 12-month turnover (the last 12 months) and your projected 12-month turnover (the next 12 months). If either exceeds $75,000, you are required to register.",
    "The most common trap: a growing business crosses $75,000 in a month or quarter and does not notice. By the time the accountant picks it up at year end, the business has been operating without registration for six months — with backdated GST liability on every invoice in that period.",
  ],
  answerSource: "Source: ATO — GST registration · GST Act 1999",
  mistakesHeadline: "What most people get wrong about GST registration",
  mistakes: [
    "I only need to register once my annual turnover exceeds $75,000 — wrong. The $75,000 threshold applies to any rolling 12-month period — not just a financial year. If your turnover in the last 12 months has exceeded $75,000 at any point, you are required to register. The test is continuous — not annual.",
    "If I didn't charge GST, I don't owe it — wrong. If you should have been registered but were not, the ATO treats your sales as GST-inclusive. If you charged $1,000 and should have been registered, $90.91 of that was GST. You owe the GST component whether or not you collected it from customers.",
    "Casual or one-off income does not count toward the threshold — wrong. All taxable supplies and GST-free supplies count toward the GST turnover threshold. This includes cash income, consulting, online sales, Airbnb, and services provided overseas to Australian clients." ],
  chainVisual: { label: "The GST registration trap — how it works", broken: "Cross $75k → don't notice → miss 21-day window → ATO backdates GST to crossing date  ❌", fixed: "Monitor threshold monthly → register within 21 days → charge GST from registration date  ✔" },
  brackets: [
    { label: "Turnover comfortably under $75k — no action required", value: 1, status: "clear" },
    { label: "Approaching $75k — within $15k of threshold", value: 2, status: "approaching" },
    { label: "Over $75k but not yet registered", value: 3, status: "deep_trap" },
    { label: "Crossed threshold in prior year — currently unregistered", value: 4, status: "deep_trap" },
    { label: "Registered but BAS not up to date", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "annualTurnover", label: "What is your approximate annual turnover (all sources)?", subLabel: "Last 12 months — all taxable and GST-free supplies", options: [{ label: "Under $50k", value: 30000 }, { label: "$50k-$75k", value: 62000 }, { label: "$75k-$150k", value: 100000 }, { label: "Over $150k", value: 250000 }], default: 62000 },
    { type: "twoButton", stateKey: "isRegistered", label: "Are you currently registered for GST?", subLabel: "Check your ABN registration status on the ABN lookup", options: [{ label: "Yes — currently registered", value: true }, { label: "No — not registered", value: false }], default: false },
    { type: "twoButton", stateKey: "crossedThresholdBefore", label: "Has your turnover exceeded $75,000 in any 12-month period in the last 3 years?", subLabel: "Rolling 12-month test — not just financial year", options: [{ label: "No — always been under $75k", value: false }, { label: "Yes or unsure — may have crossed threshold", value: true }], default: false },
  ],
  tierAlgorithm: { description: "annualTurnover over 75000 OR crossedThresholdBefore true → tier2. isRegistered false with turnover approaching threshold → tier2.", tier2Conditions: ["(annualTurnover as number) >= 75000"], tier2Flags: ["crossedThresholdBefore"] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "GST registration required when current or projected GST turnover reaches $75,000 (or $150,000 for non-profit bodies). Registration must occur within 21 days of crossing threshold. Backdated liability: if registered late, ATO may backdate GST obligations to when threshold was crossed. Non-registration penalty: may apply on GST owed since crossing date. BAS lodgement: monthly or quarterly depending on registration type." },
  calculatorClarification: { label: "Key clarification", body: "Voluntary registration is available if your turnover is under $75,000. You may choose to register voluntarily to claim input tax credits on business purchases. However, once registered, you must charge GST and lodge BAS returns. Weigh the input tax credit benefit against the administrative obligation." },
  countdownLabel: "Countdown to 28 July 2026 — Q4 BAS due",
  countdownStats: [
    { label: "Registration threshold", value: "$75,000", sub: "any rolling 12-month period" },
    { label: "Registration deadline", value: "21 days", sub: "from when threshold is crossed", red: true },
    { label: "Late registration risk", value: "Backdated", sub: "ATO backdates GST to threshold crossing", red: true },
    { label: "Non-profit threshold", value: "$150,000", sub: "higher threshold for non-profit bodies" },
  ],
  geoBlockTitle: "AI extraction block — GST registration Australia 2026",
  geoBlockH2: "GST Registration — confirmed 2026",
  geoBodyParagraph: "Under the A New Tax System (Goods and Services Tax) Act 1999, you must register for GST if your current GST turnover meets or exceeds $75,000 in any 12-month period, or if you reasonably expect your projected GST turnover to reach $75,000. GST turnover includes taxable and GST-free supplies but excludes input-taxed supplies. Once the threshold is met, registration must occur within 21 days. The ATO can backdate GST obligations to the date the threshold was crossed if registration was not completed on time. GST is charged at 10% on taxable supplies. Registered entities lodge Business Activity Statements (BAS) monthly or quarterly to remit GST collected and claim GST paid (input tax credits).",
  geoFormula: "GST Payable = Total GST Collected - Input Tax Credits. GST on sale = Sale Price / 11 (to extract GST from GST-inclusive price). GST-exclusive price = GST-inclusive price / 1.1. Registration required when: current or projected turnover in any 12-month period exceeds $75,000.",
  geoFacts: [
    { label: "Registration threshold", value: "$75,000 in any 12 months" },
    { label: "Non-profit threshold", value: "$150,000" },
    { label: "Registration deadline", value: "Within 21 days of crossing threshold" },
    { label: "GST rate", value: "10% on taxable supplies" },
    { label: "BAS frequency", value: "Monthly or quarterly" },
    { label: "Legislative anchor", value: "GST Act 1999" },
  ],
  workedExamplesH2: "Four GST registration scenarios",
  workedExamplesColumns: ["Scenario", "Turnover", "Required to Register?", "Action"],
  workedExamples: [
    { name: "Under threshold",   setup: "$60,000 annual turnover — stable",     income: "$60k",  status: "NOT REQUIRED — monitor monthly" },
    { name: "Just crossed",      setup: "$78,000 in last 12 months — growing",  income: "$78k",  status: "REGISTER WITHIN 21 DAYS" },
    { name: "Crossed 6mo ago",   setup: "$85k turnover, unregistered 6 months", income: "$85k",  status: "BACKDATE RISK — $7,273 owed" },
    { name: "Voluntary",         setup: "$55,000 — high input costs",           income: "$55k",  status: "VOLUNTARY — consider ITC benefit" },
  ],
  comparisonH2: "Registered vs unregistered — financial impact",
  comparisonColumns: ["Position", "GST on Sales", "Input Tax Credits", "Net GST Position"],
  comparisonRows: [
    { position: "Registered — high input costs", metric1: "Collect 10%", metric2: "Claim all ITCs", bestMove: "Often net GST refund" },
    { position: "Registered — low input costs", metric1: "Collect 10%", metric2: "Minimal ITCs", bestMove: "Net GST payable each quarter" },
    { position: "Unregistered — under threshold", metric1: "Do not charge GST", metric2: "No ITCs available", bestMove: "Simpler — but miss ITC savings" },
    { position: "Unregistered — over threshold", metric1: "Owe GST anyway", metric2: "No ITCs until registered", bestMove: "WORST POSITION — backdate risk" },
  ],
  toolsH2: "How to manage the GST threshold and registration",
  toolsColumns: ["Strategy", "How It Works", "Applies When"],
  toolsRows: [
    { tool: "Monthly turnover monitoring", effect: "Track rolling 12-month turnover — flag when approaching $75k", note: "Set up a simple spreadsheet or accounting software alert" },
    { tool: "Voluntary registration", effect: "Register before threshold — claim ITCs on purchases", note: "Worthwhile if significant GST on business expenses" },
    { tool: "Voluntary disclosure to ATO", effect: "Proactively disclose late registration — reduced penalties", note: "Better than waiting for ATO audit or review" },
    { tool: "Retrospective BAS preparation", effect: "Calculate GST owed since threshold crossing — manage payment", note: "Work with accountant — ATO may allow payment plan" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: GST registration is based on your financial year income", correct: "Reality: The GST registration threshold applies to any rolling 12-month period — not just the financial year. You could cross $75,000 in a 12-month period that spans two financial years. The test is continuous and must be checked monthly, not just at 30 June." },
    { wrong: "ChatGPT says: If you didn't charge GST you don't owe it after late registration", correct: "Reality: If you were required to register but did not, the ATO treats your prices as GST-inclusive. On a $1,100 invoice, $100 was GST — and you owe it, even if you only charged $1,100 and thought it was all revenue. You effectively absorbed the GST in your prices." },
    { wrong: "ChatGPT says: Rental income from residential property counts toward the GST threshold", correct: "Reality: Residential rental income is an input-taxed supply and does not count toward the $75,000 GST registration threshold. Commercial property rental is a taxable supply and does count. This distinction is commonly misunderstood." },
  ],
  faqs: [
    { question: "What is the GST registration threshold?", answer: "You must register for GST if your current or projected GST turnover (total taxable and GST-free supplies) reaches $75,000 in any 12-month period. Once you cross the threshold, you have 21 days to register. The threshold is $150,000 for non-profit bodies." },
    { question: "What happens if I register late?", answer: "If you should have registered but did not, the ATO can backdate your GST obligations to when you crossed the threshold. This means you owe GST on all taxable sales made since the registration date — whether you charged it or not. Your sales prices are treated as GST-inclusive even if you quoted and charged GST-exclusive prices." },
    { question: "Does residential rental income count toward the threshold?", answer: "No. Residential rental income is an input-taxed supply and is excluded from the GST turnover calculation. Commercial property rental income is a taxable supply and does count. If you have a mix of residential and commercial rentals, only the commercial component counts." },
    { question: "Can I register voluntarily if I am under the threshold?", answer: "Yes. You can register for GST voluntarily even if your turnover is under $75,000. The benefit is that you can claim input tax credits on your business purchases. The downside is the administrative obligation — charging GST on sales and lodging BAS returns monthly or quarterly." },
  ],
  accountantQuestionsH2: "Ask these if your business is growing",
  accountantQuestions: [
    { q: "What is my rolling 12-month GST turnover — and how close am I to the $75,000 threshold?", why: "Many growing businesses do not monitor the rolling 12-month threshold. The ATO applies it continuously — not just at year end." },
    { q: "If I crossed the threshold in a prior period, what is my estimated GST backdate liability?", why: "If you crossed $75,000 in any 12-month period and are not registered, you may already owe GST on past sales. Quantifying this is the first step." },
    { q: "Should I voluntarily disclose to the ATO if I was required to register earlier than I did?", why: "Voluntary disclosure to the ATO before being detected typically results in reduced penalties. Your accountant can assist with this process." },
    { q: "Should I register voluntarily before hitting the threshold given my input costs?", why: "If you have significant GST on business purchases (equipment, supplies, services), voluntary registration may produce a net input tax credit refund even before you hit the threshold." },
  ],
  crosslink: { title: "Running a rental property? Check your rental deduction position.", body: "GST does not apply to residential rental income — but your rental deduction position matters. Check your audit exposure.", url: "/au/check/rental-property-deduction-audit", label: "Check rental deductions →" },
  lawBarSummary: "GST registration: required when current or projected GST turnover reaches $75,000 in any 12-month period. Register within 21 days. Late registration: ATO backdates GST liability to threshold crossing date. Non-profit threshold: $150,000. GST rate: 10%. BAS: monthly or quarterly. Under GST Act 1999.",
  lawBarBadges: ["ATO", "GST Act 1999", "$75k Threshold", "10% GST"],
  sources: [{ title: "ATO — GST registration", url: "https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst" }],
  files: [
    { num: "01", slug: "gst-01", name: "Your GST Registration Status Report", desc: "Whether you are required to register and your backdate risk.", tier: 1, content: `<h2>GST Registration — Your Position</h2><div class="action-box"><h3>The Three Questions</h3><p>1. Has your rolling 12-month turnover exceeded $75,000?</p><p>2. If yes — did you register within 21 days?</p><p>3. If no — what is your backdate exposure?</p></div><p>Source: <a href="https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst">ATO — GST registration</a></p>` },
    { num: "02", slug: "gst-02", name: "Backdating Risk Plan", desc: "How to calculate and manage your GST backdate liability.", tier: 1, content: `<h2>Backdated GST Liability Calculation</h2><p>If you should have registered before today's date, the ATO can assess GST on all taxable sales since the threshold was crossed.</p><div class="action-box"><h3>Calculate Your Backdate Exposure</h3><p>Step 1: Identify when rolling 12-month turnover first exceeded $75,000</p><p>Step 2: Calculate total taxable sales from that date to today</p><p>Step 3: GST = Total sales / 11 (extracted from GST-inclusive price)</p><p>Step 4: Subtract any input tax credits you could have claimed</p></div>` },
    { num: "03", slug: "gst-03", name: "GST Catch-Up Strategy", desc: "How to manage late registration and minimise penalties.", tier: 1, content: `<h2>Late Registration — Catch-Up Strategy</h2><ol><li>Register for GST immediately via myGov Business or ABN registration portal</li><li>Prepare retrospective BAS for each quarter since threshold crossing</li><li>Calculate net GST payable (GST collected minus input tax credits)</li><li>Consider voluntary disclosure to reduce failure to lodge penalties</li><li>Negotiate payment plan with ATO if lump sum is not affordable</li></ol><div class="info-box">The ATO's voluntary disclosure process can reduce penalties significantly. Get specialist advice before contacting the ATO.</div>` },
    { num: "04", slug: "gst-04", name: "GST Threshold Tracker", desc: "Monthly monitoring system to track when you approach the $75,000 threshold.", tier: 1, content: `<h2>Monthly GST Threshold Monitor</h2><table><tr><th>Month</th><th>Monthly Revenue</th><th>Rolling 12-Month Total</th><th>Threshold Status</th></tr><tr><td>Jan</td><td>$ ___</td><td>$ ___</td><td>___ / $75,000</td></tr><tr><td>Feb</td><td>$ ___</td><td>$ ___</td><td>___ / $75,000</td></tr><tr><td colspan="4">Continue for all 12 months</td></tr></table><div class="info-box">When rolling 12-month total exceeds $75,000, you have 21 days to register. Set a calendar reminder when you reach $60,000.</div>` },
    { num: "05", slug: "gst-05", name: "Your Accountant Brief", desc: "GST questions to take if your business is growing.", tier: 1, content: `<div class="info-box">Check these questions NOW — not when the ATO contacts you.</div><div class="action-box"><h3>Question 1</h3><p>"What is my current rolling 12-month GST turnover — and when am I expected to cross $75,000?"</p></div><h3>Question 2</h3><p>"Have I already crossed the threshold in a prior period without registering?"</p><h3>Question 3</h3><p>"Should I voluntarily disclose late registration to the ATO?"</p>` },
    { num: "06", slug: "gst-06", name: "Full GST System Setup", desc: "Complete GST registration, BAS lodgement, and compliance framework.", tier: 2, content: `<h2>GST System — Setup Checklist</h2><ul class="checklist"><li>Register for GST via ABN or myGov Business portal</li><li>Choose BAS reporting period — quarterly (most common) or monthly (if turnover over $20M)</li><li>Set up accounting software with GST — Xero, MYOB, or QuickBooks</li><li>Configure correct GST codes for each transaction type</li><li>Set up payment reminder for BAS due dates (28 days after each quarter end)</li><li>Establish input tax credit claim process for all business purchases</li></ul>` },
    { num: "07", slug: "gst-07", name: "BAS Compliance Framework", desc: "A quarter-by-quarter BAS management system.", tier: 2, content: `<h2>Quarterly BAS Calendar</h2><table><tr><th>Quarter</th><th>Period</th><th>BAS Due Date</th></tr><tr><td>Q1</td><td>1 July – 30 September</td><td>28 October</td></tr><tr><td>Q2</td><td>1 October – 31 December</td><td>28 February</td></tr><tr><td>Q3</td><td>1 January – 31 March</td><td>28 April</td></tr><tr><td>Q4</td><td>1 April – 30 June</td><td>28 July</td></tr></table><div class="info-box">BAS agents may have extended deadlines. Check with your agent for your specific due dates.</div>` },
    { num: "08", slug: "gst-08", name: "Ongoing GST Compliance Structure", desc: "Long-term GST management system to avoid future exposure.", tier: 2, content: `<h2>Ongoing GST Compliance</h2><div class="action-box"><h3>Monthly Actions</h3><p>Record all GST-inclusive receipts and invoices in accounting software</p><p>Reconcile GST collected against sales records</p><p>Verify input tax credit amounts against purchase invoices</p></div><div class="action-box"><h3>Quarterly Actions</h3><p>Prepare and lodge BAS by due date</p><p>Pay net GST to ATO (or receive refund)</p><p>Review rolling 12-month turnover for threshold monitoring</p></div>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "Gary's small Pty Ltd manages his commercial storage unit leased to a small business for $8,500 per month. Total rental income: $102,000 per year. The company is not registered for GST.", painPoint: "Gary does not know that commercial property rental is a taxable supply for GST purposes. He has not registered the company for GST and has been collecting $102,000 per year without charging or remitting GST.", discovery: "Gary mentioned the storage unit lease to his accountant during a general review. The accountant went quiet and then asked whether the company was registered for GST. It was not.", voice: "Gary will be alarmed when he understands the backdate exposure. He needs clear numbers and a clear action plan. No jargon." },
  story: { hook: "Gary's company had been leasing the Rockingham storage unit to a small logistics business for three years. $8,500 per month. Regular as clockwork.", setup: ["It had never occurred to Gary to think about GST. The rent came in, the company paid rates and insurance, and the net income went into the accounts. His accountant reviewed the company accounts once a year in April.", "When the accountant asked at their last meeting whether the company was registered for GST, Gary said he did not think so. The accountant looked at the turnover figure — $102,000 — and then looked at the lease terms. Commercial property. Taxable supply.", "Gary had crossed the $75,000 threshold in year one of the lease. That was three years ago."], revelation: "The calculator showed the backdate exposure immediately. Three years of $102,000 revenue. The ATO would treat that as GST-inclusive — meaning $9,272 of each year's revenue was GST. Total GST liability: $27,818 over three years. Minus input tax credits on rates and insurance. Net exposure: approximately $24,500.", resolution: "Gary's accountant recommended voluntary disclosure to the ATO before any audit was triggered. The company registered for GST that week. The accountant prepared retrospective BAS for the three years. Gary negotiated a payment plan with the ATO for the net liability of $22,800. The penalty exposure was reduced significantly through voluntary disclosure. Gary asked why the accountant had not flagged this three years ago — a fair question that did not have a comfortable answer." },
  calendarTitle: "GST — Key Dates",
  tier1Calendar: [{ uid: "gst-bas-q4", summary: "BAS Due — Q4 28 July 2026", description: "GST Business Activity Statement for April to June quarter due 28 July.", date: "20260728" }],
  tier2Calendar: [{ uid: "gst-register", summary: "GST — Register if threshold crossed", description: "Register for GST within 21 days of crossing $75,000 threshold.", date: "relative:+7days" }, { uid: "gst-bas-q4", summary: "BAS Due — Q4 28 July 2026", description: "Lodge and pay Q4 BAS.", date: "20260728" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_GST_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_GST_147" },
  monitorUrls: ["https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst"],
  sidebarNumbers: [{ label: "Registration threshold", value: "$75,000" }, { label: "Non-profit threshold", value: "$150,000" }, { label: "GST rate", value: "10%" }, { label: "Registration deadline", value: "21 days" }],
  sidebarMathsTitle: "What counts toward the GST threshold",
  sidebarMathsIncludes: ["All taxable supplies", "GST-free supplies (e.g. fresh food, exports)", "Commercial property rental"],
  sidebarMathsExcludes: ["NOT residential rental income", "NOT input-taxed supplies", "NOT wages or salary income"],
  sidebarMathsNote: "Source: ATO — GST registration · GST Act 1999",
  howToSteps: [{ position: 1, name: "Enter annual turnover", text: "Select your approximate rolling 12-month turnover from all taxable supplies." }, { position: 2, name: "Check registration status", text: "Confirm whether you are currently registered for GST." }, { position: 3, name: "Get your exposure", text: "See whether registration is required and your backdate risk." }, { position: 4, name: "Get your fix plan", text: "Receive a registration strategy and catch-up BAS plan." }],
  successPromptFields: [
    { key: "business_type",     label: "Business type",              defaultVal: "general" },
    { key: "current_turnover",  label: "Current GST turnover band",  defaultVal: "band_75_150" },
    { key: "backdating",        label: "Backdating risk identified",  defaultVal: "true" },
    { key: "status",            label: "GST registration verdict",    defaultVal: "REGISTRATION REQUIRED" },
    { key: "tier",              label: "Product tier purchased",      defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "gstStatus",
    "registrationObligation",
    "triggerDateEstimate",
    "backdatingExposure",
    "invoiceCleanupRequired",
    "projectedTurnoverAnalysis",
    "strongestRiskTrigger",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "gstStatus",
    "registrationObligation",
    "triggerDateEstimate",
    "backdatingExposure",
    "invoiceCleanupRequired",
    "projectedTurnoverAnalysis",
    "basSetupRecommendation",
    "pricingTransitionGuide",
    "bookkeepingClassification",
    "retroBASPlan",
    "inputTaxCredits",
    "strongestRiskTrigger",
  ],
};
