import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "cgt-main-residence-trap", name: "CGT Main Residence Trap Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/cgt-main-residence-trap", url: "https://taxchecknow.com/au/check/cgt-main-residence-trap", apiRoute: "/api/rules/cgt-main-residence-trap",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "ITAA 1997 — Main Residence Exemption (s.118-110)", legislation: "Income Tax Assessment Act 1997 s.118-110 to s.118-195 — Main Residence CGT Exemption", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Main Residence CGT Fix Plan", tagline: "Is your tax-free home actually taxable?", value: "A personalised CGT audit built around your purchase date, rental periods, and sale date — not a generic ATO guide.", cta: "Get My CGT Fix Plan — $67 →", productKey: "au_67_cgt_main_residence_trap", envVar: "STRIPE_AU_CGT_MR_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your CGT Minimisation System", tagline: "Minimise CGT with the right timing, structure, and documentation", value: "A full CGT minimisation plan including ownership structuring, sale timing strategy, and partial exemption calculation.", cta: "Get My CGT System — $147 →", productKey: "au_147_cgt_main_residence_trap", envVar: "STRIPE_AU_CGT_MR_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-06-30T23:59:59.000+10:00", display: "30 June 2027", short: "30 Jun 2027", description: "Australian tax year end — CGT events in 2026/27 must be reported", urgencyLabel: "EOFY", countdownLabel: "Countdown to 30 June 2027 EOFY" },
  h1: "CGT Main Residence 2026: Is Your Tax-Free Home Actually Taxable?", metaTitle: "CGT Main Residence Exemption Australia 2026 — Is Your Home Fully Tax-Free? | TaxCheckNow", metaDescription: "The main residence CGT exemption is not automatic. Renting your home, moving out, or using the 6-year rule incorrectly can make part of your sale taxable. Free calculator shows your position in 2 minutes.", canonical: "https://taxchecknow.com/au/check/cgt-main-residence-trap",
  answerHeadline: "Is your home sale tax-free in Australia? Not always.",
  answerBody: [
    "You only get a full CGT exemption if all of these are true: you lived in the property as your main residence the entire time; you did not use it to produce income; you did not treat another property as your main residence at the same time; and you were an Australian resident at the time of sale. Break any one of these and part — or all — of your gain becomes taxable.",
    "Critical exceptions most people and AI miss: you may still pay CGT if you were a foreign resident at the time of sale; if you rented the property out (the 6-year rule applies but has strict limits); if you first used the property to produce income before moving in (market value reset rules apply); if you used part of the home as a dedicated place of business or claimed occupancy expenses; or if you owned multiple properties and nominated another as your main residence.",
    "The taxable portion is calculated as: non-exempt days ÷ total ownership days × capital gain. Apply the 50% CGT discount if held for more than 12 months, then adjust for any market value reset under s118-192 if the property was first used to produce income. These are the rules where most unexpected tax bills come from.",
  ],
  answerSource: "Source: ATO — ITAA 1997 s118-110 (exemption) · s118-145 (6-year rule) · s118-190 (income use) · s118-192 (first income use) · ATO foreign resident guidance 2026",
  mistakesHeadline: "What most people (and AI) get wrong about the main residence exemption",
  mistakes: [
    "My home is always tax-free — wrong. You only get a full CGT exemption if all of these are true: you lived there as your main residence the entire time, you did not use it to produce income, you did not treat another property as your main residence simultaneously, and you were an Australian resident at time of sale. Break any one of these and part or all of your gain becomes taxable.",
    "Renting it for a bit doesn't matter — wrong. Any rental period outside the 6-year absence rule creates a taxable fraction. The formula is: taxable portion = (days NOT covered by exemption ÷ total days owned) × capital gain. A property owned for 10 years and rented for 3 years has a 30% taxable fraction — even if it was genuinely your home for the other 7 years.",
    "Working from home has no CGT impact — wrong. Claiming occupancy expenses (not just running costs like phone or internet) or using a dedicated part of the home as a place of business can reduce the main residence exemption for that portion of the property. This is frequently overlooked — a deduction claimed years ago can create a partial CGT liability on sale.",
    "Foreign residents just lose the 50% discount — wrong. Foreign residents at the time of sale generally lose the entire main residence exemption — not just the CGT discount. Under rules that took effect from 1 July 2020, most foreign residents cannot access the exemption at all, regardless of how long they previously lived in the property.",
  ],
  chainVisual: { label: "How the main residence exemption actually works", broken: "Property was my home = fully tax-free  ❌  Most people assume this", fixed: "Exempt days divided by total days = exempt fraction  ✔  Proportional calculation" },
  brackets: [
    { label: "Always your main residence — never rented or used for business", value: 1, status: "clear" },
    { label: "Rented out for under 6 years — 6-year rule may apply", value: 2, status: "approaching" },
    { label: "Rented out for over 6 years — partial CGT likely", value: 3, status: "trap" },
    { label: "Claimed home office deductions — partial exemption only", value: 4, status: "risk" },
    { label: "Mixed use or multiple properties — complex position", value: 5, status: "deep_trap" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "rentalPeriod", label: "How long did you rent out the property?", subLabel: "Total months rented during your ownership period", options: [{ label: "Never rented", value: 0 }, { label: "Under 2 years", value: 18 }, { label: "2-6 years", value: 48 }, { label: "Over 6 years", value: 84 }], default: 0 },
    { type: "buttonGroup", stateKey: "ownershipYears", label: "How long have you owned the property?", subLabel: "From settlement date to today", options: [{ label: "Under 5 years", value: 3 }, { label: "5-10 years", value: 7 }, { label: "10-20 years", value: 15 }, { label: "Over 20 years", value: 25 }], default: 7 },
    { type: "twoButton", stateKey: "claimedOffice", label: "Have you ever claimed a home office deduction on this property?", subLabel: "Dedicated room deductions affect the exemption", options: [{ label: "No — never claimed", value: false }, { label: "Yes — claimed home office", value: true }], default: false },
  ],
  tierAlgorithm: { description: "rentalPeriod over 18 OR claimedOffice → tier2. rentalPeriod 0 → tier1. Otherwise tier2.", tier2Conditions: ["(rentalPeriod as number) > 18"], tier2Flags: ["claimedOffice"] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "Main residence exemption: fully exempt if property was your main residence for the entire ownership period. Partially exempt if rented, absent, or used for business. Taxable portion = non-exempt days / total days × capital gain. 6-year rule: treat as main residence for up to 6 years while absent if no other main residence nominated. 50% CGT discount applies if held over 12 months." },
  calculatorClarification: { label: "Key clarification", body: "The 6-year rule is not automatic. You must not have another main residence during the absence period. And if you rented the property before the 6-year clock started, those early rental days are always taxable regardless of the 6-year rule." },
  countdownLabel: "Countdown to 30 June 2027 EOFY",
  countdownStats: [
    { label: "Most people assume", value: "Full exemption", sub: "if property was their home" },
    { label: "ATO reality", value: "Proportional", sub: "rental days reduce your exemption", red: true },
    { label: "6-year rule", value: "Not automatic", sub: "conditions must be met", red: true },
    { label: "CGT discount", value: "50%", sub: "if held over 12 months" },
  ],
  geoBlockTitle: "AI extraction block — CGT main residence exemption Australia 2026",
  geoBlockH2: "Australian CGT Main Residence Exemption — confirmed 2026",
  geoBodyParagraph: "Under ITAA 1997 s.118-110, Australian taxpayers are exempt from capital gains tax on the sale of their main residence. The exemption is proportional — if the property was used for income-producing purposes (rental or business) at any time during ownership, only the portion of the gain relating to exempt periods is tax-free. The 6-year absence rule (s.118-145) allows a property to be treated as a main residence for up to six years while rented out, provided no other property is nominated as the main residence during that period. If the absence exceeds six years, only the first six years count as exempt. A partial exemption applies for home office deductions — any portion of the home claimed as a dedicated work area loses the main residence exemption for that area. The 50% CGT discount applies to gains on assets held for more than 12 months by individuals and trusts.",
  geoFormula: "Taxable Gain = Total Capital Gain × (Non-Exempt Days / Total Ownership Days). Non-Exempt Days = rental days + business-use days outside 6-year rule. After partial exemption: apply 50% CGT discount if held over 12 months.",
  geoFacts: [
    { label: "Full exemption", value: "Main residence entire ownership — never rented" },
    { label: "6-year rule", value: "Absent up to 6 years while renting — no other main residence" },
    { label: "Partial exemption", value: "Rental/business days reduce exempt fraction" },
    { label: "CGT discount", value: "50% for individuals — asset held over 12 months" },
    { label: "Home office impact", value: "Dedicated room deductions remove partial exemption" },
    { label: "Legislative anchor", value: "ITAA 1997 s.118-110 to s.118-195" },
  ],
  workedExamplesH2: "Four property scenarios — how the exemption calculates",
  workedExamplesColumns: ["Scenario", "Ownership", "Rental Period", "Taxable Portion", "Status"],
  workedExamples: [
    { name: "Always main home",    setup: "Never rented, never used for business",          income: "0%",  status: "FULLY EXEMPT" },
    { name: "6-year rule applies", setup: "Rented for 4 years, no other main residence",    income: "0%",  status: "FULLY EXEMPT" },
    { name: "Over 6 years",        setup: "Rented for 8 years out of 12 years owned",       income: "16.7%", status: "PARTIAL CGT" },
    { name: "Home office claimed", setup: "Claimed 15% of home as office for 5 years",      income: "Partial", status: "PARTIAL CGT" },
  ],
  comparisonH2: "Main residence scenarios — exempt vs taxable",
  comparisonColumns: ["Situation", "Exemption", "Key Condition", "Action"],
  comparisonRows: [
    { position: "Lived in entire ownership",  metric1: "100%",     metric2: "Never rented or used for business", bestMove: "No action needed" },
    { position: "Rented under 6 years",       metric1: "100%",     metric2: "6-year rule — no other main residence", bestMove: "Document the dates" },
    { position: "Rented over 6 years",        metric1: "Partial",  metric2: "Excess rental days are taxable", bestMove: "Calculate taxable portion" },
    { position: "Home office deducted",       metric1: "Partial",  metric2: "Dedicated room loses exemption", bestMove: "Quantify area and years" },
  ],
  toolsH2: "Strategies that reduce CGT on your home",
  toolsColumns: ["Strategy", "How It Works", "Applies When"],
  toolsRows: [
    { tool: "6-year absence rule",     effect: "Treat home as main residence while renting", note: "No other main residence during absence" },
    { tool: "50% CGT discount",        effect: "Halve the taxable gain after exemption",     note: "Held over 12 months — individuals and trusts" },
    { tool: "Move back in before sale", effect: "Extend exempt period — reduce taxable days", note: "Must genuinely re-establish as main residence" },
    { tool: "Cost base maximisation",  effect: "Add all eligible costs to reduce gain",      note: "Stamp duty, legal fees, capital improvements" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: If it was your home you don't pay CGT", correct: "Reality: The exemption is proportional. If you rented the property at any point, the rental period may be taxable. The question is not whether it was your home — it is how many days it was NOT your exempt main residence." },
    { wrong: "ChatGPT says: The 6-year rule means you can rent for 6 years tax-free anytime", correct: "Reality: The 6-year rule applies from the date you moved out as a continuous absence. You must not have another main residence during that period. Rental days before you moved out for the absence do not count toward the 6-year clock." },
    { wrong: "ChatGPT says: Claiming a home office doesn't affect the main residence exemption", correct: "Reality: If you claimed a deduction for a dedicated room (not just a portion of shared space), the ATO treats that area as excluded from the main residence for CGT purposes. This creates a partial taxable gain on sale." },
    { wrong: "ChatGPT says: You must live in the property to claim the main residence exemption", correct: "Reality: The 6-year absence rule allows you to claim the main residence exemption while absent — including while renting — for up to six years, provided no other property is nominated as your main residence during that time." },
  ],
  faqs: [
    { question: "What is the main residence CGT exemption?", answer: "The main residence exemption under ITAA 1997 s.118-110 exempts your home from capital gains tax when you sell it. The exemption is automatic if the property was your main residence for the entire ownership period and was never used to produce income. If you rented it or used part of it for business, only the exempt fraction of the gain is tax-free." },
    { question: "What is the 6-year rule?", answer: "The 6-year absence rule (s.118-145) allows you to treat a property as your main residence for CGT purposes for up to six years while you are absent — including while renting it out. The rule applies only if you do not treat another property as your main residence during the absence. If you move back in and then move out again, the six-year clock resets." },
    { question: "How is the taxable portion calculated?", answer: "The taxable portion is calculated as: non-exempt days divided by total ownership days, multiplied by the total capital gain. Non-exempt days include any days the property was rented, used for business, or absent beyond the 6-year rule period. The 50% CGT discount then applies to the taxable gain if you held the asset for more than 12 months." },
    { question: "Does renting a room affect the exemption?", answer: "Renting a room on an ongoing basis (not through Airbnb occasionally) can affect the exemption. The ATO may treat the rented room as a non-exempt portion of the property, proportional to the floor area rented relative to the total floor area." },
    { question: "What about Airbnb?", answer: "Short-term Airbnb rentals can affect the main residence exemption. The ATO has confirmed that renting your home on short-stay platforms constitutes income-producing use. The taxable portion depends on how many days the property was listed and rented relative to your total ownership period." },
    { question: "Can I claim the exemption if I never lived in the property?", answer: "No. The property must have been your main residence at some point during your ownership. You cannot nominate a property as your main residence if you never genuinely lived there. The ATO looks at where you actually resided — not where you nominate on paper." },
    { question: "What records do I need?", answer: "Keep evidence of the dates you moved in and out, any rental agreements and income records, utility bills and bank statements showing your address, records of any home office claims, and invoices for capital improvements (these increase your cost base). Keep all records for at least 5 years after disposal, and longer where CGT calculations span multiple years or involve market value resets." },
    { question: "Does the exemption apply to properties held in a company or trust?", answer: "Companies cannot access the main residence exemption — the full gain is taxable. Trusts have limited access under strict conditions — certain types of trusts (such as some fixed trusts) may be eligible, but discretionary trusts and unit trusts generally cannot claim the exemption. Get professional advice before assuming a trust structure is covered." },
  ],
  accountantQuestionsH2: "Ask these before you sell",
  accountantQuestions: [
    { q: "What is the exact number of exempt and non-exempt days for my property — and have you calculated the taxable fraction?", why: "Most people guess at the rental period. The ATO calculates to the day. Even a few months of rental can create a meaningful taxable gain on a high-value property." },
    { q: "Do I qualify for the 6-year absence rule — and have I met all the conditions including not nominating another main residence?", why: "The 6-year rule has strict conditions. Many people assume it applies automatically when it does not." },
    { q: "Have I made any home office deductions that might reduce my main residence exemption?", why: "This is frequently overlooked. A dedicated home office deduction claimed years ago can create a partial CGT liability on sale." },
    { q: "What can I add to my cost base to reduce the taxable gain?", why: "Stamp duty, legal fees on purchase and sale, capital improvements, and some holding costs can all be added to the cost base — reducing the gain dollar for dollar." },
    { q: "Should I move back into the property before selling to maximise the exempt period?", why: "Moving back in genuinely can extend the exempt period and reduce the taxable fraction. This needs to be genuine — not a paper exercise — and the timing needs to be modelled carefully." },
  ],
  crosslink: { title: "Selling investment property? Check your CGT discount timing.", body: "If this is an investment property rather than your main residence, the CGT discount timing is the key issue. Check whether your contract date qualifies for the 50% discount.", url: "/au/check/cgt-discount-timing-sniper", label: "Check CGT discount timing →" },
  lawBarSummary: "Australian CGT main residence exemption: fully exempt if main residence entire ownership. Proportional exemption if rented or used for business. 6-year absence rule applies if no other main residence nominated. 50% CGT discount for assets held over 12 months. Under ITAA 1997 s.118-110 to s.118-195.",
  lawBarBadges: ["ATO", "ITAA 1997", "s.118-110", "CGT Exemption"],
  sources: [
    { title: "ATO — Main residence exemption", url: "https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/property-and-capital-gains-tax/your-main-residence-home/main-residence-exemption" },
    { title: "ATO — 6-year absence rule", url: "https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/property-and-capital-gains-tax/your-main-residence-home/treating-former-home-as-main-residence" },
  ],
  files: [
    { num: "01", slug: "mr-01", name: "Your Main Residence CGT Verdict", desc: "Your exact exempt fraction, taxable gain estimate, and CGT liability.", tier: 1, content: `<h2>Your CGT Position</h2><div class="action-box"><h3>The Calculation</h3><p>Taxable fraction = Non-exempt days / Total ownership days</p><p>Taxable gain = Capital gain × taxable fraction</p><p>After 50% CGT discount (if held over 12 months)</p><p>Tax = Taxable gain × Marginal rate</p></div><p>Source: <a href="https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/property-and-capital-gains-tax/your-main-residence-home/main-residence-exemption">ATO — Main residence exemption</a></p>` },
    { num: "02", slug: "mr-02", name: "6-Year Rule Optimiser", desc: "Confirm whether the 6-year absence rule applies to your situation.", tier: 1, content: `<h2>6-Year Absence Rule — Eligibility Check</h2><p>The 6-year rule allows you to treat a property as your main residence for up to 6 years while absent.</p><div class="action-box"><h3>Conditions Required</h3><p>1. The property was your main residence before the absence</p><p>2. You did not nominate another property as your main residence during the absence</p><p>3. The absence was less than 6 continuous years (resets if you move back in)</p></div><table><tr><th>Scenario</th><th>Exempt?</th></tr><tr><td>Absence under 6 years, no other main residence</td><td>Yes — fully exempt</td></tr><tr><td>Absence over 6 years</td><td>Partial — excess days taxable</td></tr><tr><td>Another property nominated as main residence</td><td>No — 6-year rule does not apply</td></tr></table>` },
    { num: "03", slug: "mr-03", name: "Partial Exemption Calculator", desc: "Calculate the exact taxable portion of your gain based on rental and business-use days.", tier: 1, content: `<h2>Partial Exemption Calculation</h2><p>Use this worksheet to calculate your exact taxable fraction.</p><div class="action-box"><h3>Step-by-Step</h3><p>Step 1: Total days owned = Settlement to contract date of sale</p><p>Step 2: Non-exempt days = Rental days + business-use days outside 6-year rule</p><p>Step 3: Taxable fraction = Non-exempt days / Total days owned</p><p>Step 4: Taxable gain = Capital gain × taxable fraction</p><p>Step 5: Apply 50% CGT discount if held over 12 months</p><p>Step 6: Add to income and apply marginal tax rate</p></div>` },
    { num: "04", slug: "mr-04", name: "Cost Base Maximisation Checklist", desc: "Every cost you can add to your cost base to reduce the taxable gain.", tier: 1, content: `<h2>Cost Base — What You Can Include</h2><ul class="checklist"><li>Purchase price (settlement amount)</li><li>Stamp duty on purchase</li><li>Legal fees on purchase and sale</li><li>Agent commission on sale</li><li>Capital improvements (new kitchen, extension, new roof)</li><li>Building and pest inspections at purchase</li><li>Mortgage break costs if fixed rate broken at sale</li></ul><div class="warning-box"><strong>Cannot include:</strong> Mortgage interest, council rates, insurance, general repairs and maintenance — these are income deductions, not cost base additions.</div>` },
    { num: "05", slug: "mr-05", name: "Record-Keeping Checklist", desc: "What to keep to defend your main residence exemption if ATO audits.", tier: 1, content: `<h2>ATO Evidence Checklist</h2><ul class="checklist"><li>Settlement statement showing purchase date and price</li><li>Contract of sale showing sale date and price</li><li>Utility bills (power, gas, water) at the property address</li><li>Bank statements showing property address during main residence periods</li><li>Electoral roll registration at the property</li><li>All rental agreements and rental income records</li><li>Any home office deduction claims from prior tax returns</li><li>Receipts for all capital improvements</li></ul><div class="info-box">Keep these for 5 years after you lodge the return in which the CGT gain is reported. ATO can audit for 4 years from lodgement date.</div>` },
    { num: "06", slug: "mr-06", name: "Full CGT Minimisation Plan", desc: "All strategies to minimise CGT before and after sale.", tier: 2, content: `<h2>CGT Minimisation — Full Strategy</h2><h3>Before Sale</h3><ul><li>Consider moving back in to extend the exempt period</li><li>Maximise cost base — document all capital improvements</li><li>Time the contract date for optimal CGT discount (after 12-month anniversary)</li><li>Consider income timing — large CGT gain in a low-income year reduces tax</li></ul><h3>At Sale</h3><ul><li>Use the 50% CGT discount (12+ months held)</li><li>Apply any capital losses from other assets to reduce net gain</li><li>Consider superannuation contributions to reduce taxable income in the sale year</li></ul>` },
    { num: "07", slug: "mr-07", name: "Ownership Structuring Strategy", desc: "How ownership structure affects your main residence exemption.", tier: 2, content: `<h2>Ownership Structure and CGT</h2><table><tr><th>Structure</th><th>Exemption Available?</th><th>Notes</th></tr><tr><td>Individual</td><td>Yes</td><td>Full main residence exemption available</td></tr><tr><td>Joint tenants (couple)</td><td>Yes</td><td>Each owner's share is exempt</td></tr><tr><td>Company</td><td>No</td><td>No main residence exemption for companies</td></tr><tr><td>Discretionary trust</td><td>No</td><td>No main residence exemption for trusts</td></tr><tr><td>SMSF</td><td>No</td><td>Cannot hold main residence in SMSF</td></tr></table>` },
    { num: "08", slug: "mr-08", name: "Sale Timing Optimisation Blueprint", desc: "How to time your sale to minimise CGT across income years.", tier: 2, content: `<h2>Sale Timing Strategy</h2><p>The timing of the sale contract (not settlement) determines the CGT year. If a large gain is expected, timing the contract to fall in a year of lower income can significantly reduce tax.</p><div class="action-box"><h3>Key Timing Considerations</h3><p>Contract date = CGT event date (not settlement)</p><p>If you have unused capital losses — use them in the same year</p><p>If income is variable — model the gain in a low-income year</p><p>Consider super contributions in the sale year to reduce taxable income</p></div>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "$3.4M SMSF, commercial property and shares. Owns the family home in Baldivis and a rental unit in Mandurah bought in 2011.", painPoint: "Gary sold the Mandurah unit last year. He assumed it was tax-free because he lived there briefly when he first bought it. He has not discussed it with his accountant yet.", discovery: "Gary mentioned it to his neighbour Rod — a retired school teacher who had gone through the same thing. Rod told him it was not that simple. Gary googled it that evening.", voice: "Straightforward. Perth practical. Trusts his accountant but hates surprises. Does not want a lecture — wants to know his number." },
  story: { hook: "Gary sold the Mandurah unit in February. He had owned it since 2011 — fourteen years. He assumed the sale would be tax-free.", setup: ["He had lived there for the first eight months after he bought it. Moved in straight after settlement, before the FIFO roster kicked in properly. After that he had rented it out — first to a young couple, then to a series of different tenants. The rental income had been going into a separate account and declared every year. Gary had been organised about that much.", "What Gary had not thought about was the main residence side of things. He knew about the 50% CGT discount — his accountant had mentioned it years ago. But he assumed that because he had lived there at the start, it qualified as his home and would be exempt.", "The unit had gone up substantially. He bought it for $285,000 in 2011. It sold for $580,000 in February 2026. A gain of $295,000. Gary had told Sandra it would be a clean $295,000. No tax."], revelation: "When Gary ran the calculator, the numbers came back differently. He had owned the property for approximately 5,110 days. He had lived there for 243 days. The 6-year rule did not help — he had never moved back in and had nominated the family home as his main residence the whole time. His exempt fraction was 243 divided by 5,110 — about 4.75%. The taxable portion of his gain was $280,000. After the 50% CGT discount, he had $140,000 of taxable income to declare.", resolution: "Gary called his accountant the next morning. The news was not great but it was manageable. They worked through the cost base — stamp duty, agent fees, a new hot water system and the repaint in 2019. The gain came down to $261,000. After the discount, $130,500 added to Gary's income for the year. His accountant also checked whether any capital losses from other disposals could offset it. Gary had one — a small parcel of shares that had dropped. It helped a little. The conversation Gary needed to have with Sandra was going to be different from the one he had planned. But at least he knew the number before the return was due." },
  calendarTitle: "CGT — Key Dates",
  tier1Calendar: [{ uid: "cgt-return", summary: "CGT — Lodge tax return including property sale", description: "CGT from 2025/26 property sale must be declared in return due October 2026.", date: "20261031" }],
  tier2Calendar: [{ uid: "cgt-review", summary: "CGT — Review cost base and exemption with accountant", description: "Gather all records before meeting accountant to maximise cost base.", date: "relative:+14days" }, { uid: "cgt-return", summary: "CGT — Lodge tax return", description: "CGT declared in return due October 2026.", date: "20261031" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_CGT_MR_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_CGT_MR_147" },
  monitorUrls: ["https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/property-and-capital-gains-tax/your-main-residence-home/main-residence-exemption"],
  sidebarNumbers: [{ label: "Full exemption", value: "All conditions met" }, { label: "6-year rule", value: "Per absence — not total" }, { label: "CGT discount", value: "50% if 12mo+" }, { label: "Records", value: "5 years after disposal" }],
  sidebarMathsTitle: "Main residence exemption — what breaks it",
  sidebarMathsIncludes: [
    "Full exemption: lived there entire ownership, no income use",
    "Partial: income use or absence → taxable = non-exempt days / total days",
    "6-year rule: rented during absence, max 6 years per absence period",
    "First used to produce income: market value reset (s118-192)",
    "50% CGT discount applies to taxable portion if held 12+ months",
  ],
  sidebarMathsExcludes: [
    "NOT available to foreign residents at time of sale (post-2020)",
    "NOT if property never used as main residence",
    "NOT occupancy expense claims — partial reduction applies",
    "NOT overlap with another main residence — nomination required",
    "Usually NOT available to companies or most trusts",
  ],
  sidebarMathsNote: "Source: ATO — ITAA 1997 s118-110 (exemption) · s118-145 (6-year rule) · s118-192 (first income use) · ATO guidance 2026",
  howToSteps: [
    { position: 1, name: "Select property pathway", text: "Full residence, moved out, investment-first, mixed use, or never lived there — routes to the correct legal analysis." },
    { position: 2, name: "Answer usage questions", text: "Income use, absence duration, business use, and overlap with another property each affect the exemption." },
    { position: 3, name: "Get your exemption verdict", text: "Full / partial / no exemption — with the taxable fraction formula and strongest risk trigger." },
    { position: 4, name: "Get your plan", text: "Personalised exemption memo, timeline map, 6-year rule check, and accountant questions for your situation." },
  ],
  successPromptFields: [
    { key: "pathway",           label: "Property pathway",                    defaultVal: "moved_out" },
    { key: "exemption_status",  label: "Exemption status",                    defaultVal: "partial" },
    { key: "taxable_fraction",  label: "Estimated taxable fraction",          defaultVal: "0.3" },
    { key: "strongest_trigger", label: "Strongest exemption risk trigger",    defaultVal: "Rented during absence" },
    { key: "status",            label: "CGT main residence verdict",          defaultVal: "PARTIAL EXEMPTION" },
    { key: "tier",              label: "Product tier purchased",              defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "exemptionStatus",
    "taxableFractionCalculation",
    "sixYearRuleAnalysis",
    "incomeUseImpact",
    "foreignResidencyCheck",
    "businessUseImpact",
    "overlapPropertyIssue",
    "evidenceChecklist",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "exemptionStatus",
    "taxableFractionCalculation",
    "sixYearRuleAnalysis",
    "incomeUseImpact",
    "foreignResidencyCheck",
    "businessUseImpact",
    "overlapPropertyIssue",
    "evidenceChecklist",
    "costBaseAdjustmentMap",
    "saleTimingScenarios",
    "overlapNominationStrategy",
    "marketValueResetAnalysis",
    "firstUseIncomeRules",
    "nextActionRecommendation",
  ],
};
