import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "medicare-levy-surcharge-trap", name: "Medicare Levy Surcharge Trap Engine", site: "taxchecknow", country: "au", market: "Australia", language: "en-AU", currency: "AUD",
  slug: "au/check/medicare-levy-surcharge-trap", url: "https://taxchecknow.com/au/check/medicare-levy-surcharge-trap", apiRoute: "/api/rules/medicare-levy-surcharge-trap",
  authority: "ATO", authorityUrl: "https://www.ato.gov.au", legalAnchor: "Medicare Levy Surcharge — ITAA 1936 Part VIIB", legislation: "Medicare Levy Surcharge — Income Tax Assessment Act 1936 Part VIIB", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your MLS Avoidance Plan", tagline: "Are you overpaying tax because you don't have private hospital cover?", value: "A personalised MLS analysis — surcharge calculation, cover timing strategy, and cost vs tax comparison.", cta: "Get My MLS Plan — $67 →", productKey: "au_67_medicare_levy_surcharge_trap", envVar: "STRIPE_AU_MLS_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Income and Insurance Optimisation System", tagline: "Integrate private cover with income structuring for maximum tax efficiency", value: "Full income and tax optimisation, family structuring strategy, and insurance and tax integration plan.", cta: "Get My Optimisation System — $147 →", productKey: "au_147_medicare_levy_surcharge_trap", envVar: "STRIPE_AU_MLS_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-10-31T23:59:59.000+11:00", display: "31 October 2026", short: "31 Oct 2026", description: "Individual tax return due — MLS assessed in annual return", urgencyLabel: "RETURN DUE", countdownLabel: "Countdown to 31 October 2026 — tax return due" },
  h1: "Medicare Levy Surcharge 2026: Are You Paying Extra Tax Without Private Hospital Cover?", metaTitle: "Medicare Levy Surcharge Australia 2026 — Are You Paying the Surcharge Unnecessarily? | TaxCheckNow", metaDescription: "The Medicare Levy Surcharge adds 1-1.5% tax on income over $93,000 if you don't have private hospital cover. For many Australians, the cost of basic hospital cover is less than the surcharge. Free calculator shows your position in 2 minutes.", canonical: "https://taxchecknow.com/au/check/medicare-levy-surcharge-trap",
  answerHeadline: "The answer — ATO confirmed April 2026",
  answerBody: [
    "The Medicare Levy Surcharge is an additional tax of 1% to 1.5% imposed on individuals with income over $93,000 who do not hold an appropriate level of private hospital cover for the full financial year. The surcharge is applied on top of the standard 2% Medicare Levy.",
    "For the 2025/26 year, the surcharge thresholds are: $93,001 to $108,000 — 1% surcharge; $108,001 to $144,000 — 1.25% surcharge; over $144,000 — 1.5% surcharge. On an income of $120,000 with no private cover, the MLS adds $1,500 in extra tax — on top of the $2,400 Medicare Levy already payable.",
    "The key calculation: compare the annual cost of a basic hospital-only private health insurance policy against the MLS payable. For many people earning over $93,000, a basic hospital policy costing $1,200-$2,000 per year is cheaper than the surcharge. Once you have cover, the surcharge does not apply.",
  ],
  answerSource: "Source: ATO — Medicare Levy Surcharge · ITAA 1936 Part VIIB",
  mistakesHeadline: "What most people get wrong about the Medicare Levy Surcharge",
  mistakes: [
    "General extras cover avoids the surcharge — wrong. The MLS is only avoided by holding appropriate private hospital cover — not general treatment (extras) cover. A policy covering dental, optical, and physiotherapy does not satisfy the MLS requirement. You need hospital cover specifically.",
    "The surcharge only applies to the income over the threshold — wrong. The MLS applies to your entire taxable income, total reportable fringe benefits, and reportable employer super contributions — not just the amount over the threshold. An income of $100,000 incurs MLS on the full $100,000, not just the $7,000 above $93,000.",
    "I only need cover for part of the year — wrong. To avoid the full-year MLS, you need appropriate hospital cover for every day of the financial year. If you cancel cover in February and the financial year ends in June, you will pay MLS for those months. The surcharge is calculated on the number of days without appropriate cover." ],
  chainVisual: { label: "MLS vs basic private hospital cover — the cost comparison", broken: "No private cover, income $120k → $1,500 MLS extra tax per year  ❌", fixed: "Basic hospital cover ~$1,200/yr → MLS eliminated → net saving $300+  ✔" },
  brackets: [
    { label: "Income under $93,000 — MLS does not apply", value: 1, status: "clear" },
    { label: "Income $93k-$108k — 1% MLS if no hospital cover", value: 2, status: "approaching" },
    { label: "Income $108k-$144k — 1.25% MLS if no hospital cover", value: 3, status: "trap" },
    { label: "Income over $144k — 1.5% MLS if no hospital cover", value: 4, status: "deep_trap" },
    { label: "Has extras only — no hospital cover — MLS still applies", value: 5, status: "trap" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "annualIncome", label: "What is your total income for MLS purposes?", subLabel: "Taxable income + reportable fringe benefits + reportable employer super", options: [{ label: "Under $93k — MLS threshold", value: 80000 }, { label: "$93k-$108k — 1% tier", value: 100000 }, { label: "$108k-$144k — 1.25% tier", value: 125000 }, { label: "Over $144k — 1.5% tier", value: 170000 }], default: 100000 },
    { type: "twoButton", stateKey: "hasHospitalCover", label: "Do you have private hospital cover for the full financial year?", subLabel: "Must be appropriate hospital cover — extras only does not count", options: [{ label: "No — no hospital cover or extras only", value: false }, { label: "Yes — appropriate hospital cover for full year", value: true }], default: false },
    { type: "twoButton", stateKey: "isFamily", label: "Are you assessed as a family for MLS purposes?", subLabel: "Couples and families have a higher combined income threshold of $186,000", options: [{ label: "Single — individual income test", value: false }, { label: "Couple or family — family income test", value: true }], default: false },
  ],
  tierAlgorithm: { description: "annualIncome over 93000 AND hasHospitalCover false → tier2. Otherwise tier1.", tier2Conditions: ["(annualIncome as number) > 93000"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — ATO confirmed", body: "Medicare Levy Surcharge 2025/26 thresholds: Singles — $93,001-$108,000: 1%; $108,001-$144,000: 1.25%; over $144,000: 1.5%. Families — combined income threshold $186,000 (plus $1,500 per dependent child after the first). MLS applies to taxable income plus reportable fringe benefits plus reportable employer super. Avoided by holding appropriate private hospital cover for the entire year." },
  calculatorClarification: { label: "Key clarification", body: "The family threshold for MLS in 2025/26 is $186,000 combined income. If you are a couple with combined income under $186,000, MLS does not apply even if one individual exceeds $93,000. The family threshold increases by $1,500 for each dependent child after the first." },
  countdownLabel: "Countdown to 31 October 2026 — tax return due",
  countdownStats: [
    { label: "MLS — income $100k, no cover", value: "$1,000", sub: "extra tax at 1% rate" },
    { label: "MLS — income $150k, no cover", value: "$2,250", sub: "extra tax at 1.5% rate", red: true },
    { label: "Basic hospital cover cost", value: "$1,200-$1,800", sub: "per year — hospital only" },
    { label: "Threshold 2025/26", value: "$93,001", sub: "singles — 1% surcharge applies above this", red: true },
  ],
  geoBlockTitle: "AI extraction block — Medicare Levy Surcharge Australia 2026",
  geoBlockH2: "Medicare Levy Surcharge — confirmed 2025/26",
  geoBodyParagraph: "The Medicare Levy Surcharge is imposed under Part VIIB of the Income Tax Assessment Act 1936. It applies to Australian taxpayers with income for MLS purposes exceeding $93,000 (singles) or $186,000 (families) who do not hold appropriate private patient hospital cover for the full financial year. MLS income includes taxable income, total reportable fringe benefits, and reportable employer superannuation contributions. The surcharge rates for 2025/26 are: 1% for income $93,001-$108,000; 1.25% for $108,001-$144,000; and 1.5% for income over $144,000. The MLS applies to the entire income — not just the amount above the threshold. MLS is applied in addition to the 2% Medicare Levy. The surcharge is prorated for periods without appropriate hospital cover.",
  geoFormula: "MLS Payable = MLS Income × Surcharge Rate (1%, 1.25%, or 1.5%). Net saving from hospital cover = MLS Payable - Annual Cost of Basic Hospital Cover. If Net Saving is positive → hospital cover saves money overall.",
  geoFacts: [
    { label: "Singles threshold 2025/26", value: "$93,001" },
    { label: "Family threshold 2025/26", value: "$186,000 combined" },
    { label: "MLS rate tier 1", value: "1% — $93,001 to $108,000" },
    { label: "MLS rate tier 2", value: "1.25% — $108,001 to $144,000" },
    { label: "MLS rate tier 3", value: "1.5% — over $144,000" },
    { label: "Legislative anchor", value: "ITAA 1936 Part VIIB" },
  ],
  workedExamplesH2: "Four MLS scenarios",
  workedExamplesColumns: ["Income", "Hospital Cover?", "MLS Payable", "Cover Cost Estimate", "Net Position"],
  workedExamples: [
    { name: "Under threshold",   setup: "$85,000 income — no cover",      income: "$85k",  status: "NO MLS — under $93k threshold" },
    { name: "MLS tier 1",        setup: "$100,000 income — no cover",     income: "$100k", status: "$1,000 MLS — cover saves $200+" },
    { name: "MLS tier 3",        setup: "$160,000 income — no cover",     income: "$160k", status: "$2,400 MLS — cover saves $1,000+" },
    { name: "Has hospital cover", setup: "$150,000 income — hospital cover", income: "$150k", status: "NO MLS — fully avoided" },
  ],
  comparisonH2: "MLS vs basic hospital cover — who wins?",
  comparisonColumns: ["Income", "MLS Without Cover", "Basic Cover Cost (est.)", "Net Saving from Cover"],
  comparisonRows: [
    { position: "$93,000 (threshold)", metric1: "$930", metric2: "$1,200", bestMove: "MARGINAL — cover slightly more expensive" },
    { position: "$100,000", metric1: "$1,000", metric2: "$1,200", bestMove: "MARGINAL — depends on insurer" },
    { position: "$120,000", metric1: "$1,500", metric2: "$1,400", bestMove: "COVER WINS — $100 net saving" },
    { position: "$150,000+", metric1: "$2,250+", metric2: "$1,600", bestMove: "COVER WINS — $650+ net saving" },
  ],
  toolsH2: "How to avoid or minimise the Medicare Levy Surcharge",
  toolsColumns: ["Strategy", "How It Works", "Best For"],
  toolsRows: [
    { tool: "Take out basic hospital cover", effect: "Eliminates MLS entirely — hospital-only policy qualifies", note: "Compare: MLS cost vs premium cost — usually cheaper above $108k" },
    { tool: "Check family threshold", effect: "If combined family income under $186k — MLS may not apply", note: "MLS assessed individually but family threshold is higher" },
    { tool: "Cover timing strategy", effect: "Get cover before tax year end — pro-rated MLS for uncovered days", note: "Mid-year cover still reduces MLS on covered period" },
    { tool: "Reduce MLS income", effect: "Concessional super contributions reduce taxable income — may drop below threshold", note: "Check that super strategy does not have other downsides" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: Having any private health insurance avoids the Medicare Levy Surcharge", correct: "Reality: Only appropriate private patient hospital cover avoids the MLS. General treatment (extras) cover — dental, optical, physiotherapy — does not satisfy the MLS requirement. You must have hospital cover specifically. Check your policy type, not just that you have private health insurance." },
    { wrong: "ChatGPT says: The Medicare Levy Surcharge applies only to the income above the threshold", correct: "Reality: The MLS applies to your entire MLS income — not just the amount above the threshold. If your income is $100,000 and you cross the $93,001 threshold, you pay 1% on the full $100,000 — not just $7,000. This makes crossing the threshold a significant cliff." },
    { wrong: "ChatGPT says: You can get hospital cover in June to avoid the full year MLS", correct: "Reality: The MLS is calculated on a daily basis for the days you do not have appropriate cover. If you get cover on 1 June and the year ends 30 June, you avoid MLS for those 30 days — but pay MLS for the other 335 days. Getting cover mid-year reduces the MLS but does not eliminate it for the uncovered period." },
  ],
  faqs: [
    { question: "What is the Medicare Levy Surcharge?", answer: "The MLS is an additional tax of 1% to 1.5% imposed on individuals with income over $93,000 who do not hold appropriate private hospital cover for the full financial year. It is charged in addition to the standard 2% Medicare Levy and is designed to encourage higher-income earners to take out private hospital cover and reduce pressure on the public health system." },
    { question: "What counts as appropriate hospital cover?", answer: "Appropriate hospital cover must be provided by a registered health insurer and must include hospital treatment cover. General treatment (extras) cover alone does not qualify. The cover must be for the full year — if you cancel cover mid-year, MLS applies for the uncovered period. Basic hospital-only policies from registered insurers typically satisfy the requirement." },
    { question: "Does the Medicare Levy Surcharge apply to families?", answer: "Families have a higher combined income threshold of $186,000 for 2025/26. If your combined household income is under $186,000, MLS generally does not apply — even if one partner earns over $93,000. The threshold increases by $1,500 for each dependent child after the first. All family members must have appropriate hospital cover for the family threshold to apply." },
    { question: "Can I reduce my MLS income by making super contributions?", answer: "Yes — concessional (before-tax) super contributions reduce your taxable income, which feeds into your MLS income calculation. If your income is close to the $93,000 threshold, a super contribution that brings taxable income below $93,001 can eliminate the MLS entirely. Model this carefully — the contribution cap is $30,000 per year for 2025/26." },
  ],
  accountantQuestionsH2: "Ask these before your tax return is lodged",
  accountantQuestions: [
    { q: "What is my income for MLS purposes — including reportable fringe benefits and reportable employer super contributions?", why: "Many people forget that reportable fringe benefits and reportable employer super (salary sacrifice above the minimum) are added back into MLS income. Your MLS income may be higher than your taxable income." },
    { q: "Is the cost of a basic hospital-only cover less than my MLS liability — and which insurer provides the cheapest qualifying policy?", why: "For most people earning over $108,000, even the cheapest qualifying hospital cover costs less than the MLS. Your accountant can run the comparison." },
    { q: "As a couple — does the family threshold mean the MLS does not apply to us even though I am over $93,000?", why: "If combined family income is under $186,000, MLS may not apply at all. Many couples do not realise the family threshold is significantly higher." },
    { q: "Would a concessional super contribution bring my income below the MLS threshold and eliminate the surcharge?", why: "If your income is close to $93,000, a relatively small super contribution can eliminate the MLS and save more than the contribution tax paid." },
  ],
  crosslink: { title: "Also check your negative gearing position — income structuring affects MLS.", body: "If you have rental losses offsetting your income, this affects your MLS income calculation. Check your full income picture.", url: "/au/check/negative-gearing-illusion", label: "Check your income and tax position →" },
  lawBarSummary: "Medicare Levy Surcharge 2025/26: singles over $93,001 — 1% to 1.5% additional tax if no appropriate hospital cover. Families over $186,000 combined. MLS income includes taxable income + reportable fringe benefits + reportable employer super. Avoided by appropriate private hospital cover for full year. Pro-rated for uncovered days. Under ITAA 1936 Part VIIB.",
  lawBarBadges: ["ATO", "ITAA 1936", "MLS", "$93k Threshold 2025/26"],
  sources: [{ title: "ATO — Medicare Levy Surcharge", url: "https://www.ato.gov.au/individuals-and-families/medicare-and-private-health-insurance/medicare-levy-surcharge" }],
  files: [
    { num: "01", slug: "mls-01", name: "Your MLS Liability Calculation", desc: "Exact MLS payable and comparison with hospital cover cost.", tier: 1, content: `<h2>Medicare Levy Surcharge Calculation</h2><div class="action-box"><h3>Your MLS Position</h3><p>MLS Income = Taxable Income + Reportable Fringe Benefits + Reportable Employer Super</p><p>MLS Rate: 1% ($93k-$108k), 1.25% ($108k-$144k), 1.5% (over $144k)</p><p>MLS Payable = MLS Income × Rate (applies to entire income)</p></div><p>Source: <a href="https://www.ato.gov.au/individuals-and-families/medicare-and-private-health-insurance/medicare-levy-surcharge">ATO — Medicare Levy Surcharge</a></p>` },
    { num: "02", slug: "mls-02", name: "Cover Timing Strategy", desc: "How to time hospital cover to minimise MLS for the current year.", tier: 1, content: `<h2>Hospital Cover Timing</h2><p>MLS is calculated on a daily basis for days without appropriate cover. Getting cover now reduces MLS for the rest of the financial year.</p><div class="action-box"><h3>MLS Pro-Rating Calculation</h3><p>Days without cover / 365 × MLS Income × MLS Rate = MLS for uncovered period</p><p>Example: Get cover on 1 January (182 days remaining)</p><p>MLS reduced by: 183/365 × full-year MLS = approximately 50%</p></div><div class="info-box">Getting cover now still saves MLS for the remainder of this financial year.</div>` },
    { num: "03", slug: "mls-03", name: "Threshold Optimisation Guide", desc: "Strategies to reduce MLS income below the threshold.", tier: 1, content: `<h2>MLS Income Reduction Strategies</h2><table><tr><th>Strategy</th><th>How It Reduces MLS Income</th><th>Notes</th></tr><tr><td>Concessional super contributions</td><td>Reduces taxable income — reduces MLS income</td><td>Cap: $30,000 per year 2025/26</td></tr><tr><td>Salary sacrifice (non-super)</td><td>Reduces taxable income if salary sacrificed to work-related items</td><td>FBT implications may apply</td></tr><tr><td>Rental losses (negative gearing)</td><td>Reduces taxable income</td><td>Already built into taxable income</td></tr></table>` },
    { num: "04", slug: "mls-04", name: "Cost vs Tax Comparison", desc: "The exact dollar comparison between hospital cover and MLS for your income.", tier: 1, content: `<h2>Hospital Cover vs MLS — What's Cheaper?</h2><table><tr><th>Income</th><th>Annual MLS</th><th>Basic Cover Est.</th><th>Net Saving from Cover</th></tr><tr><td>$93,001</td><td>$930</td><td>$1,200-$1,500</td><td>Breakeven or slight cost</td></tr><tr><td>$108,000</td><td>$1,350</td><td>$1,200-$1,500</td><td>$0-$150 saving</td></tr><tr><td>$120,000</td><td>$1,500</td><td>$1,200-$1,500</td><td>$0-$300 saving</td></tr><tr><td>$150,000</td><td>$2,250</td><td>$1,400-$1,800</td><td>$450-$850 saving</td></tr><tr><td>$200,000</td><td>$3,000</td><td>$1,600-$2,000</td><td>$1,000-$1,400 saving</td></tr></table>` },
    { num: "05", slug: "mls-05", name: "Your Accountant Brief", desc: "MLS questions to take before lodging your tax return.", tier: 1, content: `<div class="info-box">Check these now — MLS is assessed in the annual return and cannot be amended without penalty exposure.</div><div class="action-box"><h3>Question 1</h3><p>"What is my MLS income including fringe benefits and employer super — and do I owe the surcharge?"</p></div><h3>Question 2</h3><p>"Is the cost of hospital cover less than my MLS liability?"</p><h3>Question 3</h3><p>"As a couple — does the family threshold mean MLS doesn't apply to us?"</p>` },
    { num: "06", slug: "mls-06", name: "Full Income and Tax Optimisation", desc: "Coordinate income, super, and private cover for minimum overall tax.", tier: 2, content: `<h2>Income and MLS Optimisation</h2><p>The MLS interacts with superannuation strategy, salary packaging, and overall income structuring. An integrated approach minimises total tax.</p><div class="action-box"><h3>Integrated Strategy</h3><p>1. Calculate MLS income accurately — include fringe benefits and employer super</p><p>2. Model super contributions — does a contribution eliminate MLS?</p><p>3. Compare net benefit of each strategy against its cost</p><p>4. Select minimum-cost approach to avoid surcharge</p></div>` },
    { num: "07", slug: "mls-07", name: "Family Structuring Strategy", desc: "How couples and families can structure income to minimise MLS.", tier: 2, content: `<h2>Family MLS Strategy</h2><p>Families have a combined income threshold of $186,000 for 2025/26. This can create planning opportunities for couples where income can be spread.</p><table><tr><th>Couple Income Split</th><th>MLS Applies?</th><th>Action</th></tr><tr><td>$140k + $46k = $186k</td><td>At threshold — borderline</td><td>Confirm family threshold applies</td></tr><tr><td>$120k + $80k = $200k</td><td>Yes — over family threshold</td><td>Both need hospital cover</td></tr><tr><td>$100k + $80k = $180k</td><td>No — under $186k</td><td>No MLS even without cover</td></tr></table>` },
    { num: "08", slug: "mls-08", name: "Insurance and Tax Integration Plan", desc: "Full integration of private cover, MLS, and income structuring.", tier: 2, content: `<h2>Integrated Insurance and Tax Strategy</h2><div class="action-box"><h3>Annual Review Checklist</h3><p>April: Review income forecast for current year — will MLS apply?</p><p>May: Compare cheapest qualifying hospital cover vs MLS</p><p>June: If cover not held — get it before 30 June to limit uncovered period</p><p>July-September: Lodge BAS / review income structuring for next year</p><p>October: Tax return — confirm MLS treatment is correct</p></div><p>For high-income earners: hospital cover is almost always cheaper than the surcharge and provides additional health access. The break-even point for most people is income between $93,000 and $108,000.</p>` },
  ],
  persona: { name: "Gary", age: 64, occupation: "Retired FIFO worker, Perth WA", location: "Perth, Western Australia", family: "Partner Sandra. Two adult kids — Jess and Liam.", financialSnapshot: "$3.4M SMSF income and company distributions. Total income approximately $155,000. Gary and Sandra have not had private health insurance since their FIFO days when it was provided by the employer.", painPoint: "Gary does not know the Medicare Levy Surcharge applies. He has been paying 1.5% MLS on his $155,000 income for at least two years — $2,325 per year in avoidable tax.", discovery: "Sandra mentioned at dinner that she had seen an ad for private health insurance and wondered if they should get it. Gary called his accountant the next day to ask whether it made financial sense.", voice: "Gary will immediately understand the cost comparison once he sees the numbers. Show him $2,325 MLS vs $1,700 for hospital cover and he will make the call that afternoon." },
  story: { hook: "Sandra had seen an ad for private health insurance on the television. She had mentioned it at dinner — maybe they should look into it. Gary had not given it much thought.", setup: ["They had both been on the FIFO employer health cover for years. When Gary retired, the cover stopped. He had not replaced it — they were generally healthy, they had Medicare, and the premiums seemed expensive. Life had moved on.", "At their last accountant meeting in April, the accountant had asked about private health insurance. Gary had said no. The accountant had nodded and moved on. Gary had not connected this to anything.", "Sandra brought it up again in May. She had been to the doctor twice that year and felt the wait at the bulk-billing clinic was getting longer. Gary called his accountant and asked directly: does not having private health insurance cost us anything at tax time?"], revelation: "The accountant's answer was immediate: yes. Gary's income — SMSF pension, company distributions — was around $155,000 for MLS purposes. The 1.5% MLS rate applied. His annual MLS was $2,325. Sandra's income was under the threshold so she was not affected individually. But Gary had been paying $2,325 in extra tax for two years. Total: $4,650 in avoidable tax.", resolution: "Gary and Sandra looked at hospital cover options that afternoon. The cheapest qualifying basic hospital policy for Gary was $1,680 per year. The net saving from taking out cover: $645 per year. Gary called the insurer and signed up before the end of the week — ensuring coverage for the last two months of the current financial year and the full year going forward. He also asked his accountant whether prior years could be amended — they could not, but the surcharge stopped from the date cover commenced. Sandra asked why the accountant had not mentioned this when she saw they had no private health insurance listed. It was a fair question." },
  calendarTitle: "Medicare Levy Surcharge — Key Dates",
  tier1Calendar: [{ uid: "mls-cover", summary: "Private health — get hospital cover before 30 June", description: "Ensure hospital cover is in place before 30 June to avoid full-year MLS.", date: "20260615" }, { uid: "mls-return", summary: "Tax Return Due — 31 October 2026", description: "MLS assessed in annual individual tax return.", date: "20261031" }],
  tier2Calendar: [{ uid: "mls-review", summary: "MLS — Annual income and cover review", description: "Review forecast income and confirm hospital cover vs MLS comparison.", date: "20260501" }, { uid: "mls-cover", summary: "Get hospital cover if needed — before 30 June", description: "Take out qualifying hospital cover to limit MLS exposure.", date: "20260615" }, { uid: "mls-return", summary: "Tax Return Due", description: "Lodge return — MLS assessed based on cover for full year.", date: "20261031" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_MLS_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_AU_MLS_147" },
  monitorUrls: ["https://www.ato.gov.au/individuals-and-families/medicare-and-private-health-insurance/medicare-levy-surcharge"],
  sidebarNumbers: [{ label: "Singles threshold", value: "$93,001" }, { label: "Family threshold", value: "$186,000" }, { label: "Top MLS rate", value: "1.5%" }, { label: "On $150k", value: "$2,250 MLS" }],
  sidebarMathsTitle: "The MLS calculation",
  sidebarMathsIncludes: ["Taxable income + reportable fringe benefits + reportable employer super", "Applies to entire MLS income — not just amount over threshold", "Avoided by appropriate hospital cover for full year"],
  sidebarMathsExcludes: ["NOT avoided by extras-only cover", "NOT pro-rated to threshold excess only", "NOT a family threshold if combined income over $186k"],
  sidebarMathsNote: "Source: ATO — Medicare Levy Surcharge · ITAA 1936 Part VIIB",
  howToSteps: [{ position: 1, name: "Enter total income", text: "Select your income including fringe benefits and reportable employer super." }, { position: 2, name: "Confirm cover status", text: "Indicate whether you have appropriate private hospital cover." }, { position: 3, name: "Get MLS calculation", text: "See your exact MLS liability and comparison with hospital cover cost." }, { position: 4, name: "Get your avoidance plan", text: "Receive cover options, timing strategy, and income structuring analysis." }],
  successPromptFields: [
    { key: "annual_income",      label: "Income band for MLS purposes",          defaultVal: "band_93_108" },
    { key: "has_hospital_cover", label: "Has appropriate hospital cover",         defaultVal: "false" },
    { key: "is_family",          label: "Family or single assessment",            defaultVal: "false" },
    { key: "status",             label: "MLS verdict status",                     defaultVal: "SURCHARGE APPLIES" },
    { key: "mls_annual",         label: "Estimated annual MLS exposure (AUD)",    defaultVal: "1000" },
    { key: "tier",               label: "Product tier purchased",                 defaultVal: "67" },
  ],
  tier1AssessmentFields: [
    "mlsStatus",
    "incomeForMLSPurposes",
    "surchargeRateTier",
    "estimatedMLSPayable",
    "coverCostEstimate",
    "netSavingFromCover",
    "coverTimingStrategy",
    "thresholdPosition",
    "strongestRiskTrigger",
    "confidenceLevel",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "mlsStatus",
    "incomeForMLSPurposes",
    "surchargeRateTier",
    "estimatedMLSPayable",
    "coverCostEstimate",
    "netSavingFromCover",
    "coverTimingStrategy",
    "partnerCoverAnalysis",
    "familyThresholdPosition",
    "superContributionOpportunity",
    "policyExcessCheck",
    "integratedPlan",
    "nextYearCalendar",
    "strongestRiskTrigger",
    "confidenceLevel",
  ],
};
