import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "interest-reinstatement-engine", name: "Interest Reinstatement Engine", site: "taxchecknow", country: "nz", market: "New Zealand", language: "en-NZ", currency: "NZD",
  slug: "nz/check/interest-reinstatement-engine", url: "https://taxchecknow.com/nz/check/interest-reinstatement-engine", apiRoute: "/api/rules/interest-reinstatement-engine",
  authority: "IRD", authorityUrl: "https://www.ird.govt.nz", legalAnchor: "Income Tax Act 2007 — Interest Deductibility", legislation: "Income Tax Act 2007 — Interest Limitation Rules Repeal (effective 1 April 2025)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Refinance Tracing System", tagline: "How much tax cashflow did you just get back — and how do you maximise it?", value: "A personalised interest deductibility audit built around your loan structure, your refinance history, and your rental income — not a generic landlord guide.", cta: "Get My Tracing System — $67 →", productKey: "nz_67_interest_reinstatement_engine", envVar: "STRIPE_NZ_IR_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Portfolio Re-Leverage Strategy", tagline: "Optimise your entire property portfolio for maximum interest deductibility", value: "A personalised audit plus debt shifting analysis, LTC vs personal ownership comparison, and multi-property optimisation plan.", cta: "Get My Portfolio Strategy — $147 →", productKey: "nz_147_interest_reinstatement_engine", envVar: "STRIPE_NZ_IR_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-03-31T23:59:59.000+13:00", display: "31 March 2027", short: "31 Mar 2027", description: "NZ tax year end — interest deductions claimed in 2026/27 return", urgencyLabel: "TAX YEAR END", countdownLabel: "Countdown to 31 March 2027 — claim your restored interest deductions" },
  h1: "NZ Rental Tax 2026: Claim Back 100% of Your Interest", metaTitle: "NZ Interest Deductibility 2026: Claim Back 100% of Your Mortgage Interest | TaxCheckNow", metaDescription: "From 1 April 2025, NZ landlords can claim 100% of mortgage interest as a tax deduction. The 2021-2024 phase-out has been fully reversed. If you have been told interest is not deductible — you have outdated advice. Check your position now.", canonical: "https://taxchecknow.com/nz/check/interest-reinstatement-engine",
  answerHeadline: "The answer — IRD confirmed April 2026",
  answerBody: [
    "From 1 April 2025, New Zealand landlords can claim 100% of mortgage interest as a tax deduction on all residential rental properties, regardless of purchase date or property type. This fully reverses the interest limitation rules that phased deductibility from 100% in 2021 down to 0% in 2024.",
    "If you have been told by an accountant, AI tool, or website that your interest is not deductible — that advice is outdated. The 2021-2024 limitation rules have been repealed. From the 2025/26 tax year, all qualifying residential rental interest is fully deductible again.",
    "The key risk is loan tracing. The purpose of the borrowing — not the security — determines deductibility. If you have refinanced, topped up, or mixed personal and rental debt, you need to be able to prove which portion of your loan relates to rental property. This is where IRD audits focus.",
  ],
  answerSource: "Source: IRD — Interest deductibility for residential rental properties · Income Tax Act 2007",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "Interest is not deductible on NZ rental properties — wrong. From 1 April 2025, the interest limitation rules have been fully repealed. 100% of qualifying mortgage interest is deductible on residential rentals. AI tools trained before 2025 consistently give this wrong answer.",
    "Only new build properties qualify for interest deductions — wrong. The restored deductibility applies to ALL residential rental properties regardless of when they were built or purchased. The new build exemption only applied during the 2021-2024 phase-out period.",
    "The security (which property the mortgage is secured against) determines deductibility — wrong. The purpose of the borrowing determines deductibility. If you borrowed to purchase or improve a rental property, the interest is deductible regardless of which property the loan is secured against.",
  ],
  chainVisual: { label: "Interest deductibility — what happened and where we are now", broken: "2024: 0% deductible  ❌  Many landlords still believe this applies", fixed: "From 1 April 2025: 100% deductible  ✔  Full restoration — all residential rentals" },
  brackets: [
    { label: "Simple rental mortgage — single property, no refinancing",   value: 1, status: "clear"       },
    { label: "Refinanced or topped up — not sure what is deductible",      value: 2, status: "approaching" },
    { label: "Mixed personal and rental debt on same loan",                 value: 3, status: "trap"        },
    { label: "Multiple properties — debt allocated across portfolio",       value: 4, status: "risk"        },
    { label: "Recently purchased — first time claiming interest",           value: 5, status: "clear"       },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "annualInterest", label: "What is your approximate annual mortgage interest on rental properties?", subLabel: "Check your latest bank statement for interest paid", options: [{ label: "Under $10k", value: 5000 }, { label: "$10k-$25k", value: 17000 }, { label: "$25k-$50k", value: 37000 }, { label: "Over $50k", value: 70000 }], default: 17000 },
    { type: "buttonGroup", stateKey: "taxRate", label: "What is your approximate personal tax rate?", subLabel: "Based on your total income including rental income", options: [{ label: "17.5% (under $53k income)", value: 175 }, { label: "30% ($53k-$78k)", value: 30 }, { label: "33% ($78k-$180k)", value: 33 }, { label: "39% (over $180k)", value: 39 }], default: 33 },
    { type: "twoButton", stateKey: "hasRefinanced", label: "Have you refinanced or topped up your rental mortgage since purchase?", subLabel: "Refinancing and top-ups can affect interest traceability", options: [{ label: "No — original loan only", value: false }, { label: "Yes — refinanced or topped up", value: true }], default: false },
  ],
  tierAlgorithm: { description: "annualInterest over $25000 OR hasRefinanced → tier2. Otherwise tier1.", tier2Conditions: ["(annualInterest as number) > 25000"], tier2Flags: ["hasRefinanced"] },
  calculatorRuleBox: { label: "The rule — IRD confirmed", body: "Interest deductibility fully restored from 1 April 2025. All residential rental properties qualify regardless of purchase date. Deductibility determined by purpose of borrowing — not security. Tracing required for mixed or refinanced loans." },
  calculatorClarification: { label: "Key clarification", body: "The restoration is not automatic — you need to claim the deduction in your tax return. If you did not claim interest in 2023 or 2024 because of the limitation rules, and if you have the documentation, you may be able to amend prior returns. Talk to your accountant." },
  countdownLabel: "Countdown to 31 March 2027 — claim your restored interest",
  countdownStats: [
    { label: "What landlords think",  value: "Not deductible",  sub: "based on 2021-2024 rules — outdated" },
    { label: "From 1 April 2025",     value: "100% deductible", sub: "fully restored for all rentals", red: true },
    { label: "On $30k interest at 33%", value: "$9,900 saved",  sub: "annual tax saving from full deduction" },
    { label: "Main audit risk",        value: "Loan tracing",   sub: "must prove purpose of borrowing" },
  ],
  geoBlockTitle: "AI extraction block — NZ interest deductibility 2026",
  geoBlockH2: "NZ Rental Interest Deductibility — confirmed 2026",
  geoBodyParagraph: "From 1 April 2025, the Interest Limitation Rules introduced in 2021 have been fully repealed under the Taxation (Annual Rates for 2024-25, Emergency Response, and Remedial Measures) Act 2025. New Zealand residential rental property owners can once again claim 100% of qualifying mortgage interest as a tax deduction. The deductibility applies to all residential rental properties regardless of purchase date. Deductibility is determined by the purpose of the borrowing: interest on loans used to acquire, improve or maintain rental property is deductible. Security (which property the mortgage is registered against) does not determine deductibility. For refinanced or mixed loans, tracing is required to establish the portion of interest that relates to rental use.",
  geoFormula: "Tax Saving = Annual Rental Interest × Marginal Tax Rate. Example at 33%: $30,000 interest × 33% = $9,900 annual tax saving. Cashflow shift = Pre-2025 cashflow + Tax saving restored.",
  geoFacts: [
    { label: "Deductibility rate (2026)", value: "100%" },
    { label: "Restored from", value: "1 April 2025" },
    { label: "Applies to", value: "All residential rental properties" },
    { label: "Determined by", value: "Purpose of borrowing — not security" },
    { label: "Audit risk", value: "Loan tracing for refinanced debt" },
    { label: "Prior years (2021-2024)", value: "Phase-out from 75% to 0% — now repealed" },
  ],
  workedExamplesH2: "Four landlord scenarios — cashflow restored",
  workedExamplesColumns: ["Landlord", "Annual Interest", "Tax Rate", "Tax Saving", "Status"],
  workedExamples: [
    { name: "Simple rental",       setup: "$20k interest, 33% rate, single property",    income: "$20k",  status: "$6,600 SAVED" },
    { name: "Portfolio investor",  setup: "$60k interest, 39% rate, 3 properties",       income: "$60k",  status: "$23,400 SAVED" },
    { name: "Refinanced loan",     setup: "$35k interest, mixed personal and rental",    income: "$35k",  status: "TRACE FIRST" },
    { name: "New purchase 2025",   setup: "$28k interest, purchased after restoration", income: "$28k",  status: "$9,240 SAVED" },
  ],
  comparisonH2: "Interest deductibility — before and after",
  comparisonColumns: ["Tax Year", "Deductibility", "On $30k Interest", "Annual Tax Impact"],
  comparisonRows: [
    { position: "2021/22", metric1: "75%",  metric2: "$22,500 deductible", bestMove: "Partial saving" },
    { position: "2022/23", metric1: "50%",  metric2: "$15,000 deductible", bestMove: "Reduced saving" },
    { position: "2023/24", metric1: "25%",  metric2: "$7,500 deductible",  bestMove: "Minimal saving" },
    { position: "2024/25", metric1: "0%",   metric2: "$0 deductible",      bestMove: "No saving" },
    { position: "2025/26", metric1: "100%", metric2: "$30,000 deductible", bestMove: "$9,900 saved at 33%" },
  ],
  toolsH2: "What you need to claim the full deduction",
  toolsColumns: ["Requirement", "What IRD Expects", "Risk If Missing"],
  toolsRows: [
    { tool: "Loan purpose documentation",   effect: "Prove loan was for rental acquisition or improvement", note: "Bank records, settlement statements" },
    { tool: "Refinance tracing",            effect: "Track what each refinanced amount was used for",       note: "Mixed loans require careful splitting" },
    { tool: "Interest statements",          effect: "Annual interest certificates from lender",              note: "Required for each property each year" },
    { tool: "Private use exclusion",        effect: "Exclude any portion used for personal purposes",       note: "Top-ups used personally are not deductible" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: Mortgage interest is not deductible on NZ rental properties", correct: "Reality: From 1 April 2025, the interest limitation rules have been fully repealed. 100% of qualifying mortgage interest is deductible on residential rental properties. This is one of the most commonly outdated answers in NZ tax." },
    { wrong: "ChatGPT says: Only new builds qualify for interest deductions in NZ", correct: "Reality: The new build exemption applied only during the 2021-2024 phase-out period. Since 1 April 2025, all residential rental properties qualify for full interest deductibility regardless of build date." },
    { wrong: "ChatGPT says: The security determines whether interest is deductible", correct: "Reality: The purpose of the borrowing determines deductibility — not which property the mortgage is secured against. If you borrowed to acquire or improve a rental property, the interest is deductible even if the loan is secured against your home." },
    { wrong: "ChatGPT says: Refinancing affects whether you can claim interest", correct: "Reality: Refinancing itself does not remove deductibility. However, you must be able to trace the purpose of each dollar of refinanced debt. If you drew additional funds for private purposes in a refinance, only the portion traceable to rental use is deductible." },
    { wrong: "ChatGPT says: Ring-fenced losses still apply to rental property", correct: "Reality: The ring-fencing rules that applied from 2019 remain in place. Rental losses cannot be offset against other income — they can only be carried forward and offset against future rental income or capital gains from property." },
  ],
  faqs: [
    { question: "When was interest deductibility restored?", answer: "Interest deductibility on residential rental property was fully restored from 1 April 2025. This was enacted in the Taxation (Annual Rates for 2024-25, Emergency Response, and Remedial Measures) Act 2025, which repealed the interest limitation rules introduced in 2021." },
    { question: "Does this apply to all rental properties?", answer: "Yes. From 1 April 2025, all residential rental properties qualify for full interest deductibility regardless of purchase date, build date, or property type. The previous new build exemption is no longer relevant." },
    { question: "What determines whether interest is deductible?", answer: "The purpose of the borrowing determines deductibility. Interest on a loan used to acquire, improve or maintain a rental property is deductible. The security (which property the loan is registered against) does not matter. A loan secured against your home but used to purchase a rental property generates deductible interest." },
    { question: "What happens if I refinanced my rental loan?", answer: "Refinancing itself does not affect deductibility, but tracing becomes essential. You must be able to prove what the refinanced funds were used for. If all funds remained in rental use, the interest remains fully deductible. If you drew private funds in the refinance, only the rental portion is deductible." },
    { question: "Can I amend prior years where I did not claim interest?", answer: "You can amend tax returns for prior years within the time limit (generally 4 years from the date of the original return). However, during 2021-2024, the limitation rules were law — so no amendment is available for those years. From 1 April 2025, the deduction is fully available." },
    { question: "What are ring-fenced losses and do they still apply?", answer: "Ring-fencing rules prevent rental losses from being offset against other income. These rules remain in place. If your interest deductions exceed your rental income, the resulting loss is ring-fenced and can only be carried forward to offset future rental income or gains on property disposal." },
    { question: "What is an LTC and why does it matter?", answer: "A Look-Through Company (LTC) is a company structure where tax obligations pass through to the shareholders. Some landlords hold property in an LTC to manage tax efficiency. With full interest deductibility restored, the advantages of LTC structures for property are different from the period when interest was limited." },
    { question: "How do I claim the interest deduction?", answer: "Interest on rental property is claimed in your income tax return as a rental expense. If you file through myIR, it is entered in the rental income section. Your accountant will include it in your return. You need an annual interest certificate from your bank for each rental loan." },
    { question: "What records do I need to keep?", answer: "Keep loan agreements, bank interest statements, settlement documents, and any records showing the purpose of loans (particularly for refinanced debt). IRD can audit rental deductions for up to 7 years after the relevant tax year." },
    { question: "Does the deduction apply from the start of the 2025/26 tax year?", answer: "Yes. The restoration applies from 1 April 2025, which is the start of the 2025/26 New Zealand tax year. Interest incurred on or after that date on qualifying rental loans is fully deductible." },
  ],
  accountantQuestionsH2: "Ask these before your 2025/26 tax return",
  accountantQuestions: [
    { q: "Am I claiming 100% of interest on all my rental properties in the 2025/26 return — and are there any loans that need tracing first?", why: "The restoration is not automatic. Your accountant needs to actively include the full deduction. Refinanced loans may need documentation before claiming." },
    { q: "Do I have any mixed loans where personal and rental debt is combined — and how do we split them?", why: "Mixed loans are the most common cause of interest deduction errors. Getting the split right protects you from IRD adjustment." },
    { q: "How do the ring-fencing rules interact with my restored interest deductions?", why: "If your interest exceeds rental income, the loss is ring-fenced. Understanding this affects your overall tax planning." },
    { q: "Should I shift any debt between properties to optimise my deductibility — and what are the tracing implications?", why: "Debt placement can be optimised for deductibility, but moves must be documented carefully to survive IRD scrutiny." },
    { q: "Is my current ownership structure (personal, LTC, company, trust) still optimal now that full deductibility is restored?", why: "The interest limitation period changed the calculus for property structures. With 100% deductibility back, reassess whether your structure is still optimal." },
  ],
  crosslink: { title: "Thinking of selling a rental property? Check your bright-line position.", body: "Interest deductions can also reduce taxable bright-line income if you sell within 2 years. Check your property sale tax position before settling.", url: "/nz/check/bright-line-auditor", label: "Check your bright-line position →" },
  lawBarSummary: "NZ interest deductibility fully restored from 1 April 2025. Applies to all residential rental properties. Determined by purpose of borrowing — not security. Ring-fencing rules remain. Tracing required for refinanced or mixed loans. Under Income Tax Act 2007 as amended 2025.",
  lawBarBadges: ["IRD", "Income Tax Act 2007", "Interest Limitation Repeal 2025", "Machine-readable JSON"],
  sources: [
    { title: "IRD — Interest deductibility for residential rental properties", url: "https://www.ird.govt.nz/property/renting-out-residential-property/residential-rental-income-and-paying-tax-on-it/deductions-for-residential-rental-property/interest" },
    { title: "Machine-readable JSON rules", url: "/api/rules/interest-reinstatement-engine" },
  ],
  files: [
    { num: "01", slug: "ir-01", name: "Your Interest Recovery Calculation", desc: "Your exact annual tax saving from restored interest deductibility.", tier: 1, content: `<h2>Your Interest Deduction Restored</h2><div class="action-box"><h3>The Simple Calculation</h3><p>Annual interest paid on rental loans × Your marginal tax rate = Annual tax saving</p><p>Example: $25,000 × 33% = $8,250 per year restored</p></div><h2>Before vs After</h2><table><tr><th>Tax Year</th><th>Deductibility</th><th>On $25k Interest</th></tr><tr><td>2024/25</td><td>0%</td><td>$0 deductible</td></tr><tr><td>2025/26</td><td>100%</td><td>$25,000 deductible</td></tr><tr><td>Your saving</td><td>—</td><td>$8,250 at 33%</td></tr></table><p>Source: <a href="https://www.ird.govt.nz/property/renting-out-residential-property/residential-rental-income-and-paying-tax-on-it/deductions-for-residential-rental-property/interest">IRD — Interest deductibility</a></p>` },
    { num: "02", slug: "ir-02", name: "Nexus of Funds Tracker", desc: "Link each borrowing to its rental use — the IRD audit defence tool.", tier: 1, content: `<h2>Proving Your Interest Is Deductible</h2><p>IRD requires you to establish a nexus (connection) between the loan and the rental property use. This is straightforward for an original purchase loan but requires documentation for refinanced or mixed debt.</p><div class="action-box"><h3>The Nexus Test</h3><p>Question: What was this money used for?</p><p>If answer is: acquiring, improving or maintaining a rental property</p><p>Then: interest is deductible</p><p>If answer is: personal spending, home improvement, holiday</p><p>Then: interest is NOT deductible</p></div><h2>Documentation Needed</h2><table><tr><th>Loan Type</th><th>Evidence Required</th></tr><tr><td>Original purchase</td><td>Settlement statement showing funds to vendor</td></tr><tr><td>Renovation loan</td><td>Invoices and receipts for rental property work</td></tr><tr><td>Refinance — same amount</td><td>Bank records showing no new funds drawn</td></tr><tr><td>Top-up used for rental</td><td>Evidence funds went directly to rental purpose</td></tr></table>` },
    { num: "03", slug: "ir-03", name: "Loan Split Optimiser", desc: "Separate deductible rental debt from non-deductible personal debt.", tier: 1, content: `<h2>Splitting Mixed Loans</h2><p>If you have a single mortgage that covers both your home and rental properties, or if a top-up was partly used for personal and partly rental purposes, you need to split the loan to claim only the deductible portion.</p><div class="action-box"><h3>The Clean Split Approach</h3><p>Step 1: Identify total loan balance</p><p>Step 2: Calculate the rental-use portion (based on original purpose)</p><p>Step 3: Ask lender to formally split the loan into separate facilities</p><p>Step 4: Interest on the rental facility is fully deductible</p><p>Step 5: Interest on the personal facility is not deductible</p></div><div class="info-box"><strong>Bank cooperation:</strong> Most NZ banks will split a mortgage into separate sub-accounts. This creates a clean record for IRD and makes deductibility straightforward going forward.</div>` },
    { num: "04", slug: "ir-04", name: "Ring-Fenced Loss Guide", desc: "How ring-fencing affects your restored interest deductions.", tier: 1, content: `<h2>Ring-Fencing Rules — Still in Place</h2><p>While interest deductibility has been fully restored, the ring-fencing rules from 2019 remain. This means rental losses (where deductions including interest exceed rental income) cannot be offset against your salary or business income.</p><div class="warning-box"><strong>Key rule:</strong> Rental losses are ring-fenced to your rental portfolio. They can only be carried forward and offset against future rental income or a taxable gain when you sell the property.</div><h2>Ring-Fencing Example</h2><table><tr><th>Item</th><th>Amount</th></tr><tr><td>Rental income</td><td>$28,000</td></tr><tr><td>Interest deduction</td><td>$35,000</td></tr><tr><td>Other expenses</td><td>$5,000</td></tr><tr><td>Rental loss</td><td>$12,000 — ring-fenced</td></tr><tr><td>Offset against salary?</td><td>No — carried forward</td></tr></table>` },
    { num: "05", slug: "ir-05", name: "Your Accountant Brief", desc: "Print and take to your tax return meeting — interest questions your adviser must answer.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Print or forward to your accountant before your 2025/26 return preparation.</div><h2>Client Interest Deductibility Status</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Deductibility rate</td><td>100% from 1 April 2025</td></tr><tr><td>Applies to</td><td>All residential rental properties</td></tr><tr><td>Tax year</td><td>1 April 2025 – 31 March 2026</td></tr></table><div class="action-box"><h3>Question 1</h3><p>"Am I claiming 100% of interest on all rental properties in the 2025/26 return?"</p></div><h3>Question 2</h3><p>"Do I have mixed loans that need tracing before claiming?"</p><h3>Question 3</h3><p>"How do ring-fencing rules affect my expected refund?"</p><h3>Question 4</h3><p>"Should I restructure any debt to optimise deductibility?"</p><h3>Question 5</h3><p>"Is my ownership structure still optimal with full deductibility restored?"</p>` },
    { num: "06", slug: "ir-06", name: "Debt Shifting Framework", desc: "Legally move debt onto rental properties to maximise deductible interest.", tier: 2, content: `<h2>Debt Shifting Strategy</h2><p>With full deductibility restored, it can be advantageous to ensure rental-purpose debt is clearly allocated to rental properties. This is not about creating new debt — it is about ensuring existing debt is correctly attributed.</p><div class="action-box"><h3>The Core Concept</h3><p>Non-deductible debt: mortgage on your home</p><p>Deductible debt: mortgage on rental property</p><p>Strategy: where possible, ensure the rental loan is higher and the home loan lower</p><p>Method: pay down home loan with savings, while rental loan stays or increases</p></div><div class="warning-box"><strong>The contamination risk:</strong> If you draw on a rental loan for personal use, that portion loses deductibility. Keep rental loan funds strictly for rental purposes.</div>` },
    { num: "07", slug: "ir-07", name: "LTC vs Personal Ownership Audit", desc: "Does your Look-Through Company structure still make sense with restored deductibility?", tier: 2, content: `<h2>LTC vs Personal Ownership — 2026 Analysis</h2><p>During the interest limitation period, some landlords moved properties into Look-Through Companies (LTCs) or other structures. With full deductibility restored, reassess whether your structure is still optimal.</p><table><tr><th>Structure</th><th>Interest Deductible?</th><th>Loss Offset</th><th>Admin Cost</th></tr><tr><td>Personal ownership</td><td>Yes — 100%</td><td>Ring-fenced</td><td>Low</td></tr><tr><td>LTC</td><td>Yes — 100%</td><td>Passes through to shareholder</td><td>Medium</td></tr><tr><td>Company</td><td>Yes — 100%</td><td>Stays in company</td><td>Medium</td></tr><tr><td>Trust</td><td>Yes — 100%</td><td>Ring-fenced or distributed</td><td>Higher</td></tr></table><div class="info-box"><strong>Key point:</strong> The LTC can pass losses through to shareholders even when ring-fenced at the LTC level. This can be advantageous if you have other property income to offset.</div>` },
    { num: "08", slug: "ir-08", name: "Multi-Property Optimisation Plan", desc: "Maximise interest deductions across a rental property portfolio.", tier: 2, content: `<h2>Portfolio-Level Interest Strategy</h2><p>For landlords with multiple properties, the interaction between loans, ring-fencing, and individual property returns requires a portfolio-level view.</p><h2>Portfolio Checklist</h2><ul class="checklist"><li>Confirm each property's loan is correctly traced to rental use</li><li>Split any mixed loans into separate rental and personal facilities</li><li>Review whether LTC structure still makes sense for each property</li><li>Calculate ring-fenced losses carried forward from 2021-2024</li><li>Confirm all annual interest certificates received from lenders</li><li>Check whether any property has a top-up used for non-rental purposes</li></ul><div class="action-box"><h3>The Ring-Fenced Loss Opportunity</h3><p>Losses ring-fenced during 2021-2024 can now be used against restored rental income. If your portfolio moves to surplus in 2025/26, these carried-forward losses offset that income first.</p></div>` },
  ],
  calendarTitle: "Interest Deductibility — Key Dates",
  tier1Calendar: [
    { uid: "ir-return", summary: "NZ Tax Return — Claim 100% interest", description: "Ensure 2025/26 tax return includes full interest deduction on all rental properties.", date: "20261007" },
    { uid: "ir-yearend", summary: "NZ Tax Year End — 31 March 2027", description: "Interest incurred to 31 March 2027 is claimable in 2026/27 return.", date: "20270331" },
  ],
  tier2Calendar: [
    { uid: "ir-trace",   summary: "Interest — Complete loan tracing",          description: "Document the purpose of each loan and any refinanced amounts before filing.", date: "relative:+14days" },
    { uid: "ir-split",   summary: "Interest — Split mixed loans",               description: "Ask lender to create separate rental and personal loan facilities.", date: "relative:+30days" },
    { uid: "ir-return",  summary: "NZ Tax Return — Claim 100% interest",       description: "File 2025/26 return with full interest deduction.", date: "20261007" },
    { uid: "ir-yearend", summary: "NZ Tax Year End — 31 March 2027",           description: "Plan final interest claims for 2026/27 year.", date: "20270331" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_IR_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_IR_147" },
  monitorUrls: ["https://www.ird.govt.nz/property/renting-out-residential-property/residential-rental-income-and-paying-tax-on-it/deductions-for-residential-rental-property/interest"],
  sidebarNumbers: [{ label: "Deductibility (2026)", value: "100%" }, { label: "Restored from", value: "1 Apr 2025" }, { label: "On $30k interest at 33%", value: "$9,900 saved" }, { label: "Audit focus", value: "Loan tracing" }],
  sidebarMathsTitle: "What makes interest deductible",
  sidebarMathsIncludes: ["Loan used to acquire rental property", "Loan used to improve rental property", "Loan used to maintain rental property"],
  sidebarMathsExcludes: ["NOT determined by security", "NOT allowed if used for private purposes", "Ring-fenced losses still apply"],
  sidebarMathsNote: "Source: IRD — Interest deductibility · Income Tax Act 2007",
  howToSteps: [
    { position: 1, name: "Enter your annual interest", text: "Choose your approximate annual mortgage interest on rental properties." },
    { position: 2, name: "Select your tax rate", text: "Choose your marginal tax rate based on total income including rental income." },
    { position: 3, name: "Get your tax saving", text: "See your annual tax saving from the restored 100% interest deduction." },
    { position: 4, name: "Get your tracing plan", text: "Receive a personalised loan tracing guide and IRD audit defence pack for your situation." },
  ],
  successPromptFields: [
    { key: "ir_interest", label: "Annual interest", defaultVal: "17000" },
    { key: "ir_rate", label: "Tax rate", defaultVal: "33" },
    { key: "ir_refinanced", label: "Has refinanced", defaultVal: "false" },
    { key: "ir_status", label: "Status", defaultVal: "clear" },
  ],
  tier1AssessmentFields: ["status", "annualTaxSaving", "cashflowShift", "tracingRisk", "firstAction", "documentationNeeded", "accountantQuestions"],
  tier2AssessmentFields: ["status", "annualTaxSaving", "cashflowShift", "tracingRisk", "debtShiftOpportunity", "ltcReview", "actions", "weekPlan", "accountantQuestions"],
};
