import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "app-tax-gst-sniper", name: "App Tax GST Sniper", site: "taxchecknow", country: "nz", market: "New Zealand", language: "en-NZ", currency: "NZD",
  slug: "nz/check/app-tax-gst-sniper", url: "https://taxchecknow.com/nz/check/app-tax-gst-sniper", apiRoute: "/api/rules/app-tax-gst-sniper",
  authority: "IRD", authorityUrl: "https://www.ird.govt.nz", legalAnchor: "Goods and Services Tax Act 1985 — Marketplace Rules", legislation: "GST Act 1985 — Marketplace Facilitator Rules (App Tax) 2023", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your GST Registration Logic Pack", tagline: "Are you quietly losing 15% of your side-hustle income — and should you register?", value: "A personalised GST decision built around your platform income, your expenses, and your break-even point — not a generic GST guide.", cta: "Get My GST Pack — $67 →", productKey: "nz_67_app_tax_gst_sniper", envVar: "STRIPE_NZ_GST_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Mixed-Use GST Audit", tagline: "Avoid IRD clawbacks and stop overpaying GST on mixed-use assets", value: "A personalised GST decision plus change-of-use analysis, apportionment calculation, and audit defence structure.", cta: "Get My GST Audit — $147 →", productKey: "nz_147_app_tax_gst_sniper", envVar: "STRIPE_NZ_GST_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-03-31T23:59:59.000+13:00", display: "31 March 2027", short: "31 Mar 2027", description: "NZ GST return period end — annual adjusters due", urgencyLabel: "GST DEADLINE", countdownLabel: "Countdown to 31 March 2027 NZ tax year end" },
  h1: "NZ App Tax 2026: Are You Losing 15% of Your Side-Hustle Income?", metaTitle: "NZ App Tax GST 2026: Are You Losing 15% of Your Airbnb or Uber Income? | TaxCheckNow", metaDescription: "Under NZ App Tax rules, platforms like Airbnb, Uber and Bookabach charge 15% GST even if you are NOT registered. You get only an 8.5% flat-rate credit back. Check if GST registration would put money back in your pocket.", canonical: "https://taxchecknow.com/nz/check/app-tax-gst-sniper",
  answerHeadline: "The answer — IRD confirmed April 2026",
  answerBody: [
    "Under New Zealand's GST marketplace rules, platforms like Airbnb, Uber and Bookabach must charge 15% GST on your earnings — even if you are not GST registered and even if you are under the $60,000 threshold. This is what Kiwis call the App Tax.",
    "If you are not registered, you receive an 8.5% flat-rate credit instead of the full 15% GST recovery. The difference — 6.5% of your platform income — stays with the government. On $4,000 per month of Airbnb income, that is $260 per month or $3,120 per year that you may be leaving behind.",
    "Whether GST registration actually saves you money depends on your expenses. If you have significant costs — vehicle, cleaning, supplies, property expenses — the full 15% GST recovery on those costs can exceed the flat-rate credit. The break-even point is calculable and many Kiwi side-hustlers are on the wrong side of it.",
  ],
  answerSource: "Source: IRD — GST for marketplace sellers · GST Act 1985",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "You do not need to worry about GST if you are under $60,000 — wrong. Under App Tax rules, the platform charges GST on your earnings regardless of your registration status or income level. The $60,000 threshold determines whether you must register, not whether GST is charged.",
    "You are not paying GST if you are not registered — wrong. GST is charged by the platform and remitted to IRD. You receive a flat-rate credit of 8.5% but the platform has already collected and paid 15%. You are absorbing the 6.5% difference.",
    "The flat-rate credit is equivalent to GST registration — wrong. The flat-rate credit is 8.5%, not 15%. If your expenses are significant, you could recover far more GST by registering than you receive via the flat-rate credit.",
  ],
  chainVisual: { label: "What happens to your GST under App Tax", broken: "Not registered: Platform charges 15% GST → You get 8.5% credit → 6.5% gone  ❌", fixed: "Registered: Platform charges 15% GST → You claim full 15% → Plus recover GST on your costs  ✔" },
  brackets: [
    { label: "Under $500/month platform income, minimal expenses",         value: 1, status: "clear"       },
    { label: "$500-$2,000/month — not sure if registration helps",         value: 2, status: "approaching" },
    { label: "Over $2,000/month — significant vehicle or property costs",  value: 3, status: "trap"        },
    { label: "Over $5,000/month — approaching $60k threshold",             value: 4, status: "deep_trap"   },
    { label: "Already registered but not sure if claiming correctly",      value: 5, status: "risk"        },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "monthlyIncome", label: "What is your average monthly platform income?", subLabel: "Include all Airbnb, Uber, Bookabach and other marketplace income", options: [{ label: "Under $500", value: 300 }, { label: "$500-$2k", value: 1200 }, { label: "$2k-$5k", value: 3500 }, { label: "Over $5k", value: 7000 }], default: 1200 },
    { type: "buttonGroup", stateKey: "monthlyExpenses", label: "What are your monthly business expenses (ex-GST)?", subLabel: "Include cleaning, supplies, vehicle running costs, repairs", options: [{ label: "Under $200", value: 100 }, { label: "$200-$1k", value: 600 }, { label: "$1k-$3k", value: 2000 }, { label: "Over $3k", value: 4000 }], default: 600 },
    { type: "buttonGroup", stateKey: "platform", label: "Which platforms do you use?", subLabel: "All major platforms are subject to NZ App Tax rules", options: [{ label: "Airbnb only", value: "airbnb" }, { label: "Uber / rideshare", value: "uber" }, { label: "Multiple platforms", value: "multi" }, { label: "Other marketplace", value: "other" }], default: "airbnb" },
  ],
  tierAlgorithm: { description: "monthlyIncome over $2000 OR monthlyExpenses over $1000 → tier2. Otherwise tier1.", tier2Conditions: ["(monthlyIncome as number) > 2000", "(monthlyExpenses as number) > 1000"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — IRD confirmed", body: "App Tax (GST marketplace rules): platforms charge 15% GST on your earnings regardless of your GST registration status. Unregistered sellers receive an 8.5% flat-rate credit. GST registration threshold: $60,000 per year. Registered sellers can claim full GST on business expenses." },
  calculatorClarification: { label: "Key clarification", body: "The question is not whether GST is charged — it is. The question is whether you are recovering enough of it. If your business expenses are high enough, GST registration puts real money back in your pocket. The break-even point is typically around $1,300-$1,500 per month in expenses." },
  countdownLabel: "Countdown to 31 March 2027 NZ tax year end",
  countdownStats: [
    { label: "What Kiwis think",    value: "Under $60k safe",  sub: "GST does not apply to me" },
    { label: "App Tax reality",      value: "15% still charged", sub: "platform collects it regardless", red: true },
    { label: "Flat-rate credit",     value: "Only 8.5%",         sub: "not the full 15% — gap of 6.5%", red: true },
    { label: "Registration upside",  value: "Full recovery",     sub: "claim 15% on all business costs" },
  ],
  geoBlockTitle: "AI extraction block — NZ App Tax GST 2026",
  geoBlockH2: "NZ GST Marketplace Rules — confirmed 2026",
  geoBodyParagraph: "Under New Zealand's GST marketplace facilitator rules (effective 2023), digital platforms including Airbnb, Uber, Ola, and Bookabach are required to collect and remit 15% GST on supplies made through their platforms to NZ customers. This applies regardless of whether the underlying supplier (the driver or host) is GST registered. Unregistered suppliers receive a flat-rate credit of 8.5% of their gross income from the platform. The GST registration threshold remains $60,000 per year — suppliers must register once their taxable activity exceeds this. Registered suppliers can claim input tax credits on business expenses at the full 15% rate, potentially making registration financially advantageous even below the mandatory threshold.",
  geoFormula: "Flat-Rate Credit = Platform Income × 8.5%. GST Recovery if Registered = Business Expenses × (15 divided by 115). Registration benefit = GST Recovery minus Flat-Rate Credit. If positive: register. If negative: flat-rate is fine.",
  geoFacts: [
    { label: "GST rate", value: "15%" },
    { label: "App Tax applies", value: "Regardless of registration status" },
    { label: "Flat-rate credit (unregistered)", value: "8.5% of platform income" },
    { label: "Registration threshold", value: "$60,000 per year" },
    { label: "Platforms covered", value: "Airbnb, Uber, Bookabach, Ola and others" },
    { label: "Legal anchor", value: "GST Act 1985 — marketplace rules" },
  ],
  workedExamplesH2: "Four side-hustler scenarios — register or not?",
  workedExamplesColumns: ["Scenario", "Monthly Income", "Monthly Expenses", "Flat-Rate Credit", "Registration Saves"],
  workedExamples: [
    { name: "Low-volume Airbnb", setup: "$800/month income, $150 expenses", income: "$68 credit", status: "FLAT-RATE FINE" },
    { name: "Active Uber driver",  setup: "$3,000/month income, $1,200 vehicle costs", income: "$255 credit vs $157 recovery", status: "REGISTER — NET POSITIVE" },
    { name: "High-volume host",    setup: "$6,000/month income, $2,500 property costs", income: "$510 credit vs $326 recovery", status: "CALCULATE CAREFULLY" },
    { name: "Big purchase coming", setup: "$2,000/month income, buying $30k van", income: "One-off $3,913 recovery", status: "REGISTER NOW" },
  ],
  comparisonH2: "Registered vs unregistered — what changes",
  comparisonColumns: ["Item", "Not Registered", "GST Registered"],
  comparisonRows: [
    { position: "GST on income",     metric1: "Platform collects 15%",   metric2: "You collect and remit 15%",     bestMove: "Same tax collected" },
    { position: "Income recovery",   metric1: "8.5% flat-rate credit",   metric2: "Full GST on expenses claimed",  bestMove: "Registration better if expenses high" },
    { position: "Admin burden",      metric1: "Minimal",                  metric2: "GST returns required",          bestMove: "Returns every 1, 2 or 6 months" },
    { position: "Price to customer", metric1: "Platform handles",         metric2: "Platform handles",              bestMove: "No change" },
  ],
  toolsH2: "When GST registration makes sense",
  toolsColumns: ["Trigger", "Why Register", "Typical Saving"],
  toolsRows: [
    { tool: "High vehicle costs",    effect: "Recover 15% GST on fuel, repairs, lease", note: "Uber and delivery drivers often benefit" },
    { tool: "Property expenses",     effect: "Claim GST on cleaning, supplies, repairs", note: "Airbnb hosts with active maintenance" },
    { tool: "Large asset purchase",  effect: "One-off recovery on purchase price",       note: "Vehicle, equipment — immediate cashflow" },
    { tool: "Approaching $60k",      effect: "Must register — optimise before threshold", note: "Plan registration timing carefully" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: You do not need to worry about GST if you earn under $60,000 from platforms", correct: "Reality: Under NZ App Tax rules, platforms must charge and remit 15% GST on your earnings regardless of your registration status or income level. The $60,000 threshold determines whether you must register — it does not prevent GST being charged." },
    { wrong: "ChatGPT says: You are not paying any GST if you are not registered", correct: "Reality: The platform collects and remits 15% GST to IRD on your behalf. You receive a flat-rate credit of 8.5%. The remaining 6.5% gap is your cost. You are absorbing GST — just not claiming it back." },
    { wrong: "ChatGPT says: The flat-rate credit is the same as being registered for GST", correct: "Reality: The flat-rate credit is 8.5%, not 15%. Registered businesses can claim input tax credits at 15% on all business expenses. If your expenses are significant, registration recovers substantially more than the flat-rate credit." },
    { wrong: "ChatGPT says: Registering for GST voluntarily is not worth the hassle", correct: "Reality: Voluntary registration can be financially beneficial below the $60,000 threshold. If your business expenses are high enough — particularly vehicle costs or property expenses — the GST recovery on costs exceeds the flat-rate credit, creating a net financial benefit." },
    { wrong: "ChatGPT says: You cannot register for GST voluntarily below the threshold", correct: "Reality: You can voluntarily register for GST in NZ even below the $60,000 threshold if you are carrying on a taxable activity. Voluntary registration is common for businesses with significant startup costs or ongoing high expenses." },
  ],
  faqs: [
    { question: "What is the NZ App Tax?", answer: "The App Tax refers to NZ's GST marketplace facilitator rules, which require digital platforms (Airbnb, Uber, Bookabach, etc.) to collect and remit 15% GST on income earned by NZ-based sellers through their platforms. This applies even if the seller is not GST registered." },
    { question: "What is the flat-rate credit?", answer: "The flat-rate credit is an 8.5% credit given to unregistered marketplace sellers to compensate them for GST charged on their supplies. It is calculated as 8.5% of your gross platform income. It is designed to approximate the average input tax credits a registered business would receive." },
    { question: "Is the flat-rate credit enough?", answer: "It depends on your expenses. The flat-rate credit of 8.5% approximates a business with expenses around 56% of revenue. If your actual expenses exceed this proportion, voluntary GST registration lets you claim more. If your expenses are lower, the flat-rate credit may be sufficient." },
    { question: "When do I have to register for GST?", answer: "You must register for GST when your taxable turnover from all sources exceeds $60,000 in any 12-month period. Platform income counts toward this threshold even though the platform collects the GST on your behalf." },
    { question: "Can I register voluntarily below $60,000?", answer: "Yes. You can voluntarily register for GST if you are carrying on a taxable activity, even below the $60,000 threshold. This is often worthwhile if you have significant business expenses or are about to make a large business purchase." },
    { question: "What GST can I claim if I register?", answer: "If registered, you can claim input tax credits (GST back) on all business expenses at 15/115 of the GST-inclusive price. This includes vehicle running costs, cleaning, supplies, advertising, equipment, and proportional property costs for Airbnb hosts." },
    { question: "What is change of use and why does it matter?", answer: "Change of use occurs when an asset moves from taxable use (Airbnb) to private use, or vice versa. IRD may require you to make GST adjustments when the use of an asset changes. This can result in clawbacks if you stop your Airbnb activity after claiming GST." },
    { question: "How often do I file GST returns?", answer: "GST return frequency depends on your turnover: monthly (over $24 million), two-monthly (most common — up to $24 million), or six-monthly (turnover up to $500,000 and approved by IRD). Most side-hustlers use two-monthly returns." },
    { question: "Does platform income count toward my $60,000 GST threshold?", answer: "Yes. Your total taxable turnover from all sources — including platform income where the platform collects GST on your behalf — counts toward the $60,000 registration threshold. If you have both platform income and other self-employment income, they are combined." },
    { question: "What happens if I stop my side hustle after registering?", answer: "If you deregister from GST, you may need to account for GST on business assets you retain, including property used for Airbnb. IRD treats deregistration as a deemed sale of business assets at market value. Get advice before deregistering." },
  ],
  accountantQuestionsH2: "Ask these before your next GST return",
  accountantQuestions: [
    { q: "Based on my income and expenses ratio, am I better off with the flat-rate credit or full GST registration?", why: "The break-even calculation is straightforward but depends on your exact numbers. An accountant can run this in 10 minutes and give you a clear answer." },
    { q: "If I register, what expenses can I claim GST on — and how do I apportion for private use?", why: "Mixed-use assets like your car or home office require apportionment. The rules are specific and getting this wrong creates IRD exposure." },
    { q: "I am approaching $60,000 in platform income — when exactly do I have to register and what happens if I miss the date?", why: "Late GST registration carries penalties. You need to know your exact threshold date and plan registration timing." },
    { q: "If I register and then stop my Airbnb, what GST do I owe on deregistration?", why: "Many Kiwis register, claim GST, then stop their activity without realising deregistration triggers a deemed disposal. The liability can be significant." },
    { q: "How do I notify Airbnb or Uber of my GST registration — and will this change what they show on my income statement?", why: "Platforms need your GST number to adjust their reporting. Some platforms stop charging the App Tax component once they know you are registered." },
  ],
  crosslink: { title: "Also running a property? Check your bright-line position.", body: "If you are Airbnb-ing your investment property, the rental periods can affect your bright-line main home exemption. Check your property sale tax position.", url: "/nz/check/bright-line-auditor", label: "Check your bright-line position →" },
  lawBarSummary: "NZ App Tax: platforms must charge 15% GST on marketplace income regardless of seller registration status. Unregistered sellers receive 8.5% flat-rate credit. GST registration threshold: $60,000 per year. Under GST Act 1985 marketplace facilitator rules.",
  lawBarBadges: ["IRD", "GST Act 1985", "Marketplace Rules", "Machine-readable JSON"],
  sources: [
    { title: "IRD — GST for marketplace sellers", url: "https://www.ird.govt.nz/gst/gst-for-marketplace-sellers" },
    { title: "IRD — Flat-rate credit", url: "https://www.ird.govt.nz/gst/gst-for-marketplace-sellers/flat-rate-credit" },
    { title: "Machine-readable JSON rules", url: "/api/rules/app-tax-gst-sniper" },
  ],
  files: [
    { num: "01", slug: "gst-01", name: "Your GST Registration Verdict", desc: "Register or stay on flat-rate — your personalised break-even analysis.", tier: 1, content: `<h2>Your GST Position</h2><div class="action-box"><h3>The Core Calculation</h3><p>Flat-rate credit = Platform income × 8.5%</p><p>GST on expenses if registered = Expenses × (15 ÷ 115)</p><p>Registration benefit = GST on expenses minus flat-rate credit</p><p>If positive: registration saves you money</p></div><h2>Flat-Rate Credit vs Registration</h2><table><tr><th>Your Situation</th><th>Better Option</th></tr><tr><td>Low expenses (under 56% of income)</td><td>Flat-rate credit fine</td></tr><tr><td>High expenses (over 56% of income)</td><td>Register for GST</td></tr><tr><td>Large purchase coming</td><td>Register before purchase</td></tr><tr><td>Approaching $60k</td><td>Must register — plan timing</td></tr></table><p>Source: <a href="https://www.ird.govt.nz/gst/gst-for-marketplace-sellers">IRD — GST for marketplace sellers</a></p>` },
    { num: "02", slug: "gst-02", name: "Big Purchase GST Recovery Tool", desc: "How to time a large purchase to maximise your GST recovery.", tier: 1, content: `<h2>Big Purchase — Register First</h2><p>If you are about to buy a vehicle, equipment or make a significant business investment, registering for GST before the purchase allows you to claim the full 15% GST back immediately.</p><div class="action-box"><h3>Example — $30,000 Vehicle</h3><p>GST content of $30,000 purchase: $3,913</p><p>Flat-rate credit on $30k income: approximately $2,550</p><p>Registering before purchase: $3,913 more recovered</p></div><table><tr><th>Asset</th><th>GST Recovery</th></tr><tr><td>$15,000 vehicle</td><td>$1,957</td></tr><tr><td>$30,000 vehicle</td><td>$3,913</td></tr><tr><td>$10,000 equipment</td><td>$1,304</td></tr></table><div class="warning-box"><strong>Timing matters:</strong> Register before settlement. You cannot claim GST on a purchase made before your registration date.</div>` },
    { num: "03", slug: "gst-03", name: "Platform GST Switch Guide", desc: "How to notify Airbnb, Uber and Bookabach of your GST registration.", tier: 1, content: `<h2>Notifying Your Platform</h2><p>Once registered, notify your platform of your GST number. This affects how the platform reports your income and may change how App Tax is applied to your account.</p><div class="action-box"><h3>Platform Notification Steps</h3><p>Airbnb: Account settings → Taxes → Add GST number</p><p>Uber: Partner app → Documents → Tax information</p><p>Bookabach: Contact support with your GST number</p></div><div class="info-box"><strong>After registering:</strong> The platform will typically remove the flat-rate credit from your payments and show your income differently on statements. Your accountant needs to know this change has occurred.</div>` },
    { num: "04", slug: "gst-04", name: "Filing Frequency Optimiser", desc: "Two-monthly vs six-monthly — which GST filing schedule suits your cashflow.", tier: 1, content: `<h2>GST Filing Frequency</h2><p>IRD allows most small businesses to file GST returns every two months or six months. The right choice depends on your cashflow and expense pattern.</p><table><tr><th>Frequency</th><th>Who Suits</th><th>Refund Timing</th></tr><tr><td>Two-monthly</td><td>Most side-hustlers</td><td>Regular refunds if expenses high</td></tr><tr><td>Six-monthly</td><td>Low volume, stable income</td><td>Larger but less frequent refunds</td></tr><tr><td>Monthly</td><td>Turnover over $24M — not applicable</td><td>N/A for side-hustlers</td></tr></table><div class="info-box"><strong>Cashflow tip:</strong> If you have consistently high expenses (e.g. vehicle costs every month), two-monthly returns get your GST refunds faster.</div>` },
    { num: "05", slug: "gst-05", name: "Your Accountant Brief", desc: "Print and take to your next meeting — GST questions your adviser must answer.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Print or forward to your accountant before your next meeting.</div><h2>Client GST Position</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Current status</td><td>Not registered — flat-rate credit applies</td></tr><tr><td>Flat-rate credit rate</td><td>8.5% of platform income</td></tr><tr><td>Registration threshold</td><td>$60,000 per year</td></tr></table><div class="action-box"><h3>Question 1</h3><p>"Based on my income and expenses, am I better off registered or on the flat-rate credit?"</p></div><h3>Question 2</h3><p>"What expenses can I claim GST on — and how do I apportion for private use?"</p><h3>Question 3</h3><p>"When exactly do I hit the $60,000 threshold and what happens if I miss it?"</p><h3>Question 4</h3><p>"If I register and then stop, what GST do I owe on deregistration?"</p><h3>Question 5</h3><p>"How do I notify my platform of my GST number?"</p>` },
    { num: "06", slug: "gst-06", name: "Change-of-Use Calculator", desc: "Avoid IRD clawbacks when your asset use changes between taxable and private.", tier: 2, content: `<h2>What Is Change of Use?</h2><p>When a GST-registered person uses a business asset for private purposes (or vice versa), IRD requires a GST adjustment. This most commonly affects Airbnb hosts who start using their property privately or stop the rental activity.</p><div class="warning-box"><strong>The clawback risk:</strong> If you claim GST on property costs and then stop Airbnb, IRD may require you to repay some of the GST you claimed. The amount depends on how much the use has changed.</div><h2>Change of Use Rules</h2><table><tr><th>Scenario</th><th>GST Impact</th></tr><tr><td>Start private use of business asset</td><td>Output tax adjustment required</td></tr><tr><td>Start business use of private asset</td><td>Input tax credit available</td></tr><tr><td>Deregister from GST</td><td>Deemed disposal at market value</td></tr></table>` },
    { num: "07", slug: "gst-07", name: "Apportionment Engine", desc: "Calculate your exact private vs business GST split for mixed-use assets.", tier: 2, content: `<h2>Mixed-Use Apportionment</h2><p>If an asset is used for both taxable (GST) and private purposes, you can only claim the business-use proportion of the GST. IRD requires you to calculate this accurately.</p><div class="action-box"><h3>Common Apportionment Methods</h3><p>Vehicle: business kilometres divided by total kilometres</p><p>Home office: business floor area divided by total floor area</p><p>Property: Airbnb nights divided by total nights available</p></div><table><tr><th>Asset</th><th>Method</th><th>Record Needed</th></tr><tr><td>Vehicle</td><td>Kilometre logbook</td><td>IRD logbook or 90-day sample</td></tr><tr><td>Home office</td><td>Floor area</td><td>Floor plan or measurements</td></tr><tr><td>Rental property</td><td>Days available</td><td>Booking calendar</td></tr></table>` },
    { num: "08", slug: "gst-08", name: "Property GST Exposure Tool", desc: "Understand your GST position if you sell a property used for Airbnb.", tier: 2, content: `<h2>GST on Property Sales</h2><p>If you have been running Airbnb from a property and are GST registered, selling the property can create a GST liability — particularly if the buyer is not GST registered.</p><div class="warning-box"><strong>The hidden risk:</strong> Selling an Airbnb property to a private buyer without applying the zero-rating rules can result in you owing 15% GST on the full sale price. For a $800,000 property that is $104,348.</div><h2>Key Rules</h2><table><tr><th>Scenario</th><th>GST Treatment</th></tr><tr><td>Sale to GST-registered buyer as going concern</td><td>Zero-rated — no GST</td></tr><tr><td>Sale to private buyer</td><td>GST at 15% may apply</td></tr><tr><td>Property stops Airbnb before sale</td><td>Change of use adjustment first</td></tr></table><div class="info-box"><strong>Always get specific advice</strong> before selling a GST-registered property. The interaction between GST, income tax, and bright-line rules creates significant complexity.</div>` },
  ],
  calendarTitle: "GST — Filing and Registration Deadlines",
  tier1Calendar: [
    { uid: "gst-q1", summary: "GST — Period 1 Return Due", description: "First GST return period for the year — check your filing date with IRD.", date: "20260430" },
    { uid: "gst-q2", summary: "GST — Period 2 Return Due", description: "Second GST return period.", date: "20260630" },
    { uid: "gst-q3", summary: "GST — Period 3 Return Due", description: "Third GST return period.", date: "20260831" },
    { uid: "gst-year", summary: "NZ Tax Year End", description: "31 March year end — ensure all GST returns are filed and annual adjustments complete.", date: "20270331" },
  ],
  tier2Calendar: [
    { uid: "gst-review", summary: "GST — Registration benefit review", description: "Calculate whether registration still makes sense based on current income and expenses.", date: "relative:+14days" },
    { uid: "gst-notify", summary: "GST — Notify platforms of registration", description: "Update GST number with all platforms after registration.", date: "relative:+7days" },
    { uid: "gst-q1", summary: "GST — Period 1 Return Due", description: "First GST return due.", date: "20260430" },
    { uid: "gst-annual", summary: "GST — Annual adjustment due", description: "Annual GST adjustment for mixed-use assets and apportionment.", date: "20270331" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_GST_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_GST_147" },
  monitorUrls: ["https://www.ird.govt.nz/gst/gst-for-marketplace-sellers"],
  sidebarNumbers: [{ label: "GST rate", value: "15%" }, { label: "Flat-rate credit", value: "8.5%" }, { label: "Registration threshold", value: "$60,000" }, { label: "Gap per $1k income", value: "$65" }],
  sidebarMathsTitle: "What App Tax means for you",
  sidebarMathsIncludes: ["15% GST charged by platform always", "8.5% flat-rate credit if not registered", "Full 15% recovery on costs if registered"],
  sidebarMathsExcludes: ["NOT safe just because under $60k", "NOT equivalent — 8.5% is NOT 15%"],
  sidebarMathsNote: "Source: IRD — GST marketplace rules · GST Act 1985",
  howToSteps: [
    { position: 1, name: "Enter your platform income", text: "Choose your average monthly income from Airbnb, Uber, Bookabach or other platforms." },
    { position: 2, name: "Enter your monthly expenses", text: "Include vehicle costs, cleaning, supplies, and other business costs." },
    { position: 3, name: "Get your GST verdict", text: "See immediately whether registration saves you money and by how much." },
    { position: 4, name: "Get your registration plan", text: "Receive a personalised GST registration guide and expense recovery strategy." },
  ],
  successPromptFields: [
    { key: "gst_income", label: "Monthly platform income", defaultVal: "1200" },
    { key: "gst_expenses", label: "Monthly expenses", defaultVal: "600" },
    { key: "gst_platform", label: "Platform", defaultVal: "airbnb" },
    { key: "gst_status", label: "GST status", defaultVal: "approaching" },
  ],
  tier1AssessmentFields: ["status", "flatRateCredit", "registrationBenefit", "breakEvenPoint", "firstAction", "bigPurchaseOpportunity", "accountantQuestions"],
  tier2AssessmentFields: ["status", "flatRateCredit", "registrationBenefit", "breakEvenPoint", "changeOfUseRisk", "apportionmentNeeded", "actions", "weekPlan", "accountantQuestions"],
  persona: {
    name: "Aroha",
    age: 43,
    occupation: "Speech language therapist (part-time), Airbnb host, landlord — Auckland",
    location: "Pt Chevalier, Auckland",
    family: "Husband Mike (civil engineer). Two teenagers — Tama (16) and Hana (14).",
    financialSnapshot: "3 properties: family home, Avondale rental (in family trust), Glen Eden Airbnb. Household income ~$180k.",
    painPoint: "Aroha does the family finances and researches before every accountant meeting to ask the right questions.",
    discovery: "Aroha found three different bright-line answers on three different websites. She needed one definitive source.",
    voice: "Thorough. Trusts research. Appreciates when complexity is acknowledged. Wry Kiwi humour.",
  },
  story: {
    hook: "Aroha had been running the Glen Eden property on Airbnb for two years. She had never thought about GST.",
    setup: [
    "The property earned around $3,200 per month when occupied. Aroha managed it herself. She was below the $60,000 GST threshold and had assumed GST simply did not apply to her.",
    "What she had not understood was the App Tax. From 2023, Airbnb had been required to collect and remit 15% GST on her earnings regardless of her registration status. The platform took the GST. She received a flat-rate credit of only 8.5%.",
    "She had also been running significant costs through the property: a new heat pump ($4,200), replacement carpet ($2,800), regular cleaning. None of the GST on those expenses was recoverable as an unregistered person.",
    ],
    revelation: "The heat pump alone — $4,200 GST-inclusive — contained $547 of recoverable GST she had walked away from. The ongoing registration calculation did not support registering. But large purchases changed the maths.",
    resolution: "Aroha did not register for GST. The ongoing numbers did not support it. But she now asks David before any major purchase whether voluntary registration for that year would be beneficial.",
  },
};
