import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "bright-line-auditor", name: "Bright-Line Escape Auditor", site: "taxchecknow", country: "nz", market: "New Zealand", language: "en-NZ", currency: "NZD",
  slug: "nz/check/bright-line-auditor", url: "https://taxchecknow.com/nz/check/bright-line-auditor", apiRoute: "/api/rules/bright-line-auditor",
  authority: "IRD", authorityUrl: "https://www.ird.govt.nz", legalAnchor: "Income Tax Act 2007 — Bright-Line Test", legislation: "Income Tax Act 2007 s CB 6A — Bright-Line Property Rule (amended 2024)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Main Home Proof Kit", tagline: "Do you owe tax on your property sale — yes or no — and can you prove it?", value: "A personalised bright-line audit built around your title date, sale date, and main home usage — not a generic property guide.", cta: "Get My Proof Kit — $67 →", productKey: "nz_67_bright_line_auditor", envVar: "STRIPE_NZ_BL_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Rollover Relief Audit", tagline: "Protect your exemption during transfers and restructuring", value: "A personalised bright-line audit plus transfer analysis, trust and associated person testing, and rollover eligibility confirmation.", cta: "Get My Rollover Audit — $147 →", productKey: "nz_147_bright_line_auditor", envVar: "STRIPE_NZ_BL_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-03-31T23:59:59.000+13:00", display: "31 March 2027", short: "31 Mar 2027", description: "NZ tax year end — property sales in the 2026/27 year must be assessed before this date", urgencyLabel: "TAX YEAR END", countdownLabel: "Countdown to 31 March 2027 NZ tax year end" },
  h1: "NZ Bright-Line 2026: Is Your Property Sale Tax-Free?", metaTitle: "NZ Bright-Line Test 2026: Is Your Property Sale Tax-Free? | TaxCheckNow", metaDescription: "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.", canonical: "https://taxchecknow.com/nz/check/bright-line-auditor",
  answerHeadline: "The answer — IRD confirmed April 2026",
  answerBody: [
    "From 1 July 2024, New Zealand's bright-line test is 2 years for ALL residential property sales. If you sell more than 730 days after your title registration date, your profit is generally tax-free. The old 5-year and 10-year rules have been repealed.",
    "The start date is your title registration date — not your purchase agreement date, and not your settlement date. Most people get this wrong. Using the wrong start date can mean thinking you are taxable when you are not, or thinking you are safe when the clock has not yet expired.",
    "The main home exemption still applies but requires passing both the time test (over 50% occupancy) and the area test (over 50% of land used as main home). Simply living in the property is not enough — you need to be able to prove it.",
  ],
  answerSource: "Source: IRD — Bright-line property rule · Income Tax Act 2007 s CB 6A",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "The 10-year bright-line still applies — wrong. From 1 July 2024, the bright-line period is 2 years for all residential property sales regardless of purchase date or property type. The old rules have been repealed.",
    "The purchase agreement date starts the bright-line clock — wrong. The start date is your title registration date. Using the wrong date can result in incorrect tax assessment.",
    "Living in the property means you are automatically exempt — wrong. You must pass both the time test (over 50% occupancy during ownership) and the area test (over 50% of land used as main home).",
  ],
  chainVisual: { label: "The bright-line clock — what starts and stops it", broken: "Purchase agreement date → sale date  ❌  WRONG — most people use this", fixed: "Title registration date → binding sale agreement  ✔  CORRECT IRD rule" },
  brackets: [
    { label: "Sold more than 2 years after title registration", value: 1, status: "clear" },
    { label: "Sold between 1-2 years after title registration", value: 2, status: "trap" },
    { label: "Sold within 12 months — possible main home exemption", value: 3, status: "approaching" },
    { label: "Property transferred to trust or family member", value: 4, status: "risk" },
    { label: "Not sure of my title registration date", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "holdingDays", label: "How long did you hold the property (title to sale agreement)?", subLabel: "Count from title registration date to binding sale agreement date", options: [{ label: "Under 365 days", value: 180 }, { label: "365-730 days", value: 548 }, { label: "Over 730 days", value: 900 }], default: 548 },
    { type: "buttonGroup", stateKey: "propertyUse", label: "How was the property used?", subLabel: "Determines main home exemption eligibility", options: [{ label: "Main home entire time", value: "main_home" }, { label: "Mix of main home and rental", value: "mixed" }, { label: "Pure rental investment", value: "rental" }, { label: "Holiday home or bach", value: "holiday" }], default: "main_home" },
    { type: "twoButton", stateKey: "wasTransferred", label: "Was the property transferred from a trust or family member?", subLabel: "Transfers can reset the bright-line clock", options: [{ label: "No — direct purchase", value: false }, { label: "Yes — transferred", value: true }], default: false },
  ],
  tierAlgorithm: { description: "holdingDays under 730 OR wasTransferred → tier2. propertyUse mixed or rental → tier2. Otherwise tier1.", tier2Conditions: ["(holdingDays as number) < 730", 'propertyUse === "mixed"', 'propertyUse === "rental"'], tier2Flags: ["wasTransferred"] },
  calculatorRuleBox: { label: "The rule — IRD confirmed", body: "Bright-line period: 2 years (730 days) for all residential property sold from 1 July 2024. Start date: title registration. End date: binding sale agreement. Main home exemption: must pass time test (over 50% occupancy) and area test (over 50% of land)." },
  calculatorClarification: { label: "Key clarification", body: "Most people are calculating from the wrong date. If you are using your purchase agreement date instead of title registration date, your bright-line calculation may be wrong. Even a few days difference can change your tax position." },
  countdownLabel: "Countdown to 31 March 2027 NZ tax year end",
  countdownStats: [
    { label: "Old rule AI cites", value: "10 years", sub: "repealed — no longer applies" },
    { label: "Actual 2026 rule", value: "2 years", sub: "for all properties from 1 July 2024", red: true },
    { label: "Start date", value: "Title reg", sub: "not purchase agreement", red: true },
    { label: "Exemption test", value: "2 tests", sub: "time AND area — both required" },
  ],
  geoBlockTitle: "AI extraction block — NZ bright-line test 2026",
  geoBlockH2: "NZ Bright-Line Property Rule — confirmed 2026",
  geoBodyParagraph: "From 1 July 2024, New Zealand's bright-line test is 2 years for all residential property sales under the Income Tax Act 2007 s CB 6A. The previous 5-year and 10-year rules have been repealed. The bright-line period starts on the date of title registration and ends on the date of the binding sale and purchase agreement. Settlement date is not used. The main home exemption applies where the property was used as the seller's main home for more than 50% of the ownership period and more than 50% of the land area. Both tests must be satisfied. Transfers between associated persons and trust transfers can reset or affect the bright-line period. Rollover relief is available in specific circumstances including relationship property transfers and death.",
  geoFormula: "Bright-Line Period = Binding Sale Date minus Title Registration Date. If period is over 730 days: generally tax-free. If 730 days or less: taxable unless an exclusion applies (main home, inherited property, relationship property transfer).",
  geoFacts: [
    { label: "Bright-line period (2026)", value: "2 years (730 days)" },
    { label: "Start date", value: "Title registration date" },
    { label: "End date", value: "Binding sale agreement date" },
    { label: "Main home time test", value: "Over 50% of ownership period" },
    { label: "Main home area test", value: "Over 50% of land" },
    { label: "Applies from", value: "Sales from 1 July 2024" },
  ],
  workedExamplesH2: "Four property sale scenarios",
  workedExamplesColumns: ["Scenario", "Title Date", "Sale Agreement", "Days Held", "Status"],
  workedExamples: [
    { name: "Clear exit",     setup: "Main home, used as primary residence throughout",     income: "900 days", status: "TAX-FREE" },
    { name: "Just inside",   setup: "Investment property, sold at 680 days",                income: "680 days", status: "TAXABLE" },
    { name: "Mixed use",     setup: "50% main home, 50% rental — 18 months held",          income: "548 days", status: "PARTIAL TAX" },
    { name: "Trust transfer", setup: "Transferred from trust — clock may have reset",       income: "Verify",   status: "AT RISK" },
  ],
  comparisonH2: "Bright-line rules — what changed",
  comparisonColumns: ["Period", "Rule", "Applies To"],
  comparisonRows: [
    { position: "Before March 2021",   metric1: "5 years",  metric2: "Most residential property", bestMove: "Repealed" },
    { position: "March 2021-July 2024", metric1: "10 years", metric2: "Investment property",       bestMove: "Repealed" },
    { position: "From 1 July 2024",    metric1: "2 years",  metric2: "All residential property",  bestMove: "Current law" },
  ],
  toolsH2: "Exclusions that can remove bright-line tax",
  toolsColumns: ["Exclusion", "Requirement", "Notes"],
  toolsRows: [
    { tool: "Main home exclusion",          effect: "Fully exempt if tests met",    note: "Time test over 50% AND area test over 50%" },
    { tool: "Inherited property",           effect: "Generally exempt",             note: "Received through deceased estate" },
    { tool: "Relationship property",        effect: "Rollover relief available",    note: "Transfer on relationship breakdown" },
    { tool: "Executor/administrator",       effect: "Exempt",                       note: "Sale as part of estate administration" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: The 10-year bright-line test still applies in NZ", correct: "Reality: The 10-year rule was repealed. From 1 July 2024, the bright-line period is 2 years for all residential property sales. AI tools consistently cite the old rules." },
    { wrong: "ChatGPT says: The purchase agreement date starts the bright-line period", correct: "Reality: The bright-line clock starts on the title registration date — not the purchase agreement date and not the settlement date. Using the wrong date is the most common bright-line calculation error." },
    { wrong: "ChatGPT says: Living in the property means you are automatically exempt", correct: "Reality: The main home exemption requires passing both the time test (over 50% occupancy) and the area test (over 50% of land used as main home). Simply living there is not sufficient." },
    { wrong: "ChatGPT says: Transfers to family or trusts are always safe", correct: "Reality: Transfers between associated persons can reset the bright-line clock or trigger tax. Rollover relief is available in specific circumstances but must be confirmed." },
    { wrong: "ChatGPT says: The bright-line test does not apply to your main home", correct: "Reality: The bright-line test can apply to your main home if you fail either the time test or area test. Partial rental use or short ownership periods can expose you even in your primary residence." },
  ],
  faqs: [
    { question: "What is the NZ bright-line test in 2026?", answer: "The bright-line test taxes profits from residential property sales where the property is sold within 2 years of the title registration date. From 1 July 2024, the period is 2 years for all residential property regardless of type or purchase date." },
    { question: "When does the bright-line period start and end?", answer: "The period starts on the date your title is registered (shown on your Certificate of Title). It ends on the date you enter into a binding sale and purchase agreement. Settlement date and purchase agreement date are not used." },
    { question: "Does the main home exemption still apply?", answer: "Yes. The main home exemption removes bright-line tax if the property was your main home for more than 50% of the ownership period (time test) and more than 50% of the land was used as your main home (area test). Both tests must be satisfied." },
    { question: "What happens if I rented out part of my main home?", answer: "Renting out part of your home (flatmate, Airbnb) can affect the area test. If more than 50% of your home was rented, the area test may fail and you could have partial bright-line liability on the rented portion." },
    { question: "Does a trust transfer reset the bright-line clock?", answer: "It can. Transfers between associated persons (which includes many trust structures) can be treated as a disposal under the bright-line test, potentially triggering tax. Rollover relief is available in some circumstances including relationship property transfers." },
    { question: "What is rollover relief?", answer: "Rollover relief allows the bright-line period to continue running after certain transfers without triggering tax. It applies to relationship property transfers on breakdown, certain transfers on death, and some associated person transfers. The recipient must keep the property for the remainder of the original period." },
    { question: "What tax rate applies to bright-line profits?", answer: "Bright-line income is added to your total income for the year and taxed at your marginal income tax rate. Rates range from 10.5% (income under $15,600) to 39% (income over $180,000)." },
    { question: "Does the bright-line test apply to commercial property?", answer: "No. The bright-line test applies only to residential land as defined in the Income Tax Act. Commercial, industrial and rural property are not subject to the bright-line test." },
    { question: "What if I inherited the property?", answer: "Property received through a deceased estate is generally excluded from the bright-line test when sold. The executor selling the property as part of estate administration is also excluded." },
    { question: "How does the bright-line test interact with the main home rollover?", answer: "The 2-year reuse restriction applies if you have claimed the main home exclusion twice in the preceding 2 years. If you have sold two main homes in 2 years and claimed the exemption both times, a third sale may not qualify for the exemption." },
    { question: "Do I need to tell IRD about a bright-line sale?", answer: "Yes. Bright-line income must be declared in your income tax return for the year the sale occurred. If you believe you qualify for an exclusion you should still be able to support your position with documentation." },
    { question: "What evidence do I need for the main home exemption?", answer: "IRD expects evidence of primary residence including utility bills, bank statements showing the address, electoral roll registration, and records of time spent at the property. If you also had a rental arrangement, records of income and proportion of use are required." },
  ],
  accountantQuestionsH2: "Ask these before settling your property sale",
  accountantQuestions: [
    { q: "What is my exact title registration date — and does that put me inside or outside the 2-year bright-line period?", why: "Using the wrong date is the most common error. Even a few days can change your tax position from taxable to exempt." },
    { q: "Do I pass both the time test and area test for the main home exclusion?", why: "Both tests must be satisfied. A flatmate, home office, or Airbnb arrangement can affect the area test without you realising." },
    { q: "If I transferred this property from a trust or family member, what was the effective start date for my bright-line period?", why: "Transfers can reset the clock. Your solicitor or accountant needs to trace the ownership chain." },
    { q: "Have I used the main home exclusion twice in the last 2 years — does the reuse restriction apply?", why: "The 2-year reuse restriction can prevent you from claiming the main home exemption on a third sale even if you genuinely lived there." },
    { q: "What documentation do I need to keep to defend my bright-line position if IRD queries the sale?", why: "IRD can audit bright-line positions years after the sale. Having the right evidence now prevents problems later." },
  ],
  crosslink: { title: "Planning to buy or sell in Perth WA?", body: "Property tax rules differ significantly between NZ and Australia. If you are considering AU property investment, check your borrowing capacity and AU tax position.", url: "https://taxchecknow.com/au/check", label: "Check AU property tax rules →" },
  lawBarSummary: "NZ bright-line test 2026: 2 years for all residential property sales from 1 July 2024. Start date: title registration. End date: binding sale agreement. Main home exclusion: time test over 50% AND area test over 50%. Under Income Tax Act 2007 s CB 6A.",
  lawBarBadges: ["IRD", "Income Tax Act 2007", "s CB 6A", "Machine-readable JSON"],
  sources: [
    { title: "IRD — Bright-line property rule", url: "https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test" },
    { title: "IRD — Main home exclusion", url: "https://www.ird.govt.nz/property/buying-and-selling/bright-line-test/main-home" },
    { title: "Machine-readable JSON rules", url: "/api/rules/bright-line-auditor" },
  ],
  files: [
    { num: "01", slug: "bl-01", name: "Your Bright-Line Verdict", desc: "Your exact bright-line position — days held, applicable rule, and tax exposure.", tier: 1, content: `<h2>Your Bright-Line Position</h2><div class="action-box"><h3>The 2026 Rule</h3><p>Bright-line period: 2 years (730 days)</p><p>Start: title registration date</p><p>End: binding sale agreement date</p><p>Result: over 730 days = generally tax-free</p></div><h2>Date Logic Table</h2><table><tr><th>Event</th><th>Counts?</th></tr><tr><td>Title registration date</td><td>YES — start date</td></tr><tr><td>Purchase agreement date</td><td>NO — not used</td></tr><tr><td>Settlement date</td><td>NO — not used</td></tr><tr><td>Binding sale agreement</td><td>YES — end date</td></tr></table><p>Source: <a href="https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test">IRD — Bright-line property rule</a></p>` },
    { num: "02", slug: "bl-02", name: "Main Home Time Test Calculator", desc: "Verify over 50% occupancy during ownership — the IRD time test.", tier: 1, content: `<h2>The Time Test</h2><p>To qualify for the main home exclusion, you must have used the property as your main home for more than 50% of the bright-line period.</p><div class="action-box"><h3>How to Calculate</h3><p>Total days owned (title to sale): X days</p><p>Days used as main home: Y days</p><p>Percentage: Y divided by X × 100</p><p>Must exceed 50% to pass</p></div><div class="warning-box"><strong>Rental periods:</strong> Any period the property was rented counts against the time test. Even short Airbnb periods can affect your percentage.</div><table><tr><th>Usage</th><th>Counts as Main Home?</th></tr><tr><td>Primary residence</td><td>Yes</td></tr><tr><td>Rented to tenants</td><td>No</td></tr><tr><td>Airbnb / short-term rental</td><td>No</td></tr><tr><td>Vacant but not rented</td><td>Depends — take advice</td></tr></table>` },
    { num: "03", slug: "bl-03", name: "Main Home Area Test Auditor", desc: "Verify over 50% of land used as main home — the IRD area test.", tier: 1, content: `<h2>The Area Test</h2><p>The property must have been used as your main home for over 50% of the land area throughout the ownership period.</p><div class="action-box"><h3>Common Area Test Issues</h3><p>Flatmate with separate entrance: may reduce main home area</p><p>Airbnb of a full room: reduces main home area percentage</p><p>Home office used for business: generally still counts as main home</p><p>Subdivision of section: affects area calculation</p></div><table><tr><th>Situation</th><th>Area Test Impact</th></tr><tr><td>Pure main home — no rental</td><td>100% — passes easily</td></tr><tr><td>One flatmate in one room</td><td>Depends on room proportion</td></tr><tr><td>Airbnb of guest room</td><td>Minor impact if under 50%</td></tr><tr><td>Subdivided section sold off</td><td>Significant — get advice</td></tr></table>` },
    { num: "04", slug: "bl-04", name: "Audit-Ready Documentation Checklist", desc: "What IRD expects if they query your bright-line exemption claim.", tier: 1, content: `<h2>IRD Evidence Checklist</h2><p>If IRD queries your bright-line position, you need documentation to support your claim. Prepare these before settlement.</p><ul class="checklist"><li>Certificate of Title showing registration date</li><li>Binding sale and purchase agreement showing date signed</li><li>Utility bills (power, internet, water) showing address throughout ownership</li><li>Bank statements showing address as primary account address</li><li>Electoral roll registration at the property address</li><li>Insurance policy showing property as main home</li><li>Records of any rental periods (tenancy agreements, Airbnb data)</li><li>Valuation or floorplan showing area proportions if mixed use</li></ul><div class="info-box"><strong>Keep these for 7 years</strong> after the sale. IRD can query bright-line positions years after the transaction.</div>` },
    { num: "05", slug: "bl-05", name: "Your Accountant Brief", desc: "Print and take to your next meeting — bright-line questions your adviser must answer.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Print or forward to your accountant or solicitor before settlement.</div><h2>Client Bright-Line Position</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Rule (2026)</td><td>2 years from title registration</td></tr><tr><td>Start date to confirm</td><td>Title registration date</td></tr><tr><td>Tax year end</td><td>31 March 2027</td></tr></table><div class="action-box"><h3>Question 1</h3><p>"What is my exact title registration date — and does that put me inside or outside 730 days?"</p></div><h3>Question 2</h3><p>"Do I pass both the time test and area test for main home exclusion?"</p><h3>Question 3</h3><p>"Was this property ever transferred from a trust or associated person — and does that affect my start date?"</p><h3>Question 4</h3><p>"Have I claimed the main home exclusion twice in the last 2 years?"</p><h3>Question 5</h3><p>"What documentation should I keep to defend this position?"</p>` },
    { num: "06", slug: "bl-06", name: "Associated Person Test", desc: "Family and trust transfer analysis — does your structure affect the bright-line period?", tier: 2, content: `<h2>Associated Persons and Bright-Line</h2><p>Transfers between associated persons can trigger the bright-line test or reset the clock. Associated persons include family members, trusts where you are a settlor or beneficiary, and companies you control.</p><div class="warning-box"><strong>Key risk:</strong> If you received the property from an associated person, your bright-line period may have started at the ORIGINAL purchase date, not the date you received it.</div><table><tr><th>Transfer Type</th><th>Bright-Line Impact</th></tr><tr><td>Spouse / partner to spouse</td><td>Rollover relief usually available</td></tr><tr><td>Trust to individual</td><td>May reset or trigger — get advice</td></tr><tr><td>Individual to trust</td><td>Can trigger bright-line on transfer</td></tr><tr><td>Company to shareholder</td><td>Associated person rules apply</td></tr></table>` },
    { num: "07", slug: "bl-07", name: "Rollover Relief Eligibility Check", desc: "Confirm your transfer qualifies for rollover — so the bright-line clock does not reset.", tier: 2, content: `<h2>What Is Rollover Relief?</h2><p>Rollover relief allows the bright-line period to continue after certain transfers without triggering a taxable event. The recipient steps into the original owner's position and must continue the clock from the original start date.</p><div class="action-box"><h3>Rollover Relief Qualifies For:</h3><p>Relationship property transfers on relationship breakdown</p><p>Transfers on death (executor to beneficiary)</p><p>Some look-through company transfers</p></div><h2>The 2-Year Reuse Restriction</h2><p>You cannot claim the main home exclusion on more than 2 properties in any 2-year period. If you have sold 2 main homes and claimed the exclusion on both in the past 2 years, a third sale may not qualify.</p>` },
    { num: "08", slug: "bl-08", name: "Transfer Strategy Roadmap", desc: "Safe restructuring options — how to move property without triggering bright-line.", tier: 2, content: `<h2>Moving Property Without Triggering Tax</h2><p>If you need to transfer a property and want to avoid bright-line tax, careful structuring is required before the transfer.</p><h2>Options to Consider</h2><table><tr><th>Option</th><th>Effect</th><th>Complexity</th></tr><tr><td>Wait until outside bright-line period</td><td>Clean exit — no tax</td><td>Low</td></tr><tr><td>Relationship property rollover</td><td>No tax on transfer</td><td>Medium</td></tr><tr><td>Death and estate transfer</td><td>Exempt</td><td>N/A</td></tr><tr><td>Deed of family arrangement</td><td>Complex — get advice</td><td>High</td></tr></table><div class="warning-box"><strong>Always get legal and tax advice before any property transfer.</strong> Bright-line consequences can be significant and are difficult to reverse once a transfer has occurred.</div>` },
  ],
  calendarTitle: "Bright-Line — Key Dates",
  tier1Calendar: [
    { uid: "bl-review", summary: "Bright-Line — Review position with accountant", description: "Confirm title date, sale date, and main home test before settlement.", date: "relative:+7days" },
    { uid: "bl-yearend", summary: "NZ Tax Year End — 31 March 2027", description: "Bright-line income from 2026/27 year sales must be declared in your return.", date: "20270331" },
  ],
  tier2Calendar: [
    { uid: "bl-docs",    summary: "Bright-Line — Gather title and sale documents",    description: "Collect Certificate of Title, sale agreement, and occupancy evidence.", date: "relative:+7days" },
    { uid: "bl-transfer", summary: "Bright-Line — Review transfer history",           description: "Confirm whether any trust or family transfer affects your start date.", date: "relative:+14days" },
    { uid: "bl-yearend", summary: "NZ Tax Year End — 31 March 2027",                  description: "Declare bright-line income in 2026/27 return.", date: "20270331" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_BL_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_NZ_BL_147" },
  monitorUrls: ["https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test"],
  sidebarNumbers: [{ label: "Bright-line period", value: "2 years" }, { label: "Start date", value: "Title registration" }, { label: "Main home tests", value: "2 required" }, { label: "Tax year end", value: "31 March" }],
  sidebarMathsTitle: "What starts the bright-line clock",
  sidebarMathsIncludes: ["Title registration date (start)", "Binding sale agreement (end)"],
  sidebarMathsExcludes: ["NOT purchase agreement date", "NOT settlement date", "NOT possession date"],
  sidebarMathsNote: "Source: IRD — Bright-line property rule · Income Tax Act 2007",
  howToSteps: [
    { position: 1, name: "Select your holding period", text: "Choose how many days elapsed between your title registration date and binding sale agreement date." },
    { position: 2, name: "Identify property use", text: "Specify whether the property was your main home, a rental, mixed use, or holiday home." },
    { position: 3, name: "Get your bright-line verdict", text: "See immediately whether your sale is tax-free, taxable, or requires further analysis." },
    { position: 4, name: "Get your proof pack", text: "Receive a personalised documentation checklist and main home test analysis for your specific situation." },
  ],
  successPromptFields: [
    { key: "bl_days", label: "Days held", defaultVal: "548" },
    { key: "bl_use", label: "Property use", defaultVal: "mixed" },
    { key: "bl_transferred", label: "Was transferred", defaultVal: "false" },
    { key: "bl_status", label: "Bright-line status", defaultVal: "at_risk" },
  ],
  tier1AssessmentFields: ["status", "daysHeld", "brightLineVerdict", "mainHomeRisk", "taxExposure", "firstAction", "documentationNeeded", "accountantQuestions"],
  tier2AssessmentFields: ["status", "daysHeld", "brightLineVerdict", "mainHomeRisk", "transferRisk", "rolloverEligibility", "actions", "weekPlan", "accountantQuestions"],
};
