import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "trust-tax-splitter", name: "Trust Tax Splitter", site: "taxchecknow", country: "nz", market: "New Zealand", language: "en-NZ", currency: "NZD",
  slug: "nz/check/trust-tax-splitter", url: "https://taxchecknow.com/nz/check/trust-tax-splitter", apiRoute: "/api/rules/trust-tax-splitter",
  authority: "IRD", authorityUrl: "https://www.ird.govt.nz", legalAnchor: "Income Tax Act 2007 — Trustee Income", legislation: "Income Tax Act 2007 — Trust taxation rules including 39% trustee rate (effective 2021)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Beneficiary Distribution Pack", tagline: "Are you paying 39% when you could legally pay 10.5%?", value: "A personalised trust tax audit built around your trust income, your beneficiaries, and your distribution strategy — not a generic trust guide.", cta: "Get My Distribution Pack — $67 →", productKey: "nz_67_trust_tax_splitter", envVar: "STRIPE_NZ_TT_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Trust vs Company Pivot Audit", tagline: "Find the most tax-efficient structure for your trust income", value: "A personalised trust audit plus company comparison, imputation credit mapping, and multi-entity optimisation strategy.", cta: "Get My Pivot Audit — $147 →", productKey: "nz_147_trust_tax_splitter", envVar: "STRIPE_NZ_TT_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-03-31T23:59:59.000+13:00", display: "31 March 2027", short: "31 Mar 2027", description: "NZ tax year end — trust distributions must be made before year end to apply personal tax rates", urgencyLabel: "DISTRIBUTION DEADLINE", countdownLabel: "Countdown to 31 March 2027 — trust distributions must be made before year end" },
  h1: "NZ Trust Tax 2026: Are You Paying 39% When You Don't Have To?", metaTitle: "NZ Trust Tax 2026: Are You Overpaying 39% Trustee Rate? | TaxCheckNow", metaDescription: "Default NZ trustee tax rate is 39%. But trust income under $10,000 stays at 33%. Distributions to adult beneficiaries can be as low as 10.5%. Many Kiwi trusts are overpaying tax unnecessarily. Check your trust position now.", canonical: "https://taxchecknow.com/nz/check/trust-tax-splitter",
  answerHeadline: "The answer — IRD confirmed April 2026",
  answerBody: [
    "The default trustee tax rate in New Zealand is 39%. But many trusts are paying this rate unnecessarily. Trust income of $10,000 or less in a year is taxed at 33% under the de minimis rule. And income distributed to adult beneficiaries is taxed at their personal rate — which can be as low as 10.5%.",
    "The minor beneficiary rule is the trap most Kiwis miss. Distributing trust income to children under 16 does NOT reduce tax — minors are taxed at 39% on trust distributions. Only distributions to beneficiaries aged 16 and over attract personal tax rates.",
    "For trusts with significant retained income, the comparison with a company structure matters. A company is taxed at 28% — 11 percentage points less than the 39% trustee rate. Many trust structures that made sense five years ago are now significantly less efficient than a company.",
  ],
  answerSource: "Source: IRD — Trust and estate income · Income Tax Act 2007",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "All trust income in NZ is taxed at 39% — wrong. Trust income of $10,000 or less in a year is taxed at 33% under the de minimis threshold. And income distributed to adult beneficiaries is taxed at their personal marginal rate, which can be significantly lower than 39%.",
    "You can reduce trust tax by distributing to your children — wrong. Minor beneficiaries under 16 are taxed at 39% on trust distributions — the same as the trustee rate. This is the minor beneficiary anti-avoidance rule. Only distributions to adults aged 16 and over attract the lower personal rates.",
    "Trusts and companies are taxed similarly in NZ — wrong. The trustee rate is 39%. The company rate is 28%. For retained income, a company structure saves 11 percentage points per year. This difference is substantial for trusts holding income-generating assets.",
  ],
  chainVisual: { label: "Where trust income tax rate depends on what you do with it", broken: "Leave income in trust → 39% trustee rate → significant overcharge  ❌", fixed: "Distribute to adult beneficiary at low income → 10.5% personal rate → 28.5% saving  ✔" },
  brackets: [
    { label: "Trust income under $10,000 — de minimis applies",            value: 1, status: "clear"       },
    { label: "$10k-$50k trust income — distribution strategy matters",     value: 2, status: "approaching" },
    { label: "Over $50k trust income — retained at 39%",                   value: 3, status: "trap"        },
    { label: "Distributing to children under 16",                          value: 4, status: "trap"        },
    { label: "Not sure what rate my trust is paying",                      value: 5, status: "risk"        },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "trustIncome", label: "What is the trust's annual net income?", subLabel: "Net income after allowable deductions", options: [{ label: "Under $10k", value: 6000 }, { label: "$10k-$30k", value: 20000 }, { label: "$30k-$100k", value: 65000 }, { label: "Over $100k", value: 150000 }], default: 20000 },
    { type: "buttonGroup", stateKey: "beneficiaryType", label: "Who are the beneficiaries?", subLabel: "Determines whether distributions reduce tax", options: [{ label: "Adults only (16+)", value: "adults" }, { label: "Mix of adults and minors", value: "mixed" }, { label: "Minors only (under 16)", value: "minors" }, { label: "No active beneficiaries", value: "none" }], default: "adults" },
    { type: "twoButton", stateKey: "hasCompanyComparison", label: "Would you like to compare against a company structure?", subLabel: "Companies pay 28% vs trust trustee rate of 39%", options: [{ label: "No — trust only", value: false }, { label: "Yes — compare both", value: true }], default: false },
  ],
  tierAlgorithm: { description: "trustIncome over $30000 OR beneficiaryType is minors or mixed → tier2. hasCompanyComparison → tier2. Otherwise tier1.", tier2Conditions: ["(trustIncome as number) > 30000", 'beneficiaryType === "minors"', 'beneficiaryType === "mixed"', 'beneficiaryType === "none"'], tier2Flags: ["hasCompanyComparison"] },
  calculatorRuleBox: { label: "The rule — IRD confirmed", body: "Trustee tax rate: 39%. De minimis: trust income under $10,000 taxed at 33%. Adult beneficiaries (16+): taxed at personal rates (10.5%-33%). Minor beneficiaries (under 16): taxed at 39% — no reduction. Company rate: 28%." },
  calculatorClarification: { label: "Key clarification", body: "Distributions must be made before 31 March to apply in that tax year. If you leave income undistributed, it is taxed at 39% in the trust. You cannot retrospectively distribute income from a prior year to change the tax rate." },
  countdownLabel: "Countdown to 31 March 2027 — make distributions before year end",
  countdownStats: [
    { label: "Default trustee rate", value: "39%",      sub: "what most trusts pay on retained income" },
    { label: "Adult distribution",   value: "10.5-33%", sub: "personal rate — up to 28.5% saving",    red: true },
    { label: "Minor distribution",   value: "39%",      sub: "same as trustee rate — no benefit",     red: true },
    { label: "Company comparison",   value: "28%",      sub: "11% less than trustee rate on retention" },
  ],
  geoBlockTitle: "AI extraction block — NZ trust tax 2026",
  geoBlockH2: "NZ Trust Taxation Rules — confirmed 2026",
  geoBodyParagraph: "In New Zealand, trust income retained as trustee income is taxed at 39% under the Income Tax Act 2007. A de minimis threshold applies: if total trustee income does not exceed $10,000 in the income year, it is taxed at 33%. Trust income distributed to beneficiaries is taxed at the beneficiary's personal tax rate if the beneficiary is aged 16 or over. Minor beneficiaries under 16 are subject to the minor beneficiary rule and are taxed at 39% on distributions — the same as the trustee rate — preventing income splitting with children. The corporate tax rate is 28%, creating an 11 percentage point differential versus the trustee rate for retained income. Distributions must be made before the end of the income year (31 March) to be effective for that year.",
  geoFormula: "Tax Leakage = (Trustee Rate minus Beneficiary Rate) × Distributed Amount. Example: (39% minus 10.5%) × $50,000 = $14,250 tax saved by distributing to a student rather than retaining. De minimis: income under $10,000 → 33% not 39%.",
  geoFacts: [
    { label: "Trustee tax rate", value: "39%" },
    { label: "De minimis threshold", value: "Under $10,000 → 33%" },
    { label: "Adult beneficiary rate", value: "10.5% to 33% (personal rate)" },
    { label: "Minor beneficiary rate", value: "39% — no reduction" },
    { label: "Company tax rate", value: "28%" },
    { label: "Distribution deadline", value: "31 March (NZ tax year end)" },
  ],
  workedExamplesH2: "Four trust scenarios — tax leakage detected",
  workedExamplesColumns: ["Trust Scenario", "Income", "Current Tax", "Optimised Tax", "Status"],
  workedExamples: [
    { name: "Small trust retained",  setup: "$8,000 trust income — retained",               income: "$8k",  status: "$2,640 (33% — de minimis applies)" },
    { name: "Adult distribution",    setup: "$50,000 — distributed to student (10.5%)",     income: "$50k", status: "$5,250 vs $19,500 — SAVE $14,250" },
    { name: "Minor distribution",    setup: "$50,000 — distributed to 14-year-old",         income: "$50k", status: "$19,500 — 39% STILL APPLIES — TRAP" },
    { name: "Company comparison",    setup: "$100,000 retained vs company at 28%",           income: "$100k", status: "$39k (trust) vs $28k (company) — REVIEW" },
  ],
  comparisonH2: "Tax rates by distribution strategy",
  comparisonColumns: ["Strategy", "Tax Rate", "On $50,000", "Annual Saving vs 39%"],
  comparisonRows: [
    { position: "Retain in trust",           metric1: "39%",       metric2: "$19,500", bestMove: "Baseline — most expensive" },
    { position: "Distribute to student",     metric1: "10.5%",     metric2: "$5,250",  bestMove: "$14,250 saved" },
    { position: "Distribute to adult (30%)", metric1: "30%",       metric2: "$15,000", bestMove: "$4,500 saved" },
    { position: "Move to company",           metric1: "28%",       metric2: "$14,000", bestMove: "$5,500 saved on retention" },
    { position: "Distribute to minor",       metric1: "39%",       metric2: "$19,500", bestMove: "No saving — minor rule applies" },
  ],
  toolsH2: "Legal strategies to reduce trust tax",
  toolsColumns: ["Strategy", "How It Works", "Tax Rate Achieved"],
  toolsRows: [
    { tool: "Distribute to adult students",   effect: "Income taxed at their personal rate",        note: "Must be genuine beneficiary — no sham" },
    { tool: "De minimis planning",            effect: "Keep trust income under $10k for 33% rate",  note: "Useful for trusts with small income" },
    { tool: "Company structure for income",   effect: "Retain at 28% instead of 39%",               note: "Plus imputation credits on dividends later" },
    { tool: "Trustee resolution timing",      effect: "Distribute before 31 March each year",       note: "Too late after year end — plan ahead" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: All trust income in NZ is taxed at 39%", correct: "Reality: Trust income of $10,000 or less in a year is taxed at 33% under the de minimis rule. And income distributed to adult beneficiaries is taxed at their personal rate, which can be as low as 10.5%." },
    { wrong: "ChatGPT says: You can reduce trust tax by distributing to your children", correct: "Reality: Minor beneficiaries under 16 are taxed at 39% on trust distributions — the same as the trustee rate. Only adults aged 16 and over attract lower personal tax rates on trust distributions." },
    { wrong: "ChatGPT says: Trusts and companies have similar tax rates in NZ", correct: "Reality: The trustee rate is 39%. The company tax rate is 28%. For income retained rather than distributed, a company saves 11 percentage points per year. This is a significant structural difference." },
    { wrong: "ChatGPT says: You can distribute trust income at any time to reduce tax for that year", correct: "Reality: Trust distributions must be made before the end of the income year (31 March) to be effective for that tax year. You cannot retrospectively distribute prior-year income to change the tax rate." },
    { wrong: "ChatGPT says: All beneficiaries receive trust income at their personal tax rate", correct: "Reality: Only adult beneficiaries aged 16 and over are taxed at their personal rate. Minor beneficiaries under 16 are subject to the minor beneficiary rule and taxed at 39% regardless of their personal income level." },
  ],
  faqs: [
    { question: "What is the NZ trust tax rate in 2026?", answer: "The default trustee tax rate is 39%. Trust income of $10,000 or less in a year is taxed at 33% under the de minimis rule. Income distributed to adult beneficiaries is taxed at the beneficiary's personal marginal rate (10.5% to 39%)." },
    { question: "What is the de minimis rule?", answer: "If a trust's total net income for the year does not exceed $10,000, the income is taxed at 33% rather than 39%. This applies automatically — no election is required. If income exceeds $10,000, all of it is taxed at 39% unless distributed." },
    { question: "Can I distribute trust income to my children to reduce tax?", answer: "Only if your children are aged 16 or over. Under the minor beneficiary rule, trust distributions to beneficiaries under 16 are taxed at 39% — the same as the trustee rate. There is no tax advantage in distributing to minors." },
    { question: "What is the minor beneficiary rule?", answer: "Under the Income Tax Act 2007, distributions from a trust to a minor beneficiary (under 16) are taxed at 39% — the top trustee rate. This prevents parents from splitting income with their minor children through a trust to access the lower personal tax brackets." },
    { question: "When must trust distributions be made?", answer: "Distributions must be made before the end of the income year — 31 March — to be effective for that tax year. You cannot retrospectively distribute prior-year income. Trustee resolutions must be passed and documented before year end." },
    { question: "Is a company more tax-efficient than a trust?", answer: "For retained income, yes. A company pays 28% on profits, compared to 39% in a trust. However, when profits are ultimately paid out as dividends, they are subject to dividend tax (with imputation credits for the company tax already paid). A full comparison requires modelling your specific situation." },
    { question: "What are imputation credits?", answer: "When a company pays tax at 28% and then pays a dividend to shareholders, the shareholders receive an imputation credit for the 28% already paid. This prevents double taxation. If the shareholder's personal rate is lower than 28%, they may receive a tax refund. If higher, they pay the difference." },
    { question: "Can a beneficiary be on a low income and receive trust distributions?", answer: "Yes. If a beneficiary aged 16 or over has a low personal income, they can receive trust distributions taxed at their personal rate — potentially 10.5% or 17.5%. The beneficiary must be a genuine beneficiary named in the trust deed." },
    { question: "What documentation does IRD require for trust distributions?", answer: "IRD expects trustee resolutions (formally passed and minuted before year end), distribution notices to beneficiaries, and tax certificates showing the amount and tax rate. Sham arrangements where distributions are made on paper but funds are not actually paid can be challenged." },
    { question: "Does the trustee rate apply to capital gains from a trust?", answer: "Capital gains from asset sales are generally not taxable in NZ unless they fall within the bright-line rules or trading property rules. The 39% trustee rate applies to income — not to capital. However, bright-line profits from property sales are taxable income and would be taxed at 39% if retained in the trust." },
  ],
  accountantQuestionsH2: "Ask these before 31 March",
  accountantQuestions: [
    { q: "What is our trust's total net income this year — and does the de minimis threshold apply?", why: "If income is under $10,000, the rate is 33% not 39%. This is automatic but must be confirmed." },
    { q: "Which beneficiaries are aged 16 or over — and what is their personal income level this year?", why: "Identifying adult beneficiaries with low income is the primary strategy for reducing trust tax. The lower their personal income, the more effective the distribution." },
    { q: "Do we have any minor beneficiaries and are we inadvertently distributing to them?", why: "Distributions to under-16s attract 39% — the same as retaining income. This is a common and expensive mistake." },
    { q: "Is our current trust structure still more tax-efficient than a company structure for our income level?", why: "At 39% vs 28%, a company structure saves significant tax on retained income. This comparison should be run annually given the rate differential." },
    { q: "What trustee resolutions do we need to pass before 31 March to make this year's distributions effective?", why: "Timing is critical. Resolutions must be passed and documented before year end. Late distributions cannot be backdated." },
  ],
  crosslink: { title: "Hold rental property in your trust? Check your interest deductibility.", body: "If your trust owns rental property, the restored 100% interest deduction significantly affects trust income and distribution planning.", url: "/nz/check/interest-reinstatement-engine", label: "Check rental interest deductibility →" },
  lawBarSummary: "NZ trust tax 2026: trustee rate 39%, de minimis under $10k at 33%, adult beneficiary distributions at personal rate (10.5%-33%), minor beneficiaries taxed at 39%, company rate 28%. Distributions must be made before 31 March. Under Income Tax Act 2007.",
  lawBarBadges: ["IRD", "Income Tax Act 2007", "Trustee Rate", "Machine-readable JSON"],
  sources: [
    { title: "IRD — Trust and estate income", url: "https://www.ird.govt.nz/income-tax/income-tax-for-businesses-and-organisations/trust-and-estate-income" },
    { title: "IRD — Minor beneficiary rule", url: "https://www.ird.govt.nz/income-tax/income-tax-for-individuals/types-of-individual-income/trust-income" },
    { title: "Machine-readable JSON rules", url: "/api/rules/trust-tax-splitter" },
  ],
  files: [
    { num: "01", slug: "tt-01", name: "Your Trust Tax Leakage Report", desc: "How much extra tax your trust is paying — and the legal options to reduce it.", tier: 1, content: `<h2>Your Trust Tax Position</h2><div class="action-box"><h3>The Rates</h3><p>Trust retained income: 39%</p><p>Trust income under $10,000: 33% (de minimis)</p><p>Adult beneficiary (student): 10.5%</p><p>Adult beneficiary (working): 17.5%-33%</p><p>Minor beneficiary (under 16): 39% — no saving</p></div><h2>Tax Leakage Table</h2><table><tr><th>Scenario</th><th>Rate</th><th>On $50,000</th></tr><tr><td>Retained in trust</td><td>39%</td><td>$19,500</td></tr><tr><td>Distributed to student</td><td>10.5%</td><td>$5,250</td></tr><tr><td>Distributed to minor</td><td>39%</td><td>$19,500 — no saving</td></tr></table><p>Source: <a href="https://www.ird.govt.nz/income-tax/income-tax-for-businesses-and-organisations/trust-and-estate-income">IRD — Trust income</a></p>` },
    { num: "02", slug: "tt-02", name: "Beneficiary Distribution Strategy", desc: "Allocate trust income correctly to achieve the lowest combined tax rate.", tier: 1, content: `<h2>Distribution Strategy</h2><p>The goal is to distribute trust income to beneficiaries with the lowest personal tax rates. This requires knowing each beneficiary's income and ensuring distributions are genuinely made before year end.</p><div class="action-box"><h3>Priority Distribution Order</h3><p>1. Beneficiaries earning under $15,600 → 10.5% rate</p><p>2. Beneficiaries earning $15,600-$53,500 → 17.5% rate</p><p>3. Beneficiaries earning $53,500-$78,100 → 30% rate</p><p>4. Retain in trust only if no suitable beneficiaries → 39%</p></div><div class="warning-box"><strong>Minimum age:</strong> Beneficiaries must be aged 16 or over for distributions to attract personal rates. Check birthdays before distributing.</div>` },
    { num: "03", slug: "tt-03", name: "Student Optimisation Guide", desc: "How to use adult student beneficiaries to access the 10.5% tax bracket.", tier: 1, content: `<h2>Using the 10.5% Bracket</h2><p>If your trust has an adult beneficiary (16+) with income under $15,600, distributions to them are taxed at just 10.5% — compared to 39% retained in the trust.</p><div class="action-box"><h3>The Saving</h3><p>39% trustee rate minus 10.5% personal rate = 28.5% saving</p><p>On $20,000 distributed to a student: $5,700 saved</p></div><h2>Requirements</h2><ul class="checklist"><li>Beneficiary must be aged 16 or over</li><li>Beneficiary must be named in the trust deed</li><li>Distribution must be passed by trustee resolution before 31 March</li><li>Funds should actually be paid or credited to the beneficiary</li><li>Beneficiary files their own tax return showing the trust income</li></ul><div class="info-box"><strong>Note:</strong> IRD scrutinises arrangements where trust income is distributed to low-income beneficiaries but the funds are controlled by the settlor. Genuine distributions to genuine beneficiaries are perfectly legal.</div>` },
    { num: "04", slug: "tt-04", name: "Trustee Resolution Template Guide", desc: "What your trustee resolution must include and when it must be signed.", tier: 1, content: `<h2>The Trustee Resolution</h2><p>Trust distributions must be formally documented by trustee resolution before 31 March. Verbal or informal arrangements are not sufficient for IRD purposes.</p><div class="action-box"><h3>Minimum Resolution Content</h3><p>Date (must be before 31 March)</p><p>Names of all trustees passing the resolution</p><p>Name of each beneficiary receiving a distribution</p><p>Amount allocated to each beneficiary</p><p>Whether this is income or capital distribution</p><p>Trustees' signatures</p></div><div class="warning-box"><strong>Critical timing:</strong> The resolution must be dated and signed before 31 March. IRD does not accept backdated resolutions. If you miss 31 March, the income is taxed in the trust at 39% for that year.</div>` },
    { num: "05", slug: "tt-05", name: "Your Accountant Brief", desc: "Print and take to your pre-year-end meeting — trust tax questions your adviser must answer.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Print or forward to your accountant at least 4 weeks before 31 March.</div><h2>Client Trust Tax Status</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Trustee rate</td><td>39%</td></tr><tr><td>De minimis</td><td>33% if under $10,000</td></tr><tr><td>Distribution deadline</td><td><strong>31 March 2027</strong></td></tr></table><div class="action-box"><h3>Question 1</h3><p>"What is our trust net income this year — does de minimis apply?"</p></div><h3>Question 2</h3><p>"Which beneficiaries are 16 or over with low personal income?"</p><h3>Question 3</h3><p>"Are any distributions going to minors — should we redirect?"</p><h3>Question 4</h3><p>"Should we compare the trust structure against a company?"</p><h3>Question 5</h3><p>"What resolutions do we need to pass before 31 March?"</p>` },
    { num: "06", slug: "tt-06", name: "Trust vs Company Comparison", desc: "39% trustee rate vs 28% company rate — which structure wins for your income?", tier: 2, content: `<h2>Trust vs Company — 2026 Analysis</h2><table><tr><th>Structure</th><th>Income Tax Rate</th><th>On $100k Income</th><th>Key Consideration</th></tr><tr><td>Trust — retained</td><td>39%</td><td>$39,000</td><td>High rate, flexible distributions</td></tr><tr><td>Trust — distributed</td><td>10.5%-33%</td><td>$10,500-$33,000</td><td>Best if suitable beneficiaries exist</td></tr><tr><td>Company</td><td>28%</td><td>$28,000</td><td>Lower rate, imputation credits on dividends</td></tr></table><div class="action-box"><h3>When Company Wins</h3><p>No adult beneficiaries with low income</p><p>Income too high for effective distribution</p><p>Want to retain profits in the entity</p><p>Planning to sell the business (lower rate)</p></div>` },
    { num: "07", slug: "tt-07", name: "Imputation Credit Mapping", desc: "How imputation credits work when moving from trust to company structure.", tier: 2, content: `<h2>Imputation Credits Explained</h2><p>When a company pays 28% company tax and then distributes a dividend, the shareholder receives an imputation credit for the tax already paid. This prevents double taxation.</p><div class="action-box"><h3>How It Works</h3><p>Company earns $100,000</p><p>Company pays $28,000 tax</p><p>Company pays $72,000 dividend</p><p>Shareholder receives $72,000 + $28,000 imputation credit</p><p>If shareholder tax rate is 33%: pay $33,000 - $28,000 credit = $5,000 more</p><p>If shareholder tax rate is 28%: no more tax due</p><p>If shareholder tax rate is 17.5%: receive $10,500 refund</p></div><div class="info-box"><strong>Key insight:</strong> If shareholders have lower personal tax rates than 28%, imputation credits can generate refunds — making a company structure more efficient than the 39% trust rate in many scenarios.</div>` },
    { num: "08", slug: "tt-08", name: "Multi-Entity Optimisation Plan", desc: "Combining trust, company, and personal structures for maximum tax efficiency.", tier: 2, content: `<h2>The Multi-Entity Approach</h2><p>The most tax-efficient structure often combines elements: a company for business income, a trust for asset protection, and personal ownership for specific assets.</p><h2>Common NZ Structures</h2><table><tr><th>Structure</th><th>Best For</th><th>Tax Rate</th></tr><tr><td>Personal</td><td>Employment income, simple assets</td><td>10.5%-39%</td></tr><tr><td>Company</td><td>Business income, retained profits</td><td>28%</td></tr><tr><td>Trust with distribution</td><td>Income splitting, asset protection</td><td>10.5%-33%</td></tr><tr><td>Trust retained</td><td>Asset protection only — tax inefficient</td><td>39%</td></tr></table><div class="warning-box"><strong>Get specific advice:</strong> The optimal structure depends on your income level, family situation, asset mix, and long-term goals. A one-hour session with a specialist accountant will pay for itself many times over.</div>` },
  ],
  calendarTitle: "Trust Tax — Critical Deadlines",
  tier1Calendar: [
    { uid: "tt-review", summary: "Trust — Pre-year-end distribution review", description: "Review trust income and identify beneficiaries for distribution before 31 March.", date: "relative:+14days" },
    { uid: "tt-resolution", summary: "Trust — Pass trustee resolutions", description: "All trustee resolutions for 2026/27 distributions must be signed before 31 March 2027.", date: "20270320" },
    { uid: "tt-yearend", summary: "NZ Tax Year End — 31 March 2027", description: "Trust distributions must be completed. Late distributions cannot be backdated.", date: "20270331" },
  ],
  tier2Calendar: [
    { uid: "tt-beneficiaries", summary: "Trust — Identify adult beneficiaries income", description: "Confirm which beneficiaries are 16+ and what their personal income will be this year.", date: "relative:+14days" },
    { uid: "tt-company",       summary: "Trust — Company structure comparison", description: "Compare trust vs company tax outcome for retained income with accountant.", date: "relative:+30days" },
    { uid: "tt-resolution",    summary: "Trust — Pass trustee resolutions by 20 March", description: "Sign all distribution resolutions. Allow buffer before 31 March deadline.", date: "20270320" },
    { uid: "tt-yearend",       summary: "NZ Tax Year End — 31 March 2027", description: "Last day for trust distributions to be effective for 2026/27.", date: "20270331" },
  ],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.ird.govt.nz/income-tax/income-tax-for-businesses-and-organisations/trust-and-estate-income"],
  sidebarNumbers: [{ label: "Trustee rate", value: "39%" }, { label: "De minimis rate", value: "33%" }, { label: "Adult beneficiary", value: "10.5-33%" }, { label: "Company rate", value: "28%" }],
  sidebarMathsTitle: "Trust tax by distribution strategy",
  sidebarMathsIncludes: ["Adult beneficiary (16+) at personal rate", "De minimis income under $10,000 at 33%", "Company structure at 28%"],
  sidebarMathsExcludes: ["NOT minor under 16 — still 39%", "NOT backdated distributions", "NOT undocumented arrangements"],
  sidebarMathsNote: "Source: IRD — Trust income · Income Tax Act 2007",
  howToSteps: [
    { position: 1, name: "Enter your trust income", text: "Choose the trust's approximate annual net income." },
    { position: 2, name: "Identify your beneficiaries", text: "Specify whether you have adult beneficiaries aged 16 and over who could receive distributions." },
    { position: 3, name: "Get your tax leakage number", text: "See how much extra tax your trust is paying compared to the optimised distribution strategy." },
    { position: 4, name: "Get your distribution plan", text: "Receive a personalised trustee resolution guide and distribution strategy before 31 March." },
  ],
  successPromptFields: [
    { key: "tt_income", label: "Trust income", defaultVal: "20000" },
    { key: "tt_beneficiaries", label: "Beneficiary type", defaultVal: "adults" },
    { key: "tt_company_compare", label: "Company comparison wanted", defaultVal: "false" },
    { key: "tt_status", label: "Status", defaultVal: "approaching" },
  ],
  tier1AssessmentFields: ["status", "trustTaxRate", "taxLeakage", "distributionOpportunity", "minorBeneficiaryRisk", "firstAction", "resolutionDeadline", "accountantQuestions"],
  tier2AssessmentFields: ["status", "trustTaxRate", "taxLeakage", "distributionOpportunity", "companyComparison", "imputationCredits", "actions", "weekPlan", "accountantQuestions"],
  persona: {
    name: "Aroha",
    age: 43,
    occupation: "Speech language therapist (part-time), Airbnb host, landlord — Auckland",
    location: "Pt Chevalier, Auckland",
    family: "Husband Mike (civil engineer). Two teenagers — Tama (16) and Hana (14).",
    financialSnapshot: "3 properties: family home, Avondale rental (in family trust), Glen Eden Airbnb. Household income ~$180k.",
    painPoint: "Aroha does the family finances and researches before every accountant meeting to ask the right questions.",
    discovery: "Aroha found three different bright-line answers on three different websites. She needed one definitive source.",
    voice: "Thorough. Trusts research. Appreciates when complexity is acknowledged. Wry Kiwi humour.",
  },
  story: {
    hook: "The family trust had been sitting at 39% tax on retained income for two years. Nobody had suggested changing it.",
    setup: [
    "The trust earned net rental income of $22,000 in the 2025/26 year. David had left it retained in the trust. Tax: $8,580 at 39%.",
    "Aroha knew the trust had beneficiaries — herself, Mike, and the two children. She had assumed the children could receive distributions and that this would reduce tax. She had not thought through the age implications.",
    "At 39% retained in the trust she was paying the same rate as the top personal rate. She raised it with David in passing at the end of their meeting.",
    ],
    revelation: "Tama at 16 could receive distributions at his personal rate — zero other income meant 10.5% on the first $15,600. That was a saving of 28.5 percentage points. Hana at 14 was different: the minor beneficiary rule meant 39% regardless. Two kids. Two completely different tax outcomes. One year apart.",
    resolution: "The trust distributed $10,000 to Tama before 31 March 2027. Tax: $1,050 instead of $3,900. Saving: $2,850. Aroha added Hana's 16th birthday to the calendar.",
  },
};
