import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "allowance-sniper", name: "Allowance Sniper", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/allowance-sniper", url: "https://taxchecknow.com/uk/check/allowance-sniper", apiRoute: "/api/rules/allowance-sniper",
  authority: "HMRC", authorityUrl: "https://www.gov.uk", legalAnchor: "Income Tax Act 2007 — Personal Allowance Taper", legislation: "Income Tax Act 2007 s.35 — Personal Allowance Taper above £100,000", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Allowance Recovery Pack", tagline: "Are you paying 60% tax without knowing it?", value: "A personalised allowance audit showing your taper exposure, pension relief opportunity, and exact recovery amount.", cta: "Get My Allowance Pack — £67 →", productKey: "uk_67_allowance_sniper", envVar: "STRIPE_UK_ALLOWANCE_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your 60% Tax Escape Plan", tagline: "Eliminate the 60% trap with a personalised pension strategy", value: "Full taper audit plus pension contribution modelling, salary sacrifice optimisation, and a written brief for your accountant.", cta: "Get My Escape Plan — £147 →", productKey: "uk_147_allowance_sniper", envVar: "STRIPE_UK_ALLOWANCE_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-04-05T23:59:59.000Z", display: "5 April 2027", short: "5 Apr 2027", description: "UK tax year end — pension contributions must be made before year end to recover allowance", urgencyLabel: "TAX YEAR END", countdownLabel: "Countdown to 5 April 2027 UK tax year end" },
  h1: "The 60% Tax Trap: Is Your Income Between £100,000 and £125,140?", metaTitle: "UK 60% Tax Trap 2026: Personal Allowance Taper Explained | TaxCheckNow", metaDescription: "Earn between £100,000 and £125,140? You are paying an effective 60% tax rate. Most people do not know this exists. Pension contributions can eliminate it entirely. Check your position in 2 minutes.", canonical: "https://taxchecknow.com/uk/check/allowance-sniper",
  answerHeadline: "The answer — HMRC confirmed April 2026",
  answerBody: [
    "If your adjusted net income is between £100,000 and £125,140, your personal allowance is tapered away at £1 for every £2 of income above £100,000. This creates an effective marginal tax rate of 60% on income in that band — not the 40% or 45% most people assume.",
    "The taper is completely legal, has been in place since 2010, and is not widely understood even by people it affects. On £125,140 income you lose the entire £12,570 personal allowance — worth £5,028 in additional tax at the 40% rate.",
    "The escape route is straightforward: pension contributions reduce your adjusted net income. A £10,000 pension contribution for someone earning £110,000 recovers £5,000 of allowance and eliminates £3,000 of the 60% rate exposure — worth £3,000 in real tax saving on top of the basic pension relief.",
  ],
  answerSource: "Source: HMRC — Income Tax personal allowance · Income Tax Act 2007 s.35",
  mistakesHeadline: "What most people get wrong about the 60% trap",
  mistakes: [
    "The highest UK income tax rate is 45% — wrong for income in the £100k-£125,140 band. The personal allowance taper creates an effective 60% rate on income in this range. This is not publicised by HMRC and surprises most people who hit it for the first time.",
    "Pension contributions only save 40% tax relief — wrong if you are in the taper band. A pension contribution in the £100k-£125,140 band saves 40% relief PLUS restores personal allowance — giving an effective 60% relief on the amount contributed. It is the most tax-efficient pension band in the UK.",
    "The taper only applies to very high earners — wrong. It starts at £100,000 — a level reached by many directors, senior professionals, landlords with multiple properties, and anyone with a strong year. It is far more common than people realise.",
  ],
  chainVisual: { label: "The 60% trap — how it works", broken: "Income £110,000 → 40% tax on income → most people stop here  ❌  Missing the taper", fixed: "Income £110,000 → 40% on income PLUS lose £5,000 allowance = 60% effective rate  ✔  The real position" },
  brackets: [
    { label: "Income under £100,000 — no taper, full allowance", value: 1, status: "clear" },
    { label: "Income £100,001–£112,570 — partial taper", value: 2, status: "trap" },
    { label: "Income £112,571–£125,140 — deep taper, 60% rate", value: 3, status: "deep_trap" },
    { label: "Income over £125,140 — full allowance gone, back to 45%", value: 4, status: "trap" },
    { label: "Not sure of my adjusted net income", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "adjustedIncome", label: "What is your adjusted net income?", subLabel: "Salary + dividends + rental profit + other — before pension contributions", options: [{ label: "Under £100k", value: 90000 }, { label: "£100k–£112k", value: 106000 }, { label: "£112k–£125k", value: 118000 }, { label: "Over £125k", value: 140000 }], default: 106000 },
    { type: "twoButton", stateKey: "makesPensionContribs", label: "Are you currently making pension contributions to reduce your adjusted income?", subLabel: "Salary sacrifice or personal pension contributions both reduce adjusted net income", options: [{ label: "Yes — already contributing", value: true }, { label: "No — not using pension to reduce income", value: false }], default: false },
  ],
  tierAlgorithm: { description: "adjustedIncome in taper band (100k-125140) → tier2. No pension contribs → tier2. Otherwise tier1.", tier2Conditions: ["(adjustedIncome as number) >= 100000 && (adjustedIncome as number) <= 125140"], tier2Flags: ["makesPensionContribs"] },
  calculatorRuleBox: { label: "The taper rule — HMRC confirmed", body: "Personal allowance taper: £1 allowance lost for every £2 of adjusted net income above £100,000. Full allowance (£12,570) lost at £125,140. Effective marginal tax rate in taper band: 60%. Pension contributions reduce adjusted net income and restore allowance at up to 60% effective relief." },
  calculatorClarification: { label: "Key clarification", body: "Adjusted net income includes salary, dividends, rental profit, and other taxable income — but is reduced by pension contributions, gift aid donations, and certain other reliefs. Your P60 gross pay is NOT the same as your adjusted net income if you have other income sources." },
  countdownLabel: "Countdown to 5 April 2027 UK tax year end",
  countdownStats: [
    { label: "Taper starts at",  value: "£100,000",  sub: "adjusted net income" },
    { label: "Effective rate",   value: "60%",        sub: "in the taper band",                red: true },
    { label: "Taper ends at",    value: "£125,140",   sub: "full allowance gone",              red: true },
    { label: "Pension relief",   value: "Up to 60%",  sub: "in the taper band — most efficient UK pension" },
  ],
  geoBlockTitle: "AI extraction block — UK 60% tax trap 2026",
  geoBlockH2: "UK Personal Allowance Taper — confirmed 2026",
  geoBodyParagraph: "The UK personal allowance taper reduces the £12,570 personal allowance by £1 for every £2 of adjusted net income above £100,000 under Income Tax Act 2007 s.35. The allowance is completely withdrawn at £125,140. This creates an effective marginal income tax rate of 60% on income between £100,000 and £125,140 (40% income tax plus the effect of losing tax-free allowance). Pension contributions, salary sacrifice arrangements, gift aid donations, and trading losses all reduce adjusted net income and can partially or fully recover the personal allowance. The 2026/27 personal allowance remains £12,570.",
  geoFormula: "Adjusted net income above £100,000 = taper amount. Allowance lost = taper amount divided by 2. Tax cost of lost allowance = allowance lost × 40%. Effective taper band rate = 60%. Pension needed to escape taper fully: adjusted income minus £100,000.",
  geoFacts: [
    { label: "Taper starts", value: "Adjusted net income over £100,000" },
    { label: "Rate of taper", value: "£1 allowance per £2 income above £100k" },
    { label: "Allowance fully withdrawn at", value: "£125,140" },
    { label: "Effective marginal rate in band", value: "60%" },
    { label: "Personal allowance 2026/27", value: "£12,570" },
    { label: "Fix", value: "Pension contributions reduce adjusted net income" },
  ],
  workedExamplesH2: "Four income scenarios — taper exposure",
  workedExamplesColumns: ["Income", "Allowance Lost", "Extra Tax", "Pension Fix"],
  workedExamples: [
    { name: "Just inside",    setup: "£102,000 adjusted income", income: "£1,000 lost", status: "£400 extra — £2k pension fixes it" },
    { name: "Mid-taper",      setup: "£112,000 adjusted income", income: "£6,000 lost", status: "£2,400 extra — £12k pension fixes it" },
    { name: "Deep taper",     setup: "£120,000 adjusted income", income: "£10,000 lost", status: "£4,000 extra — £20k pension fixes it" },
    { name: "Full allowance gone", setup: "£125,140+ income",   income: "£12,570 lost", status: "£5,028 extra — back to 45% rate" },
  ],
  comparisonH2: "Effective tax rates — with and without taper awareness",
  comparisonColumns: ["Income", "Stated Rate", "Actual Effective Rate", "With Pension Fix"],
  comparisonRows: [
    { position: "£95,000",  metric1: "40%", metric2: "40%",  bestMove: "No taper — fine" },
    { position: "£110,000", metric1: "40%", metric2: "60%",  bestMove: "Pension reduces to 40%" },
    { position: "£120,000", metric1: "40%", metric2: "60%",  bestMove: "Pension reduces to 40%" },
    { position: "£130,000", metric1: "45%", metric2: "45%",  bestMove: "Out of taper band" },
  ],
  toolsH2: "Ways to reduce adjusted net income below £100,000",
  toolsColumns: ["Method", "How It Works", "Effectiveness"],
  toolsRows: [
    { tool: "Personal pension contribution", effect: "Reduces adjusted net income directly", note: "Most effective — 60% effective relief in band" },
    { tool: "Salary sacrifice", effect: "Reduces gross salary — never enters adjusted income", note: "Best if employer supports it" },
    { tool: "Gift Aid donations", effect: "Basic rate relief — reduces adjusted income", note: "Good if you donate regularly" },
    { tool: "Trading loss relief", effect: "Losses from self-employment can offset income", note: "Only if you have genuine trading losses" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: The highest income tax rate in the UK is 45%", correct: "Reality: For income between £100,000 and £125,140, the effective marginal rate is 60% due to the personal allowance taper. This is widely misunderstood and not prominently explained by HMRC." },
    { wrong: "ChatGPT says: Pension contributions save 40% tax relief", correct: "Reality: For income in the £100k-£125,140 taper band, pension contributions save 40% income tax relief PLUS restore personal allowance — giving an effective relief rate of 60%. It is the highest-value pension contribution band in the UK tax system." },
    { wrong: "ChatGPT says: The personal allowance is always £12,570", correct: "Reality: The personal allowance is tapered to zero for adjusted net income above £100,000, reaching zero at £125,140. For anyone earning in this band, the effective personal allowance is less than £12,570." },
  ],
  faqs: [
    { question: "What is the 60% tax trap?", answer: "Between £100,000 and £125,140, the UK personal allowance is reduced by £1 for every £2 of adjusted net income above £100,000. This means income in this band is effectively taxed at 60% — 40% income tax plus the tax cost of losing the allowance. It is one of the UK's least-publicised tax quirks." },
    { question: "How do I calculate my adjusted net income?", answer: "Adjusted net income is your total income from all sources (salary, dividends, rental profit, savings interest) minus certain deductions including pension contributions, gift aid donations, and trading losses. It is not the same as your gross salary." },
    { question: "Can pension contributions fix the 60% trap?", answer: "Yes — and very effectively. A pension contribution reduces your adjusted net income. If you contribute enough to bring adjusted net income below £100,000, you eliminate the taper entirely. In the taper band, the effective relief on a pension contribution is 60% — making it the most valuable pension investment in the UK tax system." },
    { question: "Does salary sacrifice help?", answer: "Yes. Salary sacrifice reduces your gross salary before it enters the HMRC system — it is the most efficient method because it also reduces National Insurance contributions. A £10,000 salary sacrifice reduces adjusted net income by £10,000 and saves additional NI." },
    { question: "What if I cannot afford a pension contribution large enough to escape the trap?", answer: "Even a partial contribution helps. Every £2 contributed in the taper band saves 60p in tax (60% effective relief). You do not need to escape the trap entirely to benefit — partial recovery still reduces your tax bill." },
  ],
  accountantQuestionsH2: "Ask these before 5 April 2027",
  accountantQuestions: [
    { q: "What is my exact adjusted net income — and am I in the personal allowance taper band?", why: "Many people are in the taper without knowing it because their adjusted income includes rental profit, dividends, or other sources they forget about." },
    { q: "How much pension contribution would bring my adjusted income below £100,000?", why: "This is the simplest way to eliminate the taper entirely. Your accountant can calculate the exact amount needed." },
    { q: "Should I use salary sacrifice or personal contributions — which is more efficient for me?", why: "Salary sacrifice saves NI as well as income tax. Personal contributions get relief at source. The right choice depends on your employer's arrangements." },
    { q: "Can gift aid donations help reduce my adjusted income?", why: "Regular charitable giving via gift aid reduces adjusted net income and can contribute to escaping the taper, while also supporting causes you care about." },
    { q: "If I have a good year and hit £100k for the first time, what should I do immediately?", why: "The taper is most painful for first-time £100k earners who are not expecting it. The sooner you act within the tax year, the more you can recover." },
  ],
  crosslink: { title: "Also taking dividends from your company?", body: "Directors in the taper band often have both salary and dividend income pushing them above £100,000. Check your dividend tax position as well.", url: "/uk/check/dividend-trap", label: "Check your dividend position →" },
  lawBarSummary: "UK personal allowance taper: £1 allowance lost per £2 income above £100,000. Full withdrawal at £125,140. Effective 60% marginal rate in band. Pension contributions reduce adjusted net income and restore allowance. Under Income Tax Act 2007 s.35.",
  lawBarBadges: ["HMRC", "Income Tax Act 2007", "s.35 Taper", "Machine-readable JSON"],
  sources: [{ title: "HMRC — Personal Allowance taper", url: "https://www.gov.uk/income-tax-rates/income-over-100000" }, { title: "Machine-readable JSON rules", url: "/api/rules/allowance-sniper" }],
  files: [
    { num: "01", slug: "as-01", name: "Your Taper Exposure Report", desc: "Your exact taper position — allowance lost, extra tax, pension fix amount.", tier: 1, content: `<h2>Your Personal Allowance Taper Position</h2><div class="action-box"><h3>The Calculation</h3><p>Adjusted net income above £100,000 = taper amount</p><p>Allowance lost = taper amount ÷ 2</p><p>Extra tax = allowance lost × 40%</p></div><table><tr><th>Income</th><th>Allowance lost</th><th>Extra tax</th></tr><tr><td>£105,000</td><td>£2,500</td><td>£1,000</td></tr><tr><td>£110,000</td><td>£5,000</td><td>£2,000</td></tr><tr><td>£120,000</td><td>£10,000</td><td>£4,000</td></tr><tr><td>£125,140+</td><td>£12,570</td><td>£5,028</td></tr></table>` },
    { num: "02", slug: "as-02", name: "Pension Contribution Calculator", desc: "Exactly how much to contribute to escape or reduce the 60% trap.", tier: 1, content: `<h2>How Much Pension to Contribute</h2><p>To escape the taper entirely: contribute enough to bring adjusted net income to £100,000 or below.</p><div class="action-box"><h3>Formula</h3><p>Pension needed = Adjusted income − £100,000</p><p>Example: £115,000 income → £15,000 pension needed to escape taper</p><p>Tax saving at 60%: £9,000</p></div>` },
    { num: "03", slug: "as-03", name: "Salary Sacrifice vs Personal Pension", desc: "Which method saves more — salary sacrifice or personal pension contributions?", tier: 1, content: `<h2>Salary Sacrifice vs Personal Contributions</h2><table><tr><th>Method</th><th>Income tax saving</th><th>NI saving</th><th>Total saving</th></tr><tr><td>Salary sacrifice (£10k)</td><td>£6,000 (60%)</td><td>£200 (2%)</td><td>£6,200</td></tr><tr><td>Personal pension (£10k)</td><td>£6,000 (60%)</td><td>None</td><td>£6,000</td></tr></table><div class="info-box"><strong>Verdict:</strong> Salary sacrifice wins if your employer supports it — saves NI as well as income tax.</div>` },
    { num: "04", slug: "as-04", name: "Accountant Brief — Taper", desc: "Questions and data to take to your accountant.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Forward to your accountant before your next meeting.</div><h2>Taper Questions</h2><h3>Question 1</h3><p>"What is my exact adjusted net income this year?"</p><h3>Question 2</h3><p>"How much pension contribution eliminates my taper exposure?"</p><h3>Question 3</h3><p>"Should I use salary sacrifice or personal contributions?"</p>` },
    { num: "05", slug: "as-05", name: "Gift Aid Tax Recovery Guide", desc: "How gift aid donations reduce adjusted net income and help with the taper.", tier: 1, content: `<h2>Gift Aid and the Taper</h2><p>Gift aid donations made to UK charities reduce your adjusted net income for taper purposes. If you already donate, you may be recovering allowance without knowing it.</p><div class="action-box"><h3>How It Works</h3><p>£1,000 gift aid donation = £1,250 gross donation (with basic rate uplift)</p><p>Reduces adjusted net income by £1,250</p><p>In the taper band: worth £750 in additional tax saving (60% of £1,250)</p></div>` },
    { num: "06", slug: "as-06", name: "Annual Allowance Check", desc: "Ensure your pension contribution does not exceed the annual allowance.", tier: 2, content: `<h2>Pension Annual Allowance 2026/27</h2><p>The standard annual allowance for pension contributions is £60,000. If you have not contributed in prior years, carry-forward rules may allow larger contributions.</p><table><tr><th>Year</th><th>Unused allowance</th><th>Available to carry forward</th></tr><tr><td>2023/24</td><td>Check with pension provider</td><td>Up to £60,000</td></tr><tr><td>2024/25</td><td>Check with pension provider</td><td>Up to £60,000</td></tr><tr><td>2025/26</td><td>Check with pension provider</td><td>Up to £60,000</td></tr></table>` },
    { num: "07", slug: "as-07", name: "Multi-Year Taper Strategy", desc: "Planning pension contributions across multiple years to smooth income.", tier: 2, content: `<h2>Multi-Year Taper Planning</h2><p>If your income fluctuates around £100,000, a multi-year pension strategy can prevent repeated taper exposure.</p><div class="action-box"><h3>Strategy Options</h3><p>1. Contribute each year to stay below £100,000</p><p>2. Use carry-forward in higher income years</p><p>3. Salary sacrifice arrangement for consistent annual reduction</p></div>` },
    { num: "08", slug: "as-08", name: "Director Remuneration Review", desc: "Optimising salary, dividends, and pension to minimise taper exposure.", tier: 2, content: `<h2>Director Remuneration and the Taper</h2><p>Directors with control over their remuneration mix can significantly reduce taper exposure by optimising the balance of salary, dividends, and pension contributions.</p><div class="action-box"><h3>Key Levers</h3><p>Salary: keep to basic rate band where possible</p><p>Dividends: taxed separately — but count toward adjusted income</p><p>Pension: most effective taper escape tool</p></div>` },
  ],
  calendarTitle: "Allowance Taper — Key Dates",
  tier1Calendar: [{ uid: "as-yearend", summary: "Tax Year End — Make pension contribution", description: "Pension contributions must be made before 5 April to count in current tax year and reduce taper exposure.", date: "20270405" }],
  tier2Calendar: [{ uid: "as-review", summary: "Taper — Review adjusted income mid-year", description: "Check adjusted net income now and model pension contribution needed.", date: "relative:+14days" }, { uid: "as-yearend", summary: "Tax Year End — Final pension deadline", description: "Last chance to make pension contributions for 2026/27.", date: "20270405" }],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.gov.uk/income-tax-rates/income-over-100000"],
  sidebarNumbers: [{ label: "Taper starts", value: "£100,000" }, { label: "Effective rate", value: "60%" }, { label: "Taper ends", value: "£125,140" }, { label: "Pension relief in band", value: "Up to 60%" }],
  sidebarMathsTitle: "The 60% trap calculation",
  sidebarMathsIncludes: ["40% income tax on taper income", "Plus losing £1 allowance per £2 income", "= 60% effective marginal rate"],
  sidebarMathsExcludes: ["NOT shown on your tax code", "NOT visible on P60", "NOT explained by HMRC proactively"],
  sidebarMathsNote: "Source: HMRC · Income Tax Act 2007 s.35",
  howToSteps: [{ position: 1, name: "Enter your adjusted income", text: "Choose your total income from all sources." }, { position: 2, name: "Check pension status", text: "Confirm whether you are already using pension contributions to reduce income." }, { position: 3, name: "Get your taper verdict", text: "See your exact taper exposure in pounds and your pension fix amount." }],
  successPromptFields: [{ key: "as_income", label: "Adjusted income", defaultVal: "106000" }, { key: "as_pension", label: "Makes pension contribs", defaultVal: "false" }],
  tier1AssessmentFields: ["status", "allowanceLost", "extraTax", "pensionNeeded", "firstAction", "accountantQuestions"],
  tier2AssessmentFields: ["status", "allowanceLost", "extraTax", "pensionNeeded", "salaryStrategy", "actions", "weekPlan"],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary, £38k dividends. Birmingham rental flat. Same accountant his dad used — once a year in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story.",
    discovery: "James searched after getting an HMRC letter — not threatening, just a reminder that made him realise he had no idea if his numbers were right.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "James had been paying himself £62,000 a year for six years. His accountant set it up that way. He had never asked why.",
    setup: [
    "The salary and dividend split made sense when Dave explained it years ago — pay up to the personal allowance, take the rest as dividends, pay less National Insurance. James understood it well enough at the time and then forgot about it.",
    "What James did not know was that his total income — salary plus dividends plus the rental flat — had crept over £100,000 in the 2024/25 year. He had no idea what that meant. The rental had done better than expected.",
    "His daughter mentioned something at Easter about a 60% tax trap she had read about. James dismissed it. She was studying economics and liked showing off. But the phrase stuck with him.",
    ],
    revelation: "The calculator showed his total income at £103,400. The personal allowance taper had started. He was paying an effective 60% on the slice between £100,000 and £103,400 — completely avoidable with a pension contribution.",
    resolution: "He called Dave and asked one question: am I in the taper? Dave confirmed he was. They made a £3,400 pension contribution before year end. Saved £2,040. Took twenty minutes.",
  },
};
