import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "side-hustle-checker", name: "Side Hustle Checker", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/side-hustle-checker", url: "https://taxchecknow.com/uk/check/side-hustle-checker", apiRoute: "/api/rules/side-hustle-checker",
  authority: "HMRC", authorityUrl: "https://www.gov.uk", legalAnchor: "Income Tax (Trading and Other Income) Act 2005", legislation: "Income Tax (Trading and Other Income) Act 2005 — Trading Allowance and Self Assessment", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Side Hustle Tax Pack", tagline: "Does HMRC know about your side income — and should you be worried?", value: "A personalised side hustle tax assessment showing your declaration obligations, tax exposure, and whether you are already on HMRC radar.", cta: "Get My Side Hustle Pack — £67 →", productKey: "uk_67_side_hustle_checker", envVar: "STRIPE_UK_SH_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Side Hustle Registration Plan", tagline: "Get registered and compliant before HMRC contacts you", value: "Full side hustle audit plus self assessment registration guide, expense claim maximiser, and backdated disclosure plan if needed.", cta: "Get My Registration Plan — £147 →", productKey: "uk_147_side_hustle_checker", envVar: "STRIPE_UK_SH_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-10-05T23:59:59.000Z", display: "5 October 2026", short: "5 Oct 2026", description: "Self assessment registration deadline for 2025/26 income over £1,000 trading allowance", urgencyLabel: "REGISTRATION DEADLINE", countdownLabel: "Countdown to 5 October 2026 self assessment registration deadline" },
  h1: "Side Hustle Tax UK 2026: Does HMRC Already Know?", metaTitle: "Side Hustle Tax UK 2026: HMRC Now Gets Your Platform Data Automatically | TaxCheckNow", metaDescription: "From January 2026, platforms like eBay, Etsy, Airbnb and Fiverr automatically report your earnings to HMRC. The £1,000 trading allowance is gross — not profit. If you earned over £1,000, you may need to register. Check your position in 2 minutes.", canonical: "https://taxchecknow.com/uk/check/side-hustle-checker",
  answerHeadline: "The answer — HMRC confirmed April 2026",
  answerBody: [
    "From January 2026, digital platforms including eBay, Etsy, Airbnb, Fiverr, Vinted, and Uber are legally required to report your earnings to HMRC. This means HMRC receives your platform income data automatically — whether you have declared it or not.",
    "The £1,000 trading allowance is based on gross income — the total you receive before any expenses. If your gross income from all side hustles combined exceeds £1,000 in a tax year, you must register for self assessment and file a tax return, even if your profit after expenses is lower.",
    "The registration deadline is 5 October following the tax year end. For income earned in the 2025/26 tax year (ending 5 April 2026), you must register by 5 October 2026. Missing this deadline triggers an automatic £100 penalty.",
  ],
  answerSource: "Source: HMRC — Self assessment · Trading allowance · Platform reporting",
  mistakesHeadline: "What most side hustlers get wrong",
  mistakes: [
    "The £1,000 allowance is per platform — wrong. The £1,000 trading allowance is your total across ALL income sources. Multiple platforms, multiple types of side income — they all count together. Earn £600 on Etsy and £600 on Vinted and you are over the threshold.",
    "HMRC only knows if you tell them — wrong from January 2026. Digital platforms now report directly to HMRC. If you earned over a certain amount on a qualifying platform, HMRC already has your data. Undeclared income will now be cross-referenced against platform reports.",
    "The allowance covers profit not income — wrong. The £1,000 threshold is gross income — the total you receive before expenses. If your platform payments total more than £1,000, you must register, even if costs mean your profit is below £1,000.",
  ],
  chainVisual: { label: "HMRC platform reporting — how it works from 2026", broken: "Platform pays you → you decide whether to declare  ❌  No longer works — HMRC gets the data directly", fixed: "Platform pays you → platform reports to HMRC → HMRC cross-checks your return  ✔  The new reality" },
  brackets: [
    { label: "Gross side income under £1,000 — trading allowance covers it", value: 1, status: "clear"      },
    { label: "Gross income £1,000–£5,000 — must register for self assessment", value: 2, status: "trap"     },
    { label: "Gross income £5,000–£85,000 — income tax and possibly VAT", value: 3, status: "deep_trap"    },
    { label: "Gross income over £85,000 — VAT registration required",          value: 4, status: "deep_trap" },
    { label: "Not sure of my total gross platform income",                      value: 5, status: "risk"     },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "grossSideIncome", label: "What is your total gross income from all side hustles?", subLabel: "Include all platforms combined — before any expenses", options: [{ label: "Under £1,000", value: 500 }, { label: "£1,000–£5,000", value: 3000 }, { label: "£5,000–£30,000", value: 15000 }, { label: "Over £30,000", value: 50000 }], default: 3000 },
    { type: "twoButton", stateKey: "isRegistered", label: "Are you already registered for self assessment?", subLabel: "A UTR number means you are registered", options: [{ label: "Yes — already registered", value: true }, { label: "No — not registered", value: false }], default: false },
    { type: "twoButton", stateKey: "platformIncome", label: "Is your income from digital platforms (eBay, Etsy, Airbnb, Fiverr etc.)?", subLabel: "These platforms now report directly to HMRC from January 2026", options: [{ label: "Yes — platform income", value: true }, { label: "No — other side income", value: false }], default: true },
  ],
  tierAlgorithm: { description: "grossSideIncome over £1000 AND not registered → tier2. Platform income and not registered → tier2.", tier2Conditions: ["(grossSideIncome as number) > 1000"], tier2Flags: ["isRegistered"] },
  calculatorRuleBox: { label: "The rules — HMRC confirmed", body: "Trading allowance: £1,000 gross income per year — threshold, not profit. Over £1,000: must register for self assessment by 5 October after tax year end. Platform reporting: platforms report your income to HMRC from January 2026. Penalty for late registration: £100 automatically." },
  calculatorClarification: { label: "Key clarification", body: "The £1,000 allowance is per person, not per platform. All your side income from every source counts together. If you use the trading allowance you cannot also claim expenses — it is one or the other." },
  countdownLabel: "Countdown to 5 October 2026 self assessment registration deadline",
  countdownStats: [
    { label: "Registration deadline",    value: "5 October",  sub: "for 2025/26 side income" },
    { label: "Late penalty",             value: "£100",       sub: "automatic — before you even file", red: true },
    { label: "Platforms reporting",      value: "From Jan 26", sub: "HMRC gets your data directly",    red: true },
    { label: "Trading allowance",        value: "£1,000",     sub: "gross — not profit" },
  ],
  geoBlockTitle: "AI extraction block — UK side hustle tax 2026",
  geoBlockH2: "UK Side Hustle Tax and Self Assessment — confirmed 2026",
  geoBodyParagraph: "From January 2026, digital platforms operating in the UK are required to collect and report seller data to HMRC under DAC7 digital platform reporting regulations. Platforms include eBay, Etsy, Airbnb, Fiverr, Vinted, Uber, Deliveroo, and other marketplaces. The UK trading allowance is £1,000 gross income per year — if total trading income from all sources exceeds £1,000, the individual must register for self assessment by 5 October following the tax year end. The allowance is based on gross income (before expenses), not profit. If the trading allowance is claimed, no expenses can be deducted. Failure to register by 5 October results in an automatic £100 penalty.",
  geoFormula: "Side hustle tax test: If gross income from all trading sources exceeds £1,000 in tax year → must register for self assessment by 5 October after tax year end. Tax owed = (Gross income minus lower of: £1,000 trading allowance or actual expenses) × marginal income tax rate.",
  geoFacts: [
    { label: "Trading allowance", value: "£1,000 gross income" },
    { label: "Platform reporting", value: "Mandatory from January 2026" },
    { label: "Registration deadline", value: "5 October after tax year end" },
    { label: "Filing deadline", value: "31 January (online)" },
    { label: "Late registration penalty", value: "£100 automatic" },
    { label: "VAT registration threshold", value: "£90,000 from April 2024" },
  ],
  workedExamplesH2: "Four side hustler scenarios",
  workedExamplesColumns: ["Side Hustler", "Gross Income", "Tax Position", "Action Needed"],
  workedExamples: [
    { name: "Small Vinted seller",    setup: "£750 gross from selling old clothes", income: "£750",  status: "Under allowance — no action" },
    { name: "Active Etsy seller",     setup: "£4,200 gross ceramics sales",          income: "£4,200", status: "Must register by 5 October" },
    { name: "Airbnb host",            setup: "£12,000 gross room rental",            income: "£12,000", status: "Register + Rent-a-Room check" },
    { name: "Fiverr freelancer",      setup: "£28,000 gross design income",          income: "£28,000", status: "Register + class 4 NI due" },
  ],
  comparisonH2: "Trading allowance vs actual expenses — which saves more?",
  comparisonColumns: ["Method", "When It Wins", "Example"],
  comparisonRows: [
    { position: "Trading allowance (£1,000)", metric1: "Low expense businesses", metric2: "Sells on Etsy with no real costs", bestMove: "Simple — no receipts needed" },
    { position: "Actual expenses",            metric1: "High expense businesses", metric2: "Buys stock to resell",           bestMove: "More admin but often larger deduction" },
  ],
  toolsH2: "What expenses can be claimed against side hustle income",
  toolsColumns: ["Expense", "Claimable?", "Notes"],
  toolsRows: [
    { tool: "Stock / materials purchased", effect: "Yes — cost of goods sold",  note: "Keep all receipts" },
    { tool: "Platform fees",               effect: "Yes",                        note: "eBay, Etsy, Fiverr fees deductible" },
    { tool: "Home office proportion",      effect: "Yes — partial",              note: "Proportion of broadband, electricity" },
    { tool: "Postage and packaging",       effect: "Yes",                        note: "All business postage deductible" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: HMRC only knows about your side hustle if you tell them", correct: "Reality: From January 2026, digital platforms are legally required to report your earnings directly to HMRC. If you sell on eBay, Etsy, Airbnb, Vinted or similar platforms, HMRC receives your income data automatically." },
    { wrong: "ChatGPT says: You only need to register if you make a profit over £1,000", correct: "Reality: The £1,000 trading allowance is based on gross income — the total before any expenses. If your platform receipts total more than £1,000, you must register for self assessment, even if costs reduce your profit below £1,000." },
    { wrong: "ChatGPT says: You have until 31 January to register for self assessment", correct: "Reality: The self assessment REGISTRATION deadline is 5 October — not 31 January. The January date is for filing the return and paying tax. Registering late triggers a £100 penalty automatically." },
  ],
  faqs: [
    { question: "What is the £1,000 trading allowance?", answer: "The trading allowance lets you earn up to £1,000 gross from trading or self-employment activities without paying income tax or needing to file a self assessment return. If your gross income from all side hustles exceeds £1,000 in a tax year, you must register for self assessment." },
    { question: "Can I use the trading allowance and also claim expenses?", answer: "No — you cannot use both. If you claim the trading allowance, you cannot also deduct actual business expenses. If your expenses exceed £1,000, you are better off using actual expenses. You choose the most beneficial method each year." },
    { question: "Does the Rent-a-Room scheme apply to Airbnb?", answer: "The Rent-a-Room scheme allows you to earn up to £7,500 per year tax-free from letting furnished rooms in your main home. This can apply to Airbnb letting of rooms — but not to entire property lets. If you rent out a room in the house you live in, Rent-a-Room may be more beneficial than the trading allowance." },
    { question: "What if I have undeclared side income from prior years?", answer: "HMRC accepts voluntary disclosure through its Digital Disclosure Service. Disclosing voluntarily before HMRC contacts you typically results in lower penalties than being investigated. If you have undeclared income from prior years, taking advice on voluntary disclosure is strongly recommended." },
  ],
  accountantQuestionsH2: "Ask these before 5 October 2026",
  accountantQuestions: [
    { q: "Do I need to register for self assessment for my side income — and have I missed any previous years?", why: "Platform reporting from January 2026 means HMRC can now cross-check your returns against platform data. Catching up on prior years before HMRC contacts you results in significantly lower penalties." },
    { q: "Should I use the £1,000 trading allowance or claim actual expenses?", why: "The trading allowance is simpler but may not be optimal if your expenses are significant. Your accountant can run the numbers in minutes." },
    { q: "Does the Rent-a-Room scheme apply to my Airbnb letting?", why: "If you let rooms in your main home, Rent-a-Room gives you £7,500 tax-free — more than the trading allowance. But the rules are specific about what qualifies." },
  ],
  crosslink: { title: "Also a landlord with rental income?", body: "Rental income has different rules from trading income — and different MTD ITSA obligations. Check your landlord tax position separately.", url: "/uk/check/mtd-scorecard", label: "Check your landlord MTD position →" },
  lawBarSummary: "UK trading allowance: £1,000 gross income. Over £1,000: register for self assessment by 5 October. Platform reporting mandatory from January 2026. Late registration penalty: £100. Under ITTOIA 2005.",
  lawBarBadges: ["HMRC", "ITTOIA 2005", "DAC7 Reporting", "Machine-readable JSON"],
  sources: [{ title: "HMRC — Trading Allowance", url: "https://www.gov.uk/guidance/tax-free-allowances-on-property-and-trading-income" }, { title: "HMRC — Digital platform reporting", url: "https://www.gov.uk/guidance/digital-platform-reporting" }, { title: "Machine-readable JSON rules", url: "/api/rules/side-hustle-checker" }],
  files: [
    { num: "01", slug: "sh-01", name: "Your Side Hustle Tax Verdict", desc: "Your exact declaration position — what you owe and what you need to do.", tier: 1, content: `<h2>Your Side Hustle Position</h2><div class="action-box"><h3>The Key Thresholds</h3><p>Under £1,000 gross: trading allowance covers it</p><p>Over £1,000 gross: register by 5 October</p><p>Platform income: HMRC already has data from Jan 2026</p></div>` },
    { num: "02", slug: "sh-02", name: "Self Assessment Registration Guide", desc: "Step-by-step self assessment registration for side hustlers.", tier: 1, content: `<h2>How to Register for Self Assessment</h2><ol><li>Go to gov.uk/register-for-self-assessment</li><li>Select "I am self-employed or have other income"</li><li>Complete the online registration — you will receive a UTR number by post within 10 working days</li><li>Keep your UTR safe — you need it to file</li></ol><div class="warning-box"><strong>Deadline: 5 October 2026</strong> for income earned in 2025/26.</div>` },
    { num: "03", slug: "sh-03", name: "Trading Allowance vs Expenses Calculator", desc: "Which method saves you more tax — allowance or actual costs?", tier: 1, content: `<h2>Which Method Saves More?</h2><table><tr><th>Method</th><th>Use when</th><th>Tax saving</th></tr><tr><td>Trading allowance (£1,000)</td><td>Expenses under £1,000</td><td>Simple — no receipts</td></tr><tr><td>Actual expenses</td><td>Expenses over £1,000</td><td>Higher deduction</td></tr></table>` },
    { num: "04", slug: "sh-04", name: "Platform Income Record Template", desc: "Monthly income tracker for all platform earnings.", tier: 1, content: `<h2>Monthly Platform Income Record</h2><table><tr><th>Month</th><th>Platform</th><th>Gross income</th><th>Expenses</th><th>Net</th></tr><tr><td>April 2025</td><td></td><td></td><td></td><td></td></tr><tr><td>May 2025</td><td></td><td></td><td></td><td></td></tr></table>` },
    { num: "05", slug: "sh-05", name: "Accountant Brief — Side Hustle", desc: "Questions to take to your accountant.", tier: 1, content: `<h2>Side Hustle Questions</h2><h3>Question 1</h3><p>"Do I need to register — and have I missed prior years?"</p><h3>Question 2</h3><p>"Trading allowance or actual expenses?"</p><h3>Question 3</h3><p>"What expenses can I claim?"</p>` },
    { num: "06", slug: "sh-06", name: "Prior Year Disclosure Guide", desc: "How to disclose undeclared side income from previous years.", tier: 2, content: `<h2>Voluntary Disclosure</h2><p>HMRC's Digital Disclosure Service allows you to disclose undeclared income from prior years. Voluntary disclosure before HMRC contacts you results in significantly lower penalties.</p><div class="action-box"><h3>How It Works</h3><p>1. Calculate income and tax owed for each year</p><p>2. Log into Digital Disclosure Service</p><p>3. Submit disclosure and pay</p><p>4. HMRC confirms receipt and closes the matter</p></div>` },
    { num: "07", slug: "sh-07", name: "VAT Registration Assessment", desc: "When your side hustle income triggers VAT registration.", tier: 2, content: `<h2>VAT Registration Threshold</h2><p>If your gross trading income exceeds £90,000 in any 12-month period, you must register for VAT within 30 days. The threshold is rolling — not just the tax year.</p>` },
    { num: "08", slug: "sh-08", name: "Grow Your Side Hustle Tax-Efficiently", desc: "Structuring side income as your business grows.", tier: 2, content: `<h2>Scaling Your Side Hustle</h2><p>As income grows, the question changes from "do I need to declare?" to "what is the most tax-efficient structure?" Options include: sole trader, limited company, or partnership. Each has different tax treatment.</p>` },
  ],
  calendarTitle: "Side Hustle — Key Tax Dates",
  tier1Calendar: [{ uid: "sh-reg", summary: "Self Assessment Registration Deadline", description: "Register for self assessment by 5 October 2026 for 2025/26 side income.", date: "20261005" }, { uid: "sh-file", summary: "Self Assessment Filing Deadline", description: "File your 2025/26 return and pay tax by 31 January 2027.", date: "20270131" }],
  tier2Calendar: [{ uid: "sh-review", summary: "Side Hustle — Review all platform income", description: "Calculate total gross income from all platforms for 2025/26.", date: "relative:+7days" }, { uid: "sh-reg", summary: "Self Assessment Registration Deadline", description: "Register by 5 October 2026.", date: "20261005" }, { uid: "sh-file", summary: "Filing and Payment Deadline", description: "31 January 2027.", date: "20270131" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_UK_SH_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_UK_SH_147" },
  monitorUrls: ["https://www.gov.uk/guidance/tax-free-allowances-on-property-and-trading-income"],
  sidebarNumbers: [{ label: "Trading allowance", value: "£1,000 gross" }, { label: "Registration deadline", value: "5 October" }, { label: "Late penalty", value: "£100" }, { label: "VAT threshold", value: "£90,000" }],
  sidebarMathsTitle: "The trading allowance — what it covers",
  sidebarMathsIncludes: ["All trading income from all sources combined", "Platform income (Etsy, eBay, Fiverr etc.)", "Gross — before any expenses"],
  sidebarMathsExcludes: ["NOT per platform — total combined", "NOT profit — gross income", "NOT employment income"],
  sidebarMathsNote: "Source: HMRC — Trading Allowance · ITTOIA 2005",
  howToSteps: [{ position: 1, name: "Enter your gross side income", text: "Total from all platforms and trading activities combined." }, { position: 2, name: "Check registration status", text: "Whether you are already registered for self assessment." }, { position: 3, name: "Get your verdict", text: "See exactly what HMRC expects and what you need to do before 5 October." }],
  successPromptFields: [{ key: "sh_income", label: "Gross side income", defaultVal: "3000" }, { key: "sh_registered", label: "Is registered", defaultVal: "false" }, { key: "sh_platform", label: "Platform income", defaultVal: "true" }],
  tier1AssessmentFields: ["status", "declarationRequired", "taxExposure", "registrationDeadline", "firstAction"],
  tier2AssessmentFields: ["status", "declarationRequired", "taxExposure", "priorYearsRisk", "disclosureOption", "actions", "weekPlan"],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary, £38k dividends. Birmingham rental flat. Same accountant his dad used — once a year in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story.",
    discovery: "James searched after getting an HMRC letter — not threatening, just a reminder that made him realise he had no idea if his numbers were right.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "The Birmingham flat had never felt like a side hustle. It was just something James and Helen owned.",
    setup: [
    "They bought it in 2019 when Helen's mother moved into assisted living. Kept it rather than sell. Rented it to a young couple for £975 a month. The letting agent handled everything. James had barely thought about it.",
    "What changed in 2024 was Airbnb. The tenants left in January. Rather than find new long-term tenants immediately, Helen suggested trying short-term lets. Six months of Airbnb followed — decent money, more hassle than expected.",
    "Then they went back to a long-term tenant in July. So the 2024/25 year had mixed property income: six months lettings, six months Airbnb, different rules potentially applying to each period.",
    ],
    revelation: "The furnished holiday letting rules changed in April 2025. The Airbnb income no longer qualified for the old FHL tax advantages. And HMRC's platform reporting meant Airbnb had already sent his earnings data directly. The numbers needed to match.",
    resolution: "James provided Dave with the full breakdown — lettings income and Airbnb income by month. Dave recalculated. No major liability. But without the breakdown, the mismatch between HMRC data and the return could have triggered a query.",
  },
};
