import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "mtd-scorecard", name: "MTD Scorecard", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/mtd-scorecard", url: "https://taxchecknow.com/uk/check/mtd-scorecard", apiRoute: "/api/rules/mtd-scorecard",
  authority: "HMRC", authorityUrl: "https://www.gov.uk/government/organisations/hm-revenue-customs", legalAnchor: "Finance Act 2021 — Making Tax Digital", legislation: "Finance Act 2021 — MTD for Income Tax Self Assessment (MTD ITSA) phased from April 2026", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your MTD Readiness Pack", tagline: "Are you in scope for Making Tax Digital — and are you actually ready?", value: "A personalised MTD compliance audit built around your income sources, your threshold position, and your software gap — not a generic HMRC guide.", cta: "Get My MTD Pack — £67 →", productKey: "uk_67_mtd_scorecard", envVar: "STRIPE_UK_MTD_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your MTD Implementation Plan", tagline: "Get compliant before HMRC comes looking", value: "A personalised MTD audit plus quarterly submission schedule, approved software comparison, and penalty risk assessment.", cta: "Get My MTD Plan — £147 →", productKey: "uk_147_mtd_scorecard", envVar: "STRIPE_UK_MTD_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-04-05T23:59:59.000Z", display: "5 April 2026", short: "5 Apr 2026", description: "UK tax year end — MTD ITSA live for income over £50,000", urgencyLabel: "MTD LIVE", countdownLabel: "Countdown to MTD ITSA — now live for £50k+ earners" },
  h1: "Making Tax Digital 2026: Are You Actually Compliant?", metaTitle: "MTD ITSA 2026: Are You In Scope and Actually Ready? | TaxCheckNow", metaDescription: "MTD for Income Tax is live from April 2026 for self-employed and landlords earning over £50,000. Most people think quarterly updates mean four full tax returns. They do not. Check your MTD position in 2 minutes.", canonical: "https://taxchecknow.com/uk/check/mtd-scorecard",
  answerHeadline: "The answer — HMRC confirmed April 2026",
  answerBody: [
    "Making Tax Digital for Income Tax Self Assessment (MTD ITSA) is live from 6 April 2026 for self-employed individuals and landlords with combined gross income over £50,000. From April 2027 the threshold drops to £30,000, and April 2028 it drops to £20,000.",
    "MTD does NOT mean four full tax returns per year. Quarterly updates are a brief digital summary of income and expenses — not a complete self assessment. The final declaration at year end is the equivalent of your current tax return. Most people are significantly overestimating the burden.",
    "The real risk is not the quarterly update — it is the approved software requirement. From April 2026 you must use HMRC-approved MTD-compatible software for your record keeping. Spreadsheets alone do not qualify unless bridged with approved software.",
  ],
  answerSource: "Source: HMRC — Making Tax Digital for Income Tax · Finance Act 2021",
  mistakesHeadline: "What most people get wrong about MTD",
  mistakes: [
    "MTD means four full tax returns per year — wrong. Quarterly updates are a brief income and expense summary. The full annual declaration is still filed once a year. HMRC describes quarterly updates as a digital check-in, not a mini return.",
    "Spreadsheets are fine for MTD — wrong. Spreadsheets alone do not meet MTD requirements. You must use HMRC-approved software, or bridge your spreadsheet to approved software using a recognised bridging tool.",
    "MTD only applies if you are self-employed — wrong. Landlords with gross rental income over £50,000 are in scope from April 2026, even if they have no other self-employment income.",
  ],
  chainVisual: { label: "MTD — what it actually requires vs what people think", broken: "Four full tax returns per year  ❌  This is wrong — and causing unnecessary panic", fixed: "Four brief quarterly updates + one final annual declaration  ✔  Same information, different timing" },


  brackets: [
    { label: "Gross income over £50,000 — in scope from April 2026",  value: 1, status: "in_scope"     },
    { label: "Gross income £30,000–£50,000 — in scope April 2027",   value: 2, status: "approaching"  },
    { label: "Gross income £20,000–£30,000 — in scope April 2028",   value: 3, status: "approaching"  },
    { label: "Gross income under £20,000 — not yet in scope",         value: 4, status: "out_of_scope" },
    { label: "Not sure of my total gross income across all sources",  value: 5, status: "risk"         },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "grossIncome", label: "What is your total gross income from self-employment and property?", subLabel: "Include all sources — not just your main business", options: [{ label: "Under £20k", value: 15000 }, { label: "£20k–£30k", value: 25000 }, { label: "£30k–£50k", value: 40000 }, { label: "Over £50k", value: 75000 }], default: 40000 },
    { type: "buttonGroup", stateKey: "incomeSource", label: "What are your income sources?", subLabel: "MTD applies to self-employment AND property income combined", options: [{ label: "Self-employed only", value: "self_employed" }, { label: "Landlord only", value: "landlord" }, { label: "Both", value: "both" }, { label: "Company director with rental", value: "director_rental" }], default: "both" },
    { type: "twoButton", stateKey: "hasApprovedSoftware", label: "Do you currently use HMRC-approved MTD-compatible software?", subLabel: "QuickBooks, Xero, FreeAgent, Sage qualify — basic spreadsheets do not", options: [{ label: "Yes — already using approved software", value: true }, { label: "No — using spreadsheets or nothing", value: false }], default: false },
  ],
  tierAlgorithm: { description: "grossIncome over £50k OR no approved software → tier2. Otherwise tier1.", tier2Conditions: ["(grossIncome as number) >= 50000"], tier2Flags: ["hasApprovedSoftware"] },
  calculatorRuleBox: { label: "The MTD rules — HMRC confirmed", body: "MTD ITSA: live from 6 April 2026 for gross income over £50,000. April 2027: £30,000 threshold. April 2028: £20,000 threshold. Quarterly updates = brief income/expense summaries. Annual final declaration = current tax return equivalent. Must use HMRC-approved software." },
  calculatorClarification: { label: "Key clarification", body: "Gross income is the total BEFORE expenses — not your profit. A landlord with £52,000 rental income is in scope even if costs reduce profit to £15,000. Check your gross figures, not net." },
  countdownLabel: "MTD ITSA — live for £50k+ from April 2026",
  countdownStats: [
    { label: "What people think",   value: "4 tax returns",  sub: "wrong — causing unnecessary panic" },
    { label: "What it actually is", value: "4 brief updates", sub: "plus one annual declaration",       red: true },
    { label: "In scope from",       value: "April 2026",     sub: "for gross income over £50,000",     red: true },
    { label: "Software penalty",    value: "£100–£400",      sub: "for non-compliant record keeping" },
  ],
  geoBlockTitle: "AI extraction block — MTD ITSA 2026",
  geoBlockH2: "Making Tax Digital for Income Tax — confirmed rules 2026",
  geoBodyParagraph: "Making Tax Digital for Income Tax Self Assessment (MTD ITSA) is mandatory from 6 April 2026 for self-employed individuals and landlords with combined gross income from self-employment and property exceeding £50,000 per year. The threshold reduces to £30,000 from April 2027 and £20,000 from April 2028. Under MTD ITSA, taxpayers must submit four quarterly updates to HMRC each year summarising income and expenses, followed by a final declaration. Quarterly updates are not full tax returns — they are brief digital summaries. HMRC-approved software must be used for record keeping. Spreadsheets alone do not qualify unless bridged with approved bridging software. Penalties apply for late quarterly updates and for failure to use compliant software.",
  geoFormula: "MTD Scope Test: If (self-employment gross income + property gross income) exceeds £50,000 in 2025/26 → in scope from April 2026. Quarterly update months: July, October, January, April. Final declaration: by 31 January following tax year end.",
  geoFacts: [
    { label: "MTD live from", value: "6 April 2026" },
    { label: "Phase 1 threshold", value: "Gross income over £50,000" },
    { label: "Phase 2 threshold", value: "Over £30,000 from April 2027" },
    { label: "Phase 3 threshold", value: "Over £20,000 from April 2028" },
    { label: "Quarterly updates", value: "4 per year — brief summaries only" },
    { label: "Software requirement", value: "HMRC-approved software mandatory" },
  ],
  workedExamplesH2: "Four taxpayer scenarios — in scope or not?",
  workedExamplesColumns: ["Taxpayer", "Gross Income", "In Scope From", "Software Gap"],
  workedExamples: [
    { name: "James — director + landlord", setup: "£180k salary via company, £52k gross rental", income: "£52k property", status: "IN SCOPE APRIL 2026" },
    { name: "Freelance designer",          setup: "£38k gross self-employment income",            income: "£38k",           status: "IN SCOPE APRIL 2027" },
    { name: "Part-time Airbnb host",       setup: "£14k gross Airbnb income only",                income: "£14k",           status: "NOT YET IN SCOPE" },
    { name: "Self-employed + landlord",    setup: "£22k freelance + £12k rental = £34k total",    income: "£34k combined",  status: "IN SCOPE APRIL 2027" },
  ],
  comparisonH2: "MTD quarterly update vs current self assessment",
  comparisonColumns: ["Item", "Current Self Assessment", "MTD ITSA"],
  comparisonRows: [
    { position: "How often you report",       metric1: "Once a year",           metric2: "4 quarterly + 1 annual", bestMove: "More frequent but lighter" },
    { position: "What each submission covers", metric1: "Full tax year",         metric2: "One quarter — brief summary", bestMove: "Much less per submission" },
    { position: "Software required",           metric1: "Not mandatory",         metric2: "HMRC-approved only",     bestMove: "Spreadsheets no longer enough" },
    { position: "Deadline for final return",   metric1: "31 January",           metric2: "31 January — unchanged", bestMove: "Same final deadline" },
  ],
  toolsH2: "HMRC-approved MTD software options",
  toolsColumns: ["Software", "Best For", "Approximate Cost"],
  toolsRows: [
    { tool: "QuickBooks",  effect: "Self-employed and small businesses",  note: "From £10/month — widely used" },
    { tool: "Xero",        effect: "Small to medium businesses",          note: "From £15/month — accountant favourite" },
    { tool: "FreeAgent",   effect: "Freelancers and contractors",         note: "Free with some business bank accounts" },
    { tool: "Sage",        effect: "Established businesses",              note: "From £12/month — good for payroll integration" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: MTD means you have to file four full tax returns every year", correct: "Reality: Quarterly updates are brief digital summaries of income and expenses — not full tax returns. HMRC has explicitly confirmed that quarterly updates are not mini self assessments. The annual final declaration is the equivalent of your current return." },
    { wrong: "ChatGPT says: MTD only applies to self-employed people", correct: "Reality: Landlords with gross property income over £50,000 are in scope from April 2026, even with no self-employment income. Combined income from both sources counts toward the threshold." },
    { wrong: "ChatGPT says: You can use a spreadsheet for MTD", correct: "Reality: Spreadsheets alone do not meet MTD requirements. You must use HMRC-approved software, or bridge your spreadsheet to compliant software using a recognised bridging tool. Unapproved record keeping can trigger penalties." },
    { wrong: "ChatGPT says: The MTD threshold is £10,000", correct: "Reality: The threshold for April 2026 is £50,000 gross income. It reduces to £30,000 in April 2027 and £20,000 in April 2028. The old £10,000 threshold was from an earlier proposal that was revised." },
  ],
  faqs: [
    { question: "What is Making Tax Digital for Income Tax?", answer: "MTD ITSA requires self-employed individuals and landlords to keep digital records and submit quarterly updates to HMRC, plus an annual final declaration, using approved software. It replaces the existing once-a-year self assessment process for in-scope taxpayers." },
    { question: "Am I in scope for MTD ITSA in 2026?", answer: "You are in scope from April 2026 if your combined gross income from self-employment and property exceeds £50,000. The threshold is based on gross income — before expenses. Combined income from multiple sources counts." },
    { question: "What does a quarterly update actually involve?", answer: "A quarterly update is a brief digital submission summarising your income and expenses for the quarter. It is not a tax calculation or a mini return. HMRC uses the updates to give you an estimate of your tax position during the year. The actual tax calculation happens at the final annual declaration." },
    { question: "What software do I need?", answer: "You must use HMRC-approved MTD-compatible software. Popular options include QuickBooks, Xero, FreeAgent, and Sage. If you currently use spreadsheets, you need either approved software or a recognised bridging tool that connects your spreadsheet to HMRC's systems." },
    { question: "What are the penalties for non-compliance?", answer: "HMRC uses a points-based penalty system for late quarterly updates. Each missed update earns a point. At four points you receive a £200 penalty and continue accumulating penalties until the points reset. Failure to use approved software can also trigger penalties." },
    { question: "Does MTD apply to company directors?", answer: "MTD ITSA applies to self-employment and property income reported through self assessment — not employment income processed through PAYE or company income. A company director who also has self-employment income or rental property above the threshold must comply with MTD for those income sources." },
    { question: "What if I use an accountant?", answer: "Your accountant can submit MTD updates on your behalf, but the underlying records must be kept in approved software. Your accountant should be guiding you on software choice and compliance — if they have not raised MTD yet, take the questions from this page to your next meeting." },
    { question: "When are quarterly updates due?", answer: "Quarterly updates are due within one month of the end of each quarter. Quarter 1 (April-June): by 5 August. Quarter 2 (July-September): by 5 November. Quarter 3 (October-December): by 5 February. Quarter 4 (January-March): by 5 May. The final annual declaration is due by 31 January." },
  ],
  accountantQuestionsH2: "Ask these at your next meeting",
  accountantQuestions: [
    { q: "Am I in scope for MTD ITSA in 2026 — and what is my total gross income across all sources?", why: "The threshold is gross income, not profit. If you are close to £50,000 across multiple sources, you need the exact figure. Your accountant can confirm from your last return." },
    { q: "Is my current software MTD-compatible — or do I need to switch?", why: "Many landlords and sole traders are using spreadsheets or basic software that will not meet MTD requirements. Getting this wrong risks penalties." },
    { q: "Can you handle my quarterly MTD updates on my behalf — and what will that cost?", why: "Most accountants will charge for quarterly submissions on top of annual fees. Knowing the cost now lets you budget and decide whether to handle updates yourself." },
    { q: "Do I need separate MTD records for each property?", why: "Landlords with multiple properties need to understand how HMRC expects income to be reported — per property or combined. The rules differ depending on property type." },
    { q: "Will MTD change my January tax bill — or just the timing of reporting?", why: "MTD changes when you report, not necessarily how much you owe. But quarterly updates may reveal underpayments earlier, which can be useful for cashflow planning." },
  ],
  crosslink: { title: "Also paying dividends from your company?", body: "Company directors taking dividends need to check their dividend tax position separately. The dividend trap catches many directors who think they are efficiently structured.", url: "/uk/check/dividend-trap", label: "Check your dividend position →" },
  lawBarSummary: "MTD ITSA live from 6 April 2026 for gross income over £50,000. Threshold: £30,000 from April 2027, £20,000 from April 2028. Requires HMRC-approved software and four quarterly updates plus annual final declaration. Under Finance Act 2021.",
  lawBarBadges: ["HMRC", "Finance Act 2021", "MTD ITSA", "Machine-readable JSON"],
  sources: [
    { title: "HMRC — Making Tax Digital for Income Tax", url: "https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax" },
    { title: "HMRC — MTD ITSA timeline and thresholds", url: "https://www.gov.uk/government/publications/making-tax-digital-for-income-tax-self-assessment-overview" },
    { title: "Machine-readable JSON rules", url: "/api/rules/mtd-scorecard" },
  ],
  files: [
    { num: "01", slug: "mtd-01", name: "Your MTD Scope Verdict", desc: "Whether you are in scope, from when, and what it means for your specific income mix.", tier: 1, content: `<h2>Your MTD Position</h2><div class="action-box"><h3>The Thresholds</h3><p>April 2026: gross income over £50,000</p><p>April 2027: over £30,000</p><p>April 2028: over £20,000</p></div><h2>What counts toward the threshold</h2><table><tr><th>Income type</th><th>Counts?</th></tr><tr><td>Self-employment gross</td><td>Yes</td></tr><tr><td>Property gross rental</td><td>Yes</td></tr><tr><td>Employment (PAYE)</td><td>No</td></tr><tr><td>Dividends</td><td>No</td></tr></table><p>Source: <a href="https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax">HMRC — MTD ITSA</a></p>` },
    { num: "02", slug: "mtd-02", name: "MTD Software Comparison", desc: "HMRC-approved software options ranked for your situation.", tier: 1, content: `<h2>HMRC-Approved MTD Software</h2><table><tr><th>Software</th><th>Cost</th><th>Best for</th><th>HMRC approved?</th></tr><tr><td>QuickBooks</td><td>From £10/month</td><td>Self-employed, small landlords</td><td>Yes</td></tr><tr><td>Xero</td><td>From £15/month</td><td>Growing businesses</td><td>Yes</td></tr><tr><td>FreeAgent</td><td>Free–£19/month</td><td>Freelancers, contractors</td><td>Yes</td></tr><tr><td>Sage</td><td>From £12/month</td><td>Established businesses</td><td>Yes</td></tr></table><div class="warning-box"><strong>Spreadsheets alone:</strong> Do not qualify. Must be bridged with approved bridging software.</div>` },
    { num: "03", slug: "mtd-03", name: "Quarterly Update Calendar", desc: "Exact dates for all four quarterly submissions and your annual declaration.", tier: 1, content: `<h2>Your MTD Submission Calendar</h2><table><tr><th>Quarter</th><th>Period</th><th>Due Date</th></tr><tr><td>Q1</td><td>6 April – 5 July</td><td>5 August</td></tr><tr><td>Q2</td><td>6 July – 5 October</td><td>5 November</td></tr><tr><td>Q3</td><td>6 October – 5 January</td><td>5 February</td></tr><tr><td>Q4</td><td>6 January – 5 April</td><td>5 May</td></tr><tr><td>Final declaration</td><td>Full year</td><td>31 January</td></tr></table><div class="info-box"><strong>Penalty system:</strong> Each missed quarterly update = 1 point. At 4 points = £200 penalty. Points reset after 24 months of compliance.</div>` },
    { num: "04", slug: "mtd-04", name: "Accountant Brief — MTD", desc: "Questions to take to your accountant about MTD compliance.", tier: 1, content: `<div class="info-box"><strong>How to use:</strong> Forward to your accountant or take to your next meeting.</div><h2>MTD Questions for Your Accountant</h2><div class="action-box"><h3>Question 1</h3><p>"Am I in scope for MTD ITSA — and from which April?"</p></div><h3>Question 2</h3><p>"Is my current software MTD-compatible?"</p><h3>Question 3</h3><p>"Will you handle my quarterly updates — and what is the cost?"</p><h3>Question 4</h3><p>"How do I report multiple properties under MTD?"</p><h3>Question 5</h3><p>"Does MTD change my tax bill or just the timing?"</p>` },
    { num: "05", slug: "mtd-05", name: "MTD Penalty Risk Assessment", desc: "What HMRC can charge and how to avoid it.", tier: 1, content: `<h2>MTD Penalty System</h2><p>HMRC uses a points-based system for late quarterly updates.</p><table><tr><th>Points</th><th>Consequence</th></tr><tr><td>1–3 points</td><td>Warning — no financial penalty</td></tr><tr><td>4 points</td><td>£200 financial penalty</td></tr><tr><td>5+ points</td><td>£200 per additional late update</td></tr></table><div class="warning-box"><strong>Points reset:</strong> After 24 months of full compliance from the point threshold date.</div><h2>Other Penalties</h2><p>Late annual declaration: same penalty regime as current self assessment — £100 immediately, rising to £900+ after 12 months.</p>` },
    { num: "06", slug: "mtd-06", name: "Multi-Property MTD Guide", desc: "How to handle MTD if you have more than one rental property.", tier: 2, content: `<h2>Multiple Properties Under MTD</h2><p>HMRC requires landlords to report each property separately or combined depending on property type. Residential and furnished holiday let properties are reported separately.</p><table><tr><th>Property type</th><th>MTD treatment</th></tr><tr><td>Residential lets</td><td>Combined as one business</td></tr><tr><td>Furnished holiday lets</td><td>Separate MTD business</td></tr><tr><td>Commercial property</td><td>Not in scope for MTD ITSA</td></tr></table>` },
    { num: "07", slug: "mtd-07", name: "Self-Employed + Landlord Combined Plan", desc: "Managing MTD across two income sources — self-employment and property.", tier: 2, content: `<h2>Combined Income MTD Strategy</h2><p>If you have both self-employment and rental income, you have two separate MTD businesses and must report each quarterly.</p><div class="action-box"><h3>Key Decisions</h3><p>1. One software for both or separate systems?</p><p>2. Combine with accountant or handle quarterly updates yourself?</p><p>3. Set up automatic bank feeds to reduce quarterly admin?</p></div>` },
    { num: "08", slug: "mtd-08", name: "MTD Transition Checklist", desc: "Step-by-step to get compliant before your MTD start date.", tier: 2, content: `<h2>MTD Transition Checklist</h2><ul class="checklist"><li>Confirm your gross income total and in-scope date</li><li>Choose HMRC-approved software</li><li>Set up bank feeds or import system</li><li>Register for MTD ITSA with HMRC</li><li>Complete first quarterly update by due date</li><li>Brief your accountant on your software choice</li><li>Set calendar reminders for all four quarterly due dates</li><li>File annual final declaration by 31 January</li></ul>` },
  ],
  calendarTitle: "MTD ITSA — Key Dates",
  tier1Calendar: [
    { uid: "mtd-q1", summary: "MTD — Quarter 1 Update Due", description: "First MTD quarterly update covering 6 April to 5 July. Due by 5 August.", date: "20260805" },
    { uid: "mtd-q2", summary: "MTD — Quarter 2 Update Due", description: "Second quarterly update covering July to October.", date: "20261105" },
    { uid: "mtd-q3", summary: "MTD — Quarter 3 Update Due", description: "Third quarterly update.", date: "20270205" },
    { uid: "mtd-final", summary: "MTD — Annual Final Declaration Due", description: "Annual final declaration — equivalent to current self assessment.", date: "20270131" },
  ],
  tier2Calendar: [
    { uid: "mtd-software", summary: "MTD — Confirm software is HMRC-approved", description: "Check your current software against HMRC approved software list.", date: "relative:+7days" },
    { uid: "mtd-register", summary: "MTD — Register for MTD ITSA with HMRC", description: "Register via your HMRC online services account.", date: "relative:+14days" },
    { uid: "mtd-q1", summary: "MTD — Quarter 1 Update Due", description: "First quarterly update due 5 August.", date: "20260805" },
    { uid: "mtd-final", summary: "MTD — Annual Final Declaration", description: "Final annual declaration due 31 January 2027.", date: "20270131" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_UK_MTD_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_UK_MTD_147" },
  monitorUrls: ["https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax"],
  sidebarNumbers: [{ label: "Phase 1 threshold", value: "£50,000" }, { label: "Quarterly updates", value: "4 per year" }, { label: "Live from", value: "April 2026" }, { label: "Software penalty", value: "Up to £400" }],
  sidebarMathsTitle: "What counts toward the MTD threshold",
  sidebarMathsIncludes: ["Self-employment gross income", "Property gross rental income", "All sources combined"],
  sidebarMathsExcludes: ["NOT PAYE employment income", "NOT dividends", "NOT pension income"],
  sidebarMathsNote: "Source: HMRC — MTD ITSA · Finance Act 2021",
  howToSteps: [
    { position: 1, name: "Enter your gross income", text: "Choose your total gross income from self-employment and property combined." },
    { position: 2, name: "Identify your income sources", text: "Specify whether you are self-employed, a landlord, or both." },
    { position: 3, name: "Check your software", text: "Confirm whether you currently use HMRC-approved MTD-compatible software." },
    { position: 4, name: "Get your MTD verdict", text: "See immediately whether you are in scope, from when, and what your compliance gap is." },
  ],
  successPromptFields: [
    { key: "mtd_income", label: "Gross income", defaultVal: "40000" },
    { key: "mtd_source", label: "Income source", defaultVal: "both" },
    { key: "mtd_software", label: "Has approved software", defaultVal: "false" },
    { key: "mtd_status", label: "MTD status", defaultVal: "approaching" },
  ],
  tier1AssessmentFields: ["status", "inScopeFrom", "softwareGap", "quarterlyDates", "firstAction", "accountantQuestions"],
  tier2AssessmentFields: ["status", "inScopeFrom", "softwareGap", "quarterlyDates", "multiPropertyPlan", "actions", "weekPlan", "accountantQuestions"],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary, £38k dividends. Birmingham rental flat. Same accountant his dad used — once a year in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story.",
    discovery: "James searched after getting an HMRC letter — not threatening, just a reminder that made him realise he had no idea if his numbers were right.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "James got the HMRC letter on a Tuesday morning. He read it twice and still was not sure what it meant.",
    setup: [
    "He runs Hartley Precision Engineering out of a unit in Solihull. Twelve employees. Good order book. The business side he knows inside out. The tax side he leaves to his accountant Dave, who he sees every April for about forty minutes.",
    "The letter said something about Making Tax Digital and quarterly submissions. James assumed it applied to bigger companies. He makes around £280,000 in annual turnover — nowhere near what he thought the threshold would be.",
    "He typed the question into Google on his phone while the kettle boiled. The first three results said different things. One said £85,000. One said £50,000. One said it was already live. He gave up and came back to it that evening.",
    ],
    revelation: "When he ran the calculator it came back immediately: above the £50,000 threshold. MTD for Income Tax applies from April 2026. His current system — a spreadsheet Dave checks once a year — does not qualify.",
    resolution: "James called Dave the next morning with a specific question for the first time: am I compliant, and what software do we need? Dave appreciated the preparation.",
  },
};
