import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "mtd-scorecard", name: "MTD Mandation Engine", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/mtd-scorecard", url: "https://taxchecknow.com/uk/check/mtd-scorecard", apiRoute: "/api/rules/mtd-scorecard",
  authority: "HMRC", authorityUrl: "https://www.gov.uk/government/organisations/hm-revenue-customs", legalAnchor: "Finance Act 2021 — Making Tax Digital for Income Tax Self Assessment (MTD ITSA)", legislation: "Finance Act 2021 — MTD ITSA phased implementation from 6 April 2026 · Income Tax (Digital Requirements) Regulations implementing quarterly update obligations · Schedule 24 Finance Act 2021 penalty regime (£200 initial + £10/day up to 90 days per missed quarterly update) · HMRC points-based late-submission penalty system",
  lastVerified: "April 2026",
  tier1: { price: 67, name: "Your MTD Readiness Pack", tagline: "Confirm your mandate date, software gap, and penalty exposure — before HMRC does it for you", value: "Your exact mandate wave + date, software migration path ranked for your situation, quarterly submission calendar with all 4 deadlines, penalty risk assessment, and 5 accountant questions — built for your income band and record-keeping reality.", cta: "Get My MTD Readiness Pack — £67 →", productKey: "uk_67_mtd_scorecard", envVar: "STRIPE_UK_MTD_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your MTD Implementation Plan", tagline: "Execute the software migration + quarterly book-keeping before mandate day", value: "Full implementation plan: software selection + migration sequencing, quarterly book-keeping setup, penalty risk mitigation strategy, multi-property reporting plan if relevant, accountant coordination brief, and first-year quarterly dry-run schedule.", cta: "Get My MTD Implementation Plan — £147 →", productKey: "uk_147_mtd_scorecard", envVar: "STRIPE_UK_MTD_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-04-06T00:00:00.000+01:00", display: "6 April 2026", short: "6 Apr 2026", description: "6 April 2026 — MTD ITSA Phase 1 mandate date for gross income over £50,000", urgencyLabel: "MANDATED — NOT OPTIONAL", countdownLabel: "Countdown to MTD ITSA Phase 1 — 6 April 2026" },
  h1: "Making Tax Digital 2026: Are You Mandated — And What Happens If You Miss It?",
  metaTitle: "MTD ITSA 2026: Are You Mandated and What Does It Cost if You Miss It | TaxCheckNow",
  metaDescription: "MTD for Income Tax is live from 6 April 2026 for gross income over £50,000. Most people don't know the reporting changes from 1 annual return to 5 submissions per year — and miss the £1,100-per-quarter penalty regime. Run your MTD check in 2 minutes.",
  canonical: "https://taxchecknow.com/uk/check/mtd-scorecard",
  answerHeadline: "MTD is a mandate, not a readiness exercise — and the penalty regime starts on day one",
  answerBody: [
    "Making Tax Digital for Income Tax Self Assessment (MTD ITSA) is mandatory from 6 April 2026 for self-employed individuals and landlords with combined gross income from self-employment and property exceeding £50,000. The threshold drops to £30,000 from April 2027, and £20,000 from April 2028. These thresholds are statutory under Finance Act 2021 — mandate, not choice.",
    "The reporting change is larger than most taxpayers realise. MTD does NOT simply mean filing your annual tax return online. It replaces one annual self-assessment with five submissions per year: four quarterly updates (due 5 August, 5 November, 5 February, 5 May) plus a final annual declaration (still due 31 January). Each quarterly update is a brief digital summary — not a mini tax return — but it IS a mandatory filing with a deadline. Missing any of them triggers HMRC's points-based penalty system.",
    "The penalty regime is where most first-year non-compliance gets expensive: each missed quarterly update carries a £200 initial penalty plus £10 per day up to 90 days = up to £1,100 per missed quarter. Miss all four quarterly updates in a year and you are looking at up to £4,400 in penalties alone, before any late-payment interest on the underlying tax. The two biggest causes of first-year breaches are (1) taxpayers still using spreadsheets or paper records — which do NOT meet MTD requirements — and (2) taxpayers who did not realise quarterly submissions were required at all.",
  ],
  answerSource: "Source: HMRC — Making Tax Digital for Income Tax · Finance Act 2021 · Confirmed April 2026",
  mistakesHeadline: "What most people (and most MTD commentary) get wrong",
  mistakes: [
    "MTD just means filing your tax return online — wrong. MTD replaces 1 annual self-assessment with 5 submissions per year: 4 quarterly updates (every 3 months) + 1 final annual declaration. The final declaration is the current tax return equivalent. Quarterly updates are brief digital summaries of income and expenses — but they ARE mandatory filings with deadlines and penalties.",
    "It only affects big businesses — wrong. MTD ITSA is an INDIVIDUAL taxpayer obligation based on gross income from self-employment and property. A landlord with £55,000 of gross rental income is mandated from April 2026. A freelancer with £32,000 of gross self-employment income is mandated from April 2027. The threshold drops to £20,000 from April 2028 — catching small sole traders and single-property landlords.",
    "I can keep using spreadsheets — wrong. MTD requires HMRC-approved software for record-keeping and submission. Spreadsheets ALONE do not qualify. You either migrate to approved software (QuickBooks, Xero, FreeAgent, Sage) or use an approved bridging tool to connect your spreadsheet to HMRC's systems. Unapproved record-keeping is itself a penalty trigger.",
    "MTD changes when I pay tax — wrong. Reporting changes (four quarterly updates plus a final declaration) but payment dates remain the same. You still pay your tax bill by 31 January following the end of the tax year, with payments on account due 31 January and 31 July. Quarterly updates are informational submissions, not tax calculations.",
  ],
  chainVisual: { label: "MTD — the three failure modes that trigger the penalty regime", broken: "Not on approved software + unaware of quarterly + missed deadlines  ❌  Up to £4,400/year in penalties", fixed: "Approved software + quarterly habit + calendar discipline  ✔  Compliant from day one, no surprises" },
  brackets: [
    { label: "Over £50,000 gross — mandated from 6 April 2026",          value: 1, status: "deep_trap" },
    { label: "£30,000–£50,000 gross — mandated from 6 April 2027",        value: 2, status: "trap" },
    { label: "£20,000–£30,000 gross — mandated from 6 April 2028",        value: 3, status: "approaching" },
    { label: "Under £20,000 gross — not currently in scope",              value: 4, status: "clear" },
    { label: "Self-employment + property combined — check the total",      value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "incomeBand", label: "What is your total gross income from self-employment and property?", subLabel: "GROSS = before expenses. Include ALL sources combined (self-employment + rental property).", options: [{ label: "Under £20,000", value: "under_20k" }, { label: "£20,000–£30,000", value: "20k_to_30k" }, { label: "£30,000–£50,000", value: "30k_to_50k" }, { label: "Over £50,000", value: "over_50k" }], default: "30k_to_50k" },
    { type: "buttonGroup", stateKey: "incomeSource", label: "What are your income sources?", subLabel: "MTD applies to self-employment AND property income combined — PAYE and dividends don't count.", options: [{ label: "Self-employed only", value: "self_employed" }, { label: "Landlord / property only", value: "landlord" }, { label: "Both self-employed + property", value: "both" }, { label: "Company director with rental", value: "director_rental" }], default: "both" },
    { type: "buttonGroup", stateKey: "recordKeeping", label: "What do you use for record-keeping today?", subLabel: "MTD requires HMRC-approved software. Spreadsheets and paper records do NOT qualify without bridging software.", options: [{ label: "Approved software (QuickBooks, Xero, FreeAgent, Sage)", value: "digital" }, { label: "Spreadsheets only", value: "spreadsheets" }, { label: "Paper / nothing digital", value: "paper" }], default: "spreadsheets" },
    { type: "twoButton", stateKey: "quarterlyAware", label: "Did you know MTD requires 4 quarterly updates + 1 final declaration per year?", subLabel: "1 annual tax return becomes 5 submissions. Most people don't know this.", options: [{ label: "Yes — knew about quarterly", value: true }, { label: "No — thought it was still annual", value: false }], default: false },
  ],
  tierAlgorithm: { description: "Mandated (income over £30k) AND (software gap OR awareness gap) → tier2 (implementation plan). Otherwise tier1 (readiness pack).", tier2Conditions: ["incomeBand === 'over_50k'", "incomeBand === '30k_to_50k'"], tier2Flags: [] },
  calculatorRuleBox: { label: "The MTD rules — HMRC confirmed", body: "MTD ITSA live from 6 April 2026 for gross income over £50,000 (Phase 1). Phase 2 (£30k threshold) from April 2027. Phase 3 (£20k threshold) from April 2028. Reporting: 4 quarterly updates + 1 final declaration per year. Software: HMRC-approved required — spreadsheets need bridging software. Penalties: £200 initial + £10/day up to 90 days = up to £1,100 per missed quarter, up to £4,400/year." },
  calculatorClarification: { label: "Gross income, not profit — and sources combine", body: "The threshold is based on GROSS income — before expenses. A landlord with £52,000 rental income is mandated even if profit after mortgage and costs is £15,000. Sources combine: £22k self-employment + £12k rental = £34k total → mandated from April 2027. PAYE salary and dividends do NOT count toward the MTD threshold." },
  countdownLabel: "Countdown to MTD ITSA Phase 1 — 6 April 2026",
  countdownStats: [
    { label: "What people think",   value: "4 tax returns",      sub: "wrong — causes misallocated effort" },
    { label: "What it actually is", value: "4 quarterly + 1 final", sub: "1 annual return becomes 5 submissions",  red: true },
    { label: "Per-quarter penalty", value: "Up to £1,100",       sub: "£200 initial + £10/day × up to 90 days",  red: true },
    { label: "Max annual penalty",  value: "Up to £4,400",       sub: "If all 4 quarterly updates missed",         red: true },
  ],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary via company, £38k dividends. Birmingham rental flat — £18k gross rental. Uses a spreadsheet that his accountant Dave reviews in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story — he hasn't thought about MTD because he's always assumed it applied to bigger businesses.",
    discovery: "James got an HMRC letter about MTD and assumed it didn't apply to him. His rental income plus any side-consulting would push him into scope — but he has no idea which phase and he's still on a spreadsheet.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "James got the HMRC letter on a Tuesday morning. He read it twice and still was not sure what it meant.",
    setup: [
      "He runs Hartley Precision Engineering out of a unit in Solihull. Twelve employees. Good order book. The business side he knows inside out. The tax side he leaves to his accountant Dave, who he sees every April for about forty minutes.",
      "The letter said something about Making Tax Digital and quarterly submissions. James assumed it applied to bigger companies. He makes around £280,000 in annual turnover — nowhere near what he thought the threshold would be.",
      "What James had not thought about was that MTD ITSA is INDIVIDUAL, not company-level. His £18k rental flat in Birmingham plus any consulting invoices outside the company would be his personal MTD threshold — and that number was already creeping toward £50k.",
    ],
    revelation: "When he ran the calculator it came back immediately: combined personal gross income puts him in the £30,000–£50,000 band, mandated from 6 April 2027. His current spreadsheet records do not qualify. He had never heard of quarterly submissions. That combination — missed mandate + spreadsheet + no quarterly awareness — is the exact profile that pays £1,100 per missed quarter.",
    resolution: "James called Dave the next morning with a specific question for the first time: which MTD wave am I in, and what software do we need to migrate to? Dave appreciated the preparation. By the end of the week James had QuickBooks running for the rental income and a calendar reminder for every 5th of the penalty months.",
  },
  geoBlockTitle: "AI extraction block — MTD ITSA 2026 mandation thresholds",
  geoBlockH2: "Making Tax Digital for Income Tax — confirmed thresholds and penalty regime 2026",
  geoBodyParagraph: "Making Tax Digital for Income Tax Self Assessment (MTD ITSA) is a statutory digital reporting regime for self-employed individuals and landlords under Finance Act 2021. Phase 1 commences 6 April 2026 for individuals with combined gross income from self-employment and property exceeding £50,000 per tax year. Phase 2 commences 6 April 2027 for individuals with gross income between £30,000 and £50,000. Phase 3 commences 6 April 2028 for gross income between £20,000 and £30,000. The threshold is based on gross income (before expenses) aggregated across all self-employment and property sources. PAYE employment income and dividends are excluded from the threshold calculation. Under MTD ITSA, mandated taxpayers must use HMRC-approved software for record-keeping and submissions. Spreadsheets alone do not meet MTD requirements unless bridged with approved bridging software. The reporting cadence changes from one annual self-assessment to five submissions per year: four quarterly updates (due 5 August, 5 November, 5 February, 5 May) summarising income and expenses for each quarter, plus a final annual declaration (due 31 January) which is the equivalent of the current self-assessment return. Payment dates remain unchanged (31 January balance payment plus two payments on account). The penalty regime for late or missing quarterly updates is points-based: each missed submission accumulates one point, with a £200 financial penalty triggered at four points. Additional financial penalties apply per quarter at £200 initial plus £10 per day up to a 90-day cap, amounting to up to £1,100 per missed quarterly update. The maximum annual penalty exposure from missing all four quarterly updates is approximately £4,400, before late-payment interest on underlying tax.",
  geoFormula: "MTD mandate test: if (self-employment gross + property gross) exceeds threshold at phase date, then mandated. Phase 1 threshold £50,000 from 6 April 2026. Phase 2 £30,000 from 6 April 2027. Phase 3 £20,000 from 6 April 2028. Penalty per missed quarterly update = £200 + (£10 × days late up to 90 days). Max penalty per quarter = £1,100. Max annual penalty (4 quarters missed) = £4,400.",
  geoFacts: [
    { label: "Phase 1 mandate date",          value: "6 April 2026" },
    { label: "Phase 1 threshold",             value: "Gross income over £50,000" },
    { label: "Phase 2 mandate date",          value: "6 April 2027" },
    { label: "Phase 2 threshold",             value: "Gross income over £30,000" },
    { label: "Phase 3 mandate date",          value: "6 April 2028" },
    { label: "Phase 3 threshold",             value: "Gross income over £20,000" },
    { label: "Submissions per year",          value: "1 → 5 (4 quarterly + 1 final)" },
    { label: "Per-quarter penalty maximum",   value: "£1,100 (£200 + £10/day × 90 days)" },
    { label: "Annual penalty maximum",        value: "£4,400 (4 quarters missed)" },
    { label: "Legal anchor",                  value: "Finance Act 2021" },
  ],
  workedExamplesH2: "Four taxpayer scenarios — which mandate wave are they in?",
  workedExamplesColumns: ["Taxpayer", "Gross income", "Mandate wave", "Software/awareness status"],
  workedExamples: [
    { name: "James — director + landlord",        setup: "£62k salary via company (excluded), £38k dividends (excluded), £18k rental + some consulting = £40k personal gross",  income: "£40k combined",                status: "PHASE 2 — 6 APR 2027" },
    { name: "Freelance designer",                  setup: "£38k gross self-employment only",                                                                                      income: "£38k",                         status: "PHASE 2 — 6 APR 2027" },
    { name: "Full-time landlord",                  setup: "Two rental properties, £65k combined gross rental",                                                                    income: "£65k property",                status: "PHASE 1 — 6 APR 2026" },
    { name: "Part-time Airbnb host",               setup: "£14k gross Airbnb only, no other self-employment",                                                                     income: "£14k",                         status: "NOT YET IN SCOPE" },
  ],
  comparisonH2: "MTD quarterly update vs current self-assessment — what actually changes",
  comparisonColumns: ["Item", "Current Self-Assessment", "MTD ITSA (after mandate)"],
  comparisonRows: [
    { position: "Submissions per year",         metric1: "1 annual return",                 metric2: "4 quarterly + 1 final = 5",                     bestMove: "5× more submissions" },
    { position: "What each submission covers",   metric1: "Full tax year calculation",       metric2: "Quarterly = brief summary; final = full calc", bestMove: "Lighter per submission, more often" },
    { position: "Software required",             metric1: "Not mandatory",                   metric2: "HMRC-approved software mandatory",               bestMove: "Spreadsheets alone no longer enough" },
    { position: "Record-keeping frequency",      metric1: "Annual catch-up OK",              metric2: "Quarterly book-keeping discipline required",    bestMove: "Ongoing, not annual" },
    { position: "Payment dates",                 metric1: "31 Jan balance + 2 POA",          metric2: "UNCHANGED",                                      bestMove: "Reporting changes, not payment" },
    { position: "Per-missed-quarter penalty",    metric1: "N/A (annual only)",               metric2: "Up to £1,100 (£200 + £10/day × 90 days)",        bestMove: "Missing quarters is expensive" },
  ],
  toolsH2: "HMRC-approved MTD software — ranked for your situation",
  toolsColumns: ["Software", "Best For", "Approximate Cost"],
  toolsRows: [
    { tool: "QuickBooks",   effect: "Self-employed and small landlords — most widely used",  note: "From £10/month" },
    { tool: "Xero",         effect: "Multi-property landlords, accountant-shared access",    note: "From £15/month" },
    { tool: "FreeAgent",    effect: "Freelancers and contractors (free with some banks)",    note: "Free–£19/month" },
    { tool: "Sage",         effect: "Established businesses with payroll",                    note: "From £12/month" },
    { tool: "Bridging software", effect: "Keep spreadsheets, connect to MTD",                note: "£5–15/month add-on" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: MTD just means filing your tax return online",                                            correct: "Reality: MTD replaces one annual self-assessment with FIVE submissions per year — four quarterly updates plus one final declaration. The quarterly updates are brief digital summaries but each is a mandatory filing with a deadline and penalty regime." },
    { wrong: "ChatGPT says: MTD only affects big businesses",                                                          correct: "Reality: MTD ITSA is an INDIVIDUAL taxpayer obligation based on gross income from self-employment and property. Phase 3 from April 2028 lowers the threshold to £20,000 — catching small sole traders and single-property landlords. The direction of travel has consistently been downward." },
    { wrong: "ChatGPT says: You can use spreadsheets for MTD",                                                          correct: "Reality: Spreadsheets ALONE do not meet MTD requirements. You must either migrate to HMRC-approved software (QuickBooks, Xero, FreeAgent, Sage) or use an approved bridging tool to connect your spreadsheet to HMRC's systems. Unapproved record-keeping is itself a compliance failure." },
    { wrong: "ChatGPT says: MTD changes when you pay your tax bill",                                                    correct: "Reality: MTD changes REPORTING cadence, not payment dates. The balance payment is still due 31 January following the tax year, with payments on account due 31 January and 31 July. Quarterly updates are informational filings, not tax calculations or payments." },
  ],
  faqs: [
    { question: "Am I mandated under MTD ITSA?",                                                         answer: "You are mandated if your combined gross income from self-employment and property exceeds the threshold at the phase date. Phase 1: over £50,000 from 6 April 2026. Phase 2: over £30,000 from 6 April 2027. Phase 3: over £20,000 from 6 April 2028. The threshold is based on GROSS income (before expenses) aggregated across all sources. PAYE salary and dividends do not count." },
    { question: "What does a quarterly update actually involve?",                                        answer: "A quarterly update is a brief digital submission summarising your income and expenses for the quarter — NOT a mini tax return or tax calculation. You submit it via HMRC-approved software within one month of the end of each quarter. The quarterly updates feed into a final annual declaration (due 31 January) which is the equivalent of your current self-assessment return." },
    { question: "What software do I actually need?",                                                     answer: "HMRC-approved software is mandatory. Popular options: QuickBooks (from £10/month), Xero (from £15/month), FreeAgent (free with some business bank accounts), Sage (from £12/month). If you currently use spreadsheets, you need either approved software or a recognised bridging tool that connects your spreadsheet to HMRC's systems. The HMRC website maintains the current list of approved software." },
    { question: "What are the penalties if I miss a quarterly update?",                                   answer: "Each missed quarterly update triggers £200 initial penalty plus £10 per day up to 90 days = up to £1,100 per missed quarter. Missing all four quarterly updates in a year = up to £4,400 in penalties alone. HMRC also operates a points-based late-submission penalty system — each missed update earns a point, with an additional £200 financial penalty at 4 points. Points reset after 24 months of compliance." },
    { question: "Does MTD change when I pay my tax bill?",                                               answer: "No. MTD changes REPORTING cadence, not payment dates. Balance payment is still due 31 January following the tax year. Payments on account remain due 31 January and 31 July. Quarterly updates are informational filings — they don't create new tax liabilities or payment obligations. What they do is give HMRC (and you) a running view of your tax position during the year." },
    { question: "Does MTD apply to company directors?",                                                  answer: "MTD ITSA applies to self-employment and property income reported through self-assessment. Salary and dividends processed through PAYE or Company Tax Return are NOT in scope. However, a company director who also has personal self-employment income or rental property above the threshold IS in scope for those sources. Directors with rental properties often cross the threshold via rental income alone." },
    { question: "Do I need separate MTD records for multiple properties?",                              answer: "Residential rental properties are combined and reported as one MTD business. Furnished holiday lets are reported as a separate MTD business. Commercial property is not in MTD ITSA scope. If you have a mix of residential + FHL + self-employment, you have multiple MTD businesses each with their own quarterly updates." },
    { question: "What if my accountant handles my tax?",                                                 answer: "Your accountant can submit MTD updates on your behalf, but the underlying records must be kept in HMRC-approved software. Most accountants are charging extra for quarterly submissions on top of annual fees — typical range £50-£150 per quarter per business. Confirm the cost in advance and make sure your software choice is one your accountant uses." },
  ],
  accountantQuestionsH2: "Ask these before 6 April 2026",
  accountantQuestions: [
    { q: "Am I mandated under MTD ITSA — and from which April?",                                                                                        why: "Your accountant should confirm your gross income figure and which phase you fall into. The threshold is gross income, not profit. For £30-50k earners especially, the exact figure matters." },
    { q: "Is my current software MTD-compatible — or do I need to switch or add bridging software?",                                                     why: "Spreadsheets alone do not meet MTD. You either migrate to QuickBooks, Xero, FreeAgent, or Sage, OR add a recognised bridging tool. Getting this wrong triggers penalties." },
    { q: "Will you handle my quarterly updates — and what will that cost in addition to annual fees?",                                                    why: "Most accountants charge £50-£150 per quarter per business for MTD submissions. Four quarters × your number of businesses (self-employment + rental counts separately) = meaningful recurring cost. Negotiate and contract before mandate." },
    { q: "Do I need separate quarterly submissions for each rental property, or are they combined?",                                                      why: "Residential rentals combine into one MTD business. Furnished holiday lets are separate. Commercial property is out of scope. If your portfolio is mixed, you have multiple MTD businesses with separate quarterly updates." },
    { q: "What happens to my payments on account and 31 January tax bill under MTD?",                                                                    why: "Payment dates are unchanged. But quarterly updates may reveal your tax position earlier than annual review — useful for cashflow planning and avoiding the 31 January surprise." },
  ],
  crosslink: { title: "Also paying dividends from your company?", body: "Company directors taking dividends need to check their dividend tax position separately. The dividend trap catches many directors who think they are efficiently structured.", url: "/uk/check/dividend-trap", label: "Check your dividend position →" },
  lawBarSummary: "MTD ITSA Phase 1 live from 6 April 2026 for gross income over £50,000 (combined self-employment + property, before expenses). Phase 2 from 6 April 2027 (£30k threshold). Phase 3 from 6 April 2028 (£20k threshold). Mandated taxpayers use HMRC-approved software for 4 quarterly updates + 1 final declaration per year. Penalty regime: £200 initial + £10/day up to 90 days per missed quarter = up to £1,100 per quarter, up to £4,400/year. Under Finance Act 2021.",
  lawBarBadges: ["HMRC", "Finance Act 2021", "MTD ITSA", "£1,100 per quarter", "£4,400/year max", "Machine-readable JSON"],
  sources: [
    { title: "HMRC — Making Tax Digital for Income Tax",                                                  url: "https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax" },
    { title: "HMRC — MTD ITSA overview and timeline",                                                     url: "https://www.gov.uk/government/publications/making-tax-digital-for-income-tax-self-assessment-overview" },
    { title: "HMRC — Penalties for late submission under MTD",                                            url: "https://www.gov.uk/guidance/penalty-points-and-penalties-if-you-submit-your-vat-return-late" },
    { title: "Machine-readable JSON rules",                                                                url: "/api/rules/mtd-scorecard" },
  ],
  files: [
    { num: "01", slug: "mtd-01", name: "Your MTD Mandation Verdict", desc: "Which MTD phase applies to you, the exact mandate date, and what your gross income position means.", tier: 1, content: `<h2>Your MTD Mandation Position</h2><div class="action-box"><h3>The Binary Test</h3><p>Gross income from self-employment + property > threshold at phase date = MANDATED</p></div><table><tr><th>Phase</th><th>Mandate date</th><th>Threshold</th></tr><tr><td>Phase 1</td><td>6 April 2026</td><td>£50,000</td></tr><tr><td>Phase 2</td><td>6 April 2027</td><td>£30,000</td></tr><tr><td>Phase 3</td><td>6 April 2028</td><td>£20,000</td></tr></table><h3>What counts toward the threshold</h3><ul><li>✓ Self-employment gross income (before expenses)</li><li>✓ Property gross rental income (residential + FHL + commercial)</li><li>✗ PAYE employment income</li><li>✗ Dividends</li><li>✗ Pension income</li></ul><p>Source: <a href="https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax">HMRC — MTD ITSA</a> · Finance Act 2021</p>` },
    { num: "02", slug: "mtd-02", name: "MTD Software Migration Path", desc: "HMRC-approved software ranked for your situation, migration sequencing, and bridging options.", tier: 1, content: `<h2>HMRC-Approved MTD Software — Decision Framework</h2><table><tr><th>Software</th><th>Cost</th><th>Best for</th></tr><tr><td>QuickBooks</td><td>From £10/mo</td><td>Self-employed, small landlords</td></tr><tr><td>Xero</td><td>From £15/mo</td><td>Multi-property, accountant-shared</td></tr><tr><td>FreeAgent</td><td>Free–£19/mo</td><td>Freelancers, contractors</td></tr><tr><td>Sage</td><td>From £12/mo</td><td>Established businesses with payroll</td></tr><tr><td>Bridging software</td><td>£5-15/mo add-on</td><td>Keep existing spreadsheets</td></tr></table><div class="warning-box"><strong>Spreadsheets alone:</strong> Do not qualify under any scenario. Must be bridged with approved bridging software OR replaced.</div><h3>Migration Sequencing</h3><ol><li>6+ months before mandate: choose software, set up chart of accounts</li><li>3+ months before: run parallel with old system for one month</li><li>1 month before: switch fully, cut off old system</li><li>Post-mandate: first quarterly dry-run under your accountant's supervision</li></ol>` },
    { num: "03", slug: "mtd-03", name: "Your Quarterly Submission Calendar", desc: "Exact dates for all 4 quarterly updates + final declaration, with penalty windows.", tier: 1, content: `<h2>Your MTD Submission Calendar</h2><table><tr><th>Quarter</th><th>Period</th><th>Due Date</th><th>Late after</th></tr><tr><td>Q1</td><td>6 April – 5 July</td><td>5 August</td><td>Penalty point + fee clock starts</td></tr><tr><td>Q2</td><td>6 July – 5 October</td><td>5 November</td><td>Same</td></tr><tr><td>Q3</td><td>6 October – 5 January</td><td>5 February</td><td>Same</td></tr><tr><td>Q4</td><td>6 January – 5 April</td><td>5 May</td><td>Same</td></tr><tr><td>Final declaration</td><td>Full tax year</td><td>31 January</td><td>Standard SA penalty</td></tr></table><h3>Penalty Accumulation</h3><p>Each missed quarterly update: £200 initial + £10/day × up to 90 days = up to £1,100 per quarter. Missing all 4 in a year = up to £4,400 annually. Plus points-based system (4 points = £200 additional penalty).</p><div class="info-box"><strong>Calendar discipline:</strong> Set recurring reminders 2 weeks before each quarterly deadline. First-year breaches usually come from forgotten deadlines, not incapability.</div>` },
    { num: "04", slug: "mtd-04", name: "Accountant Brief — MTD Mandation", desc: "5 questions to ask your accountant BEFORE mandate day.", tier: 1, content: `<div class="info-box">Forward to your accountant or take to your next meeting. These are the questions that determine first-year compliance vs penalty exposure.</div><h2>Ask Your Accountant</h2><div class="action-box"><h3>Question 1</h3><p>"Am I mandated under MTD ITSA — and from which April?"</p></div><h3>Question 2</h3><p>"Is my current software MTD-compatible — or do I need to switch or add bridging software?"</p><h3>Question 3</h3><p>"Will you handle my quarterly updates — and what will that cost in addition to annual fees?"</p><h3>Question 4</h3><p>"Do I need separate quarterly submissions for each rental property, or are they combined?"</p><h3>Question 5</h3><p>"What happens to my payments on account and 31 January tax bill under MTD?"</p>` },
    { num: "05", slug: "mtd-05", name: "MTD Penalty Risk Assessment", desc: "What HMRC can charge and how to stay out of the penalty path.", tier: 1, content: `<h2>MTD Penalty Regime — Full Calculation</h2><h3>Per-Quarter Penalty</h3><p>£200 initial fixed penalty<br>PLUS £10 per day up to 90 days<br>= up to £1,100 per missed quarterly update</p><h3>Annual Maximum</h3><p>£1,100 per quarter × 4 quarters = up to £4,400/year in quarterly penalties alone.</p><h3>Points System</h3><table><tr><th>Points</th><th>Consequence</th></tr><tr><td>1–3 points</td><td>Warning — no financial penalty yet</td></tr><tr><td>4 points</td><td>£200 additional financial penalty</td></tr><tr><td>5+ points</td><td>£200 per additional late update</td></tr></table><h3>Points reset</h3><p>Requires 24 months of full compliance from the point threshold date. In practice, one bad year locks you into the penalty track for two years.</p><div class="warning-box"><strong>Late annual declaration:</strong> Same penalty regime as current self-assessment — £100 immediate, rising to £900+ after 12 months. ON TOP of quarterly penalties.</div>` },
    { num: "06", slug: "mtd-06", name: "Multi-Property MTD Execution Guide", desc: "How to handle MTD if you have multiple rental properties and need separate quarterly submissions.", tier: 2, content: `<h2>Multi-Property MTD Execution</h2><p>HMRC treats property types separately for MTD reporting purposes.</p><table><tr><th>Property type</th><th>MTD treatment</th></tr><tr><td>Residential rentals</td><td>Combined as ONE MTD business</td></tr><tr><td>Furnished holiday lets (UK)</td><td>Separate MTD business</td></tr><tr><td>Furnished holiday lets (EEA)</td><td>Separate MTD business</td></tr><tr><td>Commercial property</td><td>NOT in MTD ITSA scope</td></tr><tr><td>Self-employment</td><td>Separate MTD business per trade</td></tr></table><h3>Impact</h3><p>If you have residential rentals + FHL + self-employment = 3 MTD businesses = 12 quarterly updates + 3 final declarations per year.</p><h3>Software Strategy</h3><ol><li>Single software package with multi-business support (Xero does this cleanly)</li><li>Separate chart of accounts per MTD business</li><li>Accountant's quarterly fee applies per business — budget accordingly</li><li>Set up recurring calendar events 2 weeks before each deadline</li></ol>` },
    { num: "07", slug: "mtd-07", name: "Self-Employed + Landlord Combined MTD Plan", desc: "Managing MTD across two income streams — self-employment and property — in a single system.", tier: 2, content: `<h2>Combined Income MTD Strategy</h2><p>If you have both self-employment and rental income, you have two separate MTD businesses each requiring quarterly updates.</p><div class="action-box"><h3>Three Key Decisions</h3><p>1. One software for both businesses or separate systems?</p><p>2. Combine with accountant's help or handle quarterly updates yourself?</p><p>3. Set up automatic bank feeds to reduce quarterly admin burden?</p></div><h3>Recommendation</h3><p>Single software (Xero or QuickBooks) with multi-business support is cleaner than two separate systems. Bank feeds from business banking reduce quarterly data entry from hours to minutes. Accountant handles final declaration; you handle quarterlies once the habit forms.</p><h3>First-Year Plan</h3><ol><li>Q1: Run first quarter under accountant supervision — they submit, you observe</li><li>Q2: Submit with accountant review — you draft, they check</li><li>Q3 onwards: You submit, accountant available for questions</li></ol>` },
    { num: "08", slug: "mtd-08", name: "MTD Transition Checklist", desc: "Step-by-step compliance checklist from now through mandate date.", tier: 2, content: `<h2>MTD Transition Checklist</h2><h3>6+ Months Before Mandate</h3><ul class="checklist"><li>Confirm gross income total and mandate phase</li><li>Choose HMRC-approved software (see file 02 for ranking)</li><li>Brief accountant on software choice</li><li>Negotiate quarterly submission fees</li></ul><h3>3 Months Before Mandate</h3><ul class="checklist"><li>Set up software, chart of accounts, bank feeds</li><li>Migrate opening balances from previous system</li><li>Run parallel with old system for one month</li><li>Schedule calendar reminders for all 4 quarterly deadlines</li></ul><h3>1 Month Before Mandate</h3><ul class="checklist"><li>Switch fully to new system, archive old</li><li>Register for MTD ITSA with HMRC via online services account</li><li>Test a dry-run quarterly submission in approved software</li></ul><h3>First Year Under Mandate</h3><ul class="checklist"><li>Q1 submission: under accountant supervision</li><li>Build quarterly book-keeping habit (weekly or fortnightly, not month-end)</li><li>Complete first annual final declaration by 31 January following tax year end</li><li>Verify all quarterly submissions filed — check HMRC online services account</li></ul>` },
  ],
  calendarTitle: "MTD ITSA — Key Dates",
  tier1Calendar: [
    { uid: "mtd-q1", summary: "MTD — Q1 Quarterly Update Due (5 Aug)", description: "First MTD quarterly update covering 6 April to 5 July. Penalty clock starts if late.", date: "20260805" },
    { uid: "mtd-q2", summary: "MTD — Q2 Quarterly Update Due (5 Nov)", description: "Second quarterly update covering 6 July to 5 October.", date: "20261105" },
    { uid: "mtd-q3", summary: "MTD — Q3 Quarterly Update Due (5 Feb)", description: "Third quarterly update covering 6 October to 5 January.", date: "20270205" },
    { uid: "mtd-final", summary: "MTD — Annual Final Declaration Due", description: "Annual final declaration — equivalent to current self-assessment return.", date: "20270131" },
  ],
  tier2Calendar: [
    { uid: "mtd-software", summary: "MTD — Choose approved software", description: "Pick QuickBooks, Xero, FreeAgent, or Sage. Set up chart of accounts.", date: "relative:+7days" },
    { uid: "mtd-parallel", summary: "MTD — Parallel run with old system", description: "One month of parallel running before cutover.", date: "relative:+30days" },
    { uid: "mtd-register", summary: "MTD — Register with HMRC", description: "Register for MTD ITSA via HMRC online services.", date: "relative:+60days" },
    { uid: "mtd-q1", summary: "MTD — Q1 Quarterly Update Due", description: "First quarterly update — 5 August.", date: "20260805" },
    { uid: "mtd-final", summary: "MTD — Annual Final Declaration", description: "31 January 2027.", date: "20270131" },
  ],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax"],
  sidebarNumbers: [{ label: "Phase 1 threshold", value: "£50,000 (Apr 2026)" }, { label: "Submissions per year", value: "1 → 5" }, { label: "Per-quarter penalty max", value: "£1,100" }, { label: "Annual penalty max", value: "£4,400" }],
  sidebarMathsTitle: "What counts toward the MTD threshold",
  sidebarMathsIncludes: [
    "Self-employment gross income (before expenses)",
    "Property gross rental income (residential + FHL)",
    "All sources combined — a single £20k threshold",
  ],
  sidebarMathsExcludes: [
    "NOT PAYE employment income",
    "NOT dividends",
    "NOT pension income",
    "NOT commercial property rental (out of MTD ITSA scope)",
  ],
  sidebarMathsNote: "Source: HMRC — MTD ITSA · Finance Act 2021 · Confirmed April 2026",
  howToSteps: [
    { position: 1, name: "Enter your gross income band", text: "Combined self-employment + property gross income — before expenses. Determines your mandate wave." },
    { position: 2, name: "Identify your income sources", text: "Self-employed, landlord, both, or director-with-rental. Affects multi-business reporting." },
    { position: 3, name: "Check your record-keeping", text: "HMRC-approved software required. Spreadsheets alone do not qualify." },
    { position: 4, name: "Confirm quarterly awareness", text: "Most taxpayers don't know 1 annual return becomes 5 submissions. This is the awareness gap that drives first-year breaches." },
  ],
  successPromptFields: [
    { key: "income_band",          label: "Income band",                       defaultVal: "30k_to_50k" },
    { key: "income_source",        label: "Income source",                     defaultVal: "both" },
    { key: "record_keeping",       label: "Record keeping method",              defaultVal: "spreadsheets" },
    { key: "quarterly_aware",      label: "Aware of quarterly requirement",    defaultVal: "false" },
    { key: "mandated",             label: "Mandated under MTD",                defaultVal: "true" },
    { key: "mandate_date",         label: "Exact mandate date",                defaultVal: "6 April 2027" },
    { key: "mandate_wave",         label: "Mandate wave (1/2/3/null)",         defaultVal: "2" },
    { key: "software_gap",         label: "Software gap detected",             defaultVal: "true" },
    { key: "status",               label: "Verdict status",                    defaultVal: "YOU ARE IN NEXT WAVE" },
    { key: "tier",                 label: "Product tier purchased",            defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "mandationStatus",
    "exactMandateDate",
    "mandateWaveAnalysis",
    "incomeSourceImpact",
    "softwareGapAssessment",
    "awarenessGapAssessment",
    "quarterlyCalendar",
    "penaltyExposure",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "mandationStatus",
    "exactMandateDate",
    "mandateWaveAnalysis",
    "incomeSourceImpact",
    "softwareGapAssessment",
    "awarenessGapAssessment",
    "quarterlyCalendar",
    "penaltyExposure",
    "softwareMigrationPath",
    "multiPropertyReportingPlan",
    "accountantCoordinationBrief",
    "firstYearDryRunSchedule",
    "ongoingComplianceChecklist",
  ],
};
