import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "allowance-sniper", name: "60% Tax Trap Engine", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/allowance-sniper", url: "https://taxchecknow.com/uk/check/allowance-sniper", apiRoute: "/api/rules/allowance-sniper",
  authority: "HMRC", authorityUrl: "https://www.gov.uk/government/organisations/hm-revenue-customs", legalAnchor: "Income Tax Act 2007 section 35 — Personal allowance taper above £100,000", legislation: "Income Tax Act 2007 section 35 — personal allowance reduced by £1 for every £2 of adjusted net income above £100,000 · Personal allowance £12,570 for tax year 2025-26 · Allowance fully withdrawn at £125,140 · Higher rate income tax 40% on income between £50,270 and £125,140 · Additional rate income tax 45% above £125,140 · Pension contributions and salary sacrifice reduce adjusted net income for taper purposes",
  lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Allowance Audit Pack", tagline: "Your exact 60% trap exposure and the pension contribution that escapes it", value: "Your exact 60% trap exposure calculation, pension contribution needed to restore the full allowance, tax saving projection, and 5 accountant questions — built for your income band and current pension setup.", cta: "Get My Allowance Audit — £67 →", productKey: "uk_67_allowance_sniper", envVar: "STRIPE_UK_ALLOWANCE_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your 60% Tax Escape Plan", tagline: "Full escape plan: pension optimisation, salary sacrifice, bonus timing — written for your situation", value: "Full escape strategy: pension contribution sequencing, salary sacrifice vs personal contribution comparison, bonus timing to avoid the £125,140 cliff, multi-year pension planning, and written accountant coordination brief.", cta: "Get My 60% Escape Plan — £147 →", productKey: "uk_147_allowance_sniper", envVar: "STRIPE_UK_ALLOWANCE_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-04-05T23:59:59.000+01:00", display: "5 April 2027", short: "5 Apr 2027", description: "5 April 2027 — UK tax year end for 2026-27. Pension contributions must be made before year end to affect adjusted net income.", urgencyLabel: "YEAR END — ALLOWANCE LOST IF MISSED", countdownLabel: "Countdown to 5 April 2027 UK tax year end" },
  h1: "UK Earners Between £100,000 and £125,140 Face a 60% Tax Rate — Here Is Exactly What It Is Costing You",
  metaTitle: "UK 60% Tax Trap 2026: Exact Exposure and Pension Escape | TaxCheckNow",
  metaDescription: "UK earners between £100,000 and £125,140 face a 60% effective marginal tax rate because the personal allowance is withdrawn at £1 for every £2 earned. A pension contribution can restore it entirely. Run your exact trap audit in 2 minutes.",
  canonical: "https://taxchecknow.com/uk/check/allowance-sniper",
  answerHeadline: "The 60% trap is arithmetic, not opinion — and it is avoidable",
  answerBody: [
    "In the UK, the personal allowance of £12,570 is withdrawn at £100,000 at a rate of £1 for every £2 earned. By £125,140 it is gone entirely. The effect is a 60% effective marginal tax rate — 40% income tax plus the 20% value of the allowance being removed. This is not a penalty. It is arithmetic. And it is avoidable.",
    "The fix is a pension contribution or salary sacrifice arrangement that reduces adjusted net income below £100,000. Every £2 contributed restores £1 of personal allowance. A £15,000 contribution at £115,000 income restores the full allowance and saves approximately £6,000 in tax — making the net cost of the contribution £9,000 not £15,000.",
    "This has been the rule since 2010. HMRC does not flag it. Your payslip does not show it. Most people in this band discover it only when they see their tax return — by which point the year is gone.",
  ],
  answerSource: "Source: HMRC — Personal Allowances · Income Tax Act 2007 section 35 · Confirmed April 2026",
  mistakesHeadline: "What most people (and most online tax commentary) get wrong about the 60% trap",
  mistakes: [
    "I am a 40% taxpayer so I pay 40% on everything over £50,270 — wrong. Between £100,000 and £125,140 you pay a 60% effective rate because your personal allowance is simultaneously withdrawn. HMRC does not put this on your tax code or payslip — it only shows up on your self-assessment return.",
    "Earning more always means more take-home pay — wrong. Between £100,000 and £125,140 earning an extra £1,000 costs you £600 in tax. You keep £400. In some National Insurance combinations (student loan, child benefit clawback) the effective marginal rate can be even worse.",
    "Pension contributions just defer tax — wrong. A contribution that reduces adjusted net income below £100,000 restores your personal allowance, saving up to £5,028 in tax that would never have been paid at all — not deferred, eliminated. The allowance is annual use-it-or-lose-it.",
    "My employer handles this — wrong. Employers deduct PAYE but do not model personal allowance withdrawal across your total income (employment + self-employment + rental). The 60% trap is only visible when all income sources are combined on your self-assessment return. Most people in this band find out a year late.",
  ],
  chainVisual: { label: "The 60% trap chain — how the arithmetic works", broken: "Earn £1 over £100,000 → pay 40p income tax + lose 50p of allowance (worth 20p in future tax) → 60p gone  ❌  60% effective rate", fixed: "Pension contribution of £Y brings adjusted net income to £100,000 → full £12,570 allowance restored → up to £5,028 tax saved  ✔  Allowance preserved" },
  brackets: [
    { label: "Under £100,000 — full personal allowance intact",           value: 1, status: "clear" },
    { label: "£100,000–£110,000 — early trap, allowance tapering",          value: 2, status: "approaching" },
    { label: "£110,000–£120,000 — deep trap, 60% effective rate",           value: 3, status: "trap" },
    { label: "£120,000–£125,140 — edge trap, allowance nearly gone",        value: 4, status: "deep_trap" },
    { label: "Over £125,140 — past trap, allowance fully withdrawn",        value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "incomeBand", label: "What is your total income this year (employment + self-employment + rental)?", subLabel: "The 60% trap applies to adjusted net income between £100,000 and £125,140 — total income matters, not just salary.", options: [{ label: "Under £100,000", value: "under_100k" }, { label: "£100,000–£110,000", value: "100k_110k" }, { label: "£110,000–£120,000", value: "110k_120k" }, { label: "£120,000–£125,140", value: "120k_125k" }, { label: "Over £125,140", value: "over_125k" }], default: "110k_120k" },
    { type: "buttonGroup", stateKey: "pensionContributions", label: "How much are you contributing to pension this tax year (including employer contributions)?", subLabel: "Pension contributions reduce adjusted net income — every £2 contributed restores £1 of personal allowance.", options: [{ label: "None", value: "none" }, { label: "Under £5,000", value: "under_5k" }, { label: "£5,000–£10,000", value: "5k_10k" }, { label: "Over £10,000", value: "over_10k" }], default: "none" },
    { type: "buttonGroup", stateKey: "salarySacrifice", label: "Does your employer offer salary sacrifice for pension contributions?", subLabel: "Salary sacrifice saves NI as well as income tax — more efficient than personal pension contributions at this income level.", options: [{ label: "Yes — available", value: "yes" }, { label: "No — not offered", value: "no" }, { label: "Not sure / self-employed", value: "not_sure" }], default: "no" },
  ],
  tierAlgorithm: { description: "In trap (£100k-£125,140) or past trap (over £125,140) AND not already escaping via pension → tier2 (escape plan). Under £100k or fully covered by current pension → tier1 (audit).", tier2Conditions: ["incomeBand === '110k_120k'", "incomeBand === '120k_125k'", "incomeBand === 'over_125k'", "incomeBand === '100k_110k' && salarySacrifice !== 'yes'"], tier2Flags: [] },
  calculatorRuleBox: { label: "The 60% trap rule — HMRC arithmetic", body: "Personal allowance for 2025-26: £12,570. Tapers at £100,000 adjusted net income — £1 withdrawn for every £2 earned above the threshold. Fully gone at £125,140. Effective marginal rate between £100,000 and £125,140 is 60% — composed of 40% higher-rate income tax plus the 20% cost of allowance withdrawal. Pension contributions and salary sacrifice reduce adjusted net income, restoring the allowance." },
  calculatorClarification: { label: "Adjusted net income, not gross salary", body: "The taper is based on ADJUSTED NET INCOME: total income from all sources (employment, self-employment, rental, savings, dividends) minus certain deductions including gross pension contributions and Gift Aid. A £115,000 salary earner contributing £15,000 to pension has adjusted net income of £100,000 and keeps the full allowance." },
  countdownLabel: "Countdown to 5 April 2027 UK tax year end",
  countdownStats: [
    { label: "Personal allowance 2025-26",   value: "£12,570",       sub: "Withdrawn at £100k threshold" },
    { label: "Withdrawal rate",              value: "£1 per £2",     sub: "For every £2 earned over £100k" },
    { label: "Effective rate in trap",       value: "60%",           sub: "40% tax + 20% allowance cost",   red: true },
    { label: "Kept on last £10k earned",     value: "£4,000",        sub: "60p lost to tax on every £1",    red: true },
  ],
  persona: {
    name: "Daniel",
    age: 41,
    occupation: "Senior product director, London fintech",
    location: "Clapham, London",
    family: "Wife Anita, two kids (ages 8 and 11)",
    financialSnapshot: "£115,000 base salary, £10,000 annual bonus, small rental flat in Manchester generating £8,400 gross per year. Pays 4% employer-matched pension (£4,600). Spreadsheet budget. No IFA.",
    painPoint: "Daniel bumped his salary from £95k to £115k last year after a promotion. He assumed more salary meant more take-home — he did not realise his £15k above £100k was being taxed at 60% effective rate, and that the rental income was pushing his adjusted net income even higher.",
    discovery: "Daniel saw his self-assessment return in January — tax bill was about £5,000 higher than he budgeted for. Googled why. Found out about the 60% trap.",
    voice: "Analytical. Wants specific numbers. Has the discipline to execute on a plan if the plan is concrete.",
  },
  story: {
    hook: "Daniel's promotion letter was framed as a £20,000 pay rise. His payslip the following January showed otherwise.",
    setup: [
      "Daniel had been promoted in early 2025. Salary moved from £95,000 to £115,000. Small rental flat in Manchester added another £8,400 gross to his income. His wife worked part-time. Two kids. Mortgage. Clapham. The pay rise was supposed to ease the family's cash flow.",
      "It did not. The monthly take-home did go up, but not by as much as he expected. Daniel assumed it was tax at 40% on the extra — so he'd keep roughly 60% of the raise. That was wrong.",
      "In January he filed his self-assessment. Total adjusted net income: about £123,000 after including the rental. Personal allowance: almost fully withdrawn. Tax bill: £5,000 higher than his back-of-envelope estimate. He Googled why and found the phrase '60% tax trap' for the first time.",
    ],
    revelation: "Daniel ran the calculator. Adjusted net income £123,000. Allowance lost: £11,500 (almost all of the £12,570). Tax on the £23,000 of trap-band income: £13,800 at 60% effective rate. Pension contribution needed to escape entirely: £23,000. Tax saving from that contribution: roughly £9,200 (40% pension relief) plus another £4,600 from restored allowance. Net cost of contribution: about £9,200 for something worth £23,000 in his pension and about £13,800 in recovered tax.",
    resolution: "Daniel booked an IFA meeting the next week. Plan: increase salary sacrifice from 4% to the maximum his employer allowed (20%, reducing gross to £92,000), fund the gap with a personal SIPP contribution for the remaining £8,000. Bonus timing shifted to ensure it didn't push him over £125,140. Across the full year his 60% trap exposure went to near zero, with the added benefit that his pension pot now grew by £23,000/year that would otherwise have been taxed at 60%.",
  },
  geoBlockTitle: "AI extraction block — UK 60% personal allowance taper",
  geoBlockH2: "UK 60% effective marginal tax rate and personal allowance taper — confirmed April 2026",
  geoBodyParagraph: "UK earners between £100,000 and £125,140 face a 60% effective marginal tax rate because the personal allowance of £12,570 is withdrawn at a rate of £1 for every £2 of income above £100,000. This is established under Income Tax Act 2007 section 35. The allowance is fully withdrawn at £125,140. The effective rate arises from the combination of 40% income tax on earnings in the higher rate band plus the effective 20% tax cost of losing the personal allowance. A taxpayer earning £110,000 pays approximately £6,000 tax on the £10,000 above the threshold — keeping only £4,000. The mechanism can be reversed by making pension contributions or salary sacrifice arrangements that reduce adjusted net income below £100,000, restoring the full personal allowance and saving up to £5,028 in tax.",
  geoFormula: "Personal allowance reduction = max(0, (Adjusted Net Income − 100,000) / 2), capped at £12,570. Effective marginal rate in £100k-£125,140 band = 60% (40% income tax + 20% allowance withdrawal cost). Above £125,140: 45% additional rate, allowance fully lost. Pension contribution required to escape = Adjusted Net Income − 100,000. Tax saving approximately 60% of contribution amount when fully restoring allowance.",
  geoFacts: [
    { label: "Personal allowance 2025-26",              value: "£12,570" },
    { label: "Allowance taper start",                    value: "£100,000 adjusted net income" },
    { label: "Withdrawal rate",                          value: "£1 for every £2 earned above £100,000" },
    { label: "Allowance fully withdrawn at",              value: "£125,140" },
    { label: "Effective rate in trap band",              value: "60% marginal" },
    { label: "Higher rate income tax",                    value: "40% between £50,270 and £125,140" },
    { label: "Additional rate above £125,140",           value: "45%" },
    { label: "Legal anchor",                              value: "Income Tax Act 2007 section 35" },
    { label: "Taper introduced",                          value: "April 2010" },
    { label: "Reversible via",                            value: "Pension contributions or salary sacrifice" },
  ],
  workedExamplesH2: "Four UK earners — how the 60% trap affects them",
  workedExamplesColumns: ["Earner", "Income position", "Trap exposure", "Escape route"],
  workedExamples: [
    { name: "Senior PM, £105k salary",                    setup: "Just crossed threshold, no rental, standard pension",      income: "Adjusted net income £105k",    status: "£5K TRAP — ~£3K TAX" },
    { name: "Director, £118k salary + bonus",              setup: "£115k base + £10k bonus, 4% pension",                      income: "Adjusted net income £120k",    status: "£20K TRAP — ~£12K TAX" },
    { name: "Contractor, £135k take-home",                 setup: "Limited company, £95k salary + £40k dividends",             income: "Adjusted net income £135k",    status: "PAST TRAP — ALLOWANCE GONE" },
    { name: "Consultant, £98k + £15k rental",              setup: "Employed + rental flat in Leeds",                           income: "Adjusted net income £113k",    status: "£13K TRAP — HIDDEN BY RENTAL" },
  ],
  comparisonH2: "The 60% trap vs not in trap — what £15,000 of extra income actually costs",
  comparisonColumns: ["Scenario", "Marginal rate", "Tax on £15k", "Keep from £15k"],
  comparisonRows: [
    { position: "Basic rate taxpayer (£30k income)",        metric1: "20%",   metric2: "£3,000",   bestMove: "£12,000" },
    { position: "Higher rate taxpayer (£75k income)",       metric1: "40%",   metric2: "£6,000",   bestMove: "£9,000" },
    { position: "60% trap taxpayer (£115k income)",         metric1: "60%",   metric2: "£9,000",   bestMove: "£6,000" },
    { position: "Additional rate taxpayer (£150k income)",  metric1: "45%",   metric2: "£6,750",   bestMove: "£8,250" },
  ],
  toolsH2: "Tools for escaping the 60% trap",
  toolsColumns: ["Tool", "What it does", "Best for"],
  toolsRows: [
    { tool: "Employer salary sacrifice",                  effect: "Reduces gross salary → reduces adjusted net income AND saves NI",  note: "Best lever if employer offers it" },
    { tool: "Personal SIPP contribution",                 effect: "Reduces adjusted net income, gets 40% pension tax relief",           note: "Good fallback if no salary sacrifice" },
    { tool: "Bonus timing / deferral",                    effect: "Smooths income across tax years to stay under £100k",                note: "Employer-dependent option" },
    { tool: "Gift Aid donations",                         effect: "Reduces adjusted net income by gross Gift Aid value",                note: "Works but smaller scale" },
    { tool: "Spousal income shifting",                    effect: "Transfer investments / property to lower-earning spouse",             note: "Structural move — needs legal setup" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: UK income tax rates are 20%, 40%, and 45% — there is no 60% rate",                  correct: "Reality: Between £100,000 and £125,140 the EFFECTIVE marginal rate is 60% — composed of 40% higher rate income tax PLUS the 20% cost of personal allowance withdrawal (£1 withdrawn per £2 earned). It's not a headline rate — it's the real arithmetic of the taper under Income Tax Act 2007 s35." },
    { wrong: "ChatGPT says: Earning more always means more take-home pay",                                       correct: "Reality: Between £100,000 and £125,140 earning an extra £1 gives you only 40p. At some NI + student loan + child benefit clawback combinations, the effective marginal rate can exceed 70%. A £5,000 bonus in this band nets approximately £2,000 after all deductions." },
    { wrong: "ChatGPT says: Pension contributions just defer tax — you pay it later",                            correct: "Reality: A pension contribution that restores your personal allowance doesn't just defer the allowance withdrawal cost — it ELIMINATES it. The £12,570 that would never have been received tax-free gets restored. This saves up to £5,028 in tax that would otherwise never come back. That's in addition to the ordinary pension tax relief on the contribution itself." },
    { wrong: "ChatGPT says: My employer handles my tax so this is not my problem",                               correct: "Reality: PAYE handles income tax on employment income based on your tax code. It does NOT model your TOTAL adjusted net income including rental, self-employment, dividends, or side-consulting. The 60% trap only surfaces on self-assessment — by which time the allowance is already lost for that year and cannot be retrospectively restored." },
  ],
  faqs: [
    { question: "What is the UK 60% tax trap?",                                                              answer: "The 60% tax trap is the effective marginal tax rate faced by UK earners with adjusted net income between £100,000 and £125,140. The personal allowance of £12,570 is withdrawn at £1 for every £2 earned above £100,000 — fully gone at £125,140. Combined with 40% higher-rate income tax, the effective marginal rate on earnings in this band is 60%." },
    { question: "How does the personal allowance taper work?",                                               answer: "For every £2 of adjusted net income above £100,000, £1 of personal allowance is withdrawn. At £100,000 you have the full £12,570 allowance. At £110,000 you have £7,570. At £125,140 you have zero. The taper is automatic under Income Tax Act 2007 section 35. Adjusted net income includes employment, self-employment, rental, savings, and dividends — minus deductions like gross pension contributions and Gift Aid." },
    { question: "Can pension contributions really save me 60% in tax?",                                      answer: "Yes. A pension contribution that brings adjusted net income below £100,000 achieves two things simultaneously: (1) the contribution itself gets higher-rate pension relief (40% for higher-rate taxpayers), and (2) the personal allowance is restored, saving the tax that would have been paid on that £12,570 at the higher rate. Combined effective saving can approach 60% of the contribution amount." },
    { question: "What is salary sacrifice and why is it better than personal pension contributions?",          answer: "Salary sacrifice is an employer-facilitated arrangement where part of your salary is redirected to pension BEFORE tax or NI is deducted. Unlike personal pension contributions (which save only income tax), salary sacrifice also saves employee NI (8-13% depending on band) and employer NI (typically 13.8% — often reinvested into the pension). Combined saving on a £15,000 salary sacrifice at this income level can exceed 60% of the contribution amount." },
    { question: "What is adjusted net income?",                                                              answer: "Adjusted net income is the income figure used to calculate the personal allowance taper. It includes all taxable income from employment, self-employment, rental, savings, and dividends. It is REDUCED by gross pension contributions (including employer and personal), Gift Aid donations (grossed up), and certain other reliefs. It is NOT reduced by ordinary deductible expenses or capital losses. HMRC's calculator on gov.uk provides the exact definition." },
    { question: "Does the 60% trap apply if I receive dividends instead of salary?",                         answer: "Yes, in effect. Dividend income is subject to its own dividend tax rates (8.75% basic, 33.75% higher, 39.35% additional rate) but dividends still count toward adjusted net income for personal allowance taper purposes. Company directors taking £95k salary + £40k dividends can easily cross £100k adjusted net income and lose allowance — even though their marginal tax on the dividends themselves is 33.75%." },
    { question: "What about the child benefit tax charge?",                                                  answer: "The High Income Child Benefit Charge (HICBC) is a separate clawback that starts at £60,000 and fully claws back child benefit at £80,000 (thresholds changed in April 2024). This creates an additional effective tax rate stack — in the £60k-£80k band you can face a combined 50%+ effective rate depending on number of children. Above £100k you stack the 60% allowance taper on top. Can mean effective rates above 65% for families with multiple children." },
    { question: "Is there any way HMRC shows this on my payslip or tax code?",                               answer: "No, not directly. The personal allowance taper is applied at self-assessment or via adjusted tax code if HMRC has income projection data. Most taxpayers in the £100k-£125k band discover the 60% trap only when they file their tax return — often nine to twelve months after the year ends. By then the allowance for that year is permanently lost and cannot be retrospectively restored." },
  ],
  accountantQuestionsH2: "Ask these before 5 April 2027",
  accountantQuestions: [
    { q: "What is my projected adjusted net income for this tax year — including employment, self-employment, rental, savings, and dividends?",                                                  why: "Your accountant should have a forward projection, not just last year's number. Bonuses, side-income growth, and rental yield changes can push you into the trap mid-year." },
    { q: "Given that projection, what pension contribution would bring me to £100,000 exactly — and what is the combined tax saving?",                                                           why: "The answer should be specific: a pound figure, split between pension tax relief (40%) and allowance restoration (~£5,028 max), giving a total saving. Vague answers mean they haven't run the maths." },
    { q: "Is salary sacrifice available through my employer, and how does it compare to a personal SIPP contribution for me specifically?",                                                      why: "Salary sacrifice adds NI savings on top of income tax relief. Personal SIPP doesn't. On £15k at £115k income, salary sacrifice can save £1,500-£2,000 more than an equivalent personal contribution." },
    { q: "How should I time bonuses or large payments to avoid crossing £125,140 (where the allowance is fully lost)?",                                                                          why: "Above £125,140 marginal rate drops to 45% but you've fully lost the £12,570 allowance — worse overall. Bonus timing or deferral can keep you in the 60% trap band (where escape is cheaper) instead of crossing into additional rate territory." },
    { q: "What should I do before 5 April to maximise allowance restoration for this tax year — and how early should I act next year to avoid last-minute panic?",                                 why: "The allowance is annual use-it-or-lose-it. Retrospective pension contributions after year-end cannot restore the prior year's allowance. The operational discipline matters as much as the strategy." },
  ],
  crosslink: { title: "Also a company director taking dividends?", body: "Company directors often combine salary, dividends, and rental — which can cross the £100k adjusted net income threshold without crossing £100k salary alone. The dividend trap and the 60% trap often catch the same person.", url: "/uk/check/dividend-trap", label: "Check your dividend position →" },
  lawBarSummary: "UK personal allowance 2025-26: £12,570. Tapers at £100,000 adjusted net income at £1 for every £2 earned. Fully withdrawn at £125,140. Effective marginal rate in trap band: 60% (40% higher-rate income tax + 20% allowance withdrawal cost). Pension contributions and salary sacrifice reduce adjusted net income, restoring allowance proportionally. Established under Income Tax Act 2007 section 35 from April 2010.",
  lawBarBadges: ["HMRC", "Income Tax Act 2007 s35", "60% Effective Rate", "£100k Threshold", "Personal Allowance Trap"],
  sources: [
    { title: "HMRC — Income Tax rates and Personal Allowances",                                                       url: "https://www.gov.uk/income-tax-rates" },
    { title: "HMRC — Personal Allowance and income over £100,000",                                                    url: "https://www.gov.uk/income-tax-rates/income-over-100000" },
    { title: "HMRC — Tax on your private pension contributions (tax relief)",                                         url: "https://www.gov.uk/tax-on-your-private-pension" },
    { title: "Income Tax Act 2007 — section 35 (Personal allowance)",                                                  url: "https://www.legislation.gov.uk/ukpga/2007/3/section/35" },
    { title: "Machine-readable JSON rules",                                                                             url: "/api/rules/allowance-sniper" },
  ],
  files: [
    { num: "01", slug: "as-01", name: "Your 60% Trap Exposure Report", desc: "Your exact adjusted net income, allowance lost, and trap-band tax exposure.", tier: 1, content: `<h2>Your 60% Trap Exposure</h2><div class="action-box"><h3>The Binary Test</h3><p>If adjusted net income is between £100,000 and £125,140, you are in the trap.</p></div><h3>The Three Numbers That Matter</h3><ul><li>Adjusted net income (gross income minus pension, Gift Aid)</li><li>Allowance lost = max(0, (ANI − £100,000) / 2), capped at £12,570</li><li>Trap-band income = max(0, min(ANI, £125,140) − £100,000)</li></ul><h3>Allowance Taper Table</h3><table><tr><th>Adjusted net income</th><th>Personal allowance</th><th>Allowance lost</th></tr><tr><td>£100,000</td><td>£12,570</td><td>£0</td></tr><tr><td>£105,000</td><td>£10,070</td><td>£2,500</td></tr><tr><td>£110,000</td><td>£7,570</td><td>£5,000</td></tr><tr><td>£115,000</td><td>£5,070</td><td>£7,500</td></tr><tr><td>£120,000</td><td>£2,570</td><td>£10,000</td></tr><tr><td>£125,140</td><td>£0</td><td>£12,570</td></tr></table><p>Source: <a href="https://www.gov.uk/income-tax-rates/income-over-100000">HMRC — Income over £100,000</a> · Income Tax Act 2007 s35</p>` },
    { num: "02", slug: "as-02", name: "Pension Contribution to Escape", desc: "Exact pension contribution needed to restore full allowance and the tax saving it produces.", tier: 1, content: `<h2>Pension Contribution — Escape Calculator</h2><p>To escape the 60% trap, you need to reduce adjusted net income to £100,000 or below.</p><h3>The Formula</h3><p>Pension contribution required = Adjusted Net Income − £100,000</p><p>Tax saving on contribution (higher-rate relief) = 40% of contribution</p><p>Additional saving from restored allowance = up to £5,028 (depending on how much allowance was lost)</p><p>Net cost of contribution = Contribution − Total tax saving</p><h3>Worked Example — £115,000 Adjusted Net Income</h3><table><tr><th>Item</th><th>Amount</th></tr><tr><td>Pension contribution needed</td><td>£15,000</td></tr><tr><td>Pension tax relief (40%)</td><td>£6,000</td></tr><tr><td>Restored allowance saving (£7,500 × 40%)</td><td>£3,000</td></tr><tr><td>Total tax saving</td><td>£9,000</td></tr><tr><td>Net cost of contribution</td><td>£6,000</td></tr></table><p>Pension pot grows by £15,000. Tax saved £9,000. Net cost only £6,000.</p>` },
    { num: "03", slug: "as-03", name: "Salary Sacrifice vs Personal Contribution", desc: "Why salary sacrifice beats personal SIPP contributions at this income level.", tier: 1, content: `<h2>Salary Sacrifice vs Personal Contribution</h2><table><tr><th>Mechanism</th><th>Saves income tax?</th><th>Saves employee NI?</th><th>Saves employer NI?</th><th>Typical effective saving</th></tr><tr><td>Personal SIPP contribution</td><td>Yes (40% relief)</td><td>No</td><td>No</td><td>~40% of contribution</td></tr><tr><td>Employer salary sacrifice</td><td>Yes (40% relief)</td><td>Yes (2-13%)</td><td>Often reinvested (13.8%)</td><td>~55-65% of contribution</td></tr></table><h3>Bottom Line</h3><p>If your employer offers salary sacrifice, use it first. Only use personal SIPP to top up above whatever your employer allows. At £115k income salary-sacrificing £15k can save £9,000-£10,500 vs £9,000 for a personal contribution.</p>` },
    { num: "04", slug: "as-04", name: "Bonus Timing Around £125,140", desc: "How to time bonuses and irregular income to stay in the trap band (escapable) rather than crossing into additional rate territory.", tier: 1, content: `<h2>Bonus Timing Strategy</h2><p>Above £125,140 the allowance is fully gone and the marginal rate drops from 60% to 45% (additional rate). You no longer face the taper — but you've permanently lost the £12,570 tax-free band.</p><h3>The Key Question</h3><p>Are you better off at £125,000 (in trap, recoverable via pension) or £135,000 (past trap, allowance gone)?</p><h3>Answer: Depends on Your Pension Capacity</h3><ul><li>If you can contribute enough pension to bring ANI to £100,000: STAY IN the trap range and contribute. Full allowance recovered.</li><li>If you cannot contribute to reach £100,000: CROSSING into additional rate may be cheaper because you only pay 45% on the top slice instead of 60%.</li></ul><h3>Practical Levers</h3><ul><li>Defer bonus to next tax year if timing helps</li><li>Request part of bonus as pension contribution</li><li>Take bonus as shares / LTIPs that vest later</li></ul>` },
    { num: "05", slug: "as-05", name: "Your Accountant Brief — 60% Trap", desc: "5 questions to take to your accountant or IFA about the 60% trap and pension escape strategy.", tier: 1, content: `<div class="info-box">Forward to your accountant or take to your next meeting. These questions force specific numbers, not generic advice.</div><h2>Ask Your Accountant</h2><div class="action-box"><h3>Question 1</h3><p>"What is my projected adjusted net income for this tax year — including employment, self-employment, rental, savings, and dividends?"</p></div><h3>Question 2</h3><p>"Given that projection, what pension contribution brings me to £100,000 exactly — and what is the combined tax saving from pension relief plus allowance restoration?"</p><h3>Question 3</h3><p>"Is salary sacrifice available through my employer, and how does it compare to personal SIPP for me specifically?"</p><h3>Question 4</h3><p>"How should I time bonuses or large payments to avoid crossing £125,140?"</p><h3>Question 5</h3><p>"What should I do before 5 April to maximise allowance restoration for this tax year — and how early should we plan next year?"</p>` },
    { num: "06", slug: "as-06", name: "Multi-Year Pension Planning", desc: "How to optimise pension contributions across multiple tax years using carry forward and contribution capacity.", tier: 2, content: `<h2>Multi-Year Pension Planning</h2><p>Pension annual allowance is typically £60,000 per tax year (for earners below £260,000). Unused allowance from the three prior tax years can be carried forward. For 60% trap escape, rarely is the annual allowance a constraint — but for high earners making catch-up contributions, carry forward is the lever.</p><h3>Carry Forward Rules</h3><ul><li>You must have been a member of a registered pension scheme in each prior year</li><li>Current year annual allowance used first, then oldest carry-forward year</li><li>Contributions above annual allowance receive tax charge at marginal rate</li></ul><h3>Strategy</h3><p>For someone at £125,000 adjusted net income with low recent pension history: use current year £60k annual allowance + carry forward £180k = £240k capacity. Can wipe multiple years of 60% trap exposure in one big contribution if cashflow allows.</p>` },
    { num: "07", slug: "as-07", name: "Spousal Income Shifting", desc: "Transferring investments, rental property, and business income to a lower-earning spouse to reduce the higher earner's adjusted net income.", tier: 2, content: `<h2>Spousal Income Shifting</h2><p>If one spouse is in the 60% trap and the other is a basic-rate taxpayer, shifting income-producing assets creates structural tax savings.</p><h3>Mechanisms</h3><ul><li>Joint tenancy → tenants in common with 1%/99% split in favour of lower earner (rental property)</li><li>Gift investments to spouse (no CGT between spouses, s58 TCGA 1992)</li><li>Company share structure favouring lower earner (family company dividends)</li></ul><h3>Worked Example</h3><p>£8,400 rental to lower-earning spouse (20% band) taxed at £1,680. Same £8,400 taxed at 60% effective on higher earner: £5,040. Annual saving: £3,360.</p><h3>Watch</h3><ul><li>Settlements anti-avoidance — gifts must be genuine, not artificial</li><li>Stamp duty if transferring property for consideration</li><li>Cash-flow implications of the lower earner receiving the income</li></ul>` },
    { num: "08", slug: "as-08", name: "Full 60% Trap Escape Execution Plan", desc: "Step-by-step execution plan for the tax year — diagnosis through post-year-end record keeping.", tier: 2, content: `<h2>60% Trap Escape — Full Execution Plan</h2><h3>Phase 1 — Diagnosis (Month 1-2)</h3><ul class="checklist"><li>Project total adjusted net income including all sources</li><li>Calculate current trap exposure</li><li>Determine pension contribution capacity (salary sacrifice + SIPP)</li><li>Model net cost of full escape</li></ul><h3>Phase 2 — Setup (Month 2-3)</h3><ul class="checklist"><li>Increase employer salary sacrifice to practical maximum</li><li>Open SIPP for top-up contributions if needed</li><li>Brief accountant/IFA on plan</li><li>Schedule quarterly income reviews to catch bonus/side-income surprises</li></ul><h3>Phase 3 — Execution (Months 3-12)</h3><ul class="checklist"><li>Monthly salary sacrifice running</li><li>Quarterly top-up SIPP contributions if tracking above £100k</li><li>Bonus timing discussions with employer</li><li>Year-end (Feb-March) final top-up to hit £100k exactly</li></ul><h3>Phase 4 — Year-End Verification (April)</h3><ul class="checklist"><li>Confirm final adjusted net income sits at or below £100,000</li><li>Retain pension contribution certificates</li><li>Set up next year's plan based on projected bonuses and raises</li></ul>` },
  ],
  calendarTitle: "60% Tax Trap — UK Tax Year Dates",
  tier1Calendar: [
    { uid: "as-yearend", summary: "Tax Year End — Final pension contribution deadline", description: "Pension contributions must be made before 5 April to count in current tax year and affect allowance taper.", date: "20270405" },
    { uid: "as-sa", summary: "Self-Assessment Deadline — Check taper impact", description: "31 January — file 2025-26 tax return to see actual allowance taper impact.", date: "20270131" },
  ],
  tier2Calendar: [
    { uid: "as-review", summary: "Mid-year adjusted net income review", description: "Check projected full-year adjusted net income 6 months into tax year.", date: "relative:+60days" },
    { uid: "as-autumn", summary: "Autumn planning — pension top-up decision", description: "Final pension contribution planning with 5 months to go.", date: "relative:+120days" },
    { uid: "as-yearend", summary: "Tax Year End — Final pension deadline", description: "5 April — last chance to contribute for current tax year.", date: "20270405" },
    { uid: "as-sa", summary: "Self-Assessment Deadline", description: "31 January 2028 — file 2026-27 return.", date: "20280131" },
  ],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.gov.uk/income-tax-rates/income-over-100000"],
  sidebarNumbers: [{ label: "Personal allowance", value: "£12,570" }, { label: "Taper threshold", value: "£100,000 ANI" }, { label: "Effective rate in trap", value: "60%" }, { label: "Allowance fully lost at", value: "£125,140" }],
  sidebarMathsTitle: "The 60% trap arithmetic",
  sidebarMathsIncludes: [
    "Rule 1: Personal allowance £12,570 reduced by £1 for every £2 over £100,000 ANI",
    "Rule 2: Allowance fully withdrawn at £125,140",
    "Rule 3: Higher rate income tax 40% on trap-band income",
    "Rule 4: Effective marginal rate = 40% tax + 20% allowance cost = 60%",
    "Rule 5: Pension and salary sacrifice reduce ANI, restoring allowance proportionally",
  ],
  sidebarMathsExcludes: [
    "NOT shown on payslip or PAYE tax code",
    "NOT a penalty — statutory under ITA 2007 s35",
    "NOT reversible retrospectively after tax year end",
    "NOT only a salary issue — includes rental, dividends, self-employment",
  ],
  sidebarMathsNote: "Source: HMRC — Income over £100,000 · Income Tax Act 2007 section 35 · Confirmed April 2026",
  howToSteps: [
    { position: 1, name: "Enter your total income", text: "Combined employment, self-employment, rental, and relevant other income bands." },
    { position: 2, name: "Enter current pension contributions", text: "All pension contributions including employer match." },
    { position: 3, name: "Indicate salary sacrifice availability", text: "Determines optimal escape lever — sacrifice is more efficient than personal SIPP." },
    { position: 4, name: "See exact trap exposure and escape plan", text: "Tax on trap band, pension needed to escape, net cost after tax saving." },
  ],
  successPromptFields: [
    { key: "income_band",                label: "Income band",                              defaultVal: "110k_120k" },
    { key: "pension_contributions",      label: "Current pension contributions",            defaultVal: "none" },
    { key: "salary_sacrifice",           label: "Salary sacrifice availability",            defaultVal: "no" },
    { key: "adjusted_net_income",        label: "Adjusted net income",                      defaultVal: "115000" },
    { key: "trap_band_income",           label: "Income in 60% trap band",                  defaultVal: "15000" },
    { key: "trap_tax",                    label: "Tax on trap band (60%)",                   defaultVal: "9000" },
    { key: "pension_needed",              label: "Pension contribution to escape",           defaultVal: "15000" },
    { key: "pension_tax_saving",          label: "Tax saved by pension contribution",        defaultVal: "6000" },
    { key: "status",                      label: "Verdict status",                           defaultVal: "IN THE 60% TRAP — DEEP ZONE" },
    { key: "tier",                        label: "Product tier purchased",                   defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "trapStatusSummary",
    "adjustedNetIncomeCalculation",
    "allowanceTaperImpact",
    "trapBandExposure",
    "taxOnLast10k",
    "pensionEscapeRequirement",
    "taxSavingProjection",
    "salarySacrificeRecommendation",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "trapStatusSummary",
    "adjustedNetIncomeCalculation",
    "allowanceTaperImpact",
    "trapBandExposure",
    "taxOnLast10k",
    "pensionEscapeRequirement",
    "taxSavingProjection",
    "salarySacrificeOptimisation",
    "personalSippTopupStrategy",
    "bonusTimingStrategy",
    "multiYearPensionPlan",
    "spousalIncomeShifting",
    "accountantCoordinationBrief",
  ],
};
