import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "digital-link-auditor", name: "MTD Digital Link Compliance Engine", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/digital-link-auditor", url: "https://taxchecknow.com/uk/check/digital-link-auditor", apiRoute: "/api/rules/digital-link-auditor",
  authority: "HMRC", authorityUrl: "https://www.gov.uk/government/organisations/hm-revenue-customs", legalAnchor: "Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076) — digital link requirement for MTD ITSA", legislation: "Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076) · MTD ITSA commencement 6 April 2026 under Finance Act 2021 · HMRC VAT Notice 700/22 (MTD VAT digital link precedent) · Schedule 24 Finance Act 2021 penalty regime for MTD non-compliance · Income Tax Act 2007 record-keeping obligations",
  lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Digital Link Audit Pack", tagline: "Find the break in your MTD chain before HMRC does", value: "Your exact chain break point identified by step, the HMRC rule being broken, penalty exposure calculation, and 5 accountant questions specific to your break — built around your current record-keeping and submission process.", cta: "Get My Digital Link Audit — £67 →", productKey: "uk_67_digital_link_auditor", envVar: "STRIPE_UK_DLA_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Digital Link Fix Plan", tagline: "Migrate to a compliant chain before mandation — step-by-step playbook", value: "Full fix plan: bridging software selection for your setup, migration sequencing (records → transfer → submission), process documentation, accountant coordination brief, and post-fix verification checklist.", cta: "Get My Digital Link Fix Plan — £147 →", productKey: "uk_147_digital_link_auditor", envVar: "STRIPE_UK_DLA_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-04-06T00:00:00.000+01:00", display: "6 April 2026", short: "6 Apr 2026", description: "6 April 2026 — MTD ITSA Phase 1 mandate date. Digital link requirement becomes a live compliance condition for taxpayers with gross income over £50,000.", urgencyLabel: "MANDATE ACTIVE — CHAIN MUST BE LINKED", countdownLabel: "Countdown to MTD ITSA Phase 1 — 6 April 2026" },
  h1: "MTD Requires a Complete Digital Audit Trail — Not Just Digital Filing. Here Is Where Your Process Breaks the Rules.",
  metaTitle: "MTD Digital Link Audit 2026: Find Your Chain Break | TaxCheckNow",
  metaDescription: "Under MTD, data must flow digitally from first record to final submission — any manual copy/paste breaks the chain and makes your submission non-compliant. Audit your MTD process in 2 minutes against HMRC SI 2021/1076.",
  canonical: "https://taxchecknow.com/uk/check/digital-link-auditor",
  answerHeadline: "Digital link is absolute — one manual step anywhere breaks the whole chain",
  answerBody: [
    "MTD for Income Tax does not just require digital filing — it requires a complete unbroken digital chain from first record to final submission. Every step where data is manually copied, retyped, or adjusted breaks that chain. HMRC calls this a 'digital link' requirement and it is enforceable under the Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076). A compliant MTD submission is not just one sent via software — it is one where every record, every transfer, and every calculation has flowed digitally without manual intervention.",
    "The most common break point is the spreadsheet gap. Millions of UK self-employed and landlords keep records in Excel or Google Sheets. Under MTD, spreadsheets alone are not prohibited — but they must be connected to submission via HMRC-approved bridging software with no manual copy/paste step in between. Copying figures from a spreadsheet into a submission tool by hand fails the digital link test. Most people doing this do not know they are non-compliant.",
    "HMRC's approach to enforcement is phased and has been lenient during rollout. But as MTD becomes mandatory for the £50,000 threshold from April 2026 and expands downward, enforcement will follow the same trajectory as VAT MTD — where digital link failures became the primary audit trigger. The time to fix the process is before mandation, not after a compliance notice.",
  ],
  answerSource: "Source: HMRC — Making Tax Digital for Income Tax · Income Tax (Digital Requirements) Regulations 2021 SI 2021/1076 · Confirmed April 2026",
  mistakesHeadline: "What most people (and most MTD commentary) get wrong about digital links",
  mistakes: [
    "I submit via software so I am MTD compliant — wrong. Submission via software is necessary but not sufficient. Every step in the chain — from first record to final submission — must be digitally linked. A manual copy/paste step anywhere in the process breaks compliance even if the final submission is made through approved software.",
    "Spreadsheets are not allowed under MTD — wrong. Spreadsheets are permitted under MTD provided they are connected to HMRC-approved bridging software with no manual data breaks. The requirement is a digital link — not a specific type of software. Excel with bridging software equals compliant. Excel with manual copy/paste to submission equals non-compliant.",
    "My accountant handles MTD so I do not need to worry — wrong. The digital link obligation sits with the taxpayer, not the agent. If your accountant is manually adjusting figures between your records and their submission software, that break is your compliance risk. Ask specifically: how does data move from my records to the submission?",
    "Digital link failures are minor technical issues — wrong. Under HMRC's MTD regulations, a non-compliant submission process can result in the submission being treated as not made — triggering late filing penalties as if no submission occurred. The digital link requirement is a substantive compliance condition, not a formatting preference.",
  ],
  chainVisual: { label: "Your MTD chain — digital link must survive every step", broken: "Records → manual copy → spreadsheet → manual paste → submission  ❌  Digital link broken at every step", fixed: "Records → bridging software → automated transfer → HMRC submission  ✔  Complete digital chain" },
  brackets: [
    { label: "Approved software + integrated submission — compliant chain",                 value: 1, status: "clear" },
    { label: "Spreadsheets + HMRC-approved bridging software — compliant chain",            value: 2, status: "clear" },
    { label: "Mixed systems + occasional manual adjustments — at risk",                      value: 3, status: "approaching" },
    { label: "Spreadsheets submitted directly without bridging — non-compliant",             value: 4, status: "trap" },
    { label: "Manual copy/paste anywhere in chain — non-compliant regardless of submission", value: 5, status: "deep_trap" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "recordKeeping", label: "How do you currently keep your income and expense records?", subLabel: "MTD requires records to be kept in digital form from the point of transaction.", options: [{ label: "Digital software only (Xero, QuickBooks, FreeAgent, Sage)", value: "digital_software" }, { label: "Spreadsheets (Excel, Google Sheets)", value: "spreadsheets" }, { label: "Mix of software and spreadsheets", value: "mix" }, { label: "Paper / manual records", value: "paper" }], default: "spreadsheets" },
    { type: "buttonGroup", stateKey: "dataFlow", label: "How does data move from your records to your MTD submission?", subLabel: "The data transfer step is the most common digital link break point.", options: [{ label: "Directly through integrated software", value: "integrated" }, { label: "Automated export/import between systems", value: "automated_export_import" }, { label: "I copy figures manually between systems", value: "manual_copy_paste" }, { label: "My accountant handles it — not sure how", value: "accountant_unknown" }], default: "manual_copy_paste" },
    { type: "buttonGroup", stateKey: "bridging", label: "Do you use bridging software to connect spreadsheets to HMRC?", subLabel: "HMRC-approved bridging software is required for any spreadsheet-to-submission path.", options: [{ label: "Yes — HMRC-approved bridging software", value: "yes" }, { label: "No — I submit directly from spreadsheet", value: "no_submit_direct" }, { label: "No — I do not use spreadsheets", value: "no_no_spreadsheets" }, { label: "Not sure what bridging software is", value: "not_sure" }], default: "no_submit_direct" },
    { type: "buttonGroup", stateKey: "manualAdjustments", label: "Do you manually adjust any figures between your records and your submission?", subLabel: "Manual adjustment anywhere in the chain breaks the digital link — even occasional ones.", options: [{ label: "Never — data flows automatically", value: "never" }, { label: "Sometimes — minor adjustments", value: "sometimes" }, { label: "Yes — I regularly adjust figures manually", value: "regularly" }, { label: "My accountant does this — unknown to me", value: "accountant_unknown" }], default: "sometimes" },
  ],
  tierAlgorithm: { description: "NON-COMPLIANT or AT-RISK → tier2 (fix plan). COMPLIANT → tier1 (audit confirmation).", tier2Conditions: ["recordKeeping === 'paper'", "dataFlow === 'manual_copy_paste'", "manualAdjustments === 'regularly'", "recordKeeping === 'spreadsheets' && bridging === 'no_submit_direct'", "dataFlow === 'accountant_unknown'", "manualAdjustments === 'sometimes'"], tier2Flags: [] },
  calculatorRuleBox: { label: "The digital link rule — HMRC confirmed", body: "Under MTD ITSA, records must be kept digitally and transferred digitally at every step to submission. A 'digital link' is any automated electronic transfer with no manual intervention (integration, API, approved export/import, or HMRC-approved bridging software). Manual copy/paste, retyping, or figure adjustment anywhere in the chain breaks compliance. Statutory under Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076)." },
  calculatorClarification: { label: "Digital link is absolute, not partial", body: "HMRC does not accept 'mostly compliant' or 'occasional' breaks. A single manual copy/paste step anywhere in the chain — even at the very end just before submission — makes the whole submission non-compliant. The requirement applies at every quarterly update and the final declaration." },
  countdownLabel: "Countdown to MTD ITSA Phase 1 — 6 April 2026",
  countdownStats: [
    { label: "Mandate date",               value: "6 Apr 2026",  sub: "Phase 1 — income over £50,000" },
    { label: "Legal anchor",               value: "SI 2021/1076", sub: "Income Tax (Digital Requirements) Regulations" },
    { label: "Per-quarter penalty",        value: "Up to £1,100", sub: "Non-compliant submission rejected",         red: true },
    { label: "Max annual penalty",         value: "Up to £4,400", sub: "If all 4 quarters rejected",                red: true },
  ],
  persona: {
    name: "Emma",
    age: 44,
    occupation: "Limited company director + single-property landlord",
    location: "Reading, Berkshire",
    family: "Husband Paul (teacher). Three kids (ages 8, 11, 14).",
    financialSnapshot: "Emma runs a small marketing consultancy through a limited company. £88k salary + £32k dividends. One rental property in Reading generating £18k gross. She tracks rental income/expenses in an Excel spreadsheet and types figures into HMRC online when filing.",
    painPoint: "Emma read that MTD starts April 2026. She assumed because she files online she is already compliant. She does not realise her spreadsheet-to-typed-submission process is exactly the pattern SI 2021/1076 prohibits, and that her £18k rental puts her in Phase 2 (April 2027 mandate).",
    discovery: "Emma searched MTD compliance after her accountant mentioned 'digital links' in an email. Googled the term. Found it was a technical rule she had never heard of.",
    voice: "Organised. Spreadsheet-native. Will fix the process once she sees exactly what breaks it.",
  },
  story: {
    hook: "Emma had been running her rental spreadsheet the same way for eight years. Every April she typed the figures into her self-assessment. Job done.",
    setup: [
      "Her limited company accounts went through her accountant — FreeAgent, compliant, automated. The rental spreadsheet was her own. She tracked tenant payments, repair invoices, mortgage interest. At year-end she totalled the columns and typed the numbers into HMRC online.",
      "In February her accountant mentioned MTD for Income Tax was arriving. He emailed a checklist with 'verify digital link compliance' as item 4. Emma had no idea what that meant. She Googled. Found SI 2021/1076. Read the words 'manual copy is prohibited'. Felt her stomach drop.",
      "Her £18k rental income put her in Phase 2 — mandated from 6 April 2027. Her 'spreadsheet then type into HMRC' process was exactly the pattern the regulations prohibited. It had worked fine for years only because MTD did not apply to her rental yet.",
    ],
    revelation: "Emma ran the digital link auditor. Step 1: spreadsheets. Step 2: she copies the totals manually. Step 3: no bridging software. Step 4: she sometimes adjusts figures at year-end for rounded-up maintenance costs. Result: NON-COMPLIANT at step 2 (manual copy/paste), with secondary break at step 3 (no bridging) and step 4 (adjustments). Penalty exposure from 6 April 2027: up to £1,100 per rejected quarter, up to £4,400/year.",
    resolution: "Emma chose a £9/month HMRC-approved bridging tool that connected her existing Excel spreadsheet to HMRC submissions directly. No migration to new software needed. She stopped manually adjusting figures — instead updating the source cells when she found a correction. Cost of compliance: £108/year. Penalty avoided: up to £4,400/year plus peace of mind that her accountant wasn't going to flag her for audit.",
  },
  geoBlockTitle: "AI extraction block — MTD ITSA digital link requirement",
  geoBlockH2: "MTD ITSA Digital Link Compliance — SI 2021/1076, Confirmed April 2026",
  geoBodyParagraph: "Under Making Tax Digital for Income Tax (MTD ITSA), HMRC requires taxpayers to maintain digital records and submit quarterly updates via a complete unbroken digital chain — known as the 'digital link' requirement. This is established under the Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076). A digital link is defined as any electronic transfer of data that does not require manual intervention — including automated imports, API connections, and direct software integrations. Manual copy and paste, retyping of figures, and manual adjustment of exported data all break the digital link and render the MTD process non-compliant regardless of whether the final submission is made through HMRC-approved software. Spreadsheets are permitted under MTD but must be connected to submission via HMRC-approved bridging software with no manual data transfer in between. MTD for Income Tax applies mandatorily from April 2026 for gross income over £50,000, April 2027 for income over £30,000, and April 2028 for income over £20,000. Enforcement of digital link requirements is expected to follow the VAT MTD precedent where digital link failures became a primary audit trigger following mandatory rollout.",
  geoFormula: "Digital link compliance test: records digital + all data transfers automated + no manual figure adjustments = compliant. Any manual step in the chain = non-compliant regardless of submission method. Non-compliant submissions can be treated as unsubmitted under Finance Act 2021 penalty regime = £200 initial + £10/day up to 90 days = up to £1,100 per rejected quarter, up to £4,400 annually.",
  geoFacts: [
    { label: "Legal anchor",                            value: "SI 2021/1076 (Income Tax Digital Requirements Regulations 2021)" },
    { label: "MTD ITSA Phase 1 mandate",                 value: "6 April 2026 — income over £50,000" },
    { label: "MTD ITSA Phase 2 mandate",                 value: "6 April 2027 — income over £30,000" },
    { label: "MTD ITSA Phase 3 mandate",                 value: "6 April 2028 — income over £20,000" },
    { label: "Digital link definition",                   value: "Automated electronic transfer with no manual intervention" },
    { label: "Spreadsheets — compliant if",              value: "Connected via HMRC-approved bridging software" },
    { label: "Paper records under MTD",                   value: "Not compliant — cannot satisfy digital requirement" },
    { label: "Per-quarter penalty (rejected submission)", value: "Up to £1,100 (£200 + £10/day × 90 days)" },
    { label: "Max annual penalty",                         value: "Up to £4,400 if all 4 quarters rejected" },
    { label: "Digital link obligation holder",             value: "Taxpayer, not agent" },
  ],
  workedExamplesH2: "Four taxpayer processes — compliant, at risk, or non-compliant?",
  workedExamplesColumns: ["Taxpayer", "Process", "Verdict", "Break point"],
  workedExamples: [
    { name: "Freelancer on FreeAgent",           setup: "FreeAgent tracks all income/expenses, auto-submits to HMRC",       income: "Integrated software",            status: "COMPLIANT" },
    { name: "Landlord with bridging tool",        setup: "Excel spreadsheet + approved bridging add-in connects to HMRC",     income: "Spreadsheet + bridging",         status: "COMPLIANT" },
    { name: "Consultant manual typing",           setup: "Excel totals typed into HMRC online submission form",               income: "Spreadsheet → manual type",      status: "NON-COMPLIANT (step 2)" },
    { name: "Director with occasional tweaks",    setup: "Xero integrated but accountant sometimes adjusts at year-end",      income: "Software + manual adjustments",  status: "AT RISK (step 4)" },
  ],
  comparisonH2: "Compliant vs non-compliant chains — what HMRC actually enforces",
  comparisonColumns: ["Process type", "Digital link status", "Under MTD", "Fix cost"],
  comparisonRows: [
    { position: "Approved software, integrated submission",                   metric1: "Unbroken",          metric2: "COMPLIANT",                 bestMove: "£10-15/month software" },
    { position: "Spreadsheets + HMRC-approved bridging software",              metric1: "Unbroken",          metric2: "COMPLIANT",                 bestMove: "£5-15/month bridging add-on" },
    { position: "Spreadsheets submitted directly (manual typing)",             metric1: "Broken at step 3",  metric2: "NON-COMPLIANT",             bestMove: "Add bridging software" },
    { position: "Software but manual copy/paste between systems",              metric1: "Broken at step 2",  metric2: "NON-COMPLIANT",             bestMove: "Integrate systems or migrate" },
    { position: "Paper records",                                                metric1: "No digital basis",  metric2: "NON-COMPLIANT",             bestMove: "Full migration to software" },
    { position: "Integrated software with occasional manual adjustments",      metric1: "Intermittent break", metric2: "AT RISK / NON-COMPLIANT",  bestMove: "Discipline: source-only corrections" },
  ],
  toolsH2: "Bridging software options — when spreadsheets are your record-keeping choice",
  toolsColumns: ["Tool", "Best for", "Approximate cost"],
  toolsRows: [
    { tool: "Tax Optimiser bridging",    effect: "Excel-based spreadsheet users, simple connection to HMRC",         note: "From £5/month" },
    { tool: "123 Sheets",                effect: "Google Sheets users, cloud-based",                                  note: "From £9/month" },
    { tool: "Absolute Excel add-in",      effect: "Power users with complex Excel workbooks",                          note: "~£10/month" },
    { tool: "VitalTax",                  effect: "Multi-business users, multiple MTD businesses in one spreadsheet",  note: "From £15/month" },
    { tool: "HMRC Free Basic (if available)", effect: "Simple cases meeting HMRC basic tool criteria",                 note: "Free but limited" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: I submit via software so I am MTD compliant",                                                   correct: "Reality: Submission via software is NECESSARY but NOT SUFFICIENT. Every step in the chain — from first record to final submission — must be digitally linked. A manual copy/paste step anywhere in the process breaks compliance even if the final submission is made through approved software. SI 2021/1076 requires an UNBROKEN chain." },
    { wrong: "ChatGPT says: Spreadsheets are not allowed under MTD",                                                         correct: "Reality: Spreadsheets ARE permitted under MTD provided they are connected to HMRC-approved bridging software with no manual data breaks. The requirement is a digital LINK — not a specific type of software. Excel with bridging software = compliant. Excel with manual copy/paste to submission = non-compliant. Bridging tools cost £5-15/month." },
    { wrong: "ChatGPT says: My accountant handles MTD so I do not need to worry",                                            correct: "Reality: The digital link obligation sits with the TAXPAYER, not the agent (under SI 2021/1076). If your accountant is manually adjusting figures between your records and their submission software, that break is YOUR compliance risk. Ask specifically: 'How does data move from my records to the submission?' If the answer includes manual entry anywhere, you are exposed." },
    { wrong: "ChatGPT says: Digital link failures are minor technical issues",                                                correct: "Reality: Under HMRC's MTD regulations, a non-compliant submission PROCESS can result in the submission being treated as NOT MADE — triggering late filing penalties as if no submission occurred. The digital link requirement is a SUBSTANTIVE compliance condition, not a formatting preference. Up to £4,400/year if all 4 quarters rejected." },
  ],
  faqs: [
    { question: "What is a digital link under MTD?",                                                                    answer: "A digital link is an automated electronic transfer of data between systems that does not require manual intervention. Examples include direct integration between software packages, API connections, automated file imports, and HMRC-approved bridging software. Examples that are NOT digital links: manual copy and paste, retyping of figures, and manual adjustment of exported data before import." },
    { question: "Can I still use spreadsheets under MTD?",                                                              answer: "Yes. Spreadsheets are permitted under MTD provided they are connected to submission via HMRC-approved bridging software. The requirement is for an unbroken digital chain — not a specific type of software. Excel or Google Sheets + approved bridging software + no manual data transfer = compliant. Common bridging tools cost £5-15/month and attach to your existing spreadsheet." },
    { question: "What counts as 'breaking' the digital link?",                                                          answer: "Any step in the data flow from first record to final submission that requires a human to copy, type, or adjust a figure. Examples: copying totals from a spreadsheet into the HMRC portal by hand; retyping invoice data from one software into another; manually adjusting an exported CSV file before importing it to submission software. If a human touches the numbers between systems, the link is broken." },
    { question: "What are the penalties for a non-compliant submission?",                                                answer: "Under the MTD penalty regime (Schedule 24 Finance Act 2021), a submission made through a non-compliant process can be treated as NOT MADE. This triggers the standard late-filing penalty: £200 initial + £10 per day up to 90 days = up to £1,100 per affected quarter. Missing all four quarterly updates in a year = up to £4,400 in penalties alone. Plus points accumulating toward additional financial penalties." },
    { question: "Is my accountant responsible for digital link compliance?",                                             answer: "No — the obligation is on the taxpayer under SI 2021/1076. Your accountant may PROCESS your records and make submissions, but if their process includes manual adjustments or copy/paste steps, the compliance risk sits with you. Ask your accountant directly: 'How does data move from my records to the submission?' If any manual step is in the chain, you need to discuss fixing it together." },
    { question: "When does the digital link requirement start enforcing?",                                               answer: "The requirement is already statutory under SI 2021/1076 for VAT MTD. For Income Tax MTD (ITSA), it starts 6 April 2026 for taxpayers with gross income over £50,000, then April 2027 for £30k+, and April 2028 for £20k+. HMRC has signalled phased enforcement — lenient in year one, then following the VAT MTD precedent where digital link failures became the primary audit trigger once mandation completed." },
    { question: "What is bridging software and when do I need it?",                                                      answer: "Bridging software is HMRC-approved software that connects a spreadsheet to HMRC's MTD submission system directly. You need it if you keep records in a spreadsheet and submit to MTD. Without bridging software, the only way to submit from a spreadsheet is by copying figures manually — which breaks the digital link. Bridging tools cost £5-15/month and are listed on HMRC's website of approved MTD software." },
    { question: "Do I have to migrate to Xero or QuickBooks?",                                                            answer: "No. You can stay on spreadsheets provided you add HMRC-approved bridging software. Migration to integrated software (Xero, QuickBooks, FreeAgent, Sage) is an alternative path but not required. For simple sole traders and single-property landlords, spreadsheet + bridging is often cheaper and simpler than full software migration." },
  ],
  accountantQuestionsH2: "Ask these before 6 April 2026",
  accountantQuestions: [
    { q: "How does data move from my records to the submission — step by step, with every intermediate system named?",                                 why: "Generic 'we handle it' answers hide manual steps. If there is any typing, copying, or adjusting between systems, that is a break you are exposed to under SI 2021/1076." },
    { q: "If I keep my rental in a spreadsheet, do you submit via bridging software or by typing into the portal?",                                    why: "Spreadsheet + manual typing = non-compliant. Spreadsheet + bridging software = compliant. Your accountant might be doing either — you need to know specifically." },
    { q: "Do you manually adjust any figures between my records and the submission — and if so, why?",                                                 why: "Adjustments break the chain. Even 'minor' or 'occasional' ones. If adjustments are needed, they must happen in your source records, not between systems." },
    { q: "What is my mandate date based on my total gross income from self-employment and property?",                                                  why: "Your digital link fix timeline depends on your mandate date. Phase 1 (April 2026) members need compliance now; Phase 2 (April 2027) and Phase 3 (April 2028) have more lead time but the requirement is the same." },
    { q: "If HMRC audited my MTD submissions today, would my process pass the digital link test — and can you put that in writing?",                   why: "An accountant willing to put digital link compliance in writing has actually thought about it. One who deflects has not. Written confirmation also shifts some evidentiary weight if HMRC queries later." },
  ],
  crosslink: { title: "Not sure which MTD wave you are in?", body: "MTD ITSA mandate depends on your total gross income from self-employment and property. Phase 1 from April 2026 at £50k+. Our MTD Mandation Engine confirms your exact wave and penalty exposure.", url: "/uk/check/mtd-scorecard", label: "Check my MTD mandate wave →" },
  lawBarSummary: "MTD digital link requirement: every step from first record to final submission must be an automated electronic transfer with no manual intervention. Spreadsheets permitted with HMRC-approved bridging software. Manual copy/paste, retyping, or figure adjustment anywhere in the chain is non-compliant. Statutory under Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076). Enforcement phased with MTD ITSA rollout from 6 April 2026.",
  lawBarBadges: ["HMRC", "SI 2021/1076", "Digital Link Required", "MTD ITSA", "April 2026 Mandatory"],
  sources: [
    { title: "HMRC — Making Tax Digital for Income Tax",                                                              url: "https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax" },
    { title: "Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076)",                                     url: "https://www.legislation.gov.uk/uksi/2021/1076/contents" },
    { title: "HMRC — Check which software works with MTD for Income Tax",                                              url: "https://www.gov.uk/guidance/find-software-thats-compatible-with-making-tax-digital-for-income-tax" },
    { title: "HMRC VAT Notice 700/22 — MTD VAT digital link precedent",                                                url: "https://www.gov.uk/government/publications/vat-notice-70022-making-tax-digital-for-vat" },
    { title: "Machine-readable JSON rules",                                                                              url: "/api/rules/digital-link-auditor" },
  ],
  files: [
    { num: "01", slug: "dla-01", name: "Your Chain Break Point Report", desc: "Which step in your MTD process breaks the digital link — with HMRC citation.", tier: 1, content: `<h2>Your Digital Link Break Point</h2><div class="action-box"><h3>The Four-Step Chain</h3><p>Step 1: Record-keeping (records must be digital at source)</p><p>Step 2: Data transfer (between systems — must be automated)</p><p>Step 3: Bridging (spreadsheet-to-submission needs HMRC-approved tool)</p><p>Step 4: Submission (no manual figure adjustments anywhere in chain)</p></div><h3>Where Your Chain Breaks</h3><p>See your verdict panel for the specific step where your process fails the digital link test, with the HMRC regulation that applies.</p><h3>HMRC Anchor</h3><p>All four steps must pass for compliance under Income Tax (Digital Requirements) Regulations 2021 (SI 2021/1076). A break at any single step makes the whole submission non-compliant.</p><p>Source: <a href="https://www.legislation.gov.uk/uksi/2021/1076/contents">SI 2021/1076</a> · <a href="https://www.gov.uk/guidance/use-making-tax-digital-for-income-tax">HMRC MTD ITSA</a></p>` },
    { num: "02", slug: "dla-02", name: "HMRC-Approved Bridging Software Comparison", desc: "Ranked bridging software options if spreadsheets are your record-keeping choice.", tier: 1, content: `<h2>HMRC-Approved Bridging Software</h2><p>Bridging software connects a spreadsheet to HMRC's MTD submission system directly — no manual typing, no broken chain.</p><table><tr><th>Tool</th><th>Cost</th><th>Best for</th></tr><tr><td>Tax Optimiser</td><td>From £5/month</td><td>Simple Excel users</td></tr><tr><td>123 Sheets</td><td>From £9/month</td><td>Google Sheets cloud users</td></tr><tr><td>Absolute Excel add-in</td><td>~£10/month</td><td>Complex Excel workbooks</td></tr><tr><td>VitalTax</td><td>From £15/month</td><td>Multi-business users</td></tr></table><h3>Selection Criteria</h3><ul><li>Confirm current HMRC-approved status at gov.uk</li><li>Check compatibility with your spreadsheet format</li><li>Test in parallel before mandate date</li></ul>` },
    { num: "03", slug: "dla-03", name: "The Five Common Break Points", desc: "Real-world break points most taxpayers do not realise are non-compliant.", tier: 1, content: `<h2>Five Common Digital Link Breaks</h2><ol><li><strong>Spreadsheet-to-HMRC manual typing</strong> — the most common break. Fix: add bridging software.</li><li><strong>Multi-property landlord combining totals in Excel</strong> — if the combining is done by copy/paste, the chain breaks before submission. Fix: separate MTD businesses per property type, each with its own digital link.</li><li><strong>Accountant's internal spreadsheet adjustment</strong> — your accountant pulls data from your software into their own spreadsheet for review, then submits from the spreadsheet. Fix: ask them to use bridging software or integrated submission.</li><li><strong>Year-end correction adjustments</strong> — manually tweaking figures after export but before submission. Fix: correct at source in your records, re-run the automated transfer.</li><li><strong>Migration leftovers</strong> — just switched software, and the handover used manual re-entry. Fix: verify opening balances came via a digital migration tool, not typed.</li></ol>` },
    { num: "04", slug: "dla-04", name: "Process Documentation Template", desc: "Template for documenting your MTD data chain — what you need if HMRC asks.", tier: 1, content: `<h2>MTD Process Documentation Template</h2><div class="info-box">Keep this with your records. If HMRC queries digital link compliance, you need to show the chain.</div><h3>For Each MTD Business (Rental, Self-Employment, etc.)</h3><p><strong>System 1 — Record-keeping:</strong> Name of software or spreadsheet. Where records are kept. Who updates it and how often.</p><p><strong>Data transfer mechanism:</strong> Integration, API, file export/import, or bridging software. Name of method and vendor.</p><p><strong>System 2 — Submission:</strong> How records reach HMRC. Direct software submission, approved bridging tool, or accountant's system.</p><p><strong>Manual intervention:</strong> Yes or no. If yes, at which step and why.</p><p><strong>Digital link status:</strong> Compliant / At risk / Non-compliant. Evidence reference.</p>` },
    { num: "05", slug: "dla-05", name: "Your Accountant Brief — Digital Link", desc: "5 questions for your accountant about your MTD chain.", tier: 1, content: `<div class="info-box">Forward to your accountant or take to your next meeting. These questions force specific process disclosure — vague 'we handle it' responses mean the chain has not been verified.</div><h2>Ask Your Accountant</h2><div class="action-box"><h3>Question 1</h3><p>"How does data move from my records to the submission — step by step, with every intermediate system named?"</p></div><h3>Question 2</h3><p>"If I keep my rental in a spreadsheet, do you submit via bridging software or by typing into the portal?"</p><h3>Question 3</h3><p>"Do you manually adjust any figures between my records and the submission — and if so, why?"</p><h3>Question 4</h3><p>"What is my mandate date based on my total gross income from self-employment and property?"</p><h3>Question 5</h3><p>"If HMRC audited my MTD submissions today, would my process pass the digital link test — and can you put that in writing?"</p>` },
    { num: "06", slug: "dla-06", name: "Migration Sequencing Playbook", desc: "Step-by-step plan to migrate from broken chain to compliant chain without disrupting current filings.", tier: 2, content: `<h2>Digital Link Migration — Full Playbook</h2><h3>Phase 1 — Diagnose (Month 1)</h3><ul class="checklist"><li>Document current chain for each MTD business (use template from file 04)</li><li>Identify specific break points at each step</li><li>Decide path: bridging software (spreadsheet-stay) or full software migration</li></ul><h3>Phase 2 — Tool Selection (Month 2)</h3><ul class="checklist"><li>For bridging path: trial 2-3 HMRC-approved tools, pick based on spreadsheet compatibility</li><li>For migration path: evaluate software options, plan data import approach</li><li>Confirm accountant's preferred tools (they may already work with specific platforms)</li></ul><h3>Phase 3 — Parallel Run (Month 3)</h3><ul class="checklist"><li>Run new compliant chain alongside old process for one quarter</li><li>Reconcile outputs to catch discrepancies</li><li>Document new process in your records</li></ul><h3>Phase 4 — Cutover (Month 4)</h3><ul class="checklist"><li>Switch fully to compliant chain</li><li>Retire old manual steps</li><li>Confirm no handoff requires typing or copying</li></ul><h3>Phase 5 — Ongoing Verification (Every Quarter)</h3><ul class="checklist"><li>Quarterly review: any new tools or workflows added? Do they maintain digital link?</li><li>Annual audit: accountant confirms chain in writing</li></ul>` },
    { num: "07", slug: "dla-07", name: "Multi-Business Digital Link Strategy", desc: "How to maintain digital link compliance across multiple MTD businesses (self-employment + rental + etc).", tier: 2, content: `<h2>Multi-Business Digital Link Strategy</h2><p>If you have self-employment + rental properties + furnished holiday lets, you have multiple MTD businesses — each requiring its own compliant digital chain.</p><h3>Option A — Single Unified Software</h3><p>Xero or QuickBooks with multi-business support keeps all records in one system with multiple ledgers. One software, multiple chains, but each chain is independent and compliant.</p><h3>Option B — Spreadsheet Per Business + Shared Bridging</h3><p>Keep one spreadsheet per MTD business. Use one bridging tool that supports multiple spreadsheet connections. Cheaper than full software but harder to maintain.</p><h3>Option C — Hybrid</h3><p>Software for self-employment (higher volume), spreadsheet + bridging for rental (lower volume). Works provided each chain is independently compliant.</p><h3>Risk: Cross-Business Data Movement</h3><p>If you combine numbers across businesses for any purpose (personal budgeting, etc.), that combining must NOT flow into MTD submissions. Keep the submission chain strictly within each MTD business.</p>` },
    { num: "08", slug: "dla-08", name: "Post-Mandate Verification Checklist", desc: "Ongoing compliance checks after MTD mandation lands for you — to catch chain breaks before HMRC does.", tier: 2, content: `<h2>Post-Mandate Verification Checklist</h2><h3>Every Quarter</h3><ul class="checklist"><li>Verify quarterly submission was made via compliant chain (not manually rescued)</li><li>Check that no new tools or processes have been added without chain verification</li><li>Confirm no figures were manually adjusted between records and submission</li><li>Save submission confirmation emails — evidence of on-time filing</li></ul><h3>Annually</h3><ul class="checklist"><li>Full chain re-audit using this product's 4-step test</li><li>Accountant written confirmation of chain compliance</li><li>Review HMRC's approved software list — confirm your tools are still listed</li><li>Update process documentation if anything changed during the year</li></ul><h3>Red Flags to Watch</h3><ul class="checklist"><li>Accountant starts 'tidying up' your numbers in their own spreadsheet</li><li>Software vendor drops HMRC-approved status</li><li>You add a new income stream (rental, side-gig) without extending the chain</li><li>Year-end adjustments start creeping in to 'correct' minor issues</li></ul>` },
  ],
  calendarTitle: "Digital Link Compliance — Key Dates",
  tier1Calendar: [
    { uid: "dla-phase1", summary: "MTD ITSA Phase 1 Mandate — 6 April 2026", description: "Digital link requirement becomes a live compliance condition for income over £50,000.", date: "20260406" },
    { uid: "dla-phase2", summary: "MTD ITSA Phase 2 Mandate — 6 April 2027", description: "Mandate expands to income over £30,000.", date: "20270406" },
    { uid: "dla-phase3", summary: "MTD ITSA Phase 3 Mandate — 6 April 2028", description: "Mandate expands to income over £20,000.", date: "20280406" },
  ],
  tier2Calendar: [
    { uid: "dla-diagnose", summary: "Digital Link — Diagnose current chain", description: "Document current chain for each MTD business.", date: "relative:+7days" },
    { uid: "dla-tool", summary: "Digital Link — Select bridging or migration tool", description: "Decide path and select HMRC-approved tool.", date: "relative:+30days" },
    { uid: "dla-parallel", summary: "Digital Link — Parallel run", description: "Run new compliant chain alongside old process for one quarter.", date: "relative:+60days" },
    { uid: "dla-cutover", summary: "Digital Link — Full cutover", description: "Switch fully to compliant chain.", date: "relative:+120days" },
    { uid: "dla-phase1", summary: "MTD ITSA Phase 1 Mandate", description: "6 April 2026 — compliance chain must be in place.", date: "20260406" },
  ],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.legislation.gov.uk/uksi/2021/1076/contents", "https://www.gov.uk/guidance/find-software-thats-compatible-with-making-tax-digital-for-income-tax"],
  sidebarNumbers: [{ label: "Legal anchor", value: "SI 2021/1076" }, { label: "Phase 1 mandate", value: "6 Apr 2026" }, { label: "Per-quarter penalty max", value: "£1,100" }, { label: "Annual penalty max", value: "£4,400" }],
  sidebarMathsTitle: "Digital link requirement — the four gates",
  sidebarMathsIncludes: [
    "Gate 1: Records kept in digital form from source",
    "Gate 2: Data transfer between systems is automated",
    "Gate 3: Spreadsheet-to-submission via HMRC-approved bridging",
    "Gate 4: No manual figure adjustments anywhere in chain",
    "All four gates must pass for compliance",
  ],
  sidebarMathsExcludes: [
    "NOT satisfied by submission-via-software alone",
    "NOT acceptable 'occasional' manual intervention",
    "NOT the accountant's obligation — yours as taxpayer",
    "NOT a formatting preference — substantive compliance condition",
  ],
  sidebarMathsNote: "Source: Income Tax (Digital Requirements) Regulations 2021 SI 2021/1076 · HMRC confirmed April 2026",
  howToSteps: [
    { position: 1, name: "State your record-keeping method", text: "Digital software, spreadsheets, mix, or paper." },
    { position: 2, name: "Describe how data moves to submission", text: "Integrated, automated export/import, manual copy/paste, or accountant-handled." },
    { position: 3, name: "Confirm bridging software use (if spreadsheets)", text: "HMRC-approved bridging tool required for any spreadsheet-to-submission path." },
    { position: 4, name: "State whether manual adjustments occur", text: "Any manual figure change between systems breaks the chain — this step is the most commonly overlooked." },
  ],
  successPromptFields: [
    { key: "record_keeping",        label: "Record-keeping method",                    defaultVal: "spreadsheets" },
    { key: "data_flow",             label: "Data flow method",                          defaultVal: "manual_copy_paste" },
    { key: "bridging",              label: "Bridging software status",                  defaultVal: "no_submit_direct" },
    { key: "manual_adjustments",    label: "Manual adjustments frequency",              defaultVal: "sometimes" },
    { key: "compliance_status",     label: "Compliance verdict",                        defaultVal: "NON_COMPLIANT" },
    { key: "break_step",            label: "Chain break step (1-4)",                    defaultVal: "2" },
    { key: "break_point",           label: "Break point description",                   defaultVal: "Manual copy/paste between systems" },
    { key: "status",                label: "Verdict status",                            defaultVal: "NON-COMPLIANT — DIGITAL LINK BROKEN AT STEP 2" },
    { key: "tier",                   label: "Product tier purchased",                    defaultVal: "147" },
  ],
  tier1AssessmentFields: [
    "complianceStatusSummary",
    "chainBreakIdentification",
    "hmrcRequirementCitation",
    "specificFixRequired",
    "penaltyExposureCalculation",
    "bridgingSoftwareOptions",
    "processDocumentationStart",
    "accountantQuestions",
    "firstAction",
  ],
  tier2AssessmentFields: [
    "complianceStatusSummary",
    "chainBreakIdentification",
    "hmrcRequirementCitation",
    "specificFixRequired",
    "penaltyExposureCalculation",
    "bridgingSoftwareSelection",
    "migrationSequencingPlan",
    "processDocumentationTemplate",
    "multiBusinessStrategy",
    "accountantCoordinationBrief",
    "postMandateVerificationChecklist",
    "ongoingComplianceSchedule",
  ],
};
