import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "digital-link-auditor", name: "Digital Link Auditor", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/digital-link-auditor", url: "https://taxchecknow.com/uk/check/digital-link-auditor", apiRoute: "/api/rules/digital-link-auditor",
  authority: "HMRC", authorityUrl: "https://www.gov.uk", legalAnchor: "VAT Notice 700/22 — Making Tax Digital for VAT", legislation: "VAT Notice 700/22 — Digital Links requirement for MTD VAT", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Digital Link Audit Pack", tagline: "Is your VAT return process MTD-compliant — or are you copying and pasting?", value: "A personalised digital link audit showing your compliance gaps and the fastest fix for each one.", cta: "Get My Digital Link Pack — £67 →", productKey: "uk_67_digital_link_auditor", envVar: "STRIPE_UK_DLA_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your MTD VAT Compliance Plan", tagline: "Close every digital link gap before HMRC audits your process", value: "Full digital link audit plus spreadsheet bridge options, software comparison, and a compliance roadmap.", cta: "Get My Compliance Plan — £147 →", productKey: "uk_147_digital_link_auditor", envVar: "STRIPE_UK_DLA_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-08-07T23:59:59.000Z", display: "7 August 2026", short: "7 Aug 2026", description: "Next VAT return period end — digital links required for all MTD VAT returns", urgencyLabel: "VAT RETURN DUE", countdownLabel: "Countdown to next VAT return deadline" },
  h1: "MTD VAT Digital Links 2026: Is Your Process Actually Compliant?", metaTitle: "MTD VAT Digital Links 2026: Copy-Paste Fails HMRC — Check Your Process | TaxCheckNow", metaDescription: "Copying figures from your accounting software into your VAT return breaks the digital link requirement. Most businesses do not know this. HMRC can issue penalties for non-compliant processes. Check your VAT chain in 2 minutes.", canonical: "https://taxchecknow.com/uk/check/digital-link-auditor",
  answerHeadline: "The answer — HMRC confirmed April 2026",
  answerBody: [
    "Under MTD for VAT, there must be a digital link between every step in your VAT accounting process — from the original transaction records through to the final VAT return submission. A digital link means data is transferred electronically — not manually retyped or copy-pasted.",
    "The most common breach is copying figures from accounting software into a separate spreadsheet, then typing those figures into the HMRC portal. Every manual re-entry breaks the digital link chain. HMRC expects an unbroken electronic trail from source records to submission.",
    "Permitted digital links include: automated data feeds, API connections, CSV imports, and formulaic links within spreadsheets. Copy-paste between separate files breaks the chain. Manually typing a figure from one system to another breaks the chain.",
  ],
  answerSource: "Source: HMRC — VAT Notice 700/22 · MTD for VAT digital links",
  mistakesHeadline: "What most businesses get wrong about digital links",
  mistakes: [
    "Copying figures between spreadsheets is fine for MTD — wrong. Copy-paste between separate files or applications breaks the digital link. The link must be maintained electronically — through import, export, formula reference, or API. Manually copying a number is not digital.",
    "As long as you use accounting software you are compliant — wrong. The digital link must run all the way from source transaction to HMRC submission. If any step in your process involves manual retyping — even just one figure — the chain is broken.",
    "HMRC has not been enforcing digital links strictly — wrong. HMRC has been auditing VAT processes and issuing penalties for digital link failures. The soft-landing period ended in 2021. Non-compliance is a live risk.",
  ],
  chainVisual: { label: "The digital link chain — what HMRC requires", broken: "Accounting software → copy figures → spreadsheet → type into portal  ❌  Two breaks in the chain", fixed: "Accounting software → CSV import → bridging software → API submission  ✔  Unbroken digital chain" },
  brackets: [
    { label: "Fully digital — accounting software submits directly to HMRC",  value: 1, status: "clear"      },
    { label: "Spreadsheet with bridging software — compliant if links intact", value: 2, status: "approaching" },
    { label: "Copy-paste from software to spreadsheet to portal",              value: 3, status: "trap"        },
    { label: "Manual process — no digital records",                            value: 4, status: "deep_trap"   },
    { label: "Not sure how my VAT return is prepared",                         value: 5, status: "risk"        },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "vatProcess", label: "How is your VAT return currently prepared?", subLabel: "Be honest — HMRC sees the process not just the final return", options: [{ label: "Direct from accounting software", value: "direct" }, { label: "Spreadsheet with bridging tool", value: "bridged" }, { label: "Copy-paste from software to spreadsheet", value: "copypaste" }, { label: "Manual process", value: "manual" }], default: "copypaste" },
    { type: "twoButton", stateKey: "usesApprovedSoftware", label: "Do you use HMRC-recognised MTD VAT software?", subLabel: "QuickBooks, Xero, Sage, FreeAgent all qualify", options: [{ label: "Yes", value: true }, { label: "No — spreadsheet only", value: false }], default: true },
  ],
  tierAlgorithm: { description: "copypaste or manual vatProcess → tier2. No approved software → tier2.", tier2Conditions: ['vatProcess === "copypaste"', 'vatProcess === "manual"'], tier2Flags: ["usesApprovedSoftware"] },
  calculatorRuleBox: { label: "The digital link rule — HMRC confirmed", body: "Every transfer of data between software programs, applications, or products in the VAT accounting process must be made using a digital link. A digital link includes: automated feeds, API, CSV/XML import, or formulaic spreadsheet links. Copy-paste between separate files is NOT a digital link. Manual retyping is NOT a digital link. Source: VAT Notice 700/22." },
  calculatorClarification: { label: "Key clarification", body: "A formula within a single spreadsheet file IS a digital link. Copying a cell value from one Excel file into another Excel file is NOT a digital link — even if both files are on the same computer. The distinction is transfer method, not software type." },
  countdownLabel: "Next VAT return deadline",
  countdownStats: [
    { label: "Most common breach", value: "Copy-paste",   sub: "between files — not compliant" },
    { label: "Soft landing ended",  value: "April 2021",  sub: "HMRC now enforcing fully",      red: true },
    { label: "Bridging tool cost",  value: "Under £100",  sub: "per year — easy fix"           },
    { label: "VAT return periods",  value: "Quarterly",   sub: "every breach = potential penalty" },
  ],
  geoBlockTitle: "AI extraction block — MTD VAT digital links 2026",
  geoBlockH2: "MTD VAT Digital Links — confirmed rules 2026",
  geoBodyParagraph: "Under Making Tax Digital for VAT (VAT Notice 700/22), there must be a continuous digital link between source transaction records and the final VAT return submission to HMRC. A digital link is defined as a transfer of data that uses an electronic method — such as an API connection, automated feed, CSV import, or formulaic reference within a single spreadsheet. Copy-paste between separate files, manual retyping, and OCR scanning without digital output are not digital links. The requirement applies to all VAT-registered businesses from April 2021. Bridging software can maintain digital links where businesses use spreadsheets by creating an API connection between the spreadsheet and HMRC's systems.",
  geoFormula: "Digital link test: Is each data transfer between steps in your VAT process made electronically without manual retyping or copy-paste? YES = compliant. NO = digital link breach. Each breach = HMRC non-compliance exposure.",
  geoFacts: [
    { label: "Digital link requirement", value: "Mandatory from April 2021" },
    { label: "What qualifies", value: "API, CSV import, automated feed, spreadsheet formula" },
    { label: "What does not qualify", value: "Copy-paste, manual retyping, OCR without digital output" },
    { label: "Bridging software", value: "Connects spreadsheet to HMRC API — low cost fix" },
    { label: "Enforcement", value: "Active — soft landing ended April 2021" },
    { label: "Legal basis", value: "VAT Notice 700/22" },
  ],
  workedExamplesH2: "Four VAT process scenarios — compliant or not?",
  workedExamplesColumns: ["Process", "Digital Link Status", "Risk", "Fix"],
  workedExamples: [
    { name: "Xero direct API",        setup: "Xero submits directly to HMRC via API",                    income: "✅ Compliant",    status: "No action needed" },
    { name: "Spreadsheet + bridge",   setup: "Excel with BTC or Absolute BridgingTools",                 income: "✅ Compliant",    status: "Maintain bridge" },
    { name: "Sage → copy → portal",   setup: "Copies figures from Sage into separate spreadsheet",       income: "❌ Non-compliant", status: "Add bridging tool" },
    { name: "Manual ledger",          setup: "Handwritten records typed into HMRC portal",               income: "❌ Non-compliant", status: "Needs full solution" },
  ],
  comparisonH2: "Digital link methods — what qualifies",
  comparisonColumns: ["Transfer Method", "Digital Link?", "Notes"],
  comparisonRows: [
    { position: "API connection",          metric1: "Yes", metric2: "Gold standard",            bestMove: "Most compliant" },
    { position: "CSV/XML import",          metric1: "Yes", metric2: "Widely supported",         bestMove: "Compliant" },
    { position: "Spreadsheet formula",     metric1: "Yes", metric2: "Within same file only",    bestMove: "Must be single file" },
    { position: "Copy-paste",              metric1: "No",  metric2: "HMRC explicitly excludes", bestMove: "Non-compliant" },
    { position: "Manual retyping",         metric1: "No",  metric2: "Always non-compliant",     bestMove: "Non-compliant" },
  ],
  toolsH2: "Bridging software options for spreadsheet users",
  toolsColumns: ["Tool", "Best For", "Cost"],
  toolsRows: [
    { tool: "Absolute BridgingTools", effect: "Excel users — widely used", note: "From £40/year" },
    { tool: "BTC Software Bridge",    effect: "Accountant practices",       note: "From £75/year" },
    { tool: "DataDear",               effect: "Excel to HMRC direct",       note: "From £50/year" },
    { tool: "VT+ MTD",                effect: "Small businesses",           note: "From £50/year" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: As long as you use accounting software, you are MTD VAT compliant", correct: "Reality: The digital link must run unbroken from source records to submission. If any step involves copy-paste or manual retyping — even between files from the same software — the link is broken and you are non-compliant." },
    { wrong: "ChatGPT says: Copy-pasting from Excel to Excel is fine for MTD", correct: "Reality: HMRC explicitly states that copy-paste between separate files is not a digital link. The digital link must be maintained electronically — through import, API, or formulaic reference within a single file." },
  ],
  faqs: [
    { question: "What is a digital link for MTD VAT?", answer: "A digital link is an electronic transfer of data between steps in your VAT accounting process. It means data moves automatically — via API, CSV import, automated feed, or spreadsheet formula — without being manually retyped or copy-pasted. HMRC requires an unbroken digital link from source transaction records to the final VAT return submission." },
    { question: "Is copy-paste compliant for MTD VAT?", answer: "No. HMRC explicitly excludes copy-paste from its definition of a digital link. Even copying a value from one cell to another in a different file is non-compliant. The digital link must be maintained electronically." },
    { question: "Can I still use spreadsheets for MTD VAT?", answer: "Yes — but you need bridging software to maintain the digital link between your spreadsheet and HMRC's submission system. Bridging software costs from around £40 per year and connects your spreadsheet to HMRC's API, completing the digital chain." },
    { question: "What happens if I have a digital link breach?", answer: "A digital link breach is a VAT return compliance failure. HMRC can issue penalties under the MTD VAT regulations. The penalty amount depends on the nature and scale of the breach. HMRC has been auditing VAT processes since the soft landing ended in 2021." },
  ],
  accountantQuestionsH2: "Ask these before your next VAT return",
  accountantQuestions: [
    { q: "Can you confirm our VAT process has an unbroken digital link from source records to HMRC submission?", why: "Many accountants prepare VAT returns using processes inherited from before MTD. The digital link requirement is easy to miss and your accountant may not have audited the specific transfer steps." },
    { q: "Do we need bridging software — and if so, which one do you recommend?", why: "If you use spreadsheets anywhere in your VAT process, bridging software is likely needed. Your accountant can identify the gap and recommend a suitable tool." },
    { q: "What documentation should we keep to evidence our digital link compliance?", why: "If HMRC asks for evidence of digital links, you need to be able to show the chain of electronic transfers. Your accountant can advise on record keeping." },
  ],
  crosslink: { title: "Also coming up for MTD Income Tax?", body: "MTD ITSA is live from April 2026 for income over £50,000. If you are also self-employed or a landlord, check your Income Tax MTD position.", url: "/uk/check/mtd-scorecard", label: "Check your MTD Income Tax position →" },
  lawBarSummary: "MTD VAT digital links: unbroken electronic transfer required at every step from source records to HMRC submission. Copy-paste non-compliant. Bridging software available. Under VAT Notice 700/22.",
  lawBarBadges: ["HMRC", "VAT Notice 700/22", "MTD VAT", "Machine-readable JSON"],
  sources: [{ title: "HMRC — VAT Notice 700/22 — MTD digital links", url: "https://www.gov.uk/government/publications/vat-notice-70022-making-tax-digital-for-vat" }, { title: "Machine-readable JSON rules", url: "/api/rules/digital-link-auditor" }],
  files: [
    { num: "01", slug: "dl-01", name: "Your Digital Link Chain Audit", desc: "Map of your current VAT process and where digital links are broken.", tier: 1, content: `<h2>Digital Link Chain Audit</h2><div class="action-box"><h3>What HMRC Requires</h3><p>Every transfer of VAT data must be digital</p><p>No copy-paste between files</p><p>No manual retyping at any step</p></div><h2>Process Map</h2><table><tr><th>Step</th><th>Your Process</th><th>Digital Link?</th></tr><tr><td>Transactions to software</td><td>Bank feed or manual entry</td><td>Check</td></tr><tr><td>Software to VAT summary</td><td>Direct or export</td><td>Check</td></tr><tr><td>VAT summary to submission</td><td>API or manual</td><td>Check</td></tr></table>` },
    { num: "02", slug: "dl-02", name: "Bridging Software Selection Guide", desc: "The right bridging tool for your spreadsheet setup.", tier: 1, content: `<h2>Bridging Software Options</h2><table><tr><th>Tool</th><th>Cost</th><th>Best for</th></tr><tr><td>Absolute BridgingTools</td><td>From £40/year</td><td>Excel users</td></tr><tr><td>BTC Software</td><td>From £75/year</td><td>Practices</td></tr><tr><td>DataDear</td><td>From £50/year</td><td>Excel power users</td></tr></table>` },
    { num: "03", slug: "dl-03", name: "Digital Link Evidence Pack", desc: "What to keep to evidence compliance if HMRC audits your process.", tier: 1, content: `<h2>Evidence Pack</h2><p>Keep records of your digital link process including: software screenshots, CSV import logs, API submission confirmations, and process documentation.</p><div class="action-box"><h3>Minimum Evidence</h3><p>Screenshot of software to submission chain</p><p>Bridging software account confirmation</p><p>VAT submission confirmations from HMRC</p></div>` },
    { num: "04", slug: "dl-04", name: "Accountant Brief — Digital Links", desc: "Questions for your accountant about VAT digital link compliance.", tier: 1, content: `<h2>Digital Link Questions</h2><h3>Question 1</h3><p>"Can you confirm our VAT process has an unbroken digital link?"</p><h3>Question 2</h3><p>"Do we need bridging software?"</p><h3>Question 3</h3><p>"What records should we keep?"</p>` },
    { num: "05", slug: "dl-05", name: "VAT Return Process Checklist", desc: "Step-by-step compliant VAT return process.", tier: 1, content: `<h2>Compliant VAT Return Process</h2><ul class="checklist"><li>All transactions recorded in approved software</li><li>Data exported via CSV or API — not copy-pasted</li><li>Bridging software connected to HMRC (if spreadsheet used)</li><li>Submission made via API — not manual portal entry</li><li>Submission confirmation saved</li></ul>` },
    { num: "06", slug: "dl-06", name: "Full Software Migration Guide", desc: "Moving from spreadsheets to fully digital accounting software.", tier: 2, content: `<h2>Moving to Fully Digital Software</h2><p>If your process has multiple compliance gaps, migrating to fully integrated accounting software may be simpler than adding bridging tools at each break.</p><div class="action-box"><h3>Migration Options</h3><p>QuickBooks: from £10/month — direct HMRC submission</p><p>Xero: from £15/month — accountant-friendly</p><p>FreeAgent: free with some bank accounts</p></div>` },
    { num: "07", slug: "dl-07", name: "Multi-Entity VAT Group Guide", desc: "Digital link requirements for VAT groups with multiple legal entities.", tier: 2, content: `<h2>VAT Groups and Digital Links</h2><p>Businesses that file a combined VAT return for a group of companies must maintain digital links across all entities in the group. Each subsidiary's data must flow digitally to the representative member's return.</p>` },
    { num: "08", slug: "dl-08", name: "HMRC Compliance Check Response", desc: "What to do if HMRC asks about your digital link process.", tier: 2, content: `<h2>Responding to HMRC Compliance Checks</h2><p>If HMRC contacts you about VAT digital link compliance, respond promptly and provide your process documentation. Co-operation typically results in more favourable outcomes than delay.</p><div class="action-box"><h3>Response Steps</h3><p>1. Review your process immediately</p><p>2. Identify and document any gaps</p><p>3. Implement fixes before responding</p><p>4. Provide evidence of current compliance</p></div>` },
  ],
  calendarTitle: "Digital Link — VAT Return Dates",
  tier1Calendar: [{ uid: "dl-vat1", summary: "VAT Return — Digital Link Check", description: "Before submitting your next VAT return, confirm your digital link chain is complete.", date: "relative:+7days" }],
  tier2Calendar: [{ uid: "dl-audit", summary: "Digital Link — Full Process Audit", description: "Complete digital link audit and implement any bridging software needed.", date: "relative:+14days" }, { uid: "dl-vat1", summary: "VAT Return — Digital Link Confirmed", description: "Submit next VAT return with confirmed compliant digital link chain.", date: "relative:+30days" }],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.gov.uk/government/publications/vat-notice-70022-making-tax-digital-for-vat"],
  sidebarNumbers: [{ label: "Most common breach", value: "Copy-paste" }, { label: "Bridging tool cost", value: "From £40/yr" }, { label: "Soft landing ended", value: "April 2021" }, { label: "VAT returns per year", value: "4 (quarterly)" }],
  sidebarMathsTitle: "What makes a digital link",
  sidebarMathsIncludes: ["API connection", "CSV/XML import", "Automated feed", "Spreadsheet formula (same file)"],
  sidebarMathsExcludes: ["NOT copy-paste between files", "NOT manual retyping", "NOT OCR without digital output"],
  sidebarMathsNote: "Source: HMRC — VAT Notice 700/22",
  howToSteps: [{ position: 1, name: "Describe your VAT process", text: "Select how your VAT return is currently prepared." }, { position: 2, name: "Check your software", text: "Confirm whether you use HMRC-recognised MTD VAT software." }, { position: 3, name: "Get your compliance verdict", text: "See exactly where your digital link chain is broken and what you need to fix." }],
  successPromptFields: [{ key: "dl_process", label: "VAT process", defaultVal: "copypaste" }, { key: "dl_software", label: "Uses approved software", defaultVal: "true" }],
  tier1AssessmentFields: ["status", "breachPoints", "fixRequired", "bridgingOption", "firstAction"],
  tier2AssessmentFields: ["status", "breachPoints", "fixRequired", "bridgingOption", "migrationOption", "actions", "weekPlan"],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary, £38k dividends. Birmingham rental flat. Same accountant his dad used — once a year in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story.",
    discovery: "James searched after getting an HMRC letter — not threatening, just a reminder that made him realise he had no idea if his numbers were right.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "James had been filing VAT returns for eleven years. He assumed he had been doing it right.",
    setup: [
    "Hartley Precision is VAT registered. James's bookkeeper Karen exports figures from the job management system into a spreadsheet, adjusts a few numbers, then Dave's office manually inputs them into the VAT return.",
    "James heard MTD for VAT was already in force. He was pretty sure they were compliant. Karen had said something about it. But when he tried to explain their process to a supplier who asked, he realised he could not actually describe it clearly.",
    "The issue, he would later learn, is not whether you use software. It is whether your data moves between systems without human retyping — what HMRC calls a digital link. Copy-pasting from a spreadsheet into the return software breaks the chain.",
    ],
    revelation: "The audit showed three broken digital links in their current process. The export from the job system was fine. But Karen's manual adjustments and the retyping into the return software both broke the MTD requirement. They were technically non-compliant.",
    resolution: "They fixed it in a week. The job system had a direct HMRC submission API they had never turned on. Cost: nothing. Time: one afternoon.",
  },
};
