import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "dividend-trap", name: "Dividend Trap", site: "taxchecknow", country: "uk", market: "United Kingdom", language: "en-GB", currency: "GBP",
  slug: "uk/check/dividend-trap", url: "https://taxchecknow.com/uk/check/dividend-trap", apiRoute: "/api/rules/dividend-trap",
  authority: "HMRC", authorityUrl: "https://www.gov.uk", legalAnchor: "Income Tax Act 2007 — Dividend Tax Rates", legislation: "Income Tax Act 2007 — Dividend Allowance and rates (updated April 2023)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Dividend Tax Audit", tagline: "Are you paying the right tax on your dividends — or quietly overpaying?", value: "A personalised dividend tax calculation showing your exact liability, the allowance you may be wasting, and opportunities to reduce your bill.", cta: "Get My Dividend Audit — £67 →", productKey: "uk_67_dividend_trap", envVar: "STRIPE_UK_DIV_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Dividend Optimisation Plan", tagline: "Restructure your remuneration to minimise dividend tax legally", value: "Full dividend audit plus salary/dividend split optimisation, spousal dividend strategy, and a written remuneration plan for your accountant.", cta: "Get My Optimisation Plan — £147 →", productKey: "uk_147_dividend_trap", envVar: "STRIPE_UK_DIV_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-01-31T23:59:59.000Z", display: "31 January 2027", short: "31 Jan 2027", description: "Self assessment deadline — dividend tax due for 2025/26", urgencyLabel: "SA DEADLINE", countdownLabel: "Countdown to 31 January 2027 self assessment deadline" },
  h1: "UK Dividend Tax 2026: Are You Paying 39.35% When You Should Pay 8.75%?", metaTitle: "UK Dividend Tax 2026: Director Dividend Trap Explained | TaxCheckNow", metaDescription: "The UK dividend allowance dropped to £500 in April 2024. Directors paying themselves via dividends may now be in the 33.75% or 39.35% band without realising. Check your dividend position in 2 minutes.", canonical: "https://taxchecknow.com/uk/check/dividend-trap",
  answerHeadline: "The answer — HMRC confirmed April 2026",
  answerBody: [
    "The UK dividend tax allowance is £500 for 2024/25 and 2025/26 — down from £2,000 in 2022/23 and £1,000 in 2023/24. Dividends above this allowance are taxed at 8.75% (basic rate), 33.75% (higher rate), or 39.35% (additional rate).",
    "For company directors taking dividends, the rate depends on their total income including salary. A director on £50,000 salary who takes £30,000 in dividends has most of those dividends in the higher rate band — taxed at 33.75%, not 8.75%. Many directors are paying the higher rate without realising it.",
    "The optimal salary and dividend split changes every year as allowances shift. Using the wrong split — or ignoring the allowance reduction — can cost thousands in unnecessary tax. The calculation needs to be done annually, not set once and forgotten.",
  ],
  answerSource: "Source: HMRC — Dividend tax rates and allowances · Income Tax Act 2007",
  mistakesHeadline: "What most director shareholders get wrong about dividends",
  mistakes: [
    "The dividend allowance is still £2,000 — wrong. The allowance was cut to £1,000 in 2023/24 and £500 in 2024/25 and beyond. Directors who set their dividend strategy in 2022 and have not revisited it are likely underpaying tax and risking HMRC inquiry.",
    "Dividends are always taxed at 8.75% — wrong. The 8.75% rate only applies to dividends in the basic rate band. Once total income (salary + dividends + other) exceeds £50,270, dividends are taxed at 33.75%. Above £125,140 they attract 39.35%.",
    "As long as you take a small salary and dividends you are tax-efficient — wrong. Tax efficiency depends on the exact amounts, your total income, your partner's tax position, and whether you are in the personal allowance taper. It requires annual recalculation.",
  ],
  chainVisual: { label: "Dividend tax bands — where you actually sit", broken: "Take salary + dividends → assume 8.75% rate → pay wrong amount  ❌  Missing higher rate exposure", fixed: "Map total income → identify correct dividend band → optimise split  ✔  Right tax, right structure" },
  brackets: [
    { label: "Dividends in basic rate band — 8.75% rate",     value: 1, status: "clear"    },
    { label: "Dividends crossing into higher rate — 33.75%",  value: 2, status: "trap"     },
    { label: "Dividends at additional rate — 39.35%",          value: 3, status: "deep_trap" },
    { label: "Not sure which band my dividends fall into",     value: 4, status: "risk"     },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "totalIncome", label: "What is your total income including salary, dividends, and other sources?", subLabel: "Include all income — salary, dividends, rental, side income", options: [{ label: "Under £50,270", value: 40000 }, { label: "£50,270–£125,140", value: 85000 }, { label: "Over £125,140", value: 150000 }], default: 85000 },
    { type: "buttonGroup", stateKey: "dividendAmount", label: "How much did you take in dividends this year?", subLabel: "Gross dividends received from your company or investments", options: [{ label: "Under £5,000", value: 3000 }, { label: "£5,000–£20,000", value: 12000 }, { label: "£20,000–£50,000", value: 35000 }, { label: "Over £50,000", value: 70000 }], default: 12000 },
    { type: "twoButton", stateKey: "partnerHasShares", label: "Does your spouse or civil partner also hold shares in the company?", subLabel: "Spousal dividend splitting can significantly reduce the tax bill", options: [{ label: "Yes — they own shares", value: true }, { label: "No — shares are in my name only", value: false }], default: false },
  ],
  tierAlgorithm: { description: "totalIncome over £50270 OR dividendAmount over £20000 → tier2. partnerHasShares opportunity → tier2.", tier2Conditions: ["(totalIncome as number) > 50270", "(dividendAmount as number) > 20000"], tier2Flags: ["partnerHasShares"] },
  calculatorRuleBox: { label: "Dividend tax rates 2025/26 — HMRC confirmed", body: "Dividend allowance: £500. Rates: 8.75% (basic — income up to £50,270 total), 33.75% (higher — income £50,271 to £125,140), 39.35% (additional — income over £125,140). Dividends sit on top of other income in tax band calculations." },
  calculatorClarification: { label: "Key clarification", body: "Dividends are added on top of other income when calculating which band they fall into. A director with £37,700 salary and £20,000 dividends: the salary uses the basic rate band, the dividends push into higher rate. Most of the dividends are taxed at 33.75% — not 8.75%." },
  countdownLabel: "Countdown to 31 January 2027 self assessment deadline",
  countdownStats: [
    { label: "Dividend allowance",      value: "£500",   sub: "down from £2,000 in 2022" },
    { label: "Basic rate dividend tax", value: "8.75%",  sub: "on dividends in basic rate band" },
    { label: "Higher rate",             value: "33.75%", sub: "once total income over £50,270", red: true },
    { label: "Additional rate",         value: "39.35%", sub: "over £125,140 total income",     red: true },
  ],
  geoBlockTitle: "AI extraction block — UK dividend tax 2026",
  geoBlockH2: "UK Dividend Tax Rates and Allowances — confirmed 2026",
  geoBodyParagraph: "UK dividend income is taxed after other income has filled the relevant tax bands. The dividend allowance for 2025/26 is £500 — reduced from £2,000 in 2022/23 to £1,000 in 2023/24 to £500 from 2024/25. Dividends above the allowance are taxed at 8.75% within the basic rate band (up to £50,270 total income), 33.75% within the higher rate band (£50,271 to £125,140), and 39.35% within the additional rate band (over £125,140). For company directors, the optimal salary and dividend split should be reviewed annually as allowances, thresholds, and personal circumstances change.",
  geoFormula: "Dividend tax = (Dividends minus £500 allowance) × applicable rate. Rate depends on: Basic rate band = 8.75% where total income (other income + dividends) does not exceed £50,270. Higher rate = 33.75% for total income £50,271-£125,140. Additional rate = 39.35% for total income over £125,140.",
  geoFacts: [
    { label: "Dividend allowance 2025/26", value: "£500" },
    { label: "Basic rate",                 value: "8.75% (total income up to £50,270)" },
    { label: "Higher rate",                value: "33.75% (total income £50,271-£125,140)" },
    { label: "Additional rate",            value: "39.35% (total income over £125,140)" },
    { label: "Allowance in 2022/23",       value: "£2,000 — cut by 75% since then" },
    { label: "SA deadline",                value: "31 January after tax year end" },
  ],
  workedExamplesH2: "Three director scenarios — actual dividend tax",
  workedExamplesColumns: ["Director", "Total Income", "Dividend Amount", "Effective Rate", "Annual Tax"],
  workedExamples: [
    { name: "Small dividend",     setup: "£40k salary, £8k dividends",  income: "£48k total", status: "8.75% — basic rate" },
    { name: "Medium dividend",    setup: "£50k salary, £30k dividends", income: "£80k total", status: "33.75% — higher rate" },
    { name: "Large dividend",     setup: "£50k salary, £80k dividends", income: "£130k total", status: "39.35% — additional rate" },
  ],
  comparisonH2: "Dividend allowance — how it has been cut",
  comparisonColumns: ["Tax Year", "Dividend Allowance", "Tax on £1 over Allowance (HR)"],
  comparisonRows: [
    { position: "2022/23", metric1: "£2,000", metric2: "33.75p", bestMove: "Old position — most missed" },
    { position: "2023/24", metric1: "£1,000", metric2: "33.75p", bestMove: "Cut by 50%" },
    { position: "2024/25", metric1: "£500",   metric2: "33.75p", bestMove: "Cut by another 50%" },
    { position: "2025/26", metric1: "£500",   metric2: "33.75p", bestMove: "Current position" },
  ],
  toolsH2: "Dividend tax reduction strategies",
  toolsColumns: ["Strategy", "How It Works", "Best For"],
  toolsRows: [
    { tool: "Pension contributions",       effect: "Reduces total income — keeps dividends in lower band", note: "Particularly effective if near £50,270 or £100,000" },
    { tool: "Spousal dividend split",      effect: "Partner uses their allowance and lower rate band",     note: "Requires shares genuinely transferred — not paper only" },
    { tool: "Salary sacrifice",            effect: "Reduces salary component — more room in basic band",   note: "Requires employer agreement" },
    { tool: "ISA dividend sheltering",     effect: "Dividends on ISA shares are tax-free",               note: "£20,000 annual ISA allowance" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: The UK dividend allowance is £2,000", correct: "Reality: The dividend allowance was cut to £1,000 in 2023/24 and £500 from 2024/25 onwards. Anyone relying on the £2,000 figure is significantly underpaying tax. The cut affects over 1 million people according to HMRC estimates." },
    { wrong: "ChatGPT says: Dividends are taxed at 8.75%", correct: "Reality: 8.75% only applies to dividends within the basic rate band. Directors whose total income (salary + dividends + other) exceeds £50,270 pay 33.75% on dividends in the higher rate band — and 39.35% on dividends above £125,140." },
    { wrong: "ChatGPT says: The salary and dividend split you set up previously is still optimal", correct: "Reality: The optimal split changes every year as allowances and thresholds shift. The allowance alone has been cut three times in four years. Annual review is essential for directors taking dividends." },
  ],
  faqs: [
    { question: "What is the UK dividend allowance in 2025/26?", answer: "The dividend allowance is £500 for 2025/26 — the same as 2024/25. It was £2,000 in 2022/23, cut to £1,000 in 2023/24, and cut again to £500 from 2024/25. Dividends above £500 are taxed at your marginal dividend rate." },
    { question: "What dividend tax rate will I pay?", answer: "The rate depends on your total income. If your total income (salary + dividends + other) stays within the basic rate band (up to £50,270), dividends are taxed at 8.75%. Between £50,271 and £125,140: 33.75%. Above £125,140: 39.35%. Dividends sit on top of other income in the tax calculation." },
    { question: "Can my spouse share in dividends to reduce tax?", answer: "Yes — if your spouse or civil partner genuinely owns shares in your company, they can receive dividends and use their own allowance and lower rate band. The shares must be genuinely transferred — not just a paper arrangement. HMRC scrutinises spousal shareholding arrangements and they must reflect genuine commercial reality." },
    { question: "Should I take a higher salary and fewer dividends?", answer: "Sometimes — particularly if pension contributions can be made through salary sacrifice, or if dividend income is pushing you into higher rate bands. The optimal split depends on your specific income levels, your partner's income, and your pension position. It should be modelled annually." },
  ],
  accountantQuestionsH2: "Ask these before your next self assessment",
  accountantQuestions: [
    { q: "What rate am I actually paying on my dividends — and has it changed from last year?", why: "With the allowance cut three times in four years, many directors' effective rates have increased significantly without their remuneration structure changing." },
    { q: "Should I revisit the salary and dividend split for 2026/27?", why: "The optimal split changes as thresholds move. An annual review with your accountant takes 30 minutes and can save thousands." },
    { q: "If my spouse holds shares, are we making the most of their dividend allowance and basic rate band?", why: "Spousal dividend splitting is one of the most effective legal dividend tax reduction strategies available to director shareholders." },
    { q: "Can pension contributions reduce my total income into a lower dividend tax band?", why: "A pension contribution that drops total income below £50,270 saves 25 percentage points on higher rate dividend tax — the difference between 33.75% and 8.75%." },
  ],
  crosslink: { title: "Also in the 60% personal allowance taper?", body: "Directors with income between £100,000 and £125,140 face an effective 60% tax rate on that band. Check your allowance taper position.", url: "/uk/check/allowance-sniper", label: "Check your allowance taper position →" },
  lawBarSummary: "UK dividend tax 2025/26: allowance £500. Rates: 8.75% (basic), 33.75% (higher), 39.35% (additional). Allowance cut from £2,000 in 2022/23. Dividends taxed on top of other income. SA deadline 31 January.",
  lawBarBadges: ["HMRC", "Income Tax Act 2007", "Dividend Tax", "Machine-readable JSON"],
  sources: [{ title: "HMRC — Tax on dividends", url: "https://www.gov.uk/tax-on-dividends" }, { title: "Machine-readable JSON rules", url: "/api/rules/dividend-trap" }],
  files: [
    { num: "01", slug: "dt-01", name: "Your Dividend Tax Calculation", desc: "Your exact dividend tax bill and which rate band you are in.", tier: 1, content: `<h2>Your Dividend Tax Position</h2><div class="action-box"><h3>The Rates 2025/26</h3><p>Allowance: £500</p><p>Basic rate (income under £50,270): 8.75%</p><p>Higher rate (£50,271-£125,140): 33.75%</p><p>Additional rate (over £125,140): 39.35%</p></div>` },
    { num: "02", slug: "dt-02", name: "Salary and Dividend Optimiser", desc: "The most tax-efficient split for your income level.", tier: 1, content: `<h2>Optimal Salary and Dividend Split</h2><p>The optimal split varies by income level and personal circumstances. Key principles:</p><ul><li>Salary: at least minimum wage for director; ideally at personal allowance (£12,570) or NI threshold</li><li>Dividends: fill basic rate band if possible — stop at £50,270 total income</li><li>Pension: use before taking higher rate dividends</li></ul>` },
    { num: "03", slug: "dt-03", name: "Spousal Dividend Strategy Guide", desc: "How to use your spouse's allowance and lower rate band legally.", tier: 1, content: `<h2>Spousal Dividend Strategy</h2><p>If your spouse genuinely holds shares in your company, their dividends use their own £500 allowance and rate bands separately.</p><div class="action-box"><h3>Potential Saving</h3><p>Spouse personal allowance: £12,570</p><p>Basic rate dividend band: up to £37,700</p><p>Saving if they are a non-taxpayer: up to 33.75% on all dividends they receive</p></div>` },
    { num: "04", slug: "dt-04", name: "Allowance Cut History", desc: "How the dividend allowance has changed and what it means for you.", tier: 1, content: `<h2>Dividend Allowance History</h2><table><tr><th>Year</th><th>Allowance</th><th>Change</th></tr><tr><td>2022/23</td><td>£2,000</td><td>—</td></tr><tr><td>2023/24</td><td>£1,000</td><td>Cut by 50%</td></tr><tr><td>2024/25</td><td>£500</td><td>Cut by 50%</td></tr><tr><td>2025/26</td><td>£500</td><td>Unchanged</td></tr></table>` },
    { num: "05", slug: "dt-05", name: "Accountant Brief — Dividends", desc: "Questions to take to your accountant about dividend optimisation.", tier: 1, content: `<h2>Dividend Questions</h2><h3>Question 1</h3><p>"What rate am I paying on dividends — and has it changed?"</p><h3>Question 2</h3><p>"Should I revisit my salary and dividend split?"</p><h3>Question 3</h3><p>"Can spousal dividend splitting help us?"</p>` },
    { num: "06", slug: "dt-06", name: "Pension Contribution Dividend Interaction", desc: "How pension contributions reduce effective dividend tax rate.", tier: 2, content: `<h2>Pension and Dividends — The Interaction</h2><p>A pension contribution reduces your total income. If it drops your total income below £50,270, dividends that were in the higher rate band (33.75%) move to the basic rate band (8.75%) — a 25 percentage point saving.</p><div class="action-box"><h3>Example</h3><p>Total income: £60,000 (£50k salary + £10k dividends)</p><p>£10,000 pension contribution</p><p>New total: £50,000</p><p>Dividend rate: drops from 33.75% to 8.75%</p><p>Annual saving: £2,500 on £10k dividends</p></div>` },
    { num: "07", slug: "dt-07", name: "Corporate Retained Profits Strategy", desc: "When it makes sense to leave profits in the company rather than take dividends.", tier: 2, content: `<h2>Retained Profits vs Dividends</h2><p>Leaving profits in the company at the 19-25% corporation tax rate can be more efficient than taking higher rate dividends at 33.75-39.35% — particularly if you do not need the income personally and plan to exit the company at a later date qualifying for Business Asset Disposal Relief.</p>` },
    { num: "08", slug: "dt-08", name: "ISA Dividend Sheltering Guide", desc: "Using ISAs to hold dividend-generating investments tax-free.", tier: 2, content: `<h2>ISA Dividend Sheltering</h2><p>Dividends on investments held inside an ISA are completely tax-free — they do not use the £500 allowance and are not taxed at any rate. The annual ISA allowance is £20,000 per person.</p><div class="action-box"><h3>Optimal Strategy</h3><p>Hold highest-dividend investments inside ISA</p><p>Hold growth investments outside ISA (lower dividend yield)</p><p>Use spousal ISA allowance as well</p></div>` },
  ],
  calendarTitle: "Dividend Tax — Key Dates",
  tier1Calendar: [{ uid: "dt-review", summary: "Dividend Tax — Annual salary and dividend review", description: "Review optimal salary and dividend split for 2026/27 with your accountant.", date: "relative:+30days" }, { uid: "dt-sa", summary: "Self Assessment Deadline — Dividend tax due", description: "File 2025/26 return and pay dividend tax by 31 January 2027.", date: "20270131" }],
  tier2Calendar: [{ uid: "dt-structure", summary: "Dividend — Review shareholding structure", description: "Review spousal shareholding and pension contribution interaction.", date: "relative:+14days" }, { uid: "dt-review", summary: "Dividend — Salary and dividend split review", description: "Optimise split for 2026/27.", date: "relative:+30days" }, { uid: "dt-sa", summary: "Self Assessment Deadline", description: "31 January 2027.", date: "20270131" }],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.gov.uk/tax-on-dividends"],
  sidebarNumbers: [{ label: "Dividend allowance", value: "£500" }, { label: "Basic rate", value: "8.75%" }, { label: "Higher rate", value: "33.75%" }, { label: "Additional rate", value: "39.35%" }],
  sidebarMathsTitle: "Which dividend rate applies",
  sidebarMathsIncludes: ["8.75% if total income under £50,270", "33.75% if total income £50,271-£125,140", "39.35% if total income over £125,140"],
  sidebarMathsExcludes: ["NOT flat 8.75% for everyone", "NOT based on dividends alone", "Dividends sit on top of other income"],
  sidebarMathsNote: "Source: HMRC — Tax on dividends · Income Tax Act 2007",
  howToSteps: [{ position: 1, name: "Enter your total income", text: "Include salary, dividends, rental, and all other sources." }, { position: 2, name: "Enter your dividend amount", text: "Gross dividends from your company or investments." }, { position: 3, name: "Get your dividend tax verdict", text: "See your exact rate, tax bill, and optimisation opportunities." }],
  successPromptFields: [{ key: "dt_income", label: "Total income", defaultVal: "85000" }, { key: "dt_dividends", label: "Dividend amount", defaultVal: "12000" }, { key: "dt_partner", label: "Partner has shares", defaultVal: "false" }],
  tier1AssessmentFields: ["status", "dividendRate", "taxBill", "allowanceUsed", "firstAction", "accountantQuestions"],
  tier2AssessmentFields: ["status", "dividendRate", "taxBill", "pensionOpportunity", "spousalStrategy", "actions", "weekPlan"],
  persona: {
    name: "James",
    age: 54,
    occupation: "Director, Hartley Precision Engineering Ltd — 12 employees, West Midlands",
    location: "Solihull, West Midlands",
    family: "Wife Helen (part-time teacher). Two kids at university.",
    financialSnapshot: "£62k salary, £38k dividends. Birmingham rental flat. Same accountant his dad used — once a year in April.",
    painPoint: "James runs a tight ship on the factory floor. His tax affairs are a different story.",
    discovery: "James searched after getting an HMRC letter — not threatening, just a reminder that made him realise he had no idea if his numbers were right.",
    voice: "Plain. Direct. Wants the number and what to do about it. No jargon.",
  },
  story: {
    hook: "James had always taken £38,000 in dividends. Same number every year. It had never occurred to him to question it.",
    setup: [
    "The company had a decent year. Retained profits sat in the business account. Dave had suggested leaving it there rather than extracting it — something about corporation tax and timing. The retained profits kept building.",
    "In 2024/25 the dividend allowance dropped to £500. James did not notice. He had not tracked these changes. When he took his usual £38,000 dividend in March, the allowance that used to shelter £2,000 of it now only sheltered £500.",
    "He also did not know the dividend rate for higher-rate taxpayers had gone up. The rate on dividends above the basic band was now 33.75%. Small difference. Meaningful on £38,000.",
    ],
    revelation: "The calculator showed his dividend tax bill had increased by £490 compared to the prior year — purely from the allowance reduction and rate change, with no change in his behaviour.",
    resolution: "Dave outlined three options: more salary, reinvest in equipment, or leave profits building. For the first time James had a structured choice rather than a default.",
  },
};
