import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "iso-amt-sniper", name: "ISO AMT Exercise Sniper", site: "taxchecknow", country: "us", market: "United States", language: "en-US", currency: "USD",
  slug: "us/check/iso-amt-sniper", url: "https://taxchecknow.com/us/check/iso-amt-sniper", apiRoute: "/api/rules/iso-amt-sniper",
  authority: "IRS", authorityUrl: "https://www.irs.gov", legalAnchor: "IRC Section 56(b)(3)", legislation: "IRC Section 56(b)(3) — Alternative Minimum Tax on ISO Exercise Spread", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Zero-AMT Exercise Map", tagline: "How many shares can you safely exercise without triggering AMT?", value: "A personalised ISO exercise analysis built around your salary, your options, and your exact safe exercise range.", cta: "Get My Exercise Map — $67 →", productKey: "us_67_iso_amt_sniper", envVar: "STRIPE_US_ISO_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your AMT Recovery System", tagline: "Turn your AMT tax loss into a recoverable asset with Form 8801", value: "A personalised ISO exercise analysis plus multi-year AMT credit recovery plan, disqualifying disposition strategy, and dual basis tracker.", cta: "Get My Recovery System — $147 →", productKey: "us_147_iso_amt_sniper", envVar: "STRIPE_US_ISO_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-12-31T23:59:59.000-05:00", display: "December 31, 2026", short: "Dec 31 2026", description: "Year-end deadline for ISO exercise decisions — AMT calculated on calendar year basis", urgencyLabel: "YEAR-END DEADLINE", countdownLabel: "Countdown to December 31, 2026 — ISO exercise decision deadline" },
  h1: "The 2026 ISO Exercise Sniper: Avoid a $150K Phantom Tax Bill", metaTitle: "ISO AMT 2026: How Many Shares Can You Exercise Without Triggering AMT? | TaxCheckNow", metaDescription: "Exercising ISOs triggers AMT on the bargain element (FMV minus strike price) — even if you cannot sell the shares. Most employees trigger AMT without realising it. Find your safe exercise range instantly.", canonical: "https://taxchecknow.com/us/check/iso-amt-sniper",
  answerHeadline: "The answer — IRS confirmed April 2026",
  answerBody: [
    "Exercising ISOs triggers AMT at exercise — not at sale. The taxable AMT spread equals the difference between the fair market value and the strike price, multiplied by shares exercised. This creates a real tax liability on paper gains even when shares are illiquid and no cash has been received.",
    "Exercising Incentive Stock Options (ISOs) can trigger the Alternative Minimum Tax (AMT). The bargain element — the spread between the 409A fair market value and your strike price — is treated as AMT income at the moment of exercise, even if you cannot sell the shares.",
    "This creates a six-figure tax bill with zero cash liquidity. Exercising 10,000 options with a $50 spread generates $500,000 of AMT income and approximately $150,000 of AMT — owed in April even if the shares are illiquid and worth nothing in cash terms.",
    "The safe exercise range is the number you need — how many shares you can exercise before AMT kicks in. Most employees never calculate this. They exercise their full grant and receive a tax bill they cannot pay.",
  ],
  answerSource: "Source: IRC §56(b)(3) (ISO AMT spread) · IRC §53 (AMT credit) · IRS Form 6251 instructions · IRS Form 8801 · IRS Form 3921 · Confirmed April 2026",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "ISOs are tax-free until you sell the shares — wrong. ISO exercise creates AMT income immediately at the spread (FMV minus strike). The tax is due in April of the year you exercise, not when you sell.",
    "AMT is rare and does not affect most employees — wrong. Any employee with significant ISO grants at a growing company is at risk. The AMT exemption phases out rapidly at higher income levels.",
    "AMT is a permanent tax — wrong. AMT paid on ISO exercise creates a Minimum Tax Credit (Form 8801) that can be recovered in future years when your regular tax exceeds your tentative minimum tax.",
  ],
  chainVisual: { label: "The ISO AMT trap — exercise without planning", broken: "Exercise full grant (10,000 shares @ $50 spread)  →  $500k AMT income  →  $150k tax bill  →  No cash to pay  ❌", fixed: "Exercise safe range (2,100 shares)  →  Stay below AMT threshold  →  $0 AMT  →  Full liquidity preserved  ✔" },
  brackets: [
    { label: "Under 1,000 shares with small spread (under $10)", value: 1, status: "clear" },
    { label: "1,000–5,000 shares with moderate spread ($10–$50)", value: 2, status: "approaching" },
    { label: "5,000–20,000 shares with significant spread ($50–$100)", value: 3, status: "trap" },
    { label: "Over 20,000 shares or spread above $100", value: 4, status: "deep_trap" },
    { label: "Not sure of my spread or 409A valuation", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "salary", label: "Your total annual salary and bonus", subLabel: "Used to calculate AMT exemption phaseout and regular tax baseline", options: [{ label: "Under $100k", value: 80_000 }, { label: "$100k–$200k", value: 150_000 }, { label: "$200k–$400k", value: 300_000 }, { label: "Over $400k", value: 500_000 }], default: 150_000 },
    { type: "buttonGroup", stateKey: "isoShares", label: "How many ISOs are you considering exercising?", subLabel: "Enter the number of shares — not the value", options: [{ label: "Under 2,000", value: 1_000 }, { label: "2,000–5,000", value: 3_500 }, { label: "5,000–15,000", value: 10_000 }, { label: "Over 15,000", value: 25_000 }], default: 3_500 },
    { type: "buttonGroup", stateKey: "spread", label: "What is your spread? (FMV minus strike price per share)", subLabel: "Use current 409A valuation minus your strike price", options: [{ label: "Under $10", value: 5 }, { label: "$10–$50", value: 30 }, { label: "$50–$150", value: 100 }, { label: "Over $150", value: 250 }], default: 30 },
  ],
  tierAlgorithm: { description: "isoShares exceeds 5000 AND spread exceeds 50 → tier2. salary exceeds 300000 → tier2. Otherwise tier1.", tier2Conditions: ["isoShares > 5000 && spread > 50", "salary > 300000"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — IRS confirmed (IRC §56(b)(3) · Form 6251)", body: "ISO exercise spread (FMV − strike) × shares = AMT preference income. Added to regular income to calculate tentative minimum tax. If tentative minimum tax exceeds regular tax → AMT owed. Form 6251 required at exercise. AMT credit (IRC §53 · Form 8801) recoverable in future years. Employer reports exercise on Form 3921. SAFE EXERCISE RANGE: (1) Start with AMT exemption ($88,100 single 2025). (2) Subtract other income already in AMT territory. (3) Remaining headroom = max AMT spread you can recognise without triggering AMT. (4) Divide by (FMV − strike) per share = max shares safe to exercise. Example: $88,100 exemption − $30,000 salary AMT income = $58,100 headroom ÷ $40 spread per share = 1,452 shares safe to exercise this year." },
  calculatorClarification: { label: "⚠️ key clarification", body: "You do not need to sell your shares to owe AMT. The tax is triggered at exercise, not at sale. If your company has not IPO'd and shares are illiquid, you still owe the AMT in April of the year you exercised. This is the liquidity trap." },
  countdownLabel: "Countdown to December 31, 2026 — ISO exercise decision deadline",
  countdownStats: [
    { label: "What employees think",  value: "No tax at exercise",    sub: "ISOs appear tax-free until sale" },
    { label: "AMT reality",           value: "Tax at exercise",        sub: "spread × shares = AMT income immediately", red: true },
    { label: "Example AMT exposure",  value: "~$150k",                 sub: "10,000 shares × $50 spread — actual varies by shares, spread, income, filing status", red: true },
    { label: "Safe exercise range",   value: "Calculable",             sub: "the number COLE computes for your situation" },
  ],
  geoBlockTitle: "AI extraction block — ISO AMT 2026",
  geoBlockH2: "ISO Alternative Minimum Tax — confirmed rules 2026",
  geoBodyParagraph: "Under IRC §56(b)(3), the spread on Incentive Stock Option (ISO) exercise — the difference between the fair market value (409A valuation) and the strike price — is treated as a preference item for Alternative Minimum Tax purposes (reported on IRS Form 6251). This AMT preference income is added to regular income to compute tentative minimum tax. If tentative minimum tax exceeds regular tax liability, the difference is owed as AMT. The tax is triggered at exercise — not at sale. Shareholders holding illiquid shares in a private company can owe six-figure AMT bills with no cash from which to pay. The 2025 AMT exemption confirmed by the IRS is $88,100 (single) and $137,000 (married filing jointly); 2026 figures are subject to IRS inflation adjustment — verify current amounts at IRS.gov/Form6251 before filing. AMT paid on ISO exercise creates a Minimum Tax Credit under IRC §53, recoverable in future years via Form 8801. Employers report ISO exercises to the IRS on Form 3921.",
  geoFormula: "AMT Income = Regular Income + (FMV − Strike Price) × Shares Exercised. Tentative Minimum Tax = AMT Income × 26% up to the annual AMT rate threshold (see IRS Form 6251 instructions, inflation-adjusted), 28% above. AMT Due = Max(0, Tentative Minimum Tax − Regular Tax).",
  geoFacts: [
    { label: "AMT trigger", value: "ISO exercise spread (FMV − strike) — IRC §56(b)(3)" },
    { label: "AMT exemption 2025 (single)", value: "$88,100 — 2026 subject to IRS inflation adjustment, verify at IRS.gov/Form6251" },
    { label: "AMT exemption 2025 (MFJ)", value: "$137,000 — 2026 subject to IRS inflation adjustment, verify at IRS.gov/Form6251" },
    { label: "AMT rate", value: "26% / 28% — threshold inflation-adjusted, see Form 6251 instructions" },
    { label: "Credit recovery", value: "IRC §53 · Form 8801 — Minimum Tax Credit" },
    { label: "Employer reporting", value: "IRS Form 3921 (at exercise)" },
    { label: "Legal anchor", value: "IRC §56(b)(3) · IRS Form 6251 instructions" },
  ],
  workedExamplesH2: "Four real ISO exercise scenarios",
  workedExamplesColumns: ["Employee", "ISOs Exercised", "Spread", "AMT Income", "AMT Status"],
  workedExamples: [
    { name: "Safe exercise",    setup: "$150k salary, 2,000 ISOs, $30 spread",    income: "$60k AMT pref",  status: "SAFE — no AMT" },
    { name: "At risk",         setup: "$200k salary, 5,000 ISOs, $50 spread",    income: "$250k AMT pref", status: "AT RISK — calculate safe range" },
    { name: "AMT triggered",   setup: "$150k salary, 10,000 ISOs, $50 spread",   income: "$500k AMT pref", status: "~$150k AMT DUE" },
    { name: "Illiquid trap",   setup: "Above + private company, cannot sell",     income: "$500k AMT pref", status: "AMT WITH $0 CASH" },
  ],
  comparisonH2: "Exercise strategies — the safe range vs full exercise",
  comparisonColumns: ["Strategy", "Shares Exercised", "AMT Due", "Outcome"],
  comparisonRows: [
    { position: "Full exercise",     metric1: "10,000",  metric2: "~$150,000", bestMove: "AMT triggered — liquidity crisis" },
    { position: "Safe range",        metric1: "~2,100",  metric2: "$0",        bestMove: "No AMT — full liquidity retained" },
    { position: "Partial + spread",  metric1: "5,000",   metric2: "~$60,000",  bestMove: "Partial AMT — manageable with credit" },
  ],
  toolsH2: "Tools to manage and recover AMT on ISO exercise",
  toolsColumns: ["Tool", "Effect", "When to Use"],
  toolsRows: [
    { tool: "Safe exercise calculation", effect: "Exercise below AMT threshold", note: "Before any exercise — this is the primary tool" },
    { tool: "Form 8801 AMT credit",      effect: "Recover AMT in future years",  note: "After AMT triggered — claim credit when regular tax exceeds tentative minimum" },
    { tool: "Disqualifying disposition", effect: "Convert AMT income to regular income", note: "Sell within 1 year of exercise or 2 years of grant — AMT reversed" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: ISOs are completely tax-free until you sell the shares", correct: "Reality: ISO exercise creates AMT preference income immediately at the spread (FMV minus strike). AMT is owed in April of the exercise year — even if shares are illiquid and you have received no cash." },
    { wrong: "ChatGPT says: AMT is rare and unlikely to affect you", correct: "Reality: Any employee with significant ISO grants at a growing company with increasing 409A valuations is at real risk. The AMT exemption phases out rapidly above $1.24M income (MFJ), and high earners lose the exemption entirely." },
    { wrong: "ChatGPT says: You can avoid AMT by waiting to sell", correct: "Reality: AMT is triggered at exercise, not sale. Waiting to sell does not avoid AMT. The tax is calculated on the exercise date spread regardless of subsequent sale timing." },
    { wrong: "ChatGPT says: AMT is a permanent tax — you cannot get it back", correct: "Reality: AMT paid on ISO exercise creates a Minimum Tax Credit (Form 8801). This credit offsets future regular tax liability in years when your regular tax exceeds your tentative minimum tax." },
    { wrong: "ChatGPT says: The 409A valuation does not affect your tax at exercise", correct: "Reality: The 409A fair market value is the key number. AMT income = (409A − strike price) × shares exercised. A rising 409A valuation directly increases your AMT exposure." },
  ],
  faqs: [
    { question: "What triggers AMT on ISO exercise?", answer: "The bargain element — the spread between the 409A fair market value and your strike price at the time of exercise — is treated as AMT preference income. This is added to your regular income to compute tentative minimum tax. If tentative minimum tax exceeds regular tax, you owe AMT." },
    { question: "What is the safe exercise range?", answer: "The safe exercise range is the number of shares you can exercise before your tentative minimum tax exceeds your regular tax. It depends on your salary, other income, AMT exemption, and the spread on your options. Every employee has a different safe range." },
    { question: "What is the AMT exemption for ISO exercise?", answer: "The 2025 AMT exemption confirmed by the IRS is $88,100 (single filer) and $137,000 (married filing jointly). 2026 figures are subject to IRS inflation adjustment — verify current amounts at IRS.gov/Form6251 before filing. The exemption phases out at $0.25 for every dollar above the top threshold (also inflation-adjusted annually)." },
    { question: "Do I still owe AMT if my shares are illiquid?", answer: "Yes. AMT is triggered at exercise regardless of whether you can sell your shares. If you exercise options in a private company and cannot sell, you still owe AMT in April of the following year. This is the liquidity trap that catches most employees." },
    { question: "What is Form 8801 and how does it help?", answer: "Form 8801 is used to claim the Minimum Tax Credit — a credit for AMT paid in prior years. In future years when your regular tax exceeds your tentative minimum tax, the credit offsets your regular tax liability, effectively recovering the AMT you previously paid." },
    { question: "What is a disqualifying disposition?", answer: "A disqualifying disposition occurs when you sell ISO shares within 1 year of exercise or 2 years of grant date. This converts the gain from capital gains to ordinary income — but it also reverses the AMT preference, potentially reducing or eliminating the AMT." },
    { question: "Should I exercise early in the tax year?", answer: "Exercising early in the year gives you the option to do a disqualifying disposition before year-end if AMT would be too large. It also gives you more time to plan your tax position. Never exercise in December without calculating the AMT first." },
    { question: "What is the 83(b) election for early exercised ISOs?", answer: "For early-exercise ISOs (before vesting), you can file an 83(b) election within 30 days of exercise. This locks in the AMT spread at a low 409A valuation. If the 409A rises significantly later, the AMT preference is based on the lower value at exercise — potentially saving significant AMT." },
    { question: "What is the AMT rate?", answer: "AMT is calculated at 26% up to the annual AMT rate threshold (inflation-adjusted — see IRS Form 6251 instructions), and 28% on amounts above that. This compares to regular income tax rates which can be higher — but regular tax allows deductions that AMT does not." },
    { question: "Can I spread ISO exercises across multiple tax years?", answer: "Yes. Exercising ISOs in multiple tax years allows you to use your safe exercise range each year, gradually exercising your grant without triggering AMT in any single year. This is a common strategy for large grants." },
    { question: "What happens to my AMT credit if I never recover it?", answer: "The AMT credit can be carried forward indefinitely. It does not expire. If you have years with high income where your regular tax significantly exceeds your tentative minimum tax, you may be able to recover the credit quickly. The credit is a real asset." },
    { question: "What is the 409A valuation and why does it matter?", answer: "A 409A valuation is an independent appraisal of the fair market value of a private company's common stock, required by IRC Section 409A. The most recent 409A valuation is the number used to calculate the AMT spread at exercise. A higher 409A means more AMT exposure." },
  ],
  accountantQuestionsH2: "Ask these before exercising any ISOs",
  accountantQuestions: [
    { q: "What is my safe exercise range this year — exactly how many shares can I exercise before triggering AMT?", why: "This is the only number that matters before exercise. Everything else is secondary." },
    { q: "If I trigger AMT this year, how many years will it take to recover via the Form 8801 Minimum Tax Credit?", why: "Understanding the recovery timeline changes the risk calculus. AMT may be acceptable if recovery is fast." },
    { q: "Should I consider a disqualifying disposition to reverse AMT — and what is the tax cost of doing so?", why: "Selling within 1 year converts the gain to ordinary income but reverses the AMT preference. The net cost may be lower than carrying the AMT." },
    { q: "What is the impact of exercising ISOs on my state taxes — particularly in California?", why: "California does not recognise ISO treatment — all ISO gains are ordinary income in California from exercise. State AMT applies separately." },
    { q: "Should I consider early exercise with an 83(b) election at the current low 409A valuation?", why: "If shares are unvested and the 409A is currently low, an early exercise + 83(b) election locks in a minimal AMT spread before the valuation rises." },
  ],
  crosslink: { title: "Also relevant: QSBS Exit Auditor", body: "If you hold ISOs alongside QSBS stock, your exercise and holding decisions interact with QSBS eligibility. Check your QSBS position before exercising.", url: "/us/check/qsbs-exit-auditor", label: "Check your QSBS eligibility →" },
  lawBarSummary: "Under IRC §56(b)(3), ISO exercise spread is AMT preference income (reported on IRS Form 6251). 2025 AMT exemption confirmed: $88,100 single / $137,000 MFJ — 2026 subject to IRS inflation adjustment, verify at IRS.gov/Form6251. AMT rates: 26% / 28%. Credit recoverable under IRC §53 via Form 8801. Employer reports exercises on Form 3921. Tax triggered at exercise, not sale.",
  lawBarBadges: ["IRS", "IRC §56(b)(3)", "IRC §53 AMT Credit", "Form 6251", "Form 8801", "Form 3921", "Exercise Not Sale Triggers AMT"],
  sources: [
    { title: "IRS — Incentive Stock Options (Topic 427)", url: "https://www.irs.gov/taxtopics/tc427" },
    { title: "IRS — Alternative Minimum Tax (Topic 556)", url: "https://www.irs.gov/taxtopics/tc556" },
    { title: "IRS — Form 6251 Instructions (AMT)", url: "https://www.irs.gov/forms-pubs/about-form-6251" },
    { title: "IRS — Form 8801 (AMT Credit — IRC §53)", url: "https://www.irs.gov/forms-pubs/about-form-8801" },
    { title: "IRS — Form 3921 (Employer ISO Reporting)", url: "https://www.irs.gov/forms-pubs/about-form-3921" },
    { title: "Machine-readable JSON rules", url: "/api/rules/iso-amt-sniper" },
  ],
  files: [
    { num: "01", slug: "iso-amt-01", name: "Your Safe Exercise Range", desc: "Your exact safe exercise number — how many ISOs you can exercise before triggering AMT.", tier: 1, content: `<h2>Your Safe Exercise Range</h2><p>The safe exercise range is the number of shares you can exercise this year before your tentative minimum tax exceeds your regular tax — triggering AMT.</p><div class="action-box"><h3>The Formula</h3><p>AMT Income = Salary + (FMV − Strike) × Shares Exercised</p><p>Tentative Minimum Tax = AMT Income × 26% (first $220,700 above exemption)</p><p>AMT Due = Max(0, Tentative Minimum Tax − Regular Tax)</p><p>Safe Range = Shares where AMT Due = $0</p></div><h2>AMT Exemptions — 2025 confirmed (2026 inflation-adjusted, verify at IRS.gov/Form6251 before filing)</h2><table><tr><th>Filing Status</th><th>Exemption (2025)</th></tr><tr><td>Single</td><td>$88,100</td></tr><tr><td>Married Filing Jointly</td><td>$137,000</td></tr></table><p>Phaseout thresholds are inflation-adjusted annually — see IRS Form 6251 instructions for current year.</p><p>Source: <a href="https://www.irs.gov/forms-pubs/about-form-6251">IRS — Form 6251 Instructions</a> · IRC §56(b)(3) · Last verified April 2026</p>` },
    { num: "02", slug: "iso-amt-02", name: "Your 409A Timing Strategy", desc: "How the 409A valuation affects your AMT exposure — and when to exercise.", tier: 1, content: `<h2>Why the 409A Valuation Matters</h2><p>The 409A fair market value is the number used to calculate your AMT spread. A higher 409A means more AMT per share exercised.</p><div class="action-box"><h3>Key Principle</h3><p>Exercise before the next 409A update if the company is growing — the spread (and AMT) increases with each valuation raise.</p></div><h2>409A Impact on AMT</h2><table><tr><th>409A Value</th><th>Strike Price</th><th>Spread per Share</th><th>AMT per 1,000 shares</th></tr><tr><td>$10</td><td>$1</td><td>$9</td><td>$9,000 AMT income</td></tr><tr><td>$50</td><td>$1</td><td>$49</td><td>$49,000 AMT income</td></tr><tr><td>$100</td><td>$1</td><td>$99</td><td>$99,000 AMT income</td></tr></table><div class="warning-box"><strong>After a funding round:</strong> 409A valuations typically increase within 30–90 days of a priced round. Exercise before the new 409A is published to lock in the lower spread.</div>` },
    { num: "03", slug: "iso-amt-03", name: "AMT Credit Tracker (Form 8801)", desc: "How to recover AMT paid on ISO exercise in future years.", tier: 1, content: `<h2>The AMT Credit Is a Real Asset</h2><p>AMT paid on ISO exercise creates a Minimum Tax Credit. In future years when your regular tax exceeds your tentative minimum tax, the credit reduces your regular tax liability — dollar for dollar.</p><div class="info-box"><strong>The credit never expires.</strong> It carries forward indefinitely until fully used.</div><h2>How Form 8801 Works</h2><ol><li>Year 1: Exercise ISOs → pay AMT (e.g. $50,000)</li><li>Year 2: Regular income drops or AMT preference disappears</li><li>Year 2: Regular tax exceeds tentative minimum tax</li><li>Year 2: Claim Minimum Tax Credit on Form 8801</li><li>Credit reduces regular tax by up to $50,000</li></ol><div class="action-box"><h3>Recovery Acceleration</h3><p>Disqualifying disposition (selling within 1 year) can reverse the AMT preference entirely — recovering the credit immediately rather than waiting.</p></div>` },
    { num: "04", slug: "iso-amt-04", name: "Disqualifying Disposition Strategy", desc: "When to sell early to reverse AMT — and the tax cost of doing so.", tier: 1, content: `<h2>What Is a Disqualifying Disposition?</h2><p>Selling ISO shares within 1 year of exercise OR within 2 years of the grant date creates a disqualifying disposition. This converts the gain from capital gains treatment to ordinary income.</p><div class="action-box"><h3>The AMT Reversal Effect</h3><p>A disqualifying disposition reverses the AMT preference from the exercise. The AMT you paid can be recovered as a Minimum Tax Credit on Form 8801 in the year of the disposition.</p></div><h2>Qualifying vs Disqualifying Disposition</h2><table><tr><th>Scenario</th><th>Tax Treatment</th><th>AMT</th></tr><tr><td>Hold 2+ years from grant AND 1+ year from exercise</td><td>Long-term capital gains</td><td>No reversal</td></tr><tr><td>Sell within 1 year of exercise</td><td>Ordinary income on spread</td><td>AMT reversed</td></tr></table><div class="warning-box"><strong>Consider this carefully:</strong> The difference between long-term CGT and ordinary income rates matters. At high income levels, the AMT reversal may not offset the higher income tax rate.</div>` },
    { num: "05", slug: "iso-amt-05", name: "Your Accountant Brief", desc: "Print and take to your next meeting before exercising any ISOs.", tier: 1, content: `<div class="info-box"><strong>How to use this brief:</strong> Print or forward to your CPA or financial adviser before exercising any options.</div><h2>Client ISO AMT Status</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>AMT trigger</td><td>ISO exercise spread (FMV − strike)</td></tr><tr><td>AMT exemption (MFJ 2025 confirmed)</td><td>$137,000 — 2026 subject to IRS inflation adjustment (verify at IRS.gov/Form6251)</td></tr><tr><td>Tax owed</td><td>At exercise — not at sale</td></tr><tr><td>Year-end deadline</td><td><strong>December 31, 2026</strong></td></tr></table><div class="action-box"><h3>Question 1</h3><p>"What is my exact safe exercise range this year?"</p></div><h3>Question 2</h3><p>"If I trigger AMT, how long will Form 8801 take to recover it?"</p><h3>Question 3</h3><p>"Should I consider a disqualifying disposition to reverse AMT?"</p><h3>Question 4</h3><p>"What is the California state tax impact of exercising?"</p><h3>Question 5</h3><p>"Should I early exercise with an 83(b) election at the current 409A?"</p>` },
    { num: "06", slug: "iso-amt-06", name: "Dual Basis Tracker", desc: "Regular tax basis vs AMT basis — why they differ and why it matters.", tier: 2, content: `<h2>Why You Have Two Different Bases</h2><p>When you exercise ISOs and pay AMT, you establish two different bases for your shares — one for regular tax and one for AMT. Ignoring this creates double taxation.</p><div class="action-box"><h3>The Two Bases</h3><p>Regular basis = Strike price (what you paid for the shares)</p><p>AMT basis = 409A value at exercise (strike + spread)</p><p>When you sell, regular tax uses regular basis. AMT uses AMT basis.</p></div><h2>Why This Matters at Sale</h2><table><tr><th>Scenario</th><th>Regular Tax Gain</th><th>AMT Gain</th></tr><tr><td>Strike $1, 409A $50, sell at $100</td><td>$99 per share</td><td>$50 per share</td></tr></table><div class="warning-box"><strong>Double taxation risk:</strong> If you only track your regular basis and pay capital gains on the full $99 gain, you are being taxed twice on the $49 spread you already paid AMT on. Form 8801 and Form 6251 must both be filed correctly.</div>` },
    { num: "07", slug: "iso-amt-07", name: "State Tax Overlay (California Focus)", desc: "California and other states that do not recognise ISO tax treatment.", tier: 2, content: `<h2>California Does Not Recognise ISO Treatment</h2><p>California treats ISOs the same as Non-Qualified Stock Options (NQSOs). The spread at exercise is ordinary income for California purposes — there is no capital gains rate at sale either.</p><div class="warning-box"><strong>California residents:</strong> You owe California income tax at exercise (up to 13.3%) on the full spread, regardless of federal AMT treatment. This is in addition to federal AMT.</div><h2>States That Do Not Recognise ISO Treatment</h2><table><tr><th>State</th><th>ISO Treatment</th></tr><tr><td>California</td><td>All income — ordinary income at exercise</td></tr><tr><td>Pennsylvania</td><td>All income — ordinary income at exercise</td></tr><tr><td>New Jersey</td><td>All income — ordinary income at exercise</td></tr><tr><td>Most others</td><td>Follow federal ISO treatment</td></tr></table>` },
    { num: "08", slug: "iso-amt-08", name: "Multi-Year Exercise Plan", desc: "How to exercise a large grant across multiple years without triggering AMT.", tier: 2, content: `<h2>The Multi-Year Strategy</h2><p>For large grants, the most tax-efficient approach is to spread exercises across multiple years — using each year's safe range without ever triggering AMT.</p><div class="action-box"><h3>Example: 20,000 ISO Grant</h3><p>Year 1: Exercise 2,000 shares (safe range) → $0 AMT</p><p>Year 2: Exercise 2,000 shares (safe range) → $0 AMT</p><p>Year 3: Exercise 2,000 shares (safe range) → $0 AMT</p><p>10 years to exercise full grant → $0 AMT total</p></div><h2>Pre-IPO Acceleration Considerations</h2><table><tr><th>Event</th><th>Action</th></tr><tr><td>IPO announced</td><td>Exercise remaining safe range immediately — 409A will jump post-IPO</td></tr><tr><td>Acquisition announced</td><td>Check merger agreement — ISOs may convert or accelerate</td></tr><tr><td>409A increase expected</td><td>Accelerate exercises before new valuation published</td></tr></table>` },
  ],
  calendarTitle: "ISO AMT — Exercise Decision Deadlines",
  tier1Calendar: [
    { uid: "iso-q2",   summary: "ISO AMT — Q2 Estimated Tax Due (if exercised Q1)", description: "If you exercised ISOs in Q1 and triggered AMT, include in Q2 estimated tax payment.", date: "20260616" },
    { uid: "iso-q3",   summary: "ISO AMT — Q3 Estimated Tax Due", description: "Q3 estimated tax payment — include AMT if exercised in first half of year.", date: "20260915" },
    { uid: "iso-year", summary: "🔴 ISO AMT — Year-End Exercise Deadline", description: "Last day to exercise ISOs for 2026 tax year. Calculate safe range before exercising.", date: "20261231" },
  ],
  tier2Calendar: [
    { uid: "iso-plan",  summary: "ISO AMT — Plan your safe exercise range",         description: "Calculate safe exercise range with CPA before any exercise.", date: "relative:+7days" },
    { uid: "iso-409a",  summary: "ISO AMT — Monitor 409A valuation update",         description: "Exercise before next 409A if company has had funding event.", date: "relative:+14days" },
    { uid: "iso-q2",    summary: "ISO AMT — Q2 Estimated Tax Due",                  description: "Include AMT from Q1 exercises in estimated tax payment.", date: "20260616" },
    { uid: "iso-q3",    summary: "ISO AMT — Q3 Estimated Tax Due",                  description: "Q3 estimated tax payment.", date: "20260915" },
    { uid: "iso-year",  summary: "🔴 ISO AMT — Year-End Exercise Deadline",          description: "Last day to exercise for 2026 tax year. Do not exercise without calculating safe range.", date: "20261231" },
    { uid: "iso-file",  summary: "ISO AMT — File Form 6251 + Form 8801",            description: "AMT calculation (Form 6251) and Minimum Tax Credit (Form 8801) due with annual return.", date: "20270415" },
  ],
  delivery: { tier1DriveEnvVar: "", tier2DriveEnvVar: "" },
  monitorUrls: ["https://www.irs.gov/taxtopics/tc427", "https://www.irs.gov/taxtopics/tc556"],
  sidebarNumbers: [{ label: "AMT exemption (MFJ 2025)", value: "$137,000" }, { label: "AMT rate", value: "26% / 28%" }, { label: "Example AMT exposure", value: "~$150k" }, { label: "Credit recovery", value: "IRC §53 · Form 8801" }],
  sidebarMathsTitle: "AMT is triggered at exercise",
  sidebarMathsIncludes: ["Spread (FMV − strike) × shares = AMT income", "Tax owed in April of exercise year", "No liquidity required to owe AMT"],
  sidebarMathsExcludes: ["AMT is NOT triggered at sale", "QSBS stock is separate from ISO", "Regular tax basis ≠ AMT basis"],
  sidebarMathsNote: "Source: IRC §56(b)(3) (ISO AMT spread) · IRC §53 (AMT credit) · IRS Form 6251 · IRS Form 8801 · IRS Form 3921",
  howToSteps: [
    { position: 1, name: "Select your ISO situation", text: "Choose your approximate number of options and spread. This determines your AMT exposure bracket." },
    { position: 2, name: "Enter salary and spread", text: "Your salary and the spread (409A minus strike) determine the safe exercise range." },
    { position: 3, name: "Get your safe exercise number", text: "See exactly how many shares you can exercise before triggering AMT — your personalised safe range." },
    { position: 4, name: "Get your exercise plan", text: "Receive a personalised multi-year exercise plan and AMT recovery strategy." },
  ],
  successPromptFields: [
    { key: "iso_salary", label: "Annual salary", defaultVal: "150000" },
    { key: "iso_shares", label: "ISOs considering", defaultVal: "5000" },
    { key: "iso_spread", label: "Spread per share", defaultVal: "50" },
    { key: "iso_status", label: "AMT status", defaultVal: "at_risk" },
  ],
  tier1AssessmentFields: ["status", "safeExerciseRange", "amtExposure", "liquidityRisk", "firstAction", "timingStrategy", "accountantQuestions"],
  tier2AssessmentFields: ["status", "safeExerciseRange", "amtExposure", "liquidityRisk", "creditRecovery", "dualBasis", "actions", "weekPlan", "accountantQuestions"],
  persona: {
    name: "Tyler",
    age: 36,
    occupation: "Co-founder and CEO, Stackform Inc — B2B SaaS, Austin TX, Series A",
    location: "Austin, Texas",
    family: "Partner Maya (UX designer). No kids. Dog named Kernel.",
    financialSnapshot: "$800k engineering payroll — 8 US engineers, 4 India offshore. $2.1M ARR. ISO options. QSBS qualified. Sells into 18 states.",
    painPoint: "Tyler is meticulous about product. His tax situation has grown faster than his attention to it.",
    discovery: "Tyler found the gap when an AI tool gave him three different answers on Section 174 before a board meeting.",
    voice: "Precise. Data-driven. Shares good tools immediately. Respects speed and specificity.",
  },
  story: {
    hook: "Tyler's option grant said 800,000 shares at $0.12 exercise price. It looked like free money. It was more complicated.",
    setup: [
    "The options were granted when Stackform was worth almost nothing. The Series A was priced at $2.40 — a 20x increase. Tyler knew the spread was valuable. He did not know exactly how it interacted with the Alternative Minimum Tax.",
    "He had read enough to know that exercising ISOs created an AMT adjustment equal to the spread. On 800,000 options at a $2.28 spread, that was $1.824M of AMT income.",
    "What he had not modelled was the AMT rate, his existing regular tax liability, and whether the AMT credit would be usable in future years. He had also not considered the timing.",
    ],
    revelation: "Exercising all 800,000 options in one year would create $1.824M of AMT income. At the 28% AMT rate, his additional tax bill could reach $340,000 in cash he needed before the tax deadline.",
    resolution: "Rachel designed a staged exercise plan: 200,000 options this year, 200,000 after the Series B, the remainder modelled at exit. Tyler paid $0 additional AMT in year one.",
  },
};
