import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "wayfair-nexus-sniper", name: "Wayfair Nexus Sniper", site: "taxchecknow", country: "us", market: "United States", language: "en-US", currency: "USD",
  slug: "us/check/wayfair-nexus-sniper", url: "https://taxchecknow.com/us/check/wayfair-nexus-sniper", apiRoute: "/api/rules/wayfair-nexus-sniper",
  authority: "IRS", authorityUrl: "https://www.irs.gov", legalAnchor: "South Dakota v. Wayfair (2018)", legislation: "South Dakota v. Wayfair, Inc. (2018) — Economic Nexus for Sales Tax", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Nexus Heatmap Action Plan", tagline: "Are you already non-compliant — and how much do you owe right now?", value: "A personalised nexus audit built around your sales by state, your marketplace channels, and your FBA inventory locations.", cta: "Get My Nexus Plan — $67 →", productKey: "us_67_wayfair_nexus_sniper", envVar: "STRIPE_US_NEXUS_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your VDA Shield System", tagline: "Reduce penalties and limit lookback with Voluntary Disclosure — before the audit letter arrives", value: "A personalised nexus audit plus multi-state VDA strategy, penalty reduction calculation, and amnesty tracker.", cta: "Get My VDA Shield — $147 →", productKey: "us_147_wayfair_nexus_sniper", envVar: "STRIPE_US_NEXUS_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-12-31T23:59:59.000-05:00", display: "December 31, 2026", short: "Dec 31 2026", description: "Year-end nexus review deadline — each year of non-compliance increases lookback exposure", urgencyLabel: "COMPLIANCE DEADLINE", countdownLabel: "Countdown to year-end — every month of delay increases your exposure" },
  h1: "The 2026 Wayfair Nexus Sniper: Are You Already Non-Compliant?", metaTitle: "Wayfair Nexus 2026: Are You Already Non-Compliant? | TaxCheckNow", metaDescription: "Most US states enforce economic nexus at $100,000 in GROSS sales — including marketplace sales. FBA inventory creates immediate nexus with no threshold. States can audit years later. Check your nexus exposure instantly.", canonical: "https://taxchecknow.com/us/check/wayfair-nexus-sniper",
  answerHeadline: "The answer — state tax authorities confirmed 2026",
  answerBody: [
    "Following South Dakota v. Wayfair (2018), most US states enforce economic nexus based on $100,000 in gross sales or 200 transactions in the prior 12 months. In 2026, several states including Illinois have removed the transaction threshold — gross sales alone trigger nexus.",
    "Gross sales means total revenue from all channels — not just taxable sales. Marketplace sales through Amazon, Etsy, and Walmart count toward your nexus threshold even though the marketplace collects the tax. FBA inventory in any Amazon fulfilment centre creates physical nexus immediately — no threshold required.",
    "States can audit you years later for uncollected sales tax, even if you never registered or knew you had nexus. Voluntary Disclosure Agreements (VDAs) can limit the lookback period and reduce penalties — but only before the audit letter arrives.",
  ],
  answerSource: "Source: South Dakota v. Wayfair, Inc. (2018) · State Department of Revenue · Sales Tax Institute 2026",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: [
    "You only count taxable sales toward nexus thresholds — wrong. Most states use gross revenue from all sales — including exempt transactions — to measure nexus thresholds. Sellers who exclude exempt sales significantly undercount their exposure.",
    "Amazon handles all my sales tax so I do not have nexus — wrong. Marketplace facilitator laws require Amazon to collect and remit sales tax on your behalf — but your gross marketplace sales still count toward nexus thresholds in most states.",
    "You need 200 transactions to trigger nexus — wrong. Multiple states including Illinois removed the 200-transaction threshold in 2026. Gross sales alone now trigger nexus in these states.",
  ],
  chainVisual: { label: "The nexus calculation — what counts toward your threshold", broken: "Taxable direct sales only (what most sellers count)  ❌  WRONG — misses marketplace + exempt sales", fixed: "Gross sales ALL channels (direct + Amazon + Etsy + exempt)  ✔  CORRECT — triggers nexus sooner than you think" },
  brackets: [
    { label: "Under $50k total gross sales across all states",          value: 1, status: "clear" },
    { label: "$50k–$100k gross sales — approaching thresholds",         value: 2, status: "approaching" },
    { label: "$100k–$500k gross sales — likely nexus in multiple states", value: 3, status: "trap" },
    { label: "Over $500k gross sales OR FBA inventory in use",           value: 4, status: "deep_trap" },
    { label: "Not sure of my gross sales by state",                     value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "annualGrossSales", label: "Your total gross sales last 12 months (all channels, all states)", subLabel: "Include marketplace sales — these count toward nexus thresholds", options: [{ label: "Under $50k", value: 30_000 }, { label: "$50k–$100k", value: 75_000 }, { label: "$100k–$500k", value: 300_000 }, { label: "Over $500k", value: 750_000 }], default: 75_000 },
    { type: "buttonGroup", stateKey: "channels", label: "Where do you sell?", subLabel: "Each channel adds to your nexus exposure", options: [{ label: "Direct only (my website)", value: "direct" }, { label: "Amazon FBA", value: "fba" }, { label: "Amazon + other marketplaces", value: "multi" }, { label: "All channels", value: "all" }], default: "direct" },
    { type: "twoButton", stateKey: "hasFBA", label: "Do you use Amazon FBA (Fulfilment by Amazon)?", subLabel: "FBA inventory creates physical nexus in every state with a fulfilment centre — no threshold required", options: [{ label: "No FBA", value: false }, { label: "Yes — FBA user", value: true }], default: false },
  ],
  tierAlgorithm: { description: "annualGrossSales >= 100000 OR hasFBA → tier2. channels is fba or multi or all → tier2. Otherwise tier1.", tier2Conditions: ["annualGrossSales >= 100000", 'channels === "fba"', 'channels === "multi"', 'channels === "all"'], tier2Flags: ["hasFBA"] },
  calculatorRuleBox: { label: "The rule — state tax authorities confirmed", body: "Economic nexus: ~$100,000 gross sales OR 200 transactions in most states. Some states (IL, etc.) removed transaction threshold in 2026. FBA inventory = physical nexus, no threshold. Gross sales = all channels including marketplace. States audit retroactively with no statute of limitations in some jurisdictions." },
  calculatorClarification: { label: "⚠️ key clarification", body: "Nexus liability starts the day you cross the threshold — not the day you register. If you crossed $100k in gross sales in Georgia 6 months ago without registering, you have been non-compliant for 6 months and liability has been accruing daily." },
  countdownLabel: "Countdown to year-end — every month of delay increases exposure",
  countdownStats: [
    { label: "What sellers think",    value: "Taxable sales only",  sub: "common misunderstanding of nexus thresholds" },
    { label: "Nexus reality",         value: "Gross sales count",   sub: "all channels, all products, including exempt", red: true },
    { label: "FBA reality",           value: "Immediate nexus",     sub: "no threshold — inventory presence = nexus", red: true },
    { label: "Lookback risk",         value: "Unlimited in some",   sub: "states can audit with no statute of limitations" },
  ],
  geoBlockTitle: "AI extraction block — Wayfair economic nexus 2026",
  geoBlockH2: "Economic nexus rules — confirmed 2026",
  geoBodyParagraph: "Following South Dakota v. Wayfair, Inc. (2018), US states can require out-of-state sellers to collect and remit sales tax based on economic activity alone — without physical presence. As of 2026, most states enforce economic nexus at $100,000 in gross sales or 200 transactions in the prior 12-month period. Several states including Illinois have removed the transaction threshold — gross sales alone now trigger nexus. Gross sales means total revenue from all channels and all products, including exempt items and marketplace sales. Marketplace facilitator laws require platforms like Amazon, Etsy and Walmart to collect and remit sales tax — but marketplace sales still count toward the seller's nexus threshold. Amazon FBA inventory creates physical nexus immediately in every state containing an Amazon fulfilment centre, with no threshold requirement. States can assess tax retroactively to the date nexus was established, with some states having no statute of limitations for non-filers.",
  geoFormula: "Economic Nexus = Total Gross Sales (ALL channels, ALL products) ≥ $100,000 in prior 12 months. Physical Nexus = FBA inventory present in state = immediate nexus from $1 in sales.",
  geoFacts: [
    { label: "Economic nexus threshold", value: "$100,000 gross sales (most states)" },
    { label: "Transaction threshold",    value: "Removed in some states (e.g. IL 2026)" },
    { label: "Marketplace sales",        value: "Count toward threshold even if platform collects" },
    { label: "FBA inventory",            value: "Physical nexus — no threshold required" },
    { label: "Lookback period",          value: "Potentially unlimited for non-filers" },
    { label: "Legal anchor",             value: "South Dakota v. Wayfair (2018)" },
  ],
  workedExamplesH2: "Four real nexus scenarios — compliant or exposed",
  workedExamplesColumns: ["Seller", "Sales", "Channels", "FBA?", "Nexus Status"],
  workedExamples: [
    { name: "Small direct seller",  setup: "$40k direct sales only, no FBA",                income: "$40k",  status: "CLEAR — under threshold" },
    { name: "Amazon FBA seller",    setup: "$60k total sales, FBA in 20 states",            income: "$60k",  status: "NEXUS IN 20 STATES" },
    { name: "Multi-channel seller", setup: "$150k across Amazon + Etsy + own site",         income: "$150k", status: "NON-COMPLIANT — threshold crossed" },
    { name: "Exempt goods seller",  setup: "$120k gross but only $80k taxable — not registered", income: "$120k", status: "NON-COMPLIANT — gross counts" },
  ],
  comparisonH2: "Nexus triggers — what creates obligation in 2026",
  comparisonColumns: ["Trigger Type", "Threshold", "Applies From", "Example"],
  comparisonRows: [
    { position: "Economic nexus",  metric1: "$100k gross or 200 transactions", metric2: "Day threshold crossed", bestMove: "Most common for online sellers" },
    { position: "Physical nexus",  metric1: "No threshold",                    metric2: "Day inventory arrives", bestMove: "FBA, warehouse, employees" },
    { position: "Affiliate nexus", metric1: "Varies by state",                 metric2: "Day affiliate agreement signed", bestMove: "Referral partners in state" },
  ],
  toolsH2: "Tools to fix nexus exposure and reduce penalties",
  toolsColumns: ["Tool", "Effect", "Best For"],
  toolsRows: [
    { tool: "Voluntary Disclosure Agreement (VDA)", effect: "Limit lookback period, reduce penalties", note: "Must be filed before audit letter — anonymous filing available" },
    { tool: "Sales tax software (TaxJar, Avalara)", effect: "Automate registration and filing", note: "Essential once nexus established in 5+ states" },
    { tool: "Amnesty programmes", effect: "Some states offer penalty forgiveness", note: "Varies by state and year — check current programmes" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: You only count taxable sales toward nexus thresholds", correct: "Reality: Most states use gross revenue — all sales including exempt transactions — to measure nexus thresholds. Sellers who only count taxable sales significantly undercount their exposure and may be non-compliant without knowing it." },
    { wrong: "ChatGPT says: Amazon handles my sales tax so I do not have nexus", correct: "Reality: Marketplace facilitator laws require Amazon to collect and remit tax on your sales — but your gross marketplace sales still count toward nexus thresholds in most states. You may be registered as required in zero states while crossing nexus thresholds in 15." },
    { wrong: "ChatGPT says: You need 200 transactions to trigger nexus", correct: "Reality: Multiple states removed the 200-transaction threshold in 2026. Illinois is the most significant example. In these states, $100,000 in gross sales alone triggers nexus regardless of transaction count." },
    { wrong: "ChatGPT says: If you have FBA, Amazon registers you for sales tax automatically", correct: "Reality: FBA inventory creates physical nexus in every state with an Amazon fulfilment centre — immediately, with no threshold. Amazon does not register you. You must register and file in each FBA state yourself (or Amazon files on your behalf under marketplace facilitator laws — but your registration obligation still exists)." },
    { wrong: "ChatGPT says: States cannot audit you for old uncollected sales tax", correct: "Reality: States can assess tax retroactively from the date nexus was established. Some states have no statute of limitations for non-filers. A seller who crossed nexus in California 3 years ago without registering faces 3+ years of uncollected tax plus interest and penalties." },
  ],
  faqs: [
    { question: "What is economic nexus?", answer: "Economic nexus is a sales tax obligation triggered by economic activity in a state — such as making $100,000 in gross sales to customers in that state — without any physical presence. It was established by the Supreme Court in South Dakota v. Wayfair (2018)." },
    { question: "Does Amazon FBA create nexus?", answer: "Yes. Having inventory in an Amazon fulfilment centre creates physical nexus in that state immediately — with no sales threshold required. Amazon operates fulfilment centres in over 40 states. Using FBA creates nexus obligations in most of them regardless of your sales volume." },
    { question: "Do marketplace sales count toward nexus thresholds?", answer: "Yes. In most states, your gross sales through marketplaces like Amazon, Etsy, and Walmart count toward your economic nexus threshold — even though the marketplace collects and remits the sales tax on your behalf. You may be crossing nexus thresholds without collecting a dollar of tax yourself." },
    { question: "What is a Voluntary Disclosure Agreement (VDA)?", answer: "A VDA is an agreement with a state revenue authority where you voluntarily come forward and register for sales tax. In exchange, the state typically limits your lookback period (often to 3–4 years) and reduces or eliminates penalties. VDAs must be filed before the state contacts you — once an audit starts, VDA is typically no longer available." },
    { question: "How far back can states audit for uncollected sales tax?", answer: "It depends on the state. Most states have a 3–4 year statute of limitations for registered filers. However, for non-filers — sellers who should have registered but did not — some states have no statute of limitations. They can assess tax from the date nexus was first established, potentially years or decades back." },
    { question: "What is the difference between gross sales and taxable sales?", answer: "Gross sales is your total revenue from all sales — taxable and exempt — before any deductions. Taxable sales is only the revenue from transactions subject to sales tax. Most states use gross sales to determine nexus thresholds. Using only taxable sales significantly undercounts your exposure." },
    { question: "What states removed the 200-transaction threshold in 2026?", answer: "Illinois is the most notable example, removing the 200-transaction threshold effective January 1, 2026. Other states have similar changes pending. Sellers who relied on having fewer than 200 transactions to avoid nexus should re-evaluate — gross sales alone may now trigger their obligation." },
    { question: "What are the Big 5 states for sales tax nexus risk?", answer: "California (highest rates, aggressive audits), Texas (large population, broad nexus rules), New York (complex product taxability), Illinois (removed transaction threshold 2026), and Pennsylvania (economic nexus + physical presence rules). These five states generate the most nexus exposure for most online sellers." },
    { question: "Can I deregister from a state once I drop below the threshold?", answer: "Yes, but the process varies by state and the criteria differ. Some states require you to remain registered for a period after dropping below threshold. Others allow immediate deregistration. You must file a final return for the period you were registered." },
    { question: "What is the penalty for not collecting sales tax?", answer: "Penalties vary by state but typically include: 5–25% of unpaid tax, interest on unpaid tax (often 6–10% annually), and in some states, personal liability for business owners. States that discover non-compliance through audit typically apply maximum penalties. VDA significantly reduces these." },
    { question: "Should I use a marketplace facilitator or sell direct to manage nexus?", answer: "This is a strategy question with no universal answer. Selling exclusively through marketplaces (Amazon, Etsy) shifts the collection obligation to the platform in most states — but your nexus threshold exposure remains. Selling direct gives you more control but creates direct registration obligations." },
    { question: "What is the amnesty programme and how do I access it?", answer: "Some states offer periodic sales tax amnesty programmes where non-compliant sellers can register and pay back taxes with reduced or no penalties. These programmes are time-limited and vary by state. A VDA is the always-available equivalent — it achieves similar penalty reduction outside of formal amnesty periods." },
  ],
  accountantQuestionsH2: "Ask these before year-end 2026",
  accountantQuestions: [
    { q: "In which states have I crossed the economic nexus threshold based on gross sales from ALL channels including marketplaces?", why: "Most sellers only calculate direct sales. Marketplace sales are the most common cause of undetected nexus exposure." },
    { q: "Does my FBA inventory currently create physical nexus in states where I have not registered — and which states are affected?", why: "FBA nexus is immediate and has no threshold. Every state with an Amazon fulfilment centre where your inventory sits is a potential registration obligation." },
    { q: "How far back is my exposure — and should I file VDAs before this year-end to cap the lookback period?", why: "The sooner you file a VDA, the less lookback exposure you face. Waiting increases liability." },
    { q: "Are there any current state amnesty programmes I should take advantage of before they expire?", why: "Amnesty programmes offer better terms than VDAs in some states. Missing them means paying full penalties later." },
    { q: "Do I need to register in states where my marketplace handles the tax — and what does my total registration obligation look like across all states?", why: "Marketplace facilitator laws are complex. In some states you must still register even if the platform collects. Get clarity on your full compliance picture." },
  ],
  crosslink: { title: "Selling into the UK? Check your VAT obligations.", body: "UK VAT applies to digital goods sold to UK consumers from any country. The rules changed post-Brexit and most non-UK sellers are now required to register.", url: "/uk/check/mtd-scorecard", label: "Check UK tax obligations →" },
  lawBarSummary: "Economic nexus established by South Dakota v. Wayfair (2018). Most states: $100,000 gross sales or 200 transactions threshold (some states removed transaction threshold in 2026). FBA inventory = physical nexus, no threshold. Marketplace sales count toward threshold. Lookback unlimited for non-filers in some states.",
  lawBarBadges: ["Supreme Court", "S.D. v. Wayfair 2018", "State DOR", "Sales Tax Institute", "Machine-readable JSON"],
  sources: [
    { title: "Sales Tax Institute — Nexus State-by-State Guide 2026", url: "https://www.salestaxinstitute.com/sales_tax_faqs/economic-nexus-state-by-state-guide" },
    { title: "IRS — State and Local Taxes", url: "https://www.irs.gov/businesses/small-businesses-self-employed/state-and-local-taxes" },
    { title: "Supreme Court — South Dakota v. Wayfair Inc.", url: "https://www.supremecourt.gov/opinions/17pdf/17-494_j4el.pdf" },
    { title: "Machine-readable JSON rules", url: "/api/rules/wayfair-nexus-sniper" },
  ],
  files: [
    { num: "01", slug: "nexus-01", name: "Your Nexus Exposure Report", desc: "Which states you have nexus in — and your estimated liability.", tier: 1, content: `<h2>Your Nexus Position</h2><p>Economic nexus is triggered the day you cross the threshold in a state. Liability accrues from that date — not from the date you register.</p><div class="action-box"><h3>The Core Rule</h3><p>Economic nexus: $100,000 gross sales OR 200 transactions (threshold removed in some states in 2026)</p><p>Physical nexus (FBA): Immediate — no threshold</p><p>Gross sales = ALL channels, ALL products, INCLUDING exempt</p></div><h2>Nexus Triggers by Type</h2><table><tr><th>Trigger</th><th>Threshold</th><th>Timing</th></tr><tr><td>Economic nexus</td><td>$100k gross sales</td><td>Day threshold crossed</td></tr><tr><td>FBA inventory</td><td>None</td><td>Day inventory arrives in state</td></tr><tr><td>Employee in state</td><td>None</td><td>Day employment begins</td></tr></table><p>Source: <a href="https://www.salestaxinstitute.com/sales_tax_faqs/economic-nexus-state-by-state-guide">Sales Tax Institute</a> · Last verified April 2026</p>` },
    { num: "02", slug: "nexus-02", name: "Big 5 State Playbooks", desc: "California, Texas, New York, Illinois, Pennsylvania — your highest-risk states.", tier: 1, content: `<h2>The Big 5 States — Highest Priority</h2><div class="warning-box"><strong>These five states represent the highest enforcement risk for most online sellers. Prioritise registration here first.</strong></div><h2>California</h2><p>Threshold: $500,000 gross sales (higher than most states). But: physical presence rules are aggressive. FBA in California = immediate nexus. Personal liability for owners applies.</p><h2>Texas</h2><p>Threshold: $500,000 gross sales. Aggressive audit programme. Long lookback periods. VDA available — use it early.</p><h2>New York</h2><p>Threshold: $500,000 AND 100 transactions. Both tests must be met. Complex product taxability rules — many items are exempt in NY that are taxable elsewhere.</p><h2>Illinois</h2><p>Threshold: $100,000 gross sales ONLY from January 2026 (200-transaction threshold removed). Early mover advantage — register now before enforcement begins.</p><h2>Pennsylvania</h2><p>Threshold: $100,000 gross sales. Economic nexus applies to all tangible personal property and most digital goods. Enforcement active.</p>` },
    { num: "03", slug: "nexus-03", name: "FBA Inventory Nexus Audit", desc: "Which Amazon fulfilment centres create nexus — and your registration priority.", tier: 1, content: `<h2>FBA Creates Physical Nexus</h2><p>Having inventory in any Amazon fulfilment centre creates physical nexus in that state — immediately, with no sales threshold. Amazon operates fulfilment centres in over 40 states.</p><div class="action-box"><h3>How to Find Your FBA States</h3><p>1. Log into Amazon Seller Central</p><p>2. Go to Reports → Tax Document Library</p><p>3. Download your "Inventory Event Detail" report</p><p>4. Filter by state — any state with inventory = nexus</p></div><h2>High-Risk FBA States (Major Fulfilment Centres)</h2><table><tr><th>State</th><th>Sales Tax Rate</th><th>Priority</th></tr><tr><td>California</td><td>7.25% + local</td><td>Very High</td></tr><tr><td>Texas</td><td>6.25% + local</td><td>High</td></tr><tr><td>Pennsylvania</td><td>6%</td><td>High</td></tr><tr><td>New Jersey</td><td>6.625%</td><td>High</td></tr></table>` },
    { num: "04", slug: "nexus-04", name: "Filing Sequence Roadmap", desc: "The order to register across states — minimise compliance cost and complexity.", tier: 1, content: `<h2>Where to Register First</h2><p>Prioritise states by: (1) highest exposure / oldest nexus date, (2) highest audit risk, (3) highest sales volume.</p><div class="action-box"><h3>Registration Order</h3><p>Step 1: Identify all nexus states (economic + physical)</p><p>Step 2: Calculate estimated liability per state</p><p>Step 3: File VDA in highest-exposure states first</p><p>Step 4: Register in remaining states</p><p>Step 5: Set up collection and filing in each registered state</p></div><h2>VDA vs Direct Registration</h2><table><tr><th>Option</th><th>Lookback</th><th>Penalties</th><th>When</th></tr><tr><td>VDA</td><td>Limited (3–4yr)</td><td>Reduced</td><td>Before audit contact</td></tr><tr><td>Direct registration</td><td>From nexus date</td><td>Full</td><td>Going forward only</td></tr><tr><td>Amnesty programme</td><td>Varies</td><td>Waived</td><td>During amnesty window</td></tr></table>` },
    { num: "05", slug: "nexus-05", name: "Your Accountant Brief", desc: "Print and take to your next meeting — nexus questions your CPA must answer.", tier: 1, content: `<div class="info-box"><strong>How to use this brief:</strong> Print or forward to your CPA or sales tax adviser before your next meeting.</div><h2>Client Nexus Exposure Status</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Nexus standard</td><td>$100k gross sales (most states)</td></tr><tr><td>FBA creates</td><td>Physical nexus — no threshold</td></tr><tr><td>Marketplace sales</td><td>Count toward threshold</td></tr></table><div class="action-box"><h3>Question 1</h3><p>"In which states have I crossed the economic nexus threshold based on ALL gross sales?"</p></div><h3>Question 2</h3><p>"Which states does my FBA inventory create physical nexus in?"</p><h3>Question 3</h3><p>"Should we file VDAs before year-end to cap lookback periods?"</p><h3>Question 4</h3><p>"Are there any current state amnesty programmes?"</p><h3>Question 5</h3><p>"What is my estimated total uncollected tax liability across all states?"</p>` },
    { num: "06", slug: "nexus-06", name: "VDA Templates and Strategy", desc: "Voluntary Disclosure Agreements — how to file, what to say, how to limit your exposure.", tier: 2, content: `<h2>What Is a VDA?</h2><p>A Voluntary Disclosure Agreement is a formal agreement with a state revenue authority where you come forward before being contacted. In exchange, the state limits your lookback period and reduces or eliminates penalties.</p><div class="action-box"><h3>VDA Benefits</h3><p>Lookback limited: typically 3–4 years vs unlimited for non-filers</p><p>Penalties: often waived or significantly reduced</p><p>Anonymous filing: available in many states via a representative</p><p>Protection: once VDA filed, prevents audit for covered period</p></div><h2>VDA Filing Process</h2><ol><li>Calculate your liability for the lookback period</li><li>Engage a sales tax adviser (anonymous filing requires a representative)</li><li>Submit VDA application to state revenue authority</li><li>Negotiate lookback period and penalty terms</li><li>File back returns and pay agreed liability</li><li>Register for ongoing collection and filing</li></ol>` },
    { num: "07", slug: "nexus-07", name: "Penalty Reduction Calculator", desc: "Estimate your penalty savings from VDA vs audit discovery — state by state.", tier: 2, content: `<h2>The Cost of Waiting</h2><p>Every month of delay increases your nexus liability. Understanding the penalty savings from VDA vs audit motivates action.</p><h2>Typical Penalty Structure</h2><table><tr><th>Scenario</th><th>Tax Due</th><th>Penalties</th><th>Interest</th><th>Total</th></tr><tr><td>VDA — 3-year lookback</td><td>$15,000</td><td>$0 (waived)</td><td>$1,500</td><td>$16,500</td></tr><tr><td>Audit — 5-year lookback</td><td>$25,000</td><td>$5,000</td><td>$7,500</td><td>$37,500</td></tr><tr><td>VDA savings</td><td colspan="3">-</td><td>$21,000</td></tr></table><div class="action-box"><h3>Key Insight</h3><p>VDA limits lookback to 3–4 years. An audit can go back to the date nexus was established — potentially 5–10+ years. The lookback difference alone often saves $10,000–$50,000 in tax plus penalties.</p></div>` },
    { num: "08", slug: "nexus-08", name: "Multi-State VDA Strategy and Amnesty Tracker", desc: "Filing order optimisation and 2026 amnesty programme tracking.", tier: 2, content: `<h2>Multi-State Filing Strategy</h2><p>Filing VDAs in multiple states simultaneously is complex. The order matters — some states have more favourable terms or are higher risk.</p><div class="action-box"><h3>Optimal Filing Order</h3><p>Priority 1: States with unlimited lookback (no statute of limitations for non-filers)</p><p>Priority 2: States with current amnesty programmes (better terms than VDA)</p><p>Priority 3: States with highest sales volume / oldest nexus date</p><p>Priority 4: Remaining nexus states by risk level</p></div><h2>2026 Amnesty Programme Tracker</h2><table><tr><th>State</th><th>Programme Status</th><th>Deadline</th><th>Terms</th></tr><tr><td>Check Sales Tax Institute</td><td>Updated monthly</td><td>Varies</td><td>Better than VDA</td></tr></table><div class="info-box"><strong>Note:</strong> Amnesty programmes change frequently. Always verify current status with the state revenue authority or a sales tax adviser before filing. The Sales Tax Institute maintains a current tracker at salestaxinstitute.com.</div>` },
  ],
  calendarTitle: "Nexus Compliance — Critical Deadlines",
  tier1Calendar: [
    { uid: "nexus-q2",    summary: "Nexus — Q2 Sales Tax Filing Deadlines",   description: "Most states require monthly or quarterly filing. Check your registered state deadlines.", date: "20260630" },
    { uid: "nexus-q3",    summary: "Nexus — Q3 Sales Tax Filing Deadlines",   description: "Q3 sales tax returns due in most states.", date: "20260930" },
    { uid: "nexus-q4",    summary: "Nexus — Year-End Nexus Review",           description: "Review gross sales by state. Check for new nexus states. File VDAs before year-end.", date: "20261215" },
    { uid: "nexus-year",  summary: "Nexus — Annual Threshold Review",         description: "Recalculate nexus exposure for 2026 based on full-year gross sales.", date: "20261231" },
  ],
  tier2Calendar: [
    { uid: "nexus-vda",   summary: "Nexus — Prioritise VDA filing states",    description: "Identify highest-exposure states. Engage adviser for anonymous VDA filing.", date: "relative:+14days" },
    { uid: "nexus-fba",   summary: "Nexus — FBA inventory nexus audit",       description: "Download Inventory Event Detail report from Seller Central. Identify all FBA states.", date: "relative:+7days" },
    { uid: "nexus-q2",    summary: "Nexus — Q2 Filing Deadlines",             description: "Q2 sales tax returns due across registered states.", date: "20260630" },
    { uid: "nexus-q3",    summary: "Nexus — Q3 Filing Deadlines",             description: "Q3 returns due.", date: "20260930" },
    { uid: "nexus-amnesty", summary: "Nexus — Check State Amnesty Programmes", description: "Review current state amnesty programmes — better terms than VDA in some states.", date: "20261001" },
    { uid: "nexus-year",  summary: "Nexus — Year-End Compliance Review",      description: "Full gross sales by state review. File all outstanding VDAs before year-end.", date: "20261231" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_NEXUS_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_NEXUS_147" },
  monitorUrls: ["https://www.salestaxinstitute.com/sales_tax_faqs/economic-nexus-state-by-state-guide", "https://www.streamlinedsalestax.org"],
  sidebarNumbers: [{ label: "Economic nexus threshold", value: "$100k gross" }, { label: "FBA nexus", value: "Immediate" }, { label: "Marketplace sales", value: "Count toward threshold" }, { label: "Lookback risk", value: "Unlimited (some states)" }],
  sidebarMathsTitle: "What counts toward nexus threshold",
  sidebarMathsIncludes: ["Direct website sales", "Amazon marketplace sales", "Etsy / Walmart sales", "Exempt product sales", "FBA states: all sales from $1"],
  sidebarMathsExcludes: ["NOT just taxable sales", "NOT just direct sales", "NOT safe if marketplace collects"],
  sidebarMathsNote: "Source: South Dakota v. Wayfair (2018) · Sales Tax Institute 2026",
  howToSteps: [
    { position: 1, name: "Select your sales volume bracket", text: "Choose your total gross sales across all channels — direct and marketplace — in the last 12 months." },
    { position: 2, name: "Identify your channels and FBA use", text: "Specify where you sell and whether you use Amazon FBA. FBA creates immediate nexus regardless of sales volume." },
    { position: 3, name: "Get your nexus exposure verdict", text: "See which states you likely have nexus in, your estimated liability, and whether you are already non-compliant." },
    { position: 4, name: "Get your compliance plan", text: "Receive a personalised registration order, VDA strategy, and estimated penalty savings for your situation." },
  ],
  successPromptFields: [
    { key: "nexus_sales", label: "Annual gross sales", defaultVal: "150000" },
    { key: "nexus_channels", label: "Sales channels", defaultVal: "multi" },
    { key: "nexus_fba", label: "Uses FBA", defaultVal: "false" },
    { key: "nexus_status", label: "Nexus status", defaultVal: "at_risk" },
  ],
  tier1AssessmentFields: ["status", "nexusStates", "estimatedLiability", "biggestRisk", "firstAction", "registrationPriority", "accountantQuestions"],
  tier2AssessmentFields: ["status", "nexusStates", "estimatedLiability", "biggestRisk", "vdaStrategy", "penaltySavings", "actions", "weekPlan", "accountantQuestions"],
  persona: {
    name: "Tyler",
    age: 36,
    occupation: "Co-founder and CEO, Stackform Inc — B2B SaaS, Austin TX, Series A",
    location: "Austin, Texas",
    family: "Partner Maya (UX designer). No kids. Dog named Kernel.",
    financialSnapshot: "$800k engineering payroll — 8 US engineers, 4 India offshore. $2.1M ARR. ISO options. QSBS qualified. Sells into 18 states.",
    painPoint: "Tyler is meticulous about product. His tax situation has grown faster than his attention to it.",
    discovery: "Tyler found the gap when an AI tool gave him three different answers on Section 174 before a board meeting.",
    voice: "Precise. Data-driven. Shares good tools immediately. Respects speed and specificity.",
  },
  story: {
    hook: "Stackform sold into 18 states. Tyler knew about sales tax in theory. He had not checked his nexus position since launch.",
    setup: [
    "The first version of Stackform sold only to Texas companies. As the product grew, AWS Marketplace opened up sales to California, New York, Illinois, Washington, Florida, and twelve more states automatically.",
    "Tyler assumed SaaS was sometimes tax exempt. He had heard this at a founder dinner. The reality is more fragmented: some states tax SaaS fully, some partially, some not at all.",
    "Each state sets its own threshold. Most use $100,000 in annual sales or 200 transactions. Tyler had crossed both in California, New York, and Washington in the prior year without registering in any of them.",
    ],
    revelation: "The nexus audit showed active economic nexus in seven states with no sales tax registration. California exposure alone was 14 months of unregistered sales at up to 10.25%.",
    resolution: "Rachel initiated voluntary disclosure in five states. Registered in all seven. Implemented a tax calculation API in the billing system. Nexus monitoring now runs automatically at 80% of each state threshold.",
  },
};
