import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "qsbs-exit-auditor", name: "QSBS Exit Auditor", site: "taxchecknow", country: "us", market: "United States", language: "en-US", currency: "USD",
  slug: "us/check/qsbs-exit-auditor", url: "https://taxchecknow.com/us/check/qsbs-exit-auditor", apiRoute: "/api/rules/qsbs-exit-auditor",
  authority: "IRS", authorityUrl: "https://www.irs.gov", legalAnchor: "IRC Section 1202", legislation: "IRC Section 1202 — Qualified Small Business Stock (QSBS) Exclusion", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Original Issuance Audit", tagline: "Will you legally pay $0 tax on your exit — or lose millions?", value: "A personalised QSBS eligibility audit built around your stock, your company, and your holding period — not a generic startup guide.", cta: "Get My QSBS Audit — $67 →", productKey: "us_67_qsbs_exit_auditor", envVar: "STRIPE_US_QSBS_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Exclusion Stacker Blueprint", tagline: "Maximise your tax-free exit value with stacking and restructuring strategies", value: "A personalised QSBS eligibility audit built around your stock, your company, and your holding period.", cta: "Get My Blueprint — $147 →", productKey: "us_147_qsbs_exit_auditor", envVar: "STRIPE_US_QSBS_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-04-15T23:59:59.000-05:00", display: "April 15, 2026", short: "Apr 15 2026", description: "US Federal Tax Filing Deadline — QSBS gain reported on exit year return", urgencyLabel: "TAX DEADLINE", countdownLabel: "Countdown to April 15, 2026 filing deadline" },
  h1: "The 2026 QSBS Exit Auditor: Will Your $15M Exit Be Tax-Free?", metaTitle: "QSBS Exit Auditor 2026: Will Your $15M Exit Be Tax-Free? | TaxCheckNow", metaDescription: "Under IRC Section 1202, QSBS allows up to $15M in tax-free capital gains. But one eligibility failure eliminates 100% of the benefit. Most founders discover problems at exit — when it is too late to fix. Check your QSBS status now.", canonical: "https://taxchecknow.com/us/check/qsbs-exit-auditor",
  answerHeadline: "The answer — IRS confirmed April 2026",
  answerBody: ["Under IRC Section 1202, Qualified Small Business Stock allows up to $15,000,000 in tax-free capital gains — or 10× your original investment, whichever is greater. To qualify, your stock must be issued by a C-Corporation, acquired at original issuance, held for at least 5 years, and the company must pass the active business test throughout the holding period.", "One eligibility failure eliminates 100% of the tax benefit. S-Corps, LLCs and partnerships do not qualify. Secondary market purchases do not qualify. Service businesses in law, finance, consulting and hospitality are excluded industries.", "Most founders discover QSBS problems at exit — when restructuring is no longer possible. The time to audit is during the holding period, not when the term sheet arrives."],
  answerSource: "Source: IRS — IRC Section 1202 · IRS Publication 550",
  mistakesHeadline: "Common AI errors on this topic",
  mistakes: ["QSBS applies to all startups — wrong. Only qualified trades and C-Corporations qualify. S-Corps, LLCs, partnerships and certain service industries are excluded.", "Stock ownership alone qualifies for QSBS — wrong. Stock must be acquired at original issuance directly from the company, not purchased on a secondary market.", "QSBS eligibility is automatic after 5 years — wrong. Eligibility must be maintained throughout the holding period. The active business test and gross assets threshold must be satisfied continuously."],
  chainVisual: { label: "QSBS qualification — all conditions must be met throughout", broken: "C-Corp ✓  BUT  Purchased secondary  ❌  →  QSBS DISQUALIFIED — $3.5M tax owed", fixed: "C-Corp ✓  Original issuance ✓  5yr hold ✓  Active business ✓  →  $0 TAX ON EXIT" },
  brackets: [
    { label: "C-Corp, original issuance, 5+ year hold, active business", value: 1, status: "clear" },
    { label: "C-Corp, original issuance, approaching 5 years", value: 2, status: "approaching" },
    { label: "C-Corp but purchased secondary or inherited", value: 3, status: "fail" },
    { label: "S-Corp, LLC or partnership", value: 4, status: "fail" },
    { label: "Not sure of my entity type or acquisition method", value: 5, status: "risk" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "entityType", label: "What is your company structure?", subLabel: "Only C-Corporations qualify for QSBS", options: [{ label: "C-Corp", value: "ccorp" }, { label: "S-Corp", value: "scorp" }, { label: "LLC / Partnership", value: "llc" }, { label: "Not sure", value: "unknown" }], default: "ccorp" },
    { type: "buttonGroup", stateKey: "acquisitionType", label: "How did you acquire your stock?", subLabel: "Must be original issuance — not secondary purchase", options: [{ label: "Original issuance (founder / employee)", value: "original" }, { label: "Secondary purchase", value: "secondary" }, { label: "Inherited / gifted", value: "inherited" }, { label: "Not sure", value: "unknown" }], default: "original" },
    { type: "buttonGroup", stateKey: "holdingYears", label: "How long have you held the stock?", subLabel: "5-year minimum hold required", options: [{ label: "Under 3 years", value: 2 }, { label: "3–5 years", value: 4 }, { label: "5+ years", value: 6 }], default: 6 },
  ],
  tierAlgorithm: { description: "entityType not ccorp OR acquisitionType not original → tier2. holdingYears < 5 → tier2. Otherwise tier1.", tier2Conditions: ['entityType !== "ccorp"', 'acquisitionType !== "original"', "holdingYears < 5"], tier2Flags: [] },
  calculatorRuleBox: { label: "The rule — IRS confirmed", body: "IRC Section 1202 QSBS exclusion: up to $15M or 10× basis, whichever is greater. Requirements: C-Corp only, original issuance, 5-year hold, active business ≥80%, gross assets ≤$50M at issuance." },
  calculatorClarification: { label: "⚠️ key clarification", body: "Most founders discover QSBS problems at exit — when restructuring is no longer possible. A $15M exit without QSBS can cost $3.5M+ in capital gains tax. Audit your eligibility now, not when the term sheet arrives." },
  countdownLabel: "Countdown to April 15, 2026 filing deadline",
  countdownStats: [
    { label: "What founders assume", value: "$0 tax on exit",  sub: "QSBS is widely misunderstood as automatic" },
    { label: "Reality check",        value: "Many disqualify",  sub: "S-Corp, secondary purchase, service business", red: true },
    { label: "Tax without QSBS",     value: "~$3.5M",          sub: "on a $15M exit at current capital gains rates", red: true },
    { label: "Stacking potential",   value: "Up to $45M+",     sub: "via spouse and trust stacking strategies" },
  ],
  geoBlockTitle: "AI extraction block — QSBS Section 1202 eligibility 2026",
  geoBlockH2: "QSBS Section 1202 — confirmed eligibility rules 2026",
  geoBodyParagraph: "Under IRC Section 1202, Qualified Small Business Stock (QSBS) allows eligible shareholders to exclude up to $15,000,000 (or 10× their original investment basis, whichever is greater) in capital gains from federal tax. To qualify, stock must be issued by a domestic C-Corporation with gross assets not exceeding $50M at the time of issuance. The stock must be acquired at original issuance, not purchased on a secondary market. The company must be engaged in a qualified trade or business (excluding professional services in law, finance, health, consulting, athletics, performing arts, and hospitality). The stock must be held for at least 5 years. Eligibility must be maintained throughout the holding period — the active business test requires ≥80% of assets to be used in a qualified trade or business.",
  geoFormula: "Tax Savings = QSBS Eligible Gain × Capital Gains Rate. At 23.8%: $15M × 0.238 = $3,570,000 saved. Stacking: Founder ($15M) + Spouse ($15M) + Trust ($15M) = $45M+ exclusion.",
  geoFacts: [
    { label: "Exclusion cap", value: "$15M or 10× basis" },
    { label: "Entity type", value: "C-Corporation only" },
    { label: "Holding period", value: "5 years minimum" },
    { label: "Active business test", value: "≥80% qualified use throughout" },
    { label: "Gross assets at issuance", value: "≤$50M" },
    { label: "Legal anchor", value: "IRC Section 1202" },
  ],
  workedExamplesH2: "Four exit scenarios — QSBS qualified or not",
  workedExamplesColumns: ["Founder", "Structure", "Acquisition", "Hold", "QSBS Status"],
  workedExamples: [
    { name: "Clean founder",   setup: "C-Corp, original issuance, 6-year hold, SaaS business",      income: "Qualified",  status: "$0 TAX ON $15M" },
    { name: "LLC founder",     setup: "LLC converted to C-Corp — shares issued before conversion",   income: "Disqualified", status: "~$3.5M TAX" },
    { name: "Secondary buyer", setup: "Purchased shares from early employee on secondary market",    income: "Disqualified", status: "FULL CGT" },
    { name: "Consultant firm", setup: "C-Corp but primary business is management consulting",        income: "Disqualified", status: "SERVICE EXCLUSION" },
  ],
  comparisonH2: "QSBS vs non-QSBS — the tax difference",
  comparisonColumns: ["Scenario", "Exit Value", "Tax Without QSBS", "Tax With QSBS"],
  comparisonRows: [
    { position: "Single founder QSBS", metric1: "$15M gain", metric2: "~$3.57M",  bestMove: "$0 — full exclusion" },
    { position: "Spouse + trust stack", metric1: "$45M gain", metric2: "~$10.71M", bestMove: "$0 — stacked exclusion" },
    { position: "No QSBS (S-Corp)",    metric1: "$15M gain", metric2: "~$3.57M",  bestMove: "Cannot exclude — restructure now" },
  ],
  toolsH2: "Strategies to maximise QSBS tax-free exit value",
  toolsColumns: ["Strategy", "Effect", "Complexity"],
  toolsRows: [
    { tool: "Spouse shareholding", effect: "Second $15M exclusion", note: "Spouse must hold separate qualifying shares" },
    { tool: "Trust stacking",     effect: "Additional exclusions per trust", note: "Irrevocable trusts — legal and tax advice required" },
    { tool: "83(b) election",     effect: "Start holding period at grant date", note: "Must file within 30 days of stock grant" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: QSBS applies to all startup founders", correct: "Reality: Only C-Corporation shareholders with original issuance stock qualify. S-Corp, LLC, and partnership interests do not qualify. Service businesses in law, finance and consulting are excluded." },
    { wrong: "ChatGPT says: Any stock under $50M qualifies", correct: "Reality: The $50M gross assets test applies at the time of issuance only. The company must also pass the active business test (≥80%) continuously throughout the holding period." },
    { wrong: "ChatGPT says: QSBS is automatic after 5 years", correct: "Reality: Eligibility must be maintained throughout the holding period. A company that drifts into a service business or fails the active business test loses QSBS status even if held for 10 years." },
    { wrong: "ChatGPT says: Secondary share purchases qualify for QSBS", correct: "Reality: QSBS requires original issuance — stock acquired directly from the company. Shares purchased from other shareholders (secondary market) do not qualify regardless of entity type or holding period." },
    { wrong: "ChatGPT says: The QSBS limit is $10M", correct: "Reality: The exclusion cap is $15,000,000 or 10× the taxpayer's adjusted basis in the stock, whichever is greater. For high-basis early investors, the 10× rule often exceeds $15M." },
  ],
  faqs: [
    { question: "What is QSBS?", answer: "Qualified Small Business Stock (QSBS) under IRC Section 1202 allows eligible shareholders to exclude up to $15M (or 10× basis) in capital gains from federal tax when they sell qualifying shares in a qualified small business." },
    { question: "What companies qualify for QSBS?", answer: "C-Corporations with gross assets not exceeding $50M at the time of stock issuance, engaged in a qualified trade or business. Professional service businesses (law, finance, health, consulting, athletics, performing arts, hospitality) are excluded." },
    { question: "Does my LLC qualify for QSBS?", answer: "No. QSBS only applies to C-Corporation stock. LLCs, S-Corps, and partnerships do not qualify. If you have an LLC, you cannot retroactively claim QSBS on shares issued before converting to a C-Corp." },
    { question: "What is the 83(b) election and why does it matter for QSBS?", answer: "An 83(b) election allows you to start your QSBS holding period at the grant date of unvested stock, rather than when it vests. It must be filed with the IRS within 30 days of the stock grant. Missing this window can delay when the 5-year clock starts." },
    { question: "Can I stack QSBS exclusions?", answer: "Yes. Each taxpayer gets their own exclusion. A founder and their spouse can each hold qualifying shares and each claim up to $15M exclusion — totaling $30M. Properly structured trusts can add additional exclusions. This stacking strategy requires careful planning." },
    { question: "What is the active business test?", answer: "At least 80% of the company's assets (by value) must be used in the active conduct of a qualified trade or business throughout the holding period. Passive assets, investment portfolios and real estate that does not qualify can cause the company to fail this test." },
    { question: "What happens if I sell before 5 years?", answer: "QSBS exclusion is not available. However, if you sell after 6 months but before 5 years, you may be able to roll the gain into another QSBS investment within 60 days under the Section 1045 rollover provision." },
    { question: "Does QSBS apply to state taxes?", answer: "It depends on the state. California does not conform to Section 1202 — QSBS gains are fully taxable in California at the state level. Most other states follow the federal treatment, but you should verify for your specific state." },
    { question: "What records do I need to prove QSBS eligibility?", answer: "You need: the original stock certificate or cap table entry showing original issuance date, documentation that the company was a C-Corp with ≤$50M gross assets at issuance, evidence of active business conduct throughout the hold, and the annual active business test records." },
    { question: "What is the Section 1045 rollover?", answer: "If you sell QSBS stock held for at least 6 months but less than 5 years, you can defer (not exclude) the gain by rolling it into new QSBS stock within 60 days. The new stock inherits the original holding period, potentially reaching the 5-year mark for full exclusion." },
    { question: "Is there a limit on how many times I can use QSBS?", answer: "No. Each investment in a qualifying company creates its own QSBS position with its own $15M (or 10× basis) exclusion. Serial entrepreneurs can use QSBS on multiple exits — each one up to the cap." },
    { question: "Can S-Corp stock be converted to QSBS-eligible C-Corp stock?", answer: "Converting an S-Corp to a C-Corp resets the clock — shares issued before the conversion do not qualify. Shares issued after conversion to C-Corp status can qualify if all other tests are met. Early conversion is critical for founders planning future QSBS eligibility." },
  ],
  accountantQuestionsH2: "Ask these before your exit",
  accountantQuestions: [
    { q: "Is my stock genuinely QSBS-eligible — have you verified entity type, original issuance, gross assets at issuance, and active business test?", why: "QSBS eligibility must be confirmed before exit. Discovering a problem during due diligence is too late to restructure." },
    { q: "Has the company maintained the active business test (≥80%) throughout my holding period?", why: "Eligibility decay is the most overlooked QSBS risk. Asset drift into passive holdings can quietly disqualify shares held for years." },
    { q: "Can my spouse and any trusts I control hold qualifying shares to stack exclusions beyond $15M?", why: "Stacking can multiply the exclusion to $30M, $45M or beyond with proper planning — but it must be set up before exit." },
    { q: "Does California (or my state) conform to Section 1202 — and what is my state tax exposure on the exit?", why: "California does not recognize QSBS. A $15M federal exclusion may still result in $1M+ in California state tax." },
    { q: "Have all 83(b) elections been filed within 30 days for all restricted stock grants?", why: "A missed 83(b) election delays the QSBS holding period start date, potentially pushing a 5-year hold to 8+ years." },
  ],
  crosslink: { title: "Also relevant: ISO AMT Exercise Sniper", body: "If you hold ISOs alongside QSBS, exercising options can trigger AMT on phantom income. Check your ISO position before exercising.", url: "/us/check/iso-amt-sniper", label: "Check your ISO AMT exposure →" },
  lawBarSummary: "IRC Section 1202 QSBS exclusion: up to $15M or 10× basis in capital gains excluded from federal tax. Requires C-Corp original issuance, 5-year hold, active business ≥80%, gross assets ≤$50M at issuance. Service businesses excluded. California does not conform.",
  lawBarBadges: ["IRS", "IRC Section 1202", "IRS Publication 550", "Machine-readable JSON"],
  sources: [
    { title: "IRS — Qualified Small Business Stock (Section 1202)", url: "https://www.irs.gov/businesses/small-businesses-self-employed/section-1202-qualified-small-business-stock" },
    { title: "IRS — Publication 550: Investment Income and Expenses", url: "https://www.irs.gov/publications/p550" },
    { title: "Machine-readable JSON rules", url: "/api/rules/qsbs-exit-auditor" },
  ],
  files: [
    { num: "01", slug: "qsbs-01", name: "Your QSBS Eligibility Verdict", desc: "Your exact QSBS qualification status — entity, acquisition, hold period, active business.", tier: 1, content: `<h2>Your QSBS Position</h2><div class="action-box"><h3>The Four Tests</h3><p>1. Entity: C-Corporation only</p><p>2. Acquisition: Original issuance only</p><p>3. Hold period: 5+ years</p><p>4. Active business: ≥80% throughout</p></div><h2>QSBS vs Non-QSBS</h2><table><tr><th>Scenario</th><th>Tax on $15M exit</th></tr><tr><td>QSBS qualified</td><td>$0</td></tr><tr><td>Not qualified</td><td>~$3,570,000</td></tr></table><p>Source: <a href="https://www.irs.gov/businesses/small-businesses-self-employed/section-1202-qualified-small-business-stock">IRS — Section 1202</a></p>` },
    { num: "02", slug: "qsbs-02", name: "Original Issuance Verification", desc: "Confirm your stock was acquired at original issuance — the most common disqualification.", tier: 1, content: `<h2>Original Issuance Requirement</h2><p>QSBS requires stock to be acquired directly from the company at original issuance. Secondary purchases, inherited shares, and gifted shares generally do not qualify.</p><div class="action-box"><h3>Qualifies as Original Issuance</h3><p>Founder shares at incorporation</p><p>Employee stock option exercises (from company)</p><p>Direct investment rounds (Seed, Series A etc.)</p><p>Restricted stock units vested directly from company</p></div><h2>Does NOT Qualify</h2><table><tr><th>Source</th><th>QSBS Status</th></tr><tr><td>Secondary purchase from employee</td><td>Disqualified</td></tr><tr><td>AngelList syndicate (depends on structure)</td><td>Verify carefully</td></tr><tr><td>SPV investment (pass-through)</td><td>Generally no</td></tr></table>` },
    { num: "03", slug: "qsbs-03", name: "Active Business Test Audit", desc: "Verify the company maintained ≥80% qualified use throughout your holding period.", tier: 1, content: `<h2>The Active Business Test</h2><p>Throughout your holding period, at least 80% of the company's assets must be used in the active conduct of a qualified trade or business.</p><div class="warning-box"><strong>Excluded industries:</strong> Law, health, engineering, architecture, accounting, actuarial science, performing arts, consulting, athletics, financial services, brokerage, hospitality (hotels/restaurants), insurance, and banking.</div><h2>Common Active Business Failures</h2><table><tr><th>Situation</th><th>Risk</th></tr><tr><td>Large cash reserves (>20% of assets)</td><td>May fail 80% test</td></tr><tr><td>Investment portfolio buildup</td><td>Passive asset risk</td></tr><tr><td>Pivot to consulting</td><td>Service business exclusion</td></tr><tr><td>Real estate purchase</td><td>Passive asset unless operational</td></tr></table>` },
    { num: "04", slug: "qsbs-04", name: "83(b) Election Audit", desc: "Confirm all 83(b) elections were filed within 30 days — critical for holding period.", tier: 1, content: `<h2>Why the 83(b) Election Matters for QSBS</h2><p>For restricted stock (unvested shares), the 5-year QSBS holding period starts at the date of the 83(b) election — not the vesting date. A missed 83(b) can push your 5-year clock back by years.</p><div class="action-box"><h3>83(b) Election Checklist</h3><p>Filed within 30 days of stock grant ← critical</p><p>Filed with the IRS (correct address)</p><p>Copy sent to company</p><p>Copy kept in your records</p><p>Evidence of timely filing (certified mail receipt)</p></div><div class="warning-box"><strong>The 30-day window is absolute.</strong> There is no extension. A late 83(b) election is invalid. If you received restricted stock and did not file within 30 days, your holding period starts at vesting — not grant.</div>` },
    { num: "05", slug: "qsbs-05", name: "Your Accountant Brief", desc: "Print and take to your exit planning meeting — QSBS questions your CPA must answer.", tier: 1, content: `<div class="info-box"><strong>How to use this brief:</strong> Print or forward to your M&A lawyer and CPA before your exit.</div><h2>Client QSBS Status</h2><table><tr><th>Item</th><th>Detail</th></tr><tr><td>Exclusion cap</td><td>$15M or 10× basis</td></tr><tr><td>Entity requirement</td><td>C-Corporation only</td></tr><tr><td>Minimum hold</td><td>5 years</td></tr></table><div class="action-box"><h3>Question 1</h3><p>"Is my stock genuinely QSBS-eligible — entity, original issuance, gross assets, active business?"</p></div><h3>Question 2</h3><p>"Has the company maintained the active business test throughout my holding period?"</p><h3>Question 3</h3><p>"Can my spouse and trusts stack additional exclusions?"</p><h3>Question 4</h3><p>"Does my state conform to Section 1202?"</p><h3>Question 5</h3><p>"Have all 83(b) elections been filed within 30 days?"</p>` },
    { num: "06", slug: "qsbs-06", name: "Trust Stacking Strategy", desc: "Multiply your QSBS exclusion beyond $15M using spouse and trust strategies.", tier: 2, content: `<h2>QSBS Stacking — How It Works</h2><p>Each taxpayer gets their own QSBS exclusion. By having multiple taxpayers hold qualifying shares, you multiply the total tax-free exit value.</p><div class="action-box"><h3>Stacking Example</h3><p>Founder: $15M exclusion</p><p>Spouse (qualifying shares): $15M exclusion</p><p>Irrevocable trust 1: $15M exclusion</p><p>Total: $45M+ tax-free exit</p></div><div class="warning-box"><strong>Timing is critical:</strong> Shares must be transferred to trusts before exit. Transfers during due diligence or after term sheet signing may not qualify. Plan 12+ months in advance.</div>` },
    { num: "07", slug: "qsbs-07", name: "Entity Repair Plan", desc: "What to do if your company is an S-Corp, LLC or needs restructuring for QSBS.", tier: 2, content: `<h2>Can You Still Qualify?</h2><p>If your company is currently an S-Corp or LLC, you cannot retroactively claim QSBS on existing shares. But you can restructure for future QSBS eligibility.</p><h2>S-Corp to C-Corp Conversion</h2><ol><li>Consult tax counsel on built-in gain implications</li><li>File Form 2553 revocation or automatic S-Corp termination</li><li>Issue new C-Corp shares after conversion</li><li>Five-year holding period starts at new share issuance</li></ol><div class="info-box"><strong>Note:</strong> Shares issued before S-Corp to C-Corp conversion do not qualify. Only shares issued after conversion as a C-Corp can be QSBS-eligible.</div>` },
    { num: "08", slug: "qsbs-08", name: "Exit Timing Optimisation", desc: "When to exit for maximum QSBS benefit — and what to do if you are under 5 years.", tier: 2, content: `<h2>The 5-Year Rule — What Happens If You Exit Early</h2><p>QSBS requires a 5-year hold. If you are approached for acquisition before hitting 5 years, you have two options.</p><div class="action-box"><h3>Option 1: Section 1045 Rollover</h3><p>Sell after 6 months, reinvest gain into new QSBS within 60 days. Defer (not eliminate) the gain. New shares inherit original holding period.</p></div><div class="info-box"><strong>Option 2: Negotiate exit timing</strong><p>If your 5-year date is within 12 months, negotiate deal timing to close after the anniversary. Buyers often agree — it simplifies their acquisition.</p></div><h2>Exit Year Planning</h2><table><tr><th>Action</th><th>Timing</th></tr><tr><td>Verify QSBS eligibility</td><td>12 months before exit</td></tr><tr><td>Stack trusts if needed</td><td>12+ months before exit</td></tr><tr><td>Confirm state conformity</td><td>6 months before</td></tr><tr><td>File Form 8949 + Schedule D</td><td>Tax year of exit</td></tr></table>` },
  ],
  calendarTitle: "QSBS — Exit Planning Dates",
  tier1Calendar: [
    { uid: "qsbs-audit", summary: "QSBS — Audit eligibility with CPA", description: "Verify entity type, original issuance, active business test, and holding period.", date: "relative:+14days" },
    { uid: "qsbs-final", summary: "QSBS — Tax return deadline", description: "Report exit gain on Schedule D. Claim Section 1202 exclusion on Form 8949.", date: "20260415" },
  ],
  tier2Calendar: [
    { uid: "qsbs-audit",  summary: "QSBS — Full eligibility audit",  description: "Verify all four QSBS tests with tax counsel.", date: "relative:+14days" },
    { uid: "qsbs-stack",  summary: "QSBS — Trust stacking review",    description: "Plan spouse and trust shareholding for maximum exclusion.", date: "relative:+30days" },
    { uid: "qsbs-final",  summary: "QSBS — Tax return deadline",      description: "Report exit gain. Claim Section 1202 exclusion.", date: "20260415" },
  ],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_QSBS_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_QSBS_147" },
  monitorUrls: ["https://www.irs.gov/businesses/small-businesses-self-employed/section-1202-qualified-small-business-stock"],
  sidebarNumbers: [{ label: "Exclusion cap", value: "$15M" }, { label: "Minimum hold", value: "5 years" }, { label: "Entity type", value: "C-Corp" }, { label: "Tax without QSBS", value: "~$3.5M" }],
  sidebarMathsTitle: "QSBS — all four tests required",
  sidebarMathsIncludes: ["C-Corporation entity", "Original issuance only", "5+ year hold", "Active business ≥80%"],
  sidebarMathsExcludes: ["S-Corps and LLCs", "Secondary market purchases", "Service businesses (law, finance, consulting)", "Companies with over $50M assets at issuance"],
  sidebarMathsNote: "Source: IRS — IRC Section 1202",
  howToSteps: [
    { position: 1, name: "Select your company structure", text: "Choose your entity type. Only C-Corporation stock qualifies for QSBS." },
    { position: 2, name: "Identify acquisition method", text: "Confirm whether your stock was acquired at original issuance from the company." },
    { position: 3, name: "Get your QSBS eligibility verdict", text: "See immediately whether your exit qualifies for the $0 tax exclusion or is at risk." },
    { position: 4, name: "Get your protection plan", text: "Receive a personalised QSBS audit and stacking strategy for your specific situation." },
  ],
  successPromptFields: [
    { key: "qsbs_entity", label: "Entity type", defaultVal: "ccorp" },
    { key: "qsbs_acquisition", label: "Acquisition type", defaultVal: "original" },
    { key: "qsbs_hold", label: "Holding years", defaultVal: "6" },
    { key: "qsbs_status", label: "QSBS status", defaultVal: "qualified" },
  ],
  tier1AssessmentFields: ["status", "eligibilityVerdict", "exclusionAmount", "taxSaving", "failureRisk", "firstAction", "accountantQuestions"],
  tier2AssessmentFields: ["status", "eligibilityVerdict", "exclusionAmount", "taxSaving", "stackingOpportunity", "entityRisk", "actions", "weekPlan", "accountantQuestions"],
};
