import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "feie-nomad-auditor", name: "FEIE Nomad Auditor", site: "taxchecknow", country: "us", market: "United States", language: "en-US", currency: "USD",
  slug: "us/check/feie-nomad-auditor", url: "https://taxchecknow.com/us/check/feie-nomad-auditor", apiRoute: "/api/rules/feie-nomad-auditor",
  authority: "IRS", authorityUrl: "https://www.irs.gov", legalAnchor: "IRC Section 911 — Foreign Earned Income Exclusion", legislation: "IRC Section 911 — FEIE and Foreign Housing Exclusion (2026 limit: $126,500)", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your FEIE Eligibility Report", tagline: "Do you actually qualify for the Foreign Earned Income Exclusion — or are you exposed?", value: "A personalised FEIE eligibility audit showing which test you qualify under, your exclusion amount, and your abode risk.", cta: "Get My FEIE Report — $67 →", productKey: "us_67_feie_nomad_auditor", envVar: "STRIPE_US_FEIE_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your FEIE Optimisation Plan", tagline: "Maximise your exclusion and eliminate abode risk", value: "Full FEIE audit plus FEIE vs Foreign Tax Credit comparison, housing exclusion calculation, and multi-year optimisation plan.", cta: "Get My FEIE Plan — $147 →", productKey: "us_147_feie_nomad_auditor", envVar: "STRIPE_US_FEIE_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2027-06-15T23:59:59.000Z", display: "June 15, 2027", short: "Jun 15 2027", description: "Automatic extension for US citizens abroad — FEIE must be claimed on 2026 return", urgencyLabel: "EXPAT DEADLINE", countdownLabel: "Countdown to June 15, 2027 expat tax deadline" },
  h1: "FEIE 2026: Do You Actually Qualify — or Is Your Abode Still in the US?", metaTitle: "FEIE 2026: Foreign Earned Income Exclusion Eligibility — Nomad and Expat Tax | TaxCheckNow", metaDescription: "The FEIE excludes up to $126,500 of foreign earned income in 2026. But the abode test catches most digital nomads. If you still have a US apartment, storage unit, or family home — you may not qualify. Check your FEIE position in 2 minutes.", canonical: "https://taxchecknow.com/us/check/feie-nomad-auditor",
  answerHeadline: "The answer — IRS confirmed April 2026",
  answerBody: [
    "The Foreign Earned Income Exclusion (FEIE) allows qualifying US citizens to exclude up to $126,500 of foreign earned income from US federal tax in 2026. To qualify, you must meet either the Physical Presence Test (330 full days outside the US in a 12-month period) or the Bona Fide Residence Test (genuine resident of a foreign country for a full calendar year).",
    "The most commonly missed requirement is the tax home and abode test. Your tax home must be in a foreign country — AND you must not have an abode in the United States. Having a US apartment (even if sublet), a storage unit with significant belongings, or a family home you return to regularly can all indicate a US abode — disqualifying you from FEIE even if you pass the day-count test.",
    "The FEIE election is also irrevocable for 5 years once revoked. Switching between FEIE and the Foreign Tax Credit (FTC) mid-career requires careful planning. Many nomads claim FEIE when the FTC would save more — particularly in high-tax countries like Germany or France where the FTC offset exceeds the FEIE exclusion value.",
  ],
  answerSource: "Source: IRS — Publication 54 · IRC Section 911 · IRS Form 2555",
  mistakesHeadline: "What most digital nomads get wrong about FEIE",
  mistakes: [
    "Spending 330 days outside the US automatically qualifies you for FEIE — wrong. You must also have a foreign tax home and no US abode. A US apartment you maintain, a storage unit, or regular returns to a family property can all indicate a US abode that disqualifies you regardless of days abroad.",
    "FEIE is always better than the Foreign Tax Credit — wrong. If you live in a high-tax country (UK, Germany, France, Australia) where local taxes exceed the US rate, the Foreign Tax Credit may eliminate your US liability entirely — with no day-count requirement and no abode test.",
    "You can switch between FEIE and Foreign Tax Credit freely — wrong. Revoking the FEIE election means you cannot re-elect FEIE for 5 years without IRS permission. The decision to revoke should be modelled carefully before acting.",
  ],
  chainVisual: { label: "FEIE qualification — both tests must be met", broken: "330 days abroad → assume FEIE qualified  ❌  Day count alone is not enough", fixed: "330 days abroad + foreign tax home + NO US abode = FEIE qualified  ✔  All three required" },
  brackets: [
    { label: "Foreign bona fide resident — strongest FEIE position", value: 1, status: "clear"      },
    { label: "330-day physical presence test met — check abode carefully", value: 2, status: "approaching" },
    { label: "Between 183-329 days abroad — physical presence test fails", value: 3, status: "trap"  },
    { label: "US abode indicators — apartment, storage, family home", value: 4, status: "risk"       },
    { label: "High-tax country — FTC may be better than FEIE",          value: 5, status: "approaching" },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "daysAbroad", label: "How many full days were you outside the US in the past 12 months?", subLabel: "Full days — departure and arrival days do not count as full days abroad", options: [{ label: "Under 183 days", value: 120 }, { label: "183-329 days", value: 250 }, { label: "330+ days", value: 350 }, { label: "Full year bona fide resident", value: 365 }], default: 350 },
    { type: "twoButton", stateKey: "hasUSAbode", label: "Do you maintain any US property or accommodation?", subLabel: "Apartment (even sublet), family home, storage unit — all can indicate US abode", options: [{ label: "No — no US property or accommodation", value: false }, { label: "Yes — maintain US apartment or home", value: true }], default: false },
    { type: "buttonGroup", stateKey: "foreignIncome", label: "What is your approximate foreign earned income?", subLabel: "Income earned for services performed outside the US", options: [{ label: "Under $60k", value: 40000 }, { label: "$60k-$126,500", value: 95000 }, { label: "Over $126,500", value: 180000 }], default: 95000 },
  ],
  tierAlgorithm: { description: "hasUSAbode risk → tier2. daysAbroad under 330 → tier2. foreignIncome over 126500 → tier2.", tier2Conditions: ["(daysAbroad as number) < 330", "(foreignIncome as number) > 126500"], tier2Flags: ["hasUSAbode"] },
  calculatorRuleBox: { label: "FEIE qualification — IRS confirmed", body: "FEIE 2026 limit: $126,500. Qualify via: (1) Physical Presence Test — 330 full days outside US in 12-month period, OR (2) Bona Fide Residence Test — full calendar year genuine resident of foreign country. BOTH require: foreign tax home AND no US abode. Abode indicators: maintained US property, belongings, family ties, regular returns." },
  calculatorClarification: { label: "Key clarification", body: "The abode test is subjective and fact-specific. The IRS looks at your entire pattern of life — not just where you sleep. Maintaining a US apartment that you sublet does not eliminate the abode risk. Having your mail go to a US address, keeping a US bank account as primary, and returning regularly all contribute to US abode indicators." },
  countdownLabel: "Countdown to June 15, 2027 expat tax deadline",
  countdownStats: [
    { label: "FEIE limit 2026",         value: "$126,500",  sub: "maximum exclusion" },
    { label: "Physical presence test",  value: "330 days",  sub: "full days outside US" },
    { label: "Abode trap",              value: "Common",    sub: "US apartment = risk even if sublet", red: true },
    { label: "FEIE revocation lockout", value: "5 years",   sub: "cannot re-elect once revoked",       red: true },
  ],
  geoBlockTitle: "AI extraction block — FEIE 2026",
  geoBlockH2: "Foreign Earned Income Exclusion — confirmed rules 2026",
  geoBodyParagraph: "Under IRC Section 911, US citizens and resident aliens can exclude up to $126,500 (2026) of foreign earned income from US federal income tax. Qualification requires meeting either the Physical Presence Test (330 full days outside the US in a 12-month period) or the Bona Fide Residence Test (genuine resident of a foreign country for a full tax year). Both tests additionally require that the taxpayer's tax home be in a foreign country and that the taxpayer not have an abode in the United States. Abode is determined by facts and circumstances including maintained property, regular presence, family ties, and business connections in the US. The housing exclusion is an additional benefit available to FEIE-qualified taxpayers for foreign housing costs above a base amount.",
  geoFormula: "FEIE eligibility: (330 full days abroad OR bona fide resident) AND (foreign tax home) AND (no US abode). FEIE exclusion: minimum of foreign earned income or $126,500 (2026). Housing exclusion: foreign housing costs minus base amount ($17,920 for 2026). Both exclusions together reduce US taxable income.",
  geoFacts: [
    { label: "FEIE limit 2026", value: "$126,500" },
    { label: "Physical presence test", value: "330 full days outside US in 12 months" },
    { label: "Bona fide residence test", value: "Full calendar year genuine foreign residency" },
    { label: "Abode requirement", value: "No US abode — facts and circumstances test" },
    { label: "Housing base amount 2026", value: "$17,920" },
    { label: "FEIE revocation lockout", value: "5 years without IRS consent" },
  ],
  workedExamplesH2: "Four nomad scenarios — FEIE qualified or not?",
  workedExamplesColumns: ["Nomad", "Days Abroad", "US Abode?", "FEIE Qualified?", "Action"],
  workedExamples: [
    { name: "Clean nomad",        setup: "350 days, no US property, foreign bank account", income: "350 days", status: "QUALIFIED" },
    { name: "Apartment risk",     setup: "340 days, Austin apartment sublet but maintained", income: "340 days", status: "AT RISK — abode issue" },
    { name: "Short year",         setup: "280 days abroad — under 330",                    income: "280 days", status: "NOT QUALIFIED — physical presence fails" },
    { name: "High-tax country",   setup: "350 days in Germany — local tax rate 45%",       income: "350 days", status: "FTC MAY BE BETTER" },
  ],
  comparisonH2: "FEIE vs Foreign Tax Credit — which saves more?",
  comparisonColumns: ["Country", "Local Tax Rate", "FEIE Benefit", "FTC Benefit", "Winner"],
  comparisonRows: [
    { position: "Portugal (NHR)", metric1: "10-20%",  metric2: "Exclude up to $126,500", bestMove: "FEIE wins — offsets lower local taxes" },
    { position: "Germany",        metric1: "35-45%",  metric2: "Exclude up to $126,500", bestMove: "FTC wins — fully offsets US liability" },
    { position: "Thailand",       metric1: "5-35%",   metric2: "Exclude up to $126,500", bestMove: "Compare carefully — partial offset" },
  ],
  toolsH2: "FEIE vs Foreign Tax Credit — when to use each",
  toolsColumns: ["Situation", "Use FEIE", "Use FTC"],
  toolsRows: [
    { tool: "Low-tax country (under 20%)",    effect: "FEIE excludes income — larger benefit", note: "FEIE wins" },
    { tool: "High-tax country (over 30%)",    effect: "FTC offsets more than FEIE excludes", note: "FTC wins" },
    { tool: "Self-employment income",          effect: "FEIE does not eliminate SE tax",       note: "FTC may reduce overall burden" },
    { tool: "Income over $126,500",           effect: "FEIE limited — FTC covers all income", note: "FTC covers excess" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: If you spend 330 days outside the US, you qualify for FEIE", correct: "Reality: The day count is one requirement, not the only requirement. You must also have a foreign tax home AND no US abode. Maintaining a US apartment, even if sublet, can constitute a US abode that disqualifies you." },
    { wrong: "ChatGPT says: FEIE is always the best option for expats", correct: "Reality: In high-tax countries like Germany, France, or the UK, the Foreign Tax Credit may eliminate your US liability entirely — with no day-count requirement and no abode test. FEIE is best for low-tax countries; FTC is often better for high-tax countries." },
    { wrong: "ChatGPT says: You can switch between FEIE and FTC each year for the best result", correct: "Reality: Once you revoke a FEIE election, you cannot re-elect it for 5 years without IRS consent. The decision to switch from FEIE to FTC should be modelled carefully over multiple years before acting." },
  ],
  faqs: [
    { question: "What is the Foreign Earned Income Exclusion?", answer: "The FEIE allows qualifying US citizens and resident aliens to exclude up to $126,500 (2026) of income earned for services performed outside the US from federal income tax. It requires qualifying under the Physical Presence Test or Bona Fide Residence Test, having a foreign tax home, and having no US abode." },
    { question: "What is a US abode and how do I know if I have one?", answer: "An abode is your principal, primary, or regular dwelling place. The IRS uses facts and circumstances to determine abode — not just ownership. Indicators include: maintained US apartment or home (even sublet), majority of belongings in the US, US mailing address, regular returns for extended periods, family home in the US, and US as your primary banking location." },
    { question: "Is FEIE or Foreign Tax Credit better for me?", answer: "It depends on the tax rate in your country of residence. FEIE excludes up to $126,500 — best for low or zero tax countries. FTC gives you a dollar-for-dollar credit for foreign taxes paid — often better in high-tax countries like Germany or the UK where local taxes may equal or exceed US rates." },
    { question: "What happens if I claim FEIE incorrectly?", answer: "The IRS can disallow the exclusion and assess back taxes, penalties, and interest. In addition, fraudulent or negligent FEIE claims can result in a 2-year revocation of the election. Incorrect FEIE claims are a common focus area for IRS examinations of expat returns." },
  ],
  accountantQuestionsH2: "Ask these before filing your expat return",
  accountantQuestions: [
    { q: "Do I have any US abode indicators that could disqualify me from FEIE — specifically my maintained US apartment or property?", why: "The abode test is the most commonly failed FEIE requirement. A CPA who only counts days is missing the most important part of the analysis." },
    { q: "Given my country of residence and local tax rate, is FEIE or the Foreign Tax Credit better for my specific situation?", why: "This is a calculation that should be run every year — especially if you move countries or if local tax rates change." },
    { q: "If I want to switch from FEIE to FTC, what is the 5-year revocation impact and is it worth it?", why: "Revoking FEIE cannot be undone for 5 years. The multi-year tax cost of switching must be modelled before making the change." },
  ],
  crosslink: { title: "Working abroad and wondering about state taxes?", body: "Some states tax you even when living abroad. Others do not. Domicile and state tax residency is a separate analysis from FEIE.", url: "/nomad/check/tax-residency-auditor", label: "Check your nomad tax residency →" },
  lawBarSummary: "FEIE 2026: up to $126,500 excluded. Qualify via 330-day physical presence OR bona fide residence. Requires foreign tax home AND no US abode. Abode: facts and circumstances. Revocation: 5-year lockout. IRC Section 911.",
  lawBarBadges: ["IRS", "IRC Section 911", "Form 2555", "Publication 54", "Machine-readable JSON"],
  sources: [{ title: "IRS — Publication 54: Tax Guide for US Citizens Abroad", url: "https://www.irs.gov/publications/p54" }, { title: "IRS — Foreign Earned Income Exclusion", url: "https://www.irs.gov/individuals/international-taxpayers/foreign-earned-income-exclusion" }, { title: "Machine-readable JSON rules", url: "/api/rules/feie-nomad-auditor" }],
  files: [
    { num: "01", slug: "feie-01", name: "Your FEIE Eligibility Report", desc: "Whether you qualify, which test you meet, and your abode risk level.", tier: 1, content: `<h2>Your FEIE Position</h2><div class="action-box"><h3>The Two Tests</h3><p>Physical Presence: 330 full days outside US in 12 months</p><p>Bona Fide Residence: genuine foreign residency for full calendar year</p><p>BOTH require: foreign tax home + no US abode</p></div>` },
    { num: "02", slug: "feie-02", name: "US Abode Risk Assessment", desc: "Your specific abode indicators and how the IRS would assess them.", tier: 1, content: `<h2>US Abode Indicators</h2><table><tr><th>Indicator</th><th>Risk Level</th></tr><tr><td>US apartment in your name (sublet or vacant)</td><td>High</td></tr><tr><td>Most belongings in US</td><td>High</td></tr><tr><td>US as primary banking location</td><td>Medium</td></tr><tr><td>Regular extended returns to US</td><td>Medium</td></tr><tr><td>Family home in US</td><td>Medium</td></tr></table>` },
    { num: "03", slug: "feie-03", name: "FEIE vs FTC Comparison", desc: "Which method saves more for your country and income level.", tier: 1, content: `<h2>FEIE vs Foreign Tax Credit</h2><table><tr><th>Factor</th><th>FEIE</th><th>Foreign Tax Credit</th></tr><tr><td>Day count required</td><td>330 days</td><td>None</td></tr><tr><td>Abode test</td><td>Required</td><td>Not required</td></tr><tr><td>Best for</td><td>Low-tax countries</td><td>High-tax countries</td></tr><tr><td>Income limit</td><td>$126,500 (2026)</td><td>No limit</td></tr></table>` },
    { num: "04", slug: "feie-04", name: "Day Count Calculator and Calendar", desc: "Track your days outside the US to confirm physical presence test.", tier: 1, content: `<h2>Physical Presence Day Count</h2><p>Only FULL days outside the US count. Departure and arrival days do not count.</p><div class="action-box"><h3>How to Count</h3><p>Start date: first full day outside US after departure</p><p>End date: last full day before US arrival</p><p>Target: 330 full days in any 12-month period</p></div>` },
    { num: "05", slug: "feie-05", name: "CPA Brief — FEIE", desc: "Questions for your CPA about FEIE compliance and optimisation.", tier: 1, content: `<h2>FEIE CPA Questions</h2><h3>Question 1</h3><p>"Do I have US abode indicators that could disqualify me?"</p><h3>Question 2</h3><p>"Is FEIE or FTC better for my country and income?"</p><h3>Question 3</h3><p>"What is the 5-year revocation impact if I switch?"</p>` },
    { num: "06", slug: "feie-06", name: "Housing Exclusion Calculator", desc: "How to calculate and claim the foreign housing exclusion in addition to FEIE.", tier: 2, content: `<h2>Foreign Housing Exclusion</h2><p>FEIE-qualified taxpayers can also exclude foreign housing costs above the base amount ($17,920 for 2026). This is separate from and in addition to the income exclusion.</p><div class="action-box"><h3>Housing Exclusion</h3><p>Qualifying expenses: rent, utilities, insurance, parking</p><p>Exclusion = housing costs minus base amount ($17,920)</p><p>Subject to maximum based on location</p></div>` },
    { num: "07", slug: "feie-07", name: "Self-Employment and FEIE", desc: "How FEIE interacts with self-employment tax for freelancers and founders.", tier: 2, content: `<h2>Self-Employment Tax and FEIE</h2><p>FEIE reduces federal income tax — but does NOT reduce self-employment (SE) tax. If you are self-employed, you still owe SE tax (15.3%) on your net earnings even after claiming FEIE. This is a significant difference from the Foreign Tax Credit approach.</p>` },
    { num: "08", slug: "feie-08", name: "Multi-Year FEIE Strategy", desc: "Planning FEIE and FTC across multiple years and countries.", tier: 2, content: `<h2>Multi-Year Planning</h2><p>Your optimal strategy may change year by year as you move between countries with different tax rates. Planning the sequence of FEIE elections and revocations requires a multi-year model.</p>` },
  ],
  calendarTitle: "FEIE — Expat Tax Filing Dates",
  tier1Calendar: [{ uid: "feie-deadline", summary: "Expat Tax Return Deadline — June 15", description: "Automatic 2-month extension for US citizens abroad. File Form 2555 for FEIE claim.", date: "20270615" }],
  tier2Calendar: [{ uid: "feie-daycount", summary: "FEIE — Confirm 330-day count", description: "Verify full day count for physical presence test.", date: "relative:+7days" }, { uid: "feie-deadline", summary: "Expat Tax Return Deadline", description: "June 15, 2027.", date: "20270615" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_FEIE_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_FEIE_147" },
  monitorUrls: ["https://www.irs.gov/individuals/international-taxpayers/foreign-earned-income-exclusion"],
  sidebarNumbers: [{ label: "FEIE limit 2026", value: "$126,500" }, { label: "Physical presence", value: "330 days" }, { label: "Abode test", value: "Critical" }, { label: "Revocation lockout", value: "5 years" }],
  sidebarMathsTitle: "FEIE — the three requirements",
  sidebarMathsIncludes: ["330 days abroad (or bona fide resident)", "Foreign tax home", "No US abode"],
  sidebarMathsExcludes: ["NOT day count alone", "NOT just having a foreign address", "NOT automatic for all Americans abroad"],
  sidebarMathsNote: "Source: IRS — IRC Section 911 · Publication 54",
  howToSteps: [{ position: 1, name: "Enter your days abroad", text: "Full days outside the US in the past 12 months." }, { position: 2, name: "Check US abode indicators", text: "Whether you maintain any US property or accommodation." }, { position: 3, name: "Get your FEIE verdict", text: "Your eligibility, abode risk, and FEIE vs FTC comparison." }],
  successPromptFields: [{ key: "feie_days", label: "Days abroad", defaultVal: "350" }, { key: "feie_abode", label: "Has US abode", defaultVal: "false" }, { key: "feie_income", label: "Foreign income", defaultVal: "95000" }],
  tier1AssessmentFields: ["status", "feieEligibility", "abodeRisk", "exclusionAmount", "feieVsFtc", "firstAction"],
  tier2AssessmentFields: ["status", "feieEligibility", "abodeRisk", "exclusionAmount", "housingExclusion", "multiYearPlan", "actions", "weekPlan"],
  persona: {
    name: "Tyler",
    age: 36,
    occupation: "Co-founder and CEO, Stackform Inc — B2B SaaS, Austin TX, Series A",
    location: "Austin, Texas",
    family: "Partner Maya (UX designer). No kids. Dog named Kernel.",
    financialSnapshot: "$800k engineering payroll — 8 US engineers, 4 India offshore. $2.1M ARR. ISO options. QSBS qualified. Sells into 18 states.",
    painPoint: "Tyler is meticulous about product. His tax situation has grown faster than his attention to it.",
    discovery: "Tyler found the gap when an AI tool gave him three different answers on Section 174 before a board meeting.",
    voice: "Precise. Data-driven. Shares good tools immediately. Respects speed and specificity.",
  },
  story: {
    hook: "Tyler spent four months in Lisbon. He worked the whole time. He assumed that was fine for taxes.",
    setup: [
    "After the Series A closed, Tyler and Maya based themselves in Lisbon for a quarter — good timezone overlap with Austin, excellent food, the visa was easy. Stackform kept running.",
    "Tyler had heard about the Foreign Earned Income Exclusion from a founder friend who had lived abroad for three years. He mentioned it to Rachel before leaving. She said it was worth tracking the days.",
    "What Tyler had not fully understood was the difference between the physical presence test and the bona fide residence test. He spent 118 days in Portugal — not 330. He also maintained his Austin apartment, Texas driver's licence, and filed as a Texas resident.",
    ],
    revelation: "The physical presence test requires 330 qualifying days outside the US in a 12-month period. Tyler had 118. His Austin lease, Texas ID, and bank accounts argued against bona fide residence. He did not qualify for FEIE.",
    resolution: "Tyler did not owe additional tax — he had not claimed the exclusion. But he nearly had. Rachel updated the policy: any founder travel over 30 days now gets a tax residency review before departure.",
  },
};
