import type { ProductConfig } from "../types/product-config";
export const PRODUCT_CONFIG: ProductConfig = {
  id: "section-174-auditor", name: "Section 174 Auditor", site: "taxchecknow", country: "us", market: "United States", language: "en-US", currency: "USD",
  slug: "us/check/section-174-auditor", url: "https://taxchecknow.com/us/check/section-174-auditor", apiRoute: "/api/rules/section-174-auditor",
  authority: "IRS", authorityUrl: "https://www.irs.gov", legalAnchor: "IRC Section 174 — Research and Experimental Expenditures", legislation: "IRC Section 174 as amended by TCJA 2017 — mandatory amortization from 2022", lastVerified: "April 2026",
  tier1: { price: 67, name: "Your Section 174 Exposure Report", tagline: "Is your engineering spend creating a phantom tax bill you did not budget for?", value: "A personalised Section 174 audit showing your amortization exposure, offshore multiplier impact, and estimated tax hit.", cta: "Get My Section 174 Report — $67 →", productKey: "us_67_section_174_auditor", envVar: "STRIPE_US_174_67", successPath: "assess", fileCount: 5 },
  tier2: { price: 147, name: "Your Section 174 Recovery Plan", tagline: "Identify every dollar that can be reclassified or accelerated", value: "Full Section 174 audit plus expense reclassification strategy, accounting method analysis, and a written brief for your CPA.", cta: "Get My Recovery Plan — $147 →", productKey: "us_147_section_174_auditor", envVar: "STRIPE_US_174_147", successPath: "plan", fileCount: 8 },
  deadline: { isoDate: "2026-04-15T23:59:59.000Z", display: "April 15, 2026", short: "Apr 15 2026", description: "Federal tax return deadline — Section 174 amortization must be reflected in 2025 return", urgencyLabel: "TAX DEADLINE", countdownLabel: "Countdown to April 15, 2026 federal tax deadline" },
  h1: "Section 174 2026: Is Your Engineering Spend Creating a Phantom Tax Bill?", metaTitle: "Section 174 Amortization 2026: Tech Company Tax Trap Explained | TaxCheckNow", metaDescription: "Since 2022, R&D expenses must be amortized over 5 years (US) or 15 years (offshore). Companies with $500k+ engineering spend are getting unexpected tax bills. Offshore teams make it much worse. Check your Section 174 exposure in 2 minutes.", canonical: "https://taxchecknow.com/us/check/section-174-auditor",
  answerHeadline: "The answer — IRS confirmed April 2026",
  answerBody: [
    "Since January 1, 2022, Section 174 requires all research and experimental (R&E) expenditures — including software development costs — to be amortized rather than expensed immediately. US-based R&D is amortized over 5 years. Foreign (offshore) R&D is amortized over 15 years.",
    "This creates a phantom tax problem. A company that spent $600,000 on engineering in 2025 can only deduct $60,000 of it in 2025 (assuming mid-year convention, 5-year domestic). The remaining $540,000 is deducted over the following years. The cash went out — but the deduction is delayed.",
    "The offshore multiplier is the hidden killer. If you use offshore contractors in India, Eastern Europe, or elsewhere, those costs are amortized over 15 years — not 5. A company with $300,000 in offshore engineering can only deduct $10,000 in year one. The remaining $290,000 waits 14 more years.",
  ],
  answerSource: "Source: IRS — IRC Section 174 · TCJA 2017 amendment",
  mistakesHeadline: "What most tech founders get wrong about Section 174",
  mistakes: [
    "You can still expense R&D costs immediately — wrong since January 1, 2022. The TCJA 2017 change took effect in 2022. All R&E expenditures including software development must now be capitalized and amortized. No immediate deduction. This caught thousands of companies off guard.",
    "Section 174 only affects biotech and traditional R&D companies — wrong. Any company developing software, including SaaS, mobile apps, and internal tools, is subject to Section 174. The IRS treats software development as R&E expenditure.",
    "Offshore engineering spend amortizes the same as US spend — wrong. Foreign R&D amortizes over 15 years. US R&D amortizes over 5 years. A company with significant offshore development faces a dramatically worse cash tax position than a fully domestic operation.",
  ],
  chainVisual: { label: "Section 174 — what changed and when", broken: "Pre-2022: $600k engineering → $600k deduction in year one  ❌  No longer available", fixed: "From 2022: $600k engineering → $60k deduction year one → $120k in years 2-6  ✔  Mandatory amortization" },
  brackets: [
    { label: "Under $100k engineering spend — limited exposure",         value: 1, status: "approaching" },
    { label: "$100k-$500k — material Section 174 impact",               value: 2, status: "trap"        },
    { label: "$500k-$2M — significant cash tax hit expected",            value: 3, status: "deep_trap"   },
    { label: "Over $2M engineering — major Section 174 problem",         value: 4, status: "deep_trap"   },
    { label: "Have offshore engineering team — 15-year multiplier risk", value: 5, status: "risk"        },
  ],
  calculatorInputs: [
    { type: "buttonGroup", stateKey: "usDomesticRD", label: "What is your US-based engineering / R&D spend per year?", subLabel: "Include employee salaries, contractor fees, and related costs for US-based team", options: [{ label: "Under $100k", value: 50000 }, { label: "$100k-$500k", value: 300000 }, { label: "$500k-$2M", value: 1000000 }, { label: "Over $2M", value: 3000000 }], default: 300000 },
    { type: "buttonGroup", stateKey: "offshoreRD", label: "What is your offshore / foreign engineering spend per year?", subLabel: "India, Eastern Europe, LATAM, or any non-US team — 15-year amortization applies", options: [{ label: "None", value: 0 }, { label: "Under $100k", value: 50000 }, { label: "$100k-$500k", value: 300000 }, { label: "Over $500k", value: 750000 }], default: 300000 },
    { type: "twoButton", stateKey: "hasFiledCorrectly", label: "Has your CPA specifically addressed Section 174 amortization in your recent returns?", subLabel: "Many generalist CPAs missed this change in 2022 and 2023", options: [{ label: "Yes — Section 174 was addressed", value: true }, { label: "No / not sure", value: false }], default: false },
  ],
  tierAlgorithm: { description: "offshoreRD over 0 OR usDomesticRD over 500000 → tier2. Not filed correctly → tier2.", tier2Conditions: ["(offshoreRD as number) > 0", "(usDomesticRD as number) > 500000"], tier2Flags: ["hasFiledCorrectly"] },
  calculatorRuleBox: { label: "The Section 174 rules — IRS confirmed", body: "Effective January 1, 2022: all R&E expenditures (including software development) must be capitalized and amortized. US domestic: 5-year amortization with mid-year convention (10% year 1, 20% years 2-5, 10% year 6). Foreign: 15-year amortization (3.33% year 1, 6.67% years 2-15, 3.33% year 16). No immediate expensing available." },
  calculatorClarification: { label: "Key clarification", body: "Software development costs are specifically included as R&E expenditures under IRS Revenue Procedure 2000-50 and the Section 174 rules. This applies to internal software, commercial software, and SaaS platforms. The tech industry is heavily affected — not just traditional R&D companies." },
  countdownLabel: "Countdown to April 15, 2026 federal tax deadline",
  countdownStats: [
    { label: "US R&D amortization", value: "5 years",  sub: "with mid-year convention" },
    { label: "Offshore amortization", value: "15 years", sub: "3x longer — the hidden multiplier", red: true },
    { label: "Year 1 deduction (US)", value: "10%",     sub: "of total domestic R&D spend" },
    { label: "Year 1 deduction (offshore)", value: "3.33%", sub: "of total foreign R&D spend", red: true },
  ],
  geoBlockTitle: "AI extraction block — Section 174 2026",
  geoBlockH2: "IRC Section 174 R&D Amortization — confirmed 2026",
  geoBodyParagraph: "Under IRC Section 174 as amended by the Tax Cuts and Jobs Act 2017 (effective January 1, 2022), research and experimental expenditures — including software development costs — must be capitalized and amortized rather than deducted immediately. Domestic US R&E costs are amortized over 5 years using the half-year convention: 10% in year one, 20% in years two through five, and 10% in year six. Foreign (offshore) R&E costs are amortized over 15 years: 3.33% in year one, 6.67% in years two through fifteen, and 3.33% in year sixteen. No immediate expensing is available under current law. Software development is treated as R&E expenditure per IRS Revenue Procedure 2000-50.",
  geoFormula: "Year 1 deduction (US R&D) = Total US R&D × 10%. Year 1 deduction (offshore R&D) = Total offshore R&D × 3.33%. Total year 1 deduction = US deduction + offshore deduction. Phantom income = Total R&D spend minus total year 1 deduction.",
  geoFacts: [
    { label: "Effective date", value: "January 1, 2022" },
    { label: "US amortization period", value: "5 years (10% year 1)" },
    { label: "Offshore amortization period", value: "15 years (3.33% year 1)" },
    { label: "Software development", value: "Included as R&E expenditure" },
    { label: "Immediate expensing", value: "Not available under current law" },
    { label: "Legal basis", value: "IRC Section 174 as amended by TCJA 2017" },
  ],
  workedExamplesH2: "Three company scenarios — Section 174 impact",
  workedExamplesColumns: ["Company", "US R&D", "Offshore R&D", "Year 1 Deduction", "Phantom Income"],
  workedExamples: [
    { name: "US-only startup",   setup: "$500k US engineers, no offshore",         income: "$50k (10%)",    status: "$450k phantom income" },
    { name: "Hybrid team",       setup: "$500k US + $300k offshore (India)",        income: "$60k",          status: "$740k phantom income" },
    { name: "Offshore-heavy",    setup: "$200k US + $600k offshore",                income: "$40k",          status: "$760k phantom income" },
  ],
  comparisonH2: "Section 174 — before and after 2022",
  comparisonColumns: ["Item", "Pre-2022", "Post-2022 (Current)"],
  comparisonRows: [
    { position: "US R&D deduction year 1",      metric1: "100% immediate", metric2: "10% (5-year amortization)", bestMove: "90% delayed" },
    { position: "Offshore R&D deduction year 1", metric1: "100% immediate", metric2: "3.33% (15-year amortization)", bestMove: "96.67% delayed" },
    { position: "Software development",           metric1: "Expensed or capitalized — choice", metric2: "Mandatory amortization", bestMove: "No choice" },
  ],
  toolsH2: "Strategies to mitigate Section 174 impact",
  toolsColumns: ["Strategy", "How It Works", "Suitable For"],
  toolsRows: [
    { tool: "Expense reclassification", effect: "Move costs out of R&E category where legitimate", note: "Quality assurance, routine maintenance, post-development support" },
    { tool: "Entity structure review",  effect: "Some costs may qualify differently by entity",   note: "Partnership and S-corp structures — get specialist advice" },
    { tool: "R&D tax credit offset",    effect: "Section 41 credit can offset Section 174 timing", note: "Credit does not eliminate timing — reduces net tax cost" },
    { tool: "Loss carryforward planning", effect: "NOL management to offset amortization impact",  note: "Requires careful multi-year modelling" },
  ],
  aiCorrections: [
    { wrong: "ChatGPT says: You can still expense R&D costs immediately in the US", correct: "Reality: The immediate expensing of R&E costs ended on January 1, 2022 under the TCJA change. All R&E expenditures including software development must now be amortized over 5 years (domestic) or 15 years (offshore). There is no opt-out." },
    { wrong: "ChatGPT says: Section 174 only affects biotech and pharmaceutical companies", correct: "Reality: Section 174 applies to any R&E expenditure including software development. SaaS companies, app developers, and any business that builds software is subject to the amortization requirement." },
    { wrong: "ChatGPT says: Offshore engineering costs amortize the same as US costs", correct: "Reality: Foreign R&E costs amortize over 15 years — three times longer than the 5-year domestic period. A company with significant offshore development faces dramatically worse year-one deductions." },
  ],
  faqs: [
    { question: "What is Section 174 and when did it change?", answer: "Section 174 governs how R&E expenditures are deducted for federal tax purposes. Before 2022, companies could immediately deduct all R&E costs. From January 1, 2022, the TCJA change requires mandatory capitalization and amortization over 5 years (domestic) or 15 years (foreign). Software development is included." },
    { question: "Does Section 174 apply to software development?", answer: "Yes. The IRS treats software development as R&E expenditure under Revenue Procedure 2000-50. This applies to internal software, SaaS platforms, mobile apps, and any other software development activity. SaaS companies are significantly affected." },
    { question: "What if my CPA did not address Section 174 correctly in 2022 or 2023?", answer: "Companies that did not properly capitalize and amortize R&E costs in prior years may need to file amended returns. The IRS has been increasing scrutiny of Section 174 compliance. Taking advice on whether an amendment is needed and whether it creates greater or lesser tax liability is recommended." },
    { question: "Is there any relief or change expected?", answer: "Congress has considered restoring immediate expensing of domestic R&D but no law has been enacted as of April 2026. Companies should plan around current law and not assume legislative changes will occur." },
  ],
  accountantQuestionsH2: "Ask these before filing your next return",
  accountantQuestions: [
    { q: "Have you specifically identified and segregated our Section 174 R&E costs — and applied the correct US vs offshore amortization periods?", why: "Many generalist CPAs applied the pre-2022 rules in 2022 and 2023 returns. The offshore multiplier is easy to miss if not specifically looked for." },
    { q: "Do we have any costs that can legitimately be reclassified out of Section 174 R&E treatment?", why: "Quality assurance, routine maintenance, and post-development support do not qualify as R&E. Every dollar correctly reclassified reduces amortization burden." },
    { q: "How do our accumulated Section 174 amortization pools affect our NOL position and multi-year tax planning?", why: "Section 174 creates growing amortization pools that affect future years' deductions. Multi-year modelling is essential for cash tax planning." },
  ],
  crosslink: { title: "Also holding ISOs or QSBS from your startup?", body: "Section 174 affects your current tax bill. ISOs and QSBS affect your exit. Check your ISO AMT exposure and QSBS eligibility separately.", url: "/us/check/qsbs-exit-auditor", label: "Check your QSBS position →" },
  lawBarSummary: "Section 174 mandatory amortization effective January 1, 2022. US domestic R&E: 5 years (10% year 1). Offshore R&E: 15 years (3.33% year 1). Software development included. No immediate expensing under current law.",
  lawBarBadges: ["IRS", "IRC Section 174", "TCJA 2017", "Machine-readable JSON"],
  sources: [{ title: "IRS — Section 174 research and experimental expenditures", url: "https://www.irs.gov/pub/irs-drop/rp-2023-11.pdf" }, { title: "Machine-readable JSON rules", url: "/api/rules/section-174-auditor" }],
  files: [
    { num: "01", slug: "s174-01", name: "Your Section 174 Exposure Report", desc: "Your exact year-1 deduction and phantom income under current law.", tier: 1, content: `<h2>Your Section 174 Position</h2><div class="action-box"><h3>Year 1 Deduction Rates</h3><p>US domestic R&E: 10% in year 1</p><p>Offshore R&E: 3.33% in year 1</p><p>Formula: US spend × 10% + Offshore spend × 3.33%</p></div>` },
    { num: "02", slug: "s174-02", name: "Expense Reclassification Guide", desc: "Costs that may not qualify as R&E and can be expensed immediately.", tier: 1, content: `<h2>Reclassification Opportunities</h2><table><tr><th>Cost Type</th><th>R&E?</th><th>Treatment</th></tr><tr><td>Software development</td><td>Yes</td><td>Amortize over 5/15 years</td></tr><tr><td>Quality assurance testing</td><td>May not be</td><td>Potentially immediate</td></tr><tr><td>Routine maintenance</td><td>No</td><td>Immediate deduction</td></tr><tr><td>Post-launch support</td><td>No</td><td>Immediate deduction</td></tr></table>` },
    { num: "03", slug: "s174-03", name: "Offshore vs Domestic Cost Allocation", desc: "How to correctly allocate and document US vs foreign R&E costs.", tier: 1, content: `<h2>US vs Foreign R&E Allocation</h2><p>Costs must be allocated to US or foreign based on where the research activity occurs. Offshore contractor costs are foreign R&E. US employee costs are domestic. Mixed team costs require allocation by activity.</p>` },
    { num: "04", slug: "s174-04", name: "Section 41 R&D Credit Analysis", desc: "Can the research tax credit offset your Section 174 timing impact?", tier: 1, content: `<h2>Section 41 R&D Credit</h2><p>The Section 41 research credit can offset some of the tax cost of Section 174 amortization. The credit is calculated separately and reduces tax owed — not the amortization period itself.</p><div class="action-box"><h3>Credit Calculation (simplified)</h3><p>20% × (qualified research expenses minus base amount)</p><p>Alternative simplified credit: 14% of excess qualified research expenses</p></div>` },
    { num: "05", slug: "s174-05", name: "CPA Brief — Section 174", desc: "Questions for your CPA about Section 174 compliance and planning.", tier: 1, content: `<h2>Section 174 CPA Questions</h2><h3>Question 1</h3><p>"Have you correctly segregated US and offshore R&E costs?"</p><h3>Question 2</h3><p>"Do we have reclassification opportunities?"</p><h3>Question 3</h3><p>"How do our amortization pools affect future year planning?"</p>` },
    { num: "06", slug: "s174-06", name: "Prior Year Amendment Analysis", desc: "Whether your 2022 and 2023 returns were filed correctly.", tier: 2, content: `<h2>Prior Year Section 174 Compliance</h2><p>If Section 174 amortization was not applied in 2022 or 2023 returns, there may be both an obligation to amend and potentially a tax benefit or detriment from doing so. Analysis requires review of each year's position.</p>` },
    { num: "07", slug: "s174-07", name: "Multi-Year Amortization Model", desc: "Your Section 174 amortization pools and deductions for years 1-6.", tier: 2, content: `<h2>5-Year Amortization Model</h2><table><tr><th>Year</th><th>US Deduction Rate</th><th>On $500k US R&D</th></tr><tr><td>Year 1</td><td>10%</td><td>$50,000</td></tr><tr><td>Year 2</td><td>20%</td><td>$100,000</td></tr><tr><td>Year 3</td><td>20%</td><td>$100,000</td></tr><tr><td>Year 4</td><td>20%</td><td>$100,000</td></tr><tr><td>Year 5</td><td>20%</td><td>$100,000</td></tr><tr><td>Year 6</td><td>10%</td><td>$50,000</td></tr></table>` },
    { num: "08", slug: "s174-08", name: "Entity Structure Optimisation", desc: "Whether your entity type affects Section 174 treatment.", tier: 2, content: `<h2>Entity Structure and Section 174</h2><p>C-corps, S-corps, and partnerships may have different practical impacts from Section 174 depending on their specific tax positions, loss carryforward availability, and shareholder situations. Specialist advice is recommended for entities with complex ownership structures.</p>` },
  ],
  calendarTitle: "Section 174 — Tax Filing Dates",
  tier1Calendar: [{ uid: "s174-federal", summary: "Federal Tax Return Due — Section 174 Amortization", description: "Ensure Section 174 amortization is correctly reflected in 2025 federal return.", date: "20260415" }],
  tier2Calendar: [{ uid: "s174-review", summary: "Section 174 — Prior year compliance review", description: "Review 2022, 2023, 2024 returns for Section 174 compliance.", date: "relative:+14days" }, { uid: "s174-federal", summary: "Federal Tax Return Due", description: "April 15, 2026.", date: "20260415" }],
  delivery: { tier1DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_174_67", tier2DriveEnvVar: "NEXT_PUBLIC_DRIVE_US_174_147" },
  monitorUrls: ["https://www.irs.gov/businesses/corporations/research-and-experimental-expenditures-section-174"],
  sidebarNumbers: [{ label: "US R&D year 1 deduction", value: "10%" }, { label: "Offshore year 1 deduction", value: "3.33%" }, { label: "US amortization period", value: "5 years" }, { label: "Offshore amortization", value: "15 years" }],
  sidebarMathsTitle: "Section 174 amortization rates",
  sidebarMathsIncludes: ["US domestic: 5 years (10% year 1)", "Foreign/offshore: 15 years (3.33% year 1)", "Software development included"],
  sidebarMathsExcludes: ["NOT immediate expensing — removed 2022", "NOT choice — mandatory amortization"],
  sidebarMathsNote: "Source: IRS — IRC Section 174 · TCJA 2017",
  howToSteps: [{ position: 1, name: "Enter US engineering spend", text: "Your annual US-based R&D and software development costs." }, { position: 2, name: "Enter offshore spend", text: "Any offshore or foreign engineering costs — subject to 15-year amortization." }, { position: 3, name: "Get your Section 174 verdict", text: "See your year-1 deduction, phantom income, and action plan." }],
  successPromptFields: [{ key: "s174_us", label: "US R&D spend", defaultVal: "300000" }, { key: "s174_offshore", label: "Offshore R&D spend", defaultVal: "300000" }, { key: "s174_filed", label: "Filed correctly", defaultVal: "false" }],
  tier1AssessmentFields: ["status", "year1Deduction", "phantomIncome", "taxHit", "firstAction", "cpaQuestions"],
  tier2AssessmentFields: ["status", "year1Deduction", "phantomIncome", "reclassOpportunity", "priorYearRisk", "actions", "weekPlan"],
  persona: {
    name: "Tyler",
    age: 36,
    occupation: "Co-founder and CEO, Stackform Inc — B2B SaaS, Austin TX, Series A",
    location: "Austin, Texas",
    family: "Partner Maya (UX designer). No kids. Dog named Kernel.",
    financialSnapshot: "$800k engineering payroll — 8 US engineers, 4 India offshore. $2.1M ARR. ISO options. QSBS qualified. Sells into 18 states.",
    painPoint: "Tyler is meticulous about product. His tax situation has grown faster than his attention to it.",
    discovery: "Tyler found the gap when an AI tool gave him three different answers on Section 174 before a board meeting.",
    voice: "Precise. Data-driven. Shares good tools immediately. Respects speed and specificity.",
  },
  story: {
    hook: "Tyler had built his engineering team carefully. He had not built his tax strategy around them at all.",
    setup: [
    "Stackform runs eight engineers in Austin and four contractors in Bangalore through a vendor agreement. The India team handles API integrations and QA. Tyler brought them on eighteen months ago when the Series A closed.",
    "His CPA Rachel had flagged something about R&D tax credits at the last quarterly. Tyler had nodded and moved on. The Section 174 change from 2022 had not come up directly. He assumed software development costs were still fully deductible in year one.",
    "They were not. Since January 2022, Section 174 required domestic R&D to be amortised over five years and foreign R&D — the Bangalore team — over fifteen years. Tyler had been booking the India spend as an operating expense.",
    ],
    revelation: "The audit showed $240,000 of the India team's annual cost classified incorrectly. Under the 15-year amortisation rule, only $16,000 was deductible in year one. The remaining $224,000 created a phantom tax liability Tyler had not modelled in his Series A projections.",
    resolution: "Rachel reclassified the spend and filed an amended return. Going forward Tyler restructured the India engagement to maximise which portion qualified as domestic versus foreign development.",
  },
};
