// ─────────────────────────────────────────────────────────────────────────────
// COLE Generator — generate-calculator.ts
// Reads a ProductConfig and writes the [Pascal]Calculator.tsx client component
// LOCKED RULES:
// - No sliders ever — button groups only
// - No toggle switches — two-button pattern only
// - Popup uses native select dropdowns only
// - Tier algorithm decides — never the buyer
// Output path: app/[country]/check/[id]/[Pascal]Calculator.tsx
// ─────────────────────────────────────────────────────────────────────────────

import type { ProductConfig, ButtonGroupInput, TwoButtonInput } from "../types/product-config";

// ── MAIN EXPORT ───────────────────────────────────────────────────────────────

export function generateCalculator(config: ProductConfig): string {
  const name         = toPascal(config.id) + "Calculator";
  const stateKeys    = config.calculatorInputs.map(i => i.stateKey);
  const hasInputs    = config.calculatorInputs.length > 0;

  return `"use client";
// AUTO-GENERATED BY COLE — do not edit manually
// Product: ${config.id}
// Regenerate: npx ts-node cole/scripts/cole-generate.ts ${config.country}-${config.id}

import { useEffect, useMemo, useRef, useState } from "react";

// ── CONSTANTS ─────────────────────────────────────────────────────────────────

const DEADLINE_ISO   = "${config.deadline.isoDate}";
const DAYS_TO_END    = Math.max(0, Math.floor(
  (new Date(DEADLINE_ISO).getTime() - Date.now()) / 86_400_000
));

// ── BRACKETS ─────────────────────────────────────────────────────────────────

const BRACKETS = ${JSON.stringify(config.brackets, null, 2)} as const;

type BracketStatus = "clear" | "approaching" | "trap" | "deep_trap" | "above_trap" | "pass" | "fail" | "risk" | "in_scope" | "out_of_scope";
type PackTier      = ${config.tier1.price} | ${config.tier2.price};

// ── PRODUCTS ──────────────────────────────────────────────────────────────────

const PRODUCTS: Record<PackTier, { name: string; tagline: string; value: string; cta: string }> = {
  ${config.tier1.price}: {
    name:    "${config.tier1.name}",
    tagline: "${config.tier1.tagline}",
    value:   "${config.tier1.value}",
    cta:     "${config.tier1.cta}",
  },
  ${config.tier2.price}: {
    name:    "${config.tier2.name}",
    tagline: "${config.tier2.tagline}",
    value:   "${config.tier2.value}",
    cta:     "${config.tier2.cta}",
  },
};

// ── POPUP QUESTIONS ───────────────────────────────────────────────────────────
// Native select dropdowns — always in popup, never on main calculator

interface Answers {
  contribution_timing:     string;
  complexity_level:        string;
  main_goal:               string;
  accountant_status:       string;
  urgency:                 string;
}

// ── STATUS HELPERS ────────────────────────────────────────────────────────────

function getStatusStyle(status: BracketStatus): {
  panelClass: string;
  badgeClass: string;
  label: string;
  score: number;
} {
  switch (status) {
    case "clear":
    case "pass":
    case "out_of_scope":
      return {
        panelClass: "border-emerald-200 bg-emerald-50",
        badgeClass: "text-emerald-700",
        label:      "CLEAR — NO IMMEDIATE ACTION REQUIRED",
        score:      88,
      };
    case "approaching":
      return {
        panelClass: "border-amber-200 bg-amber-50",
        badgeClass: "text-amber-700",
        label:      "APPROACHING — REVIEW NOW",
        score:      65,
      };
    case "trap":
    case "fail":
    case "in_scope":
      return {
        panelClass: "border-red-200 bg-red-50",
        badgeClass: "text-red-700",
        label:      "ACTION REQUIRED — GAPS IDENTIFIED",
        score:      42,
      };
    case "deep_trap":
      return {
        panelClass: "border-red-200 bg-red-50",
        badgeClass: "text-red-700",
        label:      "URGENT — SIGNIFICANT GAPS",
        score:      28,
      };
    case "above_trap":
      return {
        panelClass: "border-blue-200 bg-blue-50",
        badgeClass: "text-blue-700",
        label:      "ABOVE THRESHOLD — DIFFERENT PLANNING NEEDED",
        score:      54,
      };
    case "risk":
    default:
      return {
        panelClass: "border-amber-200 bg-amber-50",
        badgeClass: "text-amber-700",
        label:      "AT RISK — VERIFICATION NEEDED",
        score:      50,
      };
  }
}

// ── TIER ALGORITHM ────────────────────────────────────────────────────────────
// COLE decides the tier — the buyer never chooses in the popup

function recommendedTier(
  bracketStatus: BracketStatus,
${stateKeys.map(k => `  ${k}: ${inferType(config, k)},`).join("\n")}
): PackTier {
  // ${config.tierAlgorithm.description}
  ${buildTierLogic(config)}
  return ${config.tier1.price};
}

// ── COMPONENT ─────────────────────────────────────────────────────────────────

export default function ${name}() {
  const [selectedBracket, setSelectedBracket] = useState<number | null>(null);
${config.calculatorInputs.map(input => buildStateDeclaration(input)).join("\n")}
  const [email,           setEmail]           = useState("");
  const [emailSent,       setEmailSent]       = useState(false);
  const [sessionId,       setSessionId]       = useState<string | null>(null);
  const [answers,         setAnswers]         = useState<Answers>({
    contribution_timing: "",
    complexity_level:    "",
    main_goal:           "",
    accountant_status:   "",
    urgency:             "",
  });
  const [overrideTier,    setOverrideTier]    = useState<PackTier | null>(null);
  const [showPopup,       setShowPopup]       = useState(false);
  const [popupStep,       setPopupStep]       = useState<"intro" | "questions">("intro");
  const [checkoutLoading, setCheckoutLoading] = useState(false);
  const [error,           setError]           = useState("");

  const resultRef = useRef<HTMLDivElement>(null);

  const selectedBracketData = selectedBracket !== null ? BRACKETS[selectedBracket] : null;
  const bracketStatus       = selectedBracketData?.status ?? "clear";
  const statusStyle         = getStatusStyle(bracketStatus);

  // Tier algorithm — COLE decides, buyer never chooses
  const calculatedTier: PackTier = recommendedTier(
    bracketStatus,
${stateKeys.map(k => `    ${k},`).join("\n")}
  );
  const effectiveTier   = overrideTier ?? calculatedTier;
  const selectedProduct = PRODUCTS[effectiveTier];
  const answersComplete = Object.values(answers).every(Boolean);

  const mobileStickyVisible = selectedBracket !== null;

  useEffect(() => {
    if (selectedBracket !== null && resultRef.current) {
      setTimeout(() => resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }), 100);
    }
  }, [selectedBracket]);

  async function handleBracketSelect(index: number) {
    setSelectedBracket(index);
${stateKeys.map(k => `    ${buildStateReset(config, k)}`).join("\n")}
    setOverrideTier(null);
    setError("");
    // Save to sessionStorage for success page
    const b = BRACKETS[index];
    sessionStorage.setItem("${config.id}_bracket", b.label);
    sessionStorage.setItem("${config.id}_status",  b.status);
    // Log to decision-sessions (non-blocking)
    try {
      const res  = await fetch("/api/decision-sessions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          product_slug:  "${config.id}",
          source_path:   "/${config.slug}",
          country_code:  "${config.country.toUpperCase()}",
          currency_code: "${config.currency}",
          site:          "${config.site}",
          inputs:        { bracket: b.label, value: b.value },
          output:        { status: b.status },
          recommended_tier: ${config.tier1.price},
        }),
      });
      const data = await res.json();
      if (data.id) {
        setSessionId(data.id);
        localStorage.setItem("${config.id}_session_id", data.id);
      }
    } catch { /* non-blocking */ }
  }

  async function handleSaveEmail() {
    if (!email) return;
    fetch("/api/save-email", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        email,
        source:       "${config.id}_result",
        country_code: "${config.country.toUpperCase()}",
        site:         "${config.site}",
        session_id:   sessionId ?? localStorage.getItem("${config.id}_session_id") ?? "",
      }),
    }).catch(() => {});
    setEmailSent(true);
  }

  async function handleContinueToPayment() {
    if (!answersComplete || checkoutLoading) return;
    // Save inputs for success page personalisation
    sessionStorage.setItem("${config.id}_answers", JSON.stringify(answers));
${stateKeys.map(k => `    sessionStorage.setItem("${config.id}_${k}", String(${k}));`).join("\n")}
    const sid          = sessionId ?? localStorage.getItem("${config.id}_session_id");
    const effectiveSid = sid ?? \`fallback_\${Date.now()}\`;
    setCheckoutLoading(true);
    setError("");
    try {
      if (sid) {
        fetch("/api/decision-sessions", {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            id:                    sid,
            tier_intended:         effectiveTier,
            product_key:           \`${config.country}_\${effectiveTier}_${config.id.replace(/-/g, "_")}\`,
            questionnaire_payload: answers,
            email:                 email || undefined,
          }),
        }).catch(() => {});
      }
      const successPath = effectiveTier === ${config.tier2.price}
        ? "${config.tier2.successPath}"
        : "${config.tier1.successPath}";
      const res  = await fetch("/api/create-checkout-session", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          decision_session_id: effectiveSid,
          tier:                effectiveTier,
          product_key:         \`${config.country}_\${effectiveTier}_${config.id.replace(/-/g, "_")}\`,
          success_url:         \`\${window.location.origin}/${config.slug}/success/\${successPath}\`,
          cancel_url:          \`\${window.location.origin}/${config.slug}\`,
        }),
      });
      const data = await res.json();
      if (!res.ok || !data.url) throw new Error(data.error ?? "Checkout failed.");
      window.location.href = data.url;
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to continue.");
      setCheckoutLoading(false);
    }
  }

  return (
    <>
      <div id="calculator" className="scroll-mt-8 space-y-5">

        {/* ── BRACKET SELECTOR ── */}
        <div className="rounded-2xl border border-neutral-200 bg-white p-6 shadow-sm sm:p-8">

          {/* Rule box — GOAT Block 3 */}
          <div className="mb-4 rounded-xl border-2 border-neutral-900 bg-neutral-950 px-4 py-4">
            <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400">
              ${config.calculatorRuleBox.label}
            </p>
            <p className="mt-1 text-sm leading-relaxed text-white">
              ${config.calculatorRuleBox.body}
            </p>
          </div>

          <p className="mb-2 font-serif text-2xl font-bold text-neutral-950">
            ${config.brackets.length > 0 ? "Select your situation" : "Check your position"}
          </p>
          <p className="mb-4 text-sm text-neutral-600">
            Tap your bracket for an instant compliance verdict.
          </p>

          {/* Bracket buttons — no sliders, no radios */}
          <div className="space-y-2">
            {BRACKETS.map((item, index) => {
              const selected = selectedBracket === index;
              return (
                <button
                  key={item.label}
                  onClick={() => handleBracketSelect(index)}
                  className={\`flex w-full items-center justify-between rounded-xl border-2 px-5 py-4 text-left transition \${
                    selected
                      ? "scale-[1.01] border-neutral-950 bg-neutral-950 text-white"
                      : "border-neutral-800 bg-white text-neutral-900 hover:bg-neutral-950 hover:text-white"
                  }\`}>
                  <span className="text-sm font-semibold">{item.label}</span>
                  <span className={\`font-mono text-[10px] uppercase tracking-widest \${selected ? "text-neutral-300" : "text-neutral-500"}\`}>
                    tap to check →
                  </span>
                </button>
              );
            })}
          </div>

          {/* Clarification box */}
          <div className="mt-4 rounded-xl border-2 border-amber-200 bg-amber-50 px-4 py-3">
            <p className="font-mono text-[10px] uppercase tracking-widest text-amber-700">
              ${config.calculatorClarification.label}
            </p>
            <p className="mt-1 text-xs leading-relaxed text-amber-900">
              ${config.calculatorClarification.body}
            </p>
          </div>
        </div>

        {/* ── RESULT PANEL ── */}
        {selectedBracket !== null && (
          <div ref={resultRef} className={\`rounded-2xl border p-6 sm:p-8 \${statusStyle.panelClass}\`}>

            {/* GOAT Block 7 — Result moment */}
            <p className={\`mb-1 font-mono text-sm font-bold uppercase tracking-widest \${statusStyle.badgeClass}\`}>
              {statusStyle.label}
            </p>
            <h3 className="mb-3 font-serif text-2xl font-bold text-neutral-950">
              {selectedProduct.tagline}
            </h3>

            {/* Compliance score — GOAT Block 8 */}
            <div className="mb-4 flex items-center gap-4 rounded-xl border border-neutral-200 bg-white px-4 py-3">
              <div className="text-center">
                <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400">Compliance score</p>
                <p className="font-serif text-3xl font-bold text-neutral-950">{statusStyle.score}</p>
                <p className="font-mono text-[10px] text-neutral-400">/ 100</p>
              </div>
              <div className="flex-1">
                <div className="mb-1 h-2 w-full overflow-hidden rounded-full bg-neutral-100">
                  <div
                    className={\`h-full rounded-full transition-all \${statusStyle.score >= 80 ? "bg-emerald-500" : statusStyle.score >= 60 ? "bg-amber-500" : "bg-red-500"}\`}
                    style={{ width: \`\${statusStyle.score}%\` }}
                  />
                </div>
                <p className="text-xs text-neutral-500">
                  {statusStyle.score >= 80 ? "Compliance in place — confirm the details" :
                   statusStyle.score >= 60 ? "Partial compliance — gaps to close" :
                   "Significant gaps — action needed now"}
                </p>
              </div>
            </div>

${hasInputs ? `            {/* ── OPTIMISATION INPUTS — button groups only, no sliders ── */}
            <div className="rounded-2xl border border-neutral-200 bg-white p-5">
              <p className="mb-4 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                Refine your position
              </p>
              <div className="space-y-5">
${config.calculatorInputs.map(input => buildInputJSX(input)).join("\n")}
              </div>
            </div>` : ""}

            {/* Email save */}
            <div className="mt-4 rounded-xl border border-neutral-200 bg-white p-4">
              <p className="mb-1 text-sm font-semibold text-neutral-800">
                Save your result to show your accountant.
              </p>
              <p className="mb-2 text-xs text-neutral-500">Free — get a copy by email.</p>
              {!emailSent ? (
                <div className="flex gap-2">
                  <input
                    type="email"
                    placeholder="Your email"
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                    className="flex-1 rounded-lg border border-neutral-200 bg-neutral-50 px-3 py-2 text-sm outline-none focus:border-neutral-400"
                  />
                  <button
                    onClick={handleSaveEmail}
                    className="rounded-lg border border-neutral-200 bg-white px-4 py-2 text-sm font-medium text-neutral-700 transition hover:bg-neutral-50">
                    Save
                  </button>
                </div>
              ) : (
                <p className="text-sm font-semibold text-emerald-700">✓ Saved.</p>
              )}
            </div>

            {/* CTA — GOAT Block 9 */}
            <button
              onClick={() => { setShowPopup(true); setPopupStep("intro"); }}
              className="mt-4 w-full rounded-xl bg-neutral-950 py-4 text-sm font-bold text-white transition hover:bg-neutral-800">
              Check my exact position →
            </button>
            <p className="mt-2 text-center text-xs text-neutral-500">
              ${config.currency === "USD" || config.currency === "NZD" || config.currency === "CAD" || config.currency === "AUD" ? "$" : "£"}{effectiveTier} · One-time · No subscription
            </p>
            {error && <p className="mt-3 text-sm font-medium text-red-700">{error}</p>}
          </div>
        )}
      </div>

      {/* ── POPUP ── */}
      {showPopup && selectedBracket !== null && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4">
          <div className="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl">

            {/* Popup header */}
            <div className="bg-neutral-950 px-5 py-4 text-white">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                    Based on your position
                  </p>
                  <p className="mt-1 font-serif text-xl font-bold text-white">{selectedProduct.name}</p>
                  <p className="mt-1 text-sm text-neutral-300">
                    {DAYS_TO_END} days to ${config.deadline.display}
                  </p>
                </div>
                <button onClick={() => setShowPopup(false)}
                  className="text-sm text-neutral-400 transition hover:text-white">✕</button>
              </div>
            </div>

            <div className="px-5 py-5">
              {popupStep === "intro" ? (
                <>
                  {/* GOAT Block 9 — Product justification */}
                  <div className="mb-4 rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-4">
                    <p className="mb-2 font-mono text-[10px] uppercase tracking-widest text-neutral-400">What you get</p>
                    <p className="mb-2 text-sm font-bold text-neutral-950">{selectedProduct.name}</p>
                    <p className="text-sm leading-relaxed text-neutral-700">{selectedProduct.value}</p>
                  </div>
                  <div className="mb-4 rounded-xl border border-neutral-200 bg-white px-4 py-3">
                    <div className="mb-1 flex items-center justify-between">
                      <p className="font-serif text-2xl font-bold text-neutral-950">${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}{effectiveTier}</p>
                      <p className="text-xs text-neutral-400">One-time · No subscription</p>
                    </div>
                    <p className="text-xs text-neutral-500">Not a generic guide. A plan for your position.</p>
                  </div>
                  <div className="mb-4 rounded-xl border border-amber-100 bg-amber-50 px-4 py-3">
                    <p className="text-xs text-amber-800">
                      💡 An accountant charges <strong>${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$250–500/hr" : "£150–300/hr"}</strong> to answer these questions.
                      This is <strong>${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}{effectiveTier}</strong>. One-time. Available right now.
                    </p>
                  </div>
                  <button
                    onClick={() => setPopupStep("questions")}
                    className="w-full rounded-xl bg-neutral-950 py-3.5 text-sm font-bold text-white transition hover:bg-neutral-800">
                    {selectedProduct.cta}
                  </button>
                  {effectiveTier === ${config.tier2.price} && (
                    <p className="mt-2 text-center">
                      <button
                        onClick={() => setOverrideTier(${config.tier1.price})}
                        className="text-xs text-neutral-400 underline transition hover:text-neutral-600">
                        Need less detail? ${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}${config.tier1.price} instead
                      </button>
                    </p>
                  )}
                  <button onClick={() => setShowPopup(false)}
                    className="mt-3 w-full text-sm text-neutral-500 underline">
                    Not now — keep reading
                  </button>
                </>
              ) : (
                // Questions step — native selects only (best mobile UX)
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                      5 quick questions then pay
                    </p>
                    <p className="font-serif text-lg font-bold text-neutral-950">${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}{effectiveTier}</p>
                  </div>
                  {[
                    { key: "contribution_timing", label: "When would you act on this?", options: [
                      ["this_week",    "This week"],
                      ["this_month",   "This month"],
                      ["before_deadline", \`Before \${DAYS_TO_END} day deadline\`],
                      ["unsure",       "Not sure yet"],
                    ]},
                    { key: "complexity_level", label: "How complex is your situation?", options: [
                      ["simple",    "Simple — one income source"],
                      ["moderate",  "Moderate — a few moving parts"],
                      ["complex",   "Complex — multiple sources"],
                      ["very_complex","Very complex — need expert help"],
                    ]},
                    { key: "main_goal", label: "What is your main goal?", options: [
                      ["confirm_position",  "Confirm my exact position"],
                      ["fix_gaps",          "Fix the gaps I have"],
                      ["plan_ahead",        "Plan ahead for next year"],
                      ["reduce_liability",  "Reduce my tax liability"],
                    ]},
                    { key: "accountant_status", label: "Accountant situation?", options: [
                      ["already_discussed", "Already discussed this"],
                      ["need_to_raise",     "Need to raise it"],
                      ["no_accountant",     "No accountant currently"],
                      ["looking_for_one",   "Looking for one"],
                    ]},
                    { key: "urgency", label: "How urgent is this for you?", options: [
                      ["very_urgent",  "Very — deadline approaching"],
                      ["urgent",       "Fairly urgent"],
                      ["planning",     "Planning ahead"],
                      ["just_curious", "Just checking"],
                    ]},
                  ].map(field => (
                    <div key={field.key}>
                      <label className="mb-1 block text-xs font-semibold text-neutral-700">
                        {field.label}
                      </label>
                      <select
                        value={answers[field.key as keyof Answers]}
                        onChange={e => setAnswers(prev => ({ ...prev, [field.key]: e.target.value }))}
                        className="w-full rounded-lg border border-neutral-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-neutral-400">
                        <option value="">Select…</option>
                        {field.options.map(([val, label]) => (
                          <option key={val} value={val}>{label}</option>
                        ))}
                      </select>
                    </div>
                  ))}
                  <button
                    onClick={handleContinueToPayment}
                    disabled={!answersComplete || checkoutLoading}
                    className="w-full rounded-xl bg-neutral-950 py-3.5 text-sm font-bold text-white transition hover:bg-neutral-800 disabled:cursor-not-allowed disabled:opacity-50">
                    {checkoutLoading ? "Redirecting…" : \`Pay ${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}\${effectiveTier} →\`}
                  </button>
                  {error && <p className="text-sm font-medium text-red-700">{error}</p>}
                  <button onClick={() => setShowPopup(false)}
                    className="w-full text-sm text-neutral-500 underline">
                    Not now — keep reading
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ── MOBILE STICKY BAR ── */}
      {mobileStickyVisible && (
        <div className="fixed bottom-0 left-0 right-0 z-[90] border-t border-neutral-200 bg-white px-4 py-3 shadow-[0_-6px_20px_rgba(0,0,0,0.08)] lg:hidden">
          <div className="flex items-center justify-between gap-3">
            <div className="min-w-0">
              <p className="truncate text-sm font-semibold text-neutral-900">{selectedProduct.name}</p>
              <p className="truncate text-xs text-neutral-500">From ${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}${config.tier1.price}</p>
            </div>
            <button
              onClick={() => { setShowPopup(true); setPopupStep("intro"); }}
              className="rounded-xl bg-neutral-950 px-4 py-3 text-sm font-bold text-white">
              From ${["USD","NZD","CAD","AUD"].includes(config.currency) ? "$" : "£"}${config.tier1.price} →
            </button>
          </div>
        </div>
      )}
    </>
  );
}
`;
}

// ── BUILD HELPERS ─────────────────────────────────────────────────────────────

function buildStateDeclaration(input: ButtonGroupInput | TwoButtonInput): string {
  if (input.type === "twoButton") {
    return `  const [${input.stateKey}, set${toPascal(input.stateKey)}] = useState<boolean>(${input.default});`;
  }
  const defaultVal = typeof input.default === "string"
    ? `"${input.default}"`
    : input.default;
  return `  const [${input.stateKey}, set${toPascal(input.stateKey)}] = useState<number | string>(${defaultVal});`;
}

function buildStateReset(config: ProductConfig, stateKey: string): string {
  const input = config.calculatorInputs.find(i => i.stateKey === stateKey);
  if (!input) return "";
  if (input.type === "twoButton") return `set${toPascal(stateKey)}(false);`;
  const defaultVal = typeof input.default === "string"
    ? `"${input.default}"`
    : input.default;
  return `set${toPascal(stateKey)}(${defaultVal});`;
}

function inferType(config: ProductConfig, stateKey: string): string {
  const input = config.calculatorInputs.find(i => i.stateKey === stateKey);
  if (!input) return "unknown";
  if (input.type === "twoButton") return "boolean";
  return "number | string";
}

function buildTierLogic(config: ProductConfig): string {
  const conditions = config.tierAlgorithm.tier2Conditions;
  const flags      = config.tierAlgorithm.tier2Flags;
  const lines: string[] = [];

  if (conditions.length > 0 || flags.length > 0) {
    // Wrap numeric comparisons with casts to avoid TS type errors
    // e.g. "dividends >= 25000" → "(dividends as number) >= 25000"
    const castConditions = conditions.map(c =>
      c.replace(/([a-zA-Z_][a-zA-Z0-9_]*)\s*(>=|<=|>|<)\s*(\d+)/g,
        '($1 as number) $2 $3')
    );
    const allConditions = [
      ...castConditions,
      ...flags.map(f => `${f} === true`),
    ];
    lines.push(`  if (${allConditions.join(" || ")}) return ${config.tier2.price};`);
  }

  return lines.join("\n") || `  // Default to tier 1`;
}

function buildInputJSX(input: ButtonGroupInput | TwoButtonInput): string {
  if (input.type === "twoButton") {
    return `                {/* TWO-BUTTON TOGGLE — ${input.label} */}
                <div>
                  <p className="mb-1 text-sm font-semibold text-neutral-800">${input.label}</p>
                  ${input.subLabel ? `<p className="mb-2 text-xs text-neutral-500">${input.subLabel}</p>` : ""}
                  <div className="flex gap-2">
                    ${input.options.map(opt => `
                    <button
                      type="button"
                      onClick={() => set${toPascal(input.stateKey)}(${opt.value})}
                      className={\`flex-1 rounded-lg border-2 py-3 text-sm font-bold transition \${
                        ${input.stateKey} === ${opt.value}
                          ? "border-neutral-950 bg-neutral-950 text-white"
                          : "border-neutral-200 bg-white text-neutral-700 hover:border-neutral-950 hover:bg-neutral-950 hover:text-white"
                      }\`}>
                      ${opt.label}
                    </button>`).join("")}
                  </div>
                </div>`;
  }

  // Button group
  const bgInput = input as ButtonGroupInput;
  return `                {/* BUTTON GROUP — ${bgInput.label} */}
                <div>
                  <p className="mb-1 text-sm font-semibold text-neutral-800">${bgInput.label}</p>
                  ${bgInput.subLabel ? `<p className="mb-2 text-xs text-neutral-500">${bgInput.subLabel}</p>` : ""}
                  <div className="flex flex-wrap gap-2">
                    ${bgInput.options.map(opt => {
                      const val = typeof opt.value === "string" ? `"${opt.value}"` : opt.value;
                      return `
                    <button
                      type="button"
                      onClick={() => set${toPascal(bgInput.stateKey)}(${val})}
                      className={\`rounded-lg border-2 px-4 py-2.5 text-sm font-bold transition \${
                        ${bgInput.stateKey} === ${val}
                          ? "border-neutral-950 bg-neutral-950 text-white"
                          : "border-neutral-200 bg-white text-neutral-700 hover:border-neutral-950 hover:bg-neutral-950 hover:text-white"
                      }\`}>
                      ${opt.label}
                    </button>`;
                    }).join("")}
                  </div>
                  ${bgInput.noteOnLast ? `
                  {${bgInput.stateKey} === ${typeof bgInput.options[bgInput.options.length - 1].value === "string" ? `"${bgInput.options[bgInput.options.length - 1].value}"` : bgInput.options[bgInput.options.length - 1].value} && (
                    <p className="mt-1.5 text-xs text-neutral-500">${bgInput.noteOnLast}</p>
                  )}` : ""}
                </div>`;
}

function toPascal(str: string): string {
  return str
    .split(/[-_]/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

// ── OUTPUT PATH HELPER ────────────────────────────────────────────────────────

export function getCalculatorPath(
  config: ProductConfig,
  appRoot: string
): string {
  const path = require("path");
  return path.join(
    appRoot,
    config.slug,
    `${toPascal(config.id)}Calculator.tsx`
  );
}
