// ── LEAD PRODUCT METADATA ────────────────────────────────────────────────
// Map of free-calculator `source` values → product display name, URL, authority, 3 generic accountant questions
// Used by app/api/leads/route.ts for the T2 email body

export interface LeadProductMeta {
  name:      string;
  url:       string;
  authority: string;
  questions: [string, string, string];
}

export const LEAD_PRODUCT_META: Record<string, LeadProductMeta> = {
  // ── AU ────────────────────────────────────────────────────────────────
  cgt_main_residence_trap:          { name: "CGT Main Residence Trap",           url: "/au/check/cgt-main-residence-trap",           authority: "ATO",  questions: ["How does the main residence exemption apply to my specific ownership history?",                           "What is the partial exemption calculation for any periods the property was rented?",                                  "Does the 6-year rule or any other extension apply to my situation?"] },
  division_7a_loan_trap:             { name: "Division 7A Loan Trap",             url: "/au/check/division-7a-loan-trap",             authority: "ATO",  questions: ["Is the loan from the company documented on complying Division 7A terms?",                                     "What minimum yearly repayment must I make to avoid a deemed dividend?",                                                "Should we refinance or offset against owner drawings before the lodgement deadline?"] },
  fbt_hidden_exposure:                { name: "FBT Hidden Exposure",                url: "/au/check/fbt-hidden-exposure",                authority: "ATO",  questions: ["Which of my benefits to employees are reportable and which are exempt?",                                         "Can we use the otherwise deductible rule or any concessions to reduce FBT?",                                          "What record-keeping would make a future FBT audit defensible?"] },
  cgt_discount_timing_sniper:          { name: "CGT Discount Timing Sniper",          url: "/au/check/cgt-discount-timing-sniper",          authority: "ATO",  questions: ["Will my asset satisfy the 12-month holding requirement before the planned sale date?",                              "How does the 50% discount interact with any capital losses I have carried forward?",                                   "If I sell close to year-end, should I defer to the next tax year to optimise bracket exposure?"] },
  negative_gearing_illusion:            { name: "Negative Gearing Illusion",            url: "/au/check/negative-gearing-illusion",            authority: "ATO",  questions: ["Is my rental property genuinely income-producing or at risk of being classified as passive?",                        "What deductions am I entitled to, and how should I apportion interest on a mixed-purpose loan?",                    "When does negative gearing actually create a benefit vs merely deferring tax?"] },
  small_business_cgt_concessions:        { name: "Small Business CGT Concessions",        url: "/au/check/small-business-cgt-concessions",        authority: "ATO",  questions: ["Do I meet the $6M maximum net asset value test or the $2M small business entity test?",                              "Which of the 4 concessions (15-year / 50% active asset / retirement / rollover) give the best outcome?",              "What timing or restructure should precede the sale to secure eligibility?"] },
  instant_asset_write_off:                 { name: "Instant Asset Write-Off",                url: "/au/check/instant-asset-write-off",                authority: "ATO",  questions: ["Is my business eligible under current instant asset write-off thresholds?",                                          "What is the cost limit this tax year, and does it apply per asset or aggregate?",                                    "Should we accelerate purchase before 30 June to claim in this tax year?"] },
  gst_registration_trap:                     { name: "GST Registration Trap",                     url: "/au/check/gst-registration-trap",                    authority: "ATO",  questions: ["Have I crossed the $75,000 threshold in any rolling 12-month period?",                                                 "If I register late, what retrospective GST do I owe, and can I claim input credits?",                                "Should I register voluntarily to recover GST on capital purchases?"] },
  rental_property_deduction_audit:            { name: "Rental Property Deduction Audit",            url: "/au/check/rental-property-deduction-audit",            authority: "ATO",  questions: ["Am I claiming all legitimate deductions — depreciation, capital works, borrowing expenses?",                         "Is my quantity surveyor report current, and have I claimed Division 40 and 43 correctly?",                           "Which of my deductions are at highest risk of ATO challenge and how do I document them?"] },
  medicare_levy_surcharge_trap:                { name: "Medicare Levy Surcharge Trap",                url: "/au/check/medicare-levy-surcharge-trap",                authority: "ATO",  questions: ["Does my current income put me over the MLS threshold for my family situation?",                                       "Would taking out eligible private hospital cover now reduce my current-year MLS?",                                   "What is the break-even on premium vs MLS for my income band?"] },
  bring_forward_window:                         { name: "Bring-Forward Window",                         url: "/au/check/bring-forward-window",                         authority: "ATO",  questions: ["Am I eligible to trigger the 3-year bring-forward this tax year?",                                                    "What is my total super balance, and does it affect the bring-forward amount available?",                             "If I contribute before 30 June, what are the consequences for future caps?"] },
  super_death_tax_trap:                          { name: "Super Death Tax Trap",                          url: "/au/check/super-death-tax-trap",                          authority: "ATO",  questions: ["What is the taxable component of my super balance, and who would pay 15-30% on it?",                                 "Should I consider a withdrawal-and-recontribution strategy to reduce the taxable component?",                        "Is my binding death benefit nomination current and directing benefits to tax-free beneficiaries?"] },
  div296_wealth_eraser:                           { name: "Div 296 Wealth Eraser",                           url: "/au/check/div296-wealth-eraser",                           authority: "ATO",  questions: ["Does my total super balance exceed $3M, and by how much?",                                                            "Should I consider withdrawing above-cap balances before the 30 June measurement date?",                             "What is the projected Div 296 liability over the next 5 years based on my contribution pattern?"] },
  super_to_trust_exit:                             { name: "Super to Trust Exit",                             url: "/au/check/super-to-trust-exit",                             authority: "ATO",  questions: ["What is the break-even calculation for exiting super to a family trust structure?",                                    "What tax triggers (CGT, benefit payment tax) apply on the exit, and over how many years?",                           "Does my age condition of release affect the exit timing and tax treatment?"] },
  transfer_balance_cap:                              { name: "Transfer Balance Cap",                              url: "/au/check/transfer-balance-cap",                              authority: "ATO",  questions: ["What is my current transfer balance account position vs the general transfer balance cap?",                              "How do indexation credits from the ATO affect my available cap space?",                                              "If I've exceeded the cap, what commutation is required and how urgently?"] },

  // ── UK ────────────────────────────────────────────────────────────────
  mtd_scorecard:                                      { name: "MTD Scorecard",                                      url: "/uk/check/mtd-scorecard",                                      authority: "HMRC", questions: ["Am I within MTD for Income Tax scope at my current income level, and from which date?",                               "Does my existing bookkeeping software meet HMRC's digital links requirements?",                                       "What penalties apply if my first MTD quarterly submission is missed?"] },
  allowance_sniper:                                      { name: "Allowance Sniper",                                      url: "/uk/check/allowance-sniper",                                      authority: "HMRC", questions: ["Am I currently claiming all allowances I'm entitled to (personal / marriage / dividend / savings)?",                       "Is there a tax code issue causing me to miss any part of my personal allowance?",                                      "Can I backdate claims to recover unclaimed allowances from previous tax years?"] },
  digital_link_auditor:                                   { name: "Digital Link Auditor",                                   url: "/uk/check/digital-link-auditor",                                   authority: "HMRC", questions: ["Do the data transfers between my software meet HMRC's digital link rules without manual copy-paste?",                       "Are there any remaining manual steps in my bookkeeping-to-VAT workflow that HMRC would flag?",                         "What bridging software is compliant for my setup?"] },
  side_hustle_checker:                                     { name: "Side Hustle Checker",                                     url: "/uk/check/side-hustle-checker",                                     authority: "HMRC", questions: ["Have I exceeded the £1,000 trading allowance that requires Self Assessment registration?",                               "Which platforms (Etsy, eBay, Airbnb etc.) now report to HMRC via the DAC7 regime?",                                    "If I owe tax from prior years, what is my Let Property Campaign or Digital Disclosure exposure?"] },
  dividend_trap:                                            { name: "Dividend Trap",                                            url: "/uk/check/dividend-trap",                                            authority: "HMRC", questions: ["What dividend allowance applies this year, and how does it interact with my personal allowance?",                           "Should I take more salary vs dividends from my limited company given current tax rates?",                              "Does the £500 dividend allowance create a filing trigger I need to notify HMRC about?"] },
  pension_iht_trap:                                           { name: "Pension IHT Trap",                                           url: "/uk/check/pension-iht-trap",                                           authority: "HMRC", questions: ["Are my pensions structured to pass outside my estate, or will they be included in IHT?",                                   "What is the impact of the 2027 rule change bringing pensions into IHT on my beneficiaries?",                            "Should I accelerate pension withdrawals or consolidate to manage IHT exposure?"] },

  // ── US ────────────────────────────────────────────────────────────────
  section_174_auditor:                                         { name: "Section 174 Auditor",                                         url: "/us/check/section-174-auditor",                                         authority: "IRS",  questions: ["Are my R&D expenses subject to the 5-year / 15-year capitalisation rule under s174?",                                      "Can I claim any immediate expensing under the 2024/2025 legislation changes?",                                           "What is the deferred tax impact of s174 capitalisation on my current-year cash tax?"] },
  feie_nomad_auditor:                                           { name: "FEIE Nomad Auditor",                                           url: "/us/check/feie-nomad-auditor",                                           authority: "IRS",  questions: ["Do I meet the physical presence test (330 days) or bona fide residence test for FEIE?",                                  "Is FEIE or Foreign Tax Credit the better strategy for my country and income level?",                                     "Are my foreign housing expenses eligible for the housing exclusion under §911(c)?"] },
  qsbs_exit_auditor:                                              { name: "QSBS Exit Auditor",                                              url: "/us/check/qsbs-exit-auditor",                                              authority: "IRS",  questions: ["Do my shares meet the 5-year holding, active business, and gross asset tests for Section 1202?",                         "What is my exclusion cap (10x basis or $10M whichever is greater) on the expected gain?",                              "Should I stack exemptions via gifts to family members or trusts before sale?"] },
  iso_amt_sniper:                                                   { name: "ISO AMT Sniper",                                                   url: "/us/check/iso-amt-sniper",                                                   authority: "IRS",  questions: ["What is my AMT liability on the ISO spread if I exercise this year?",                                                     "Should I do a partial exercise up to the AMT crossover point to avoid liability?",                                       "Can I sell some shares in the same year to manage the AMT exposure?"] },
  wayfair_nexus_sniper:                                                { name: "Wayfair Nexus Sniper",                                                url: "/us/check/wayfair-nexus-sniper",                                                authority: "IRS",  questions: ["In which states have I crossed the economic nexus threshold and from what date?",                                         "What is my historical sales tax exposure per state, and are voluntary disclosure programs available?",                   "Should I engage a sales tax automation platform, and which best fits my volume?"] },

  // ── NZ ────────────────────────────────────────────────────────────────
  bright_line_auditor:                                                   { name: "Bright-Line Auditor",                                                   url: "/nz/check/bright-line-auditor",                                                   authority: "IRD",  questions: ["Does the 2-year or 5-year bright-line period apply to my property sale?",                                                 "Am I eligible for the main home exclusion given my specific occupancy pattern?",                                          "What ACB + improvement records do I need to substantiate my gain calculation?"] },
  app_tax_gst_sniper:                                                      { name: "App Tax GST Sniper",                                                      url: "/nz/check/app-tax-gst-sniper",                                                      authority: "IRD",  questions: ["Does the listed-services 15% GST apply to my Airbnb / Uber / rideshare income from the 2024 changes?",                   "Is the platform collecting GST on my behalf, or is this my own responsibility?",                                            "If I'm GST-registered already, how does the opt-out rule affect my position?"] },
  interest_reinstatement_engine:                                              { name: "Interest Reinstatement Engine",                                              url: "/nz/check/interest-reinstatement-engine",                                              authority: "IRD",  questions: ["Given the reinstated interest deductibility rules, what % of my rental interest is deductible this year?",               "How do the transitional rules apply to property I acquired before 27 March 2021?",                                         "What is my current-year recovery from the phased reinstatement schedule?"] },
  trust_tax_splitter:                                                           { name: "Trust Tax Splitter",                                                           url: "/nz/check/trust-tax-splitter",                                                           authority: "IRD",  questions: ["Is my trust's retained income above the $10,000 threshold triggering the 39% rate?",                                      "Should I consider beneficiary distributions to individuals on lower marginal rates?",                                      "Are my trust resolutions and documentation current to support distribution decisions?"] },
  investment_boost_auditor:                                                       { name: "Investment Boost Auditor",                                                       url: "/nz/check/investment-boost-auditor",                                                       authority: "IRD",  questions: ["Does my capital expenditure qualify for the Investment Boost 20% deduction?",                                            "What is the interaction between Investment Boost and my depreciation claim?",                                             "If I'm also claiming small asset write-offs, how do the rules stack?"] },

  // ── NOMAD ─────────────────────────────────────────────────────────────
  residency_risk_index:                                                              { name: "Nomad Residency Risk Index",                                                              url: "/nomad",                                                              authority: "OECD", questions: ["Which countries am I currently a tax resident of under their domestic rules?",                                            "Where is the likely treaty tie-breaker outcome if dual residency applies?",                                                "What is my risk if my departure country still considers me resident?"] },
  tax_treaty_navigator:                                                                { name: "Tax Treaty Navigator",                                                                url: "/nomad/check/tax-treaty-navigator",                                                                authority: "OECD", questions: ["Which tax treaty between my home country and host country applies to my specific income types?",                          "Under the treaty tie-breaker, which country has primary taxing rights?",                                                  "What certificate of residence and disclosure forms do I need to claim treaty benefits?"] },
  day_183_rule:                                                                          { name: "183-Day Rule Reality Check",                                                                          url: "/nomad/check/183-day-rule",                                                                          authority: "OECD", questions: ["How does each of my residence-relevant countries count days, and which counting method applies?",                         "Have I exceeded the 183-day threshold in any jurisdiction this tax year?",                                                 "Are there home-country residency tests beyond the 183-day rule that would capture me?"] },
  exit_tax_trap:                                                                            { name: "Exit Tax Trap Auditor",                                                                            url: "/nomad/check/exit-tax-trap",                                                                            authority: "OECD", questions: ["Does my departure country impose a deemed disposition / exit tax, and on which assets?",                                 "Can I elect a deferral or post security with the tax authority to defer the charge?",                                       "Are any of my assets excluded (real estate, registered accounts, business property)?"] },
  uk_residency:                                                                                { name: "UK Statutory Residence Test Auditor",                                                                url: "/nomad/check/uk-residency",                                                                authority: "HMRC", questions: ["Under the SRT, am I automatically non-resident, automatically resident, or determined by sufficient ties?",               "How many UK days am I allowed while still satisfying my claimed test?",                                                   "What evidence should I retain to defend my SRT position under HMRC review?"] },
  uk_nrls:                                                                                       { name: "UK Non-Resident Landlord Scheme Auditor",                                                                       url: "/nomad/check/uk-nrls",                                                                       authority: "HMRC", questions: ["Is my current NRL1/NRL2 position registered with HMRC to receive gross rent?",                                           "Am I meeting the Section 216 / Section 216.1 filing obligations each tax year?",                                            "Is my letting agent / tenant withholding correctly under Part XIII equivalent UK rules?"] },
  au_expat_cgt:                                                                                    { name: "Australian Expat CGT Trap",                                                                                    url: "/nomad/check/au-expat-cgt",                                                                                    authority: "ATO",  questions: ["Will I be foreign resident at the contract signing date of my Australian property sale?",                                "Does any life events exception under s118-115(3) apply to my situation?",                                                  "Should we accelerate the sale before departure, or defer until after return to Australian residency?"] },
  us_expat_tax:                                                                                      { name: "US Citizen Abroad Optimizer",                                                                                      url: "/nomad/check/us-expat-tax",                                                                                      authority: "IRS",  questions: ["Is FEIE, Foreign Tax Credit, or a hybrid the better strategy for my country and income?",                                  "Am I meeting all FBAR and FATCA filing obligations on foreign accounts and assets?",                                        "What are my state tax obligations (or safe harbour) as a US citizen residing abroad?"] },
  au_smsf_residency:                                                                                    { name: "AU SMSF Residency Kill-Switch",                                                                                    url: "/nomad/check/australia-smsf-residency",                                                                                    authority: "ATO",  questions: ["Where is the central management and control of my fund actually exercised, factually?",                                   "Will my absence exceed 2 years, triggering the ordinary-CM&C absence rule?",                                                "Should I restructure to a corporate trustee with AU-resident directors to preserve compliance?"] },
  spain_beckham:                                                                                          { name: "Spain Beckham Eligibility Wall",                                                                                          url: "/nomad/check/spain-beckham-eligibility",                                                                                          authority: "AEAT", questions: ["Does my work arrangement qualify me for the Beckham regime (employment, posting, director, DNV)?",                          "Have I been Spanish tax resident in the 5 years preceding arrival, which disqualifies me?",                               "Have I submitted Modelo 149 within the absolute 6-month window from Spanish SS registration?"] },

  // ── CAN ───────────────────────────────────────────────────────────────
  can_departure_tax:                                                                                         { name: "Canada Departure Tax Trap",                                                                                         url: "/can/check/departure-tax-trap",                                                                                         authority: "CRA",  questions: ["What is my estimated departure tax under s128.1 given my portfolio + ACB + FMV?",                                         "Should we sell loss positions before departure to reduce the deemed gain?",                                              "Should I file Form T1244 to defer the departure tax by posting security?"] },
  can_nrls:                                                                                                   { name: "Canada Non-Resident Landlord Withholding",                                                                                                   url: "/can/check/non-resident-landlord-withholding",                                                                                                   authority: "CRA",  questions: ["Am I currently having 25% Part XIII withholding applied correctly, or do I have NR6 approval?",                            "How many past years of Section 216 refunds are still within the 2-year recovery window?",                                 "Should I apply for NR6 going forward to reduce the monthly cashflow drag?"] },
  can_property_flipping:                                                                                        { name: "Canada Property Flipping Tax Trap",                                                                                        url: "/can/check/property-flipping-tax-trap",                                                                                        authority: "CRA",  questions: ["Does the 365-day flipping rule under s12(12) apply to my specific holding period?",                                        "Does any life events exception (job relocation, marital breakdown, etc.) apply to my situation?",                          "If not yet sold, what is the tax benefit of waiting until the 365-day mark to close?"] },
  can_amt_shock:                                                                                                 { name: "Canada AMT Shock Auditor",                                                                                                 url: "/can/check/amt-shock-auditor",                                                                                                 authority: "CRA",  questions: ["Does the revised 2024 AMT apply given my triggers (capital gains, stock options, donations)?",                              "What is my estimated AMT credit carryforward, and when am I likely to recover it?",                                          "Can I spread gains or donations across tax years to manage AMT exposure?"] },
  can_eot_exit:                                                                                                    { name: "Canada EOT Exit Optimizer",                                                                                                    url: "/can/check/eot-exit-optimizer",                                                                                                    authority: "CRA",  questions: ["Does my current share ownership structure qualify, or is pre-sale restructuring required?",                                    "What is my maximum potential exemption given the number of vendors + their allocations?",                                      "Can the sale be completed before the 31 December 2026 qualifying window closes?"] },
};

// ── GENERIC FALLBACK ─────────────────────────────────────────────────────
export const GENERIC_FALLBACK: LeadProductMeta = {
  name:      "TaxCheckNow Assessment",
  url:       "/",
  authority: "Tax authority",
  questions: [
    "What are my specific obligations under the rule identified in my result?",
    "What timing or structural changes would materially reduce my tax exposure?",
    "What documentation should I retain to support my position under any future audit?",
  ],
};

export function getLeadMeta(source: string): LeadProductMeta {
  return LEAD_PRODUCT_META[source] ?? GENERIC_FALLBACK;
}
