"use client";
// AUTO-GENERATED BY COLE — do not edit manually
// Product: gst-registration-trap · Tier 2 Success Page
import { useEffect, useState } from "react";
import Link from "next/link";

const FILES = [
  {
    "num": "01",
    "slug": "gst-01",
    "name": "Your GST Registration Status Report",
    "desc": "Whether you are required to register and your backdate risk.",
    "tier": 1
  },
  {
    "num": "02",
    "slug": "gst-02",
    "name": "Backdating Risk Plan",
    "desc": "How to calculate and manage your GST backdate liability.",
    "tier": 1
  },
  {
    "num": "03",
    "slug": "gst-03",
    "name": "GST Catch-Up Strategy",
    "desc": "How to manage late registration and minimise penalties.",
    "tier": 1
  },
  {
    "num": "04",
    "slug": "gst-04",
    "name": "GST Threshold Tracker",
    "desc": "Monthly monitoring system to track when you approach the $75,000 threshold.",
    "tier": 1
  },
  {
    "num": "05",
    "slug": "gst-05",
    "name": "Your Accountant Brief",
    "desc": "GST questions to take if your business is growing.",
    "tier": 1
  },
  {
    "num": "06",
    "slug": "gst-06",
    "name": "Full GST System Setup",
    "desc": "Complete GST registration, BAS lodgement, and compliance framework.",
    "tier": 2
  },
  {
    "num": "07",
    "slug": "gst-07",
    "name": "BAS Compliance Framework",
    "desc": "A quarter-by-quarter BAS management system.",
    "tier": 2
  },
  {
    "num": "08",
    "slug": "gst-08",
    "name": "Ongoing GST Compliance Structure",
    "desc": "Long-term GST management system to avoid future exposure.",
    "tier": 2
  }
];

interface Action { title: string; deadline: string; steps: string[]; }
type Assessment = Record<string, unknown> & {
  accountantQuestions?: string[];
  actions?: Action[];
};

export default function SuccessPlan() {
  const [firstName,  setFirstName]  = useState("there");
  const [assessment, setAssessment] = useState<Assessment | null>(null);
  const [loading,    setLoading]    = useState(true);
  const [error,      setError]      = useState("");
  const [copied,     setCopied]     = useState(false);
  const [calDone,    setCalDone]    = useState(false);
  const [checked,    setChecked]    = useState<Record<number,boolean>>({});

  const daysToDeadline = Math.max(0, Math.floor(
    (new Date("2026-07-28T23:59:59.000+10:00").getTime() - Date.now()) / 86_400_000
  ));

  useEffect(() => { init(); }, []);

  async function init() {
    const params    = new URLSearchParams(window.location.search);
    const sessionId = params.get("session_id");
    let name = "there";
    if (sessionId) {
      try {
        const r = await fetch(`/api/get-session?id=${sessionId}`);
        const d = await r.json();
        if (d.firstName) { name = d.firstName; setFirstName(d.firstName); }
      } catch { /* non-fatal */ }
    }
    await generateAssessment(name);
  }

  async function generateAssessment(name: string) {
    setLoading(true);
    setError("");
    const params    = new URLSearchParams(window.location.search);
    const sessionId = params.get("session_id");

    try {
      // ── STEP 1: Try fetching pre-generated assessment from Supabase ──
      // Generated by webhook at purchase time — instant load, no API call
      if (sessionId) {
        const r = await fetch(`/api/get-assessment?session_id=${sessionId}`);
        if (r.ok) {
          const d = await r.json();
          if (d.assessment) {
            setAssessment(d.assessment);
            setLoading(false);
            return;
          }
        }
      }

      // ── STEP 2: Fallback — generate now via /api/assess ──────────────
      // Runs if webhook hasn't stored assessment yet (e.g. timing, retry)
      const business_type = sessionStorage.getItem("gst-registration-trap_business_type") || "general";
      const current_turnover = sessionStorage.getItem("gst-registration-trap_current_turnover") || "band_75_150";
      const backdating = sessionStorage.getItem("gst-registration-trap_backdating") || "true";
      const status = sessionStorage.getItem("gst-registration-trap_status") || "REGISTRATION REQUIRED";
      const tier = sessionStorage.getItem("gst-registration-trap_tier") || "147";

      // Check if we have any real inputs — sessionStorage may be empty after Stripe redirect
      const hasInputs = Object.values({
        "business_type": business_type,
        "current_turnover": current_turnover,
        "backdating": backdating,
        "status": status,
        "tier": tier,
      }).some(v => v && v !== "general");

      const res = await fetch("/api/assess", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          product_id: "gst-registration-trap",
          market:     "Australia",
          authority:  "ATO",
          tier:       2,
          name,
          inputs: {
        "Business type": business_type,
        "Current GST turnover band": current_turnover,
        "Backdating risk identified": backdating,
        "GST registration verdict": status,
        "Product tier purchased": tier,
          },
          fields: ["gstStatus","registrationObligation","triggerDateEstimate","backdatingExposure","invoiceCleanupRequired","projectedTurnoverAnalysis","basSetupRecommendation","pricingTransitionGuide","bookkeepingClassification","retroBASPlan","inputTaxCredits","strongestRiskTrigger"],
        }),
      });
      const data = await res.json();
      if (!res.ok || data.error) throw new Error(data.error || "Assessment failed");
      setAssessment(data.assessment);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate assessment");
      // Graceful fallback — page still shows files and calendar
      setAssessment({
        gstStatus: "Your personalised gstStatus is being prepared — please refresh in a moment.",
        registrationObligation: "Your personalised registrationObligation is being prepared — please refresh in a moment.",
        triggerDateEstimate: "Your personalised triggerDateEstimate is being prepared — please refresh in a moment.",
        backdatingExposure: "Your personalised backdatingExposure is being prepared — please refresh in a moment.",
        invoiceCleanupRequired: "Your personalised invoiceCleanupRequired is being prepared — please refresh in a moment.",
        projectedTurnoverAnalysis: "Your personalised projectedTurnoverAnalysis is being prepared — please refresh in a moment.",
        basSetupRecommendation: "Your personalised basSetupRecommendation is being prepared — please refresh in a moment.",
        pricingTransitionGuide: "Your personalised pricingTransitionGuide is being prepared — please refresh in a moment.",
        bookkeepingClassification: "Your personalised bookkeepingClassification is being prepared — please refresh in a moment.",
        retroBASPlan: "Your personalised retroBASPlan is being prepared — please refresh in a moment.",
        inputTaxCredits: "Your personalised inputTaxCredits is being prepared — please refresh in a moment.",
        strongestRiskTrigger: "Your personalised strongestRiskTrigger is being prepared — please refresh in a moment.",
        accountantQuestions: [
          "What is my exact ATO position based on my answers?",
          "What is the single most important action I should take before 28 July 2026?",
          "Are there any planning opportunities specific to my situation?",
        ],
        actions: [],
      } as unknown as Assessment);
    } finally {
      setLoading(false);
    }
  }

  function handleCalendar() {
    const now = new Date().toISOString().replace(/[-:]/g,"").split(".")[0] + "Z";
    const business_type = sessionStorage.getItem("gst-registration-trap_business_type") || "general";
    const current_turnover = sessionStorage.getItem("gst-registration-trap_current_turnover") || "band_75_150";
    const backdating = sessionStorage.getItem("gst-registration-trap_backdating") || "true";
    const status = sessionStorage.getItem("gst-registration-trap_status") || "REGISTRATION REQUIRED";
    const tier = sessionStorage.getItem("gst-registration-trap_tier") || "147";
    function relativeDate(d: number): string {
      return new Date(Date.now() + d * 86400000).toISOString().split("T")[0].replace(/-/g,"");
    }
    const ics = [
      "BEGIN:VCALENDAR","VERSION:2.0",
      "PRODID:-//TaxCheckNow//COLE//EN",
      "CALSCALE:GREGORIAN","METHOD:PUBLISH",
      `X-WR-CALNAME:GST Registration Trap Engine — Deadlines`,
      "BEGIN:VEVENT",
      `UID:gst-register-${Date.now()}@taxchecknow.com`,
      `DTSTART;VALUE=DATE:${relativeDate(7)}`,
      `DTEND;VALUE=DATE:${relativeDate(7)}`,
      `DTSTAMP:${now}`,
      "SUMMARY:GST — Register if threshold crossed",
      "DESCRIPTION:Register for GST within 21 days of crossing $75,000 threshold.",
      "STATUS:CONFIRMED",
      "END:VEVENT",
      "BEGIN:VEVENT",
      `UID:gst-bas-q4-${Date.now()}@taxchecknow.com`,
      `DTSTART;VALUE=DATE:${"20260728"}`,
      `DTEND;VALUE=DATE:${"20260728"}`,
      `DTSTAMP:${now}`,
      "SUMMARY:BAS Due — Q4 28 July 2026",
      "DESCRIPTION:Lodge and pay Q4 BAS.",
      "STATUS:CONFIRMED",
      "END:VEVENT",
      "END:VCALENDAR",
    ].join("\r\n");
    const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "gst-registration-trap.ics";
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(url);
    setCalDone(true);
  }

  async function handleCopy() {
    if (!assessment?.accountantQuestions?.length) return;
    const text = (assessment.accountantQuestions as string[])
      .map((q,i) => `${i+1}. "${q}"`).join("\n");
    await navigator.clipboard.writeText(
      `Your GST Compliance System — questions for my accountant:\n\n${text}\n\nTaxCheckNow · taxchecknow.com`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  }

  const hi = firstName !== "there" ? firstName : "there";
  const greeting = firstName !== "there" ? `${firstName}` : "Your";

  return (
    <div className="min-h-screen bg-neutral-50 print:bg-white">
      <style>{`@media print { .no-print{display:none!important} body{font-size:12px;color:#000} .print-section{page-break-inside:avoid} }`}</style>

      {/* NAV */}
      <nav className="no-print border-b border-neutral-200 bg-white px-6 py-4">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link href="/" className="font-serif text-lg font-bold text-neutral-950">TaxCheckNow</Link>
          <button onClick={() => window.print()}
            className="rounded-lg border border-neutral-200 bg-white px-3 py-1.5 font-mono text-xs font-bold text-neutral-700 hover:bg-neutral-950 hover:text-white transition">
            ⬇ Save PDF
          </button>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl space-y-5 px-6 py-8">

        {/* ── HERO — confirmation + personal hook ── */}
        <div className="print-section rounded-2xl border-2 border-emerald-500 bg-emerald-50 px-6 py-6">
          <p className="font-mono text-[10px] uppercase tracking-widest text-emerald-700">
            Payment confirmed · Your GST Compliance System · $147
          </p>
          <h1 className="mt-2 font-serif text-2xl font-bold text-neutral-950">
            {hi !== "there" ? `${hi}, here is your ` : "Your "}Your GST Compliance System
          </h1>
          <p className="mt-1 text-sm text-emerald-800">
            This is your full implementation plan — built around your specific inputs, not the average taxpayer.
          </p>
          <div className="mt-4 flex items-center justify-between rounded-xl bg-red-700 px-4 py-2.5">
            <span className="text-sm font-bold text-white">🔴 {daysToDeadline} days to 28 July 2026</span>
            <span className="font-mono text-sm font-bold text-white">28 Jul 2026</span>
          </div>
        </div>

        {/* ── LOADING ── */}
        {loading && (
          <div className="rounded-2xl border border-neutral-200 bg-white p-10 text-center">
            <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-2 border-neutral-950 border-t-transparent" />
            <p className="text-sm font-semibold text-neutral-700">Building your personalised assessment…</p>
            <p className="mt-1 text-xs text-neutral-400">Analysing your answers against ATO rules</p>
          </div>
        )}

        {/* ── ERROR ── */}
        {error && !loading && (
          <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
            ⚠ Assessment generation issue — showing your files and calendar below.
            <button onClick={() => generateAssessment(firstName)}
              className="no-print ml-2 underline font-semibold">Try again →</button>
          </div>
        )}

        {/* ── ASSESSMENT ── */}
        {!loading && assessment && (
          <>

            {/* YOUR POSITION — key verdict fields */}
            <div className="print-section rounded-2xl border border-neutral-200 bg-white p-6">
              <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                Your Australia ATO position
              </p>
              <h2 className="mb-4 font-serif text-xl font-bold text-neutral-950">
                What this means for {greeting}
              </h2>
              <div className="space-y-3">
                {(["gstStatus","registrationObligation","triggerDateEstimate","backdatingExposure","invoiceCleanupRequired","projectedTurnoverAnalysis"] as string[]).map(key => {
                  const val = assessment[key];
                  if (!val || typeof val !== "string") return null;
                  return (
                    <div key={key} className="rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-4">
                      <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                        {key.replace(/([A-Z])/g,' $1').replace(/_/g,' ').trim().replace(/^./,c=>c.toUpperCase())}
                      </p>
                      <p className="text-sm leading-relaxed text-neutral-900">{val}</p>
                    </div>
                  );
                })}
              </div>
            </div>


            {/* ACTIONS CHECKLIST — tier 2 */}
            {Array.isArray(assessment.actions) && assessment.actions.length > 0 && (
              <div className="print-section rounded-2xl border border-neutral-200 bg-white p-6">
                <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                  Your action checklist
                </p>
                <h2 className="mb-4 font-serif text-xl font-bold text-neutral-950">
                  What to do — in order — before 28 July 2026
                </h2>
                <div className="space-y-4">
                  {(assessment.actions as Action[]).map((action, i) => (
                    <div key={i} className={`rounded-xl border p-5 transition ${checked[i] ? "border-emerald-200 bg-emerald-50" : "border-neutral-200 bg-neutral-50"}`}>
                      <div className="flex items-start gap-3 mb-3">
                        <button onClick={() => setChecked(p => ({ ...p, [i]: !p[i] }))}
                          className={`no-print mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 transition ${checked[i] ? "border-emerald-500 bg-emerald-500" : "border-neutral-300 bg-white hover:border-neutral-950"}`}>
                          {checked[i] && <span className="text-xs font-bold text-white">✓</span>}
                        </button>
                        <div className="flex-1">
                          <div className="flex items-start justify-between gap-2">
                            <p className={`font-bold ${checked[i] ? "text-neutral-400 line-through" : "text-neutral-950"}`}>
                              {i + 1}. {action.title}
                            </p>
                            <span className="shrink-0 rounded-lg bg-red-100 px-2 py-0.5 font-mono text-[10px] font-bold text-red-700">
                              {action.deadline}
                            </span>
                          </div>
                        </div>
                      </div>
                      <div className="ml-9 space-y-2">
                        {action.steps?.map((step, j) => (
                          <div key={j} className="flex items-start gap-2">
                            <span className="mt-0.5 shrink-0 font-mono text-xs text-neutral-400">{j+1}.</span>
                            <p className="text-sm leading-relaxed text-neutral-700">{step}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* ACCOUNTANT QUESTIONS */}
            {Array.isArray(assessment.accountantQuestions) && assessment.accountantQuestions.length > 0 && (
              <div className="print-section rounded-2xl border border-blue-100 bg-blue-50 p-6">
                <div className="mb-3 flex items-start justify-between gap-4">
                  <div>
                    <p className="font-mono text-[10px] uppercase tracking-widest text-blue-700">
                      Questions for your accountant
                    </p>
                    <p className="mt-1 text-sm text-blue-800">
                      Copy these and take them to your next meeting. Each one is specific to your situation.
                    </p>
                  </div>
                  <button onClick={handleCopy}
                    className="no-print shrink-0 rounded-lg border border-blue-200 bg-white px-3 py-1.5 font-mono text-xs font-bold text-blue-700 hover:bg-blue-700 hover:text-white transition">
                    {copied ? "Copied ✓" : "Copy all →"}
                  </button>
                </div>
                <div className="space-y-2">
                  {(assessment.accountantQuestions as string[]).map((q, i) => (
                    <div key={i} className="flex items-start gap-3 rounded-xl border border-blue-100 bg-white px-4 py-3">
                      <span className="mt-0.5 shrink-0 font-mono text-xs font-bold text-blue-600">{i+1}</span>
                      <p className="text-sm leading-relaxed text-blue-900">"{q}"</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* CALENDAR */}
            <div className="print-section rounded-2xl border border-neutral-200 bg-white p-6">
              <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                Key dates for your calendar
              </p>
              <h2 className="mb-4 font-serif text-lg font-bold text-neutral-950">
                Add these now — don't rely on memory
              </h2>
              <div className="mb-4 space-y-2">
                
                <div className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3">
                  <div>
                    <p className="text-sm font-semibold text-neutral-900">GST — Register if threshold crossed</p>
                    <p className="text-xs text-neutral-500">Register for GST within 21 days of crossing $75,000 threshold.</p>
                  </div>
                  <span className="ml-3 shrink-0 font-mono text-xs font-bold text-neutral-500">
                    This week
                  </span>
                </div>
                <div className="flex items-center justify-between rounded-xl border border-neutral-100 bg-neutral-50 px-4 py-3">
                  <div>
                    <p className="text-sm font-semibold text-neutral-900">BAS Due — Q4 28 July 2026</p>
                    <p className="text-xs text-neutral-500">Lodge and pay Q4 BAS.</p>
                  </div>
                  <span className="ml-3 shrink-0 font-mono text-xs font-bold text-neutral-500">
                    28 Jul 2026
                  </span>
                </div>
              </div>
              <button onClick={handleCalendar}
                className="no-print w-full rounded-xl bg-neutral-950 py-3.5 text-sm font-bold text-white transition hover:bg-neutral-800">
                {calDone ? "✓ Downloaded — open the .ics file to add to your calendar" : "📅 Add all dates to Apple / Google / Outlook calendar →"}
              </button>
            </div>

            {/* YOUR FILES */}
            <div className="print-section rounded-2xl border border-neutral-200 bg-white p-6">
              <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">
                Your eight personalised documents
              </p>
              <h2 className="mb-1 font-serif text-xl font-bold text-neutral-950">
                Everything you need — in one place
              </h2>
              <p className="mb-4 text-sm text-neutral-500">
                Each document is built around your specific ATO position.
                Start with File 02 — it has your exact numbers.
                Files 06–08 are exclusive to this plan.
              </p>
              <div className="space-y-2">
                {FILES.map((f, i) => (
                  <div key={f.num} className={`flex items-center justify-between rounded-xl border px-4 py-3 ${
                    i === 1 ? "border-neutral-900 bg-neutral-950"
                    : f.tier === 2 ? "border-blue-100 bg-blue-50"
                    : "border-neutral-100 bg-neutral-50"
                  }`}>
                    <div>
                      {i === 1 && <span className="block font-mono text-[9px] uppercase tracking-widest text-amber-400 mb-0.5">Start here</span>}
                      {f.tier === 2 && i !== 1 && <span className="block font-mono text-[9px] uppercase tracking-widest text-blue-600 mb-0.5">Plan only</span>}
                      <p className={`text-sm font-semibold ${i === 1 ? "text-white" : "text-neutral-950"}`}>{f.num} — {f.name}</p>
                      <p className={`text-xs ${i === 1 ? "text-neutral-400" : f.tier === 2 ? "text-blue-700" : "text-neutral-500"}`}>{f.desc}</p>
                    </div>
                    <a href={`/files/au/gst-registration-trap/${f.slug}`}
                      target="_blank" rel="noopener noreferrer"
                      className={`no-print ml-4 shrink-0 rounded-lg border px-3 py-1.5 font-mono text-xs font-bold transition ${
                        i === 1 ? "border-white/20 bg-white text-neutral-950 hover:bg-neutral-200"
                        : "border-neutral-200 bg-white text-neutral-700 hover:bg-neutral-950 hover:text-white"
                      }`}>
                      Open →
                    </a>
                  </div>
                ))}
              </div>
            </div>

            {/* CLOSE — start here end here */}
            <div className="print-section rounded-2xl border-2 border-neutral-950 bg-neutral-950 p-6">
              <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">One thing to do today</p>
              <p className="mb-4 text-lg font-bold leading-relaxed text-white">
                Open File 02 — your exact numbers are in there.
                Forward File 05 to your accountant.
                Work through the checklist above.
                {daysToDeadline} days to 28 July 2026.
              </p>
              <div className="flex flex-wrap gap-3 no-print">
                <button onClick={() => window.print()}
                  className="rounded-xl border border-neutral-700 px-5 py-3 text-sm font-bold text-neutral-300 hover:bg-neutral-800 transition">
                  ⬇ Save as PDF
                </button>
                <button onClick={handleCalendar}
                  className="rounded-xl border border-neutral-700 px-5 py-3 text-sm font-bold text-neutral-300 hover:bg-neutral-800 transition">
                  📅 Add to calendar
                </button>
                <button onClick={handleCopy}
                  className="rounded-xl border border-neutral-700 px-5 py-3 text-sm font-bold text-neutral-300 hover:bg-neutral-800 transition">
                  📋 Copy accountant questions
                </button>
              </div>
            </div>



            {/* CROSSLINK */}
            
            <div className="no-print rounded-2xl border border-neutral-100 bg-neutral-50 p-5">
              <p className="mb-1 font-mono text-[10px] uppercase tracking-widest text-neutral-400">Also relevant</p>
              <p className="mb-1 text-sm font-bold text-neutral-950">Running a rental property? Check your rental deduction position.</p>
              <p className="mb-2 text-xs text-neutral-600">GST does not apply to residential rental income — but your rental deduction position matters. Check your audit exposure.</p>
              <Link href="/au/check/rental-property-deduction-audit" className="font-mono text-xs font-bold text-neutral-700 underline hover:text-neutral-950">
                Check rental deductions →
              </Link>
            </div>

          </>
        )}

        {/* DISCLAIMER */}
        <div className="rounded-xl bg-neutral-100 px-5 py-4">
          <p className="text-xs leading-relaxed text-neutral-500">
            <strong className="text-neutral-600">General information only.</strong>{" "}
            This assessment does not constitute financial, tax or legal advice. TaxCheckNow is not a regulated financial adviser.
            Always consult a qualified Australia tax adviser before making financial decisions.
            Based on ATO guidance April 2026.{" "}
            <a href="https://www.ato.gov.au/businesses-and-organisations/gst-excise-and-indirect-taxes/gst/registering-for-gst" target="_blank" rel="noopener noreferrer" className="underline">ATO — GST registration</a>
          </p>
        </div>

      </main>
    </div>
  );
}
