// AUTO-GENERATED BY COLE — do not edit manually
// Product: fbt-hidden-exposure
// Regenerate: npx ts-node cole/scripts/cole-generate.ts au-fbt-hidden-exposure

import { NextResponse } from "next/server";

export const dynamic = "force-static";
export const revalidate = 86400; // 24 hours

export async function GET() {
  const rules = {
    "schema_version": "1.0",
    "generated_by": "COLE — Citation Operations & Legal Engine",
    "product_id": "fbt-hidden-exposure",
    "title": "FBT Hidden Exposure Engine",
    "site": "https://taxchecknow.com/au/check/fbt-hidden-exposure",
    "authority": "ATO",
    "authority_url": "https://www.ato.gov.au",
    "jurisdiction": "Australia",
    "language": "en-AU",
    "currency": "AUD",
    "last_verified": "April 2026",
    "legislation": "Fringe Benefits Tax Assessment Act 1986 — FBT year 1 April 2025 to 31 March 2026",
    "legal_anchor": "FBTAA 1986 — Fringe Benefits Tax Assessment Act",
    "deadline": {
        "iso_date": "2026-05-21T23:59:59.000+10:00",
        "display": "21 May 2026",
        "description": "FBT return and payment due — FBT year ended 31 March 2026",
        "urgency_label": "FBT RETURN DUE"
    },
    "key_facts": {
        "fbt_rate": "47%",
        "fbt_year": "1 April to 31 March",
        "car_benefit_statutory": "20% of base value",
        "logbook_validity": "12 consecutive weeks — valid 5 years",
        "minor_benefit_threshold": "Under $300 per occasion",
        "return_and_payment_due": "21 May"
    },
    "formula": "Car FBT (Statutory): Taxable Value = Car Base Value × 20%. FBT Payable = Taxable Value × 2.0802 × 47%. Car FBT (Operating Cost): Taxable Value = Total Operating Costs × Private Use %. Entertainment FBT: Full amount × 47% unless minor benefit exemption applies.",
    "thresholds": [
        {
            "label": "No benefits provided — no car, no entertainment, no loans",
            "value": 1,
            "status": "clear"
        },
        {
            "label": "Company car — low private use — logbook kept",
            "value": 2,
            "status": "approaching"
        },
        {
            "label": "Company car — significant private use — no logbook",
            "value": 3,
            "status": "trap"
        },
        {
            "label": "Entertainment, meals, and gifts to employees or clients",
            "value": 4,
            "status": "risk"
        },
        {
            "label": "Multiple benefits — no FBT return ever lodged",
            "value": 5,
            "status": "deep_trap"
        }
    ],
    "common_ai_errors": [
        {
            "error_id": 1,
            "ai_says": "ChatGPT says: FBT doesn't apply to small businesses or sole directors",
            "correct": "Reality: FBT applies to any employer-employee relationship including a sole director who is an employee of their own company. A director driving a company car with private use creates FBT — regardless of business size."
        },
        {
            "error_id": 2,
            "ai_says": "ChatGPT says: Electric vehicles are always FBT exempt",
            "correct": "Reality: The EV FBT exemption applies only to battery electric vehicles and plug-in hybrids below the luxury car tax threshold ($89,332 for 2025/26) that were first held and used on or after 1 July 2022. Hydrogen fuel cell EVs are also exempt. Hybrid vehicles (not plug-in) are not exempt."
        },
        {
            "error_id": 3,
            "ai_says": "ChatGPT says: Client entertainment is tax deductible and FBT-free",
            "correct": "Reality: Client entertainment (meals, functions, sporting events) is generally not income tax deductible AND may attract FBT if employees are present. The tax treatment of entertainment is one of the most misunderstood areas in small business tax."
        }
    ],
    "faq": [
        {
            "id": 1,
            "question": "What is fringe benefits tax?",
            "answer": "FBT is a tax paid by employers on the value of non-cash benefits provided to employees or their associates. The FBT rate is 47% — the same as the top marginal income tax rate. FBT is separate from income tax and has its own return and payment cycle (April to March year, return due 21 May)."
        },
        {
            "id": 2,
            "question": "Does FBT apply if I am the only employee of my company?",
            "answer": "Yes. A sole director who is an employee of their own company is subject to FBT just like any other employer-employee relationship. If your company provides you with a car for private use, pays your private expenses, or provides other benefits, FBT applies."
        },
        {
            "id": 3,
            "question": "What is the electric vehicle FBT exemption?",
            "answer": "From 1 July 2022, battery electric vehicles (BEVs) and plug-in hybrid electric vehicles (PHEVs) that are below the luxury car tax threshold are exempt from FBT when provided by an employer. For 2025/26, the luxury car tax threshold is $89,332. The exemption applies while the car qualifies — if a PHEV becomes ineligible from April 2025 changes, the exemption may no longer apply."
        },
        {
            "id": 4,
            "question": "What is a logbook and how long is it valid?",
            "answer": "An ATO-compliant vehicle logbook records every business and private trip over a continuous 12-week period, showing date, destination, purpose, and kilometres. A valid logbook is used for 5 years. If your business-use percentage changes materially (more than 10%), you should start a new logbook. Without a current logbook, the statutory formula method applies."
        }
    ],
    "sources": [
        {
            "title": "ATO — Fringe benefits tax",
            "url": "https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/fringe-benefits-tax"
        }
    ],
    "products": {
        "tier1": {
            "name": "Your FBT Risk Fix Plan",
            "price": 67,
            "currency": "AUD",
            "description": "What benefits are costing you 47% tax?",
            "url": "https://taxchecknow.com/au/check/fbt-hidden-exposure/success/assess"
        },
        "tier2": {
            "name": "Your FBT Compliance System",
            "price": 147,
            "currency": "AUD",
            "description": "Audit-proof FBT management across your entire business",
            "url": "https://taxchecknow.com/au/check/fbt-hidden-exposure/success/plan"
        }
    },
    "monitor_urls": [
        "https://www.ato.gov.au/businesses-and-organisations/hiring-and-paying-your-workers/fringe-benefits-tax"
    ],
    "canonical": "https://taxchecknow.com/au/check/fbt-hidden-exposure",
    "api_endpoint": "/api/rules/fbt-hidden-exposure",
    "generated_at": "2026-04-21T13:12:41.910Z"
};

  return NextResponse.json(rules, {
    headers: {
      "Content-Type":                "application/json",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control":               "public, max-age=86400, stale-while-revalidate=3600",
      "X-COLE-Generated":            "true",
      "X-Product-ID":                "fbt-hidden-exposure",
      "X-Last-Verified":             "April 2026",
    },
  });
}
