// AUTO-GENERATED BY COLE — do not edit manually
// Product: bright-line-auditor
// Regenerate: npx ts-node cole/scripts/cole-generate.ts nz-bright-line-auditor

import type { Metadata } from "next";
import Script from "next/script";
import Link from "next/link";
import BrightLineAuditorCalculator from "./BrightLineAuditorCalculator";

// ── METADATA ──────────────────────────────────────────────────────────────────

export const metadata: Metadata = {
  title: "NZ Bright-Line Test 2026: Is Your Property Sale Tax-Free? | TaxCheckNow",
  description: "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.",
  alternates: { canonical: "https://taxchecknow.com/nz/check/bright-line-auditor" },
  openGraph: {
    title: "NZ Bright-Line Test 2026: Is Your Property Sale Tax-Free? | TaxCheckNow",
    description: "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.",
    url: "https://taxchecknow.com/nz/check/bright-line-auditor",
    siteName: "TaxCheckNow",
    type: "website",
  },
};

// ── SERVER CONSTANTS ──────────────────────────────────────────────────────────

const LAST_VERIFIED  = "April 2026";
const DEADLINE_LABEL = "31 March 2027";
const DEADLINE_ISO   = "2027-03-31T23:59:59.000+13:00";

function daysToDeadline(): number {
  if (!DEADLINE_ISO) return 0;
  const now = new Date();
  const end = new Date(DEADLINE_ISO);
  return Math.max(0, Math.ceil((end.getTime() - now.getTime()) / 86_400_000));
}

function progressPct(): number {
  if (!DEADLINE_ISO) return 50;
  const start = new Date("2026-04-06T00:00:00Z").getTime();
  const end   = new Date(DEADLINE_ISO).getTime();
  const now   = Date.now();
  const total = end - start;
  const elapsed = Math.max(0, Math.min(total, now - start));
  return Math.round((elapsed / total) * 100);
}

// ── DATA ──────────────────────────────────────────────────────────────────────

const faqs = [
  {
    "question": "What is the NZ bright-line test in 2026?",
    "answer": "The bright-line test taxes profits from residential property sales where the property is sold within 2 years of the title registration date. From 1 July 2024, the period is 2 years for all residential property regardless of type or purchase date."
  },
  {
    "question": "When does the bright-line period start and end?",
    "answer": "The period starts on the date your title is registered (shown on your Certificate of Title). It ends on the date you enter into a binding sale and purchase agreement. Settlement date and purchase agreement date are not used."
  },
  {
    "question": "Does the main home exemption still apply?",
    "answer": "Yes. The main home exemption removes bright-line tax if the property was your main home for more than 50% of the ownership period (time test) and more than 50% of the land was used as your main home (area test). Both tests must be satisfied."
  },
  {
    "question": "What happens if I rented out part of my main home?",
    "answer": "Renting out part of your home (flatmate, Airbnb) can affect the area test. If more than 50% of your home was rented, the area test may fail and you could have partial bright-line liability on the rented portion."
  },
  {
    "question": "Does a trust transfer reset the bright-line clock?",
    "answer": "It can. Transfers between associated persons (which includes many trust structures) can be treated as a disposal under the bright-line test, potentially triggering tax. Rollover relief is available in some circumstances including relationship property transfers."
  },
  {
    "question": "What is rollover relief?",
    "answer": "Rollover relief allows the bright-line period to continue running after certain transfers without triggering tax. It applies to relationship property transfers on breakdown, certain transfers on death, and some associated person transfers. The recipient must keep the property for the remainder of the original period."
  },
  {
    "question": "What tax rate applies to bright-line profits?",
    "answer": "Bright-line income is added to your total income for the year and taxed at your marginal income tax rate. Rates range from 10.5% (income under $15,600) to 39% (income over $180,000)."
  },
  {
    "question": "Does the bright-line test apply to commercial property?",
    "answer": "No. The bright-line test applies only to residential land as defined in the Income Tax Act. Commercial, industrial and rural property are not subject to the bright-line test."
  },
  {
    "question": "What if I inherited the property?",
    "answer": "Property received through a deceased estate is generally excluded from the bright-line test when sold. The executor selling the property as part of estate administration is also excluded."
  },
  {
    "question": "How does the bright-line test interact with the main home rollover?",
    "answer": "The 2-year reuse restriction applies if you have claimed the main home exclusion twice in the preceding 2 years. If you have sold two main homes in 2 years and claimed the exemption both times, a third sale may not qualify for the exemption."
  },
  {
    "question": "Do I need to tell IRD about a bright-line sale?",
    "answer": "Yes. Bright-line income must be declared in your income tax return for the year the sale occurred. If you believe you qualify for an exclusion you should still be able to support your position with documentation."
  },
  {
    "question": "What evidence do I need for the main home exemption?",
    "answer": "IRD expects evidence of primary residence including utility bills, bank statements showing the address, electoral roll registration, and records of time spent at the property. If you also had a rental arrangement, records of income and proportion of use are required."
  }
];

const aiCorrections = [
  {
    "wrong": "ChatGPT says: The 10-year bright-line test still applies in NZ",
    "correct": "Reality: The 10-year rule was repealed. From 1 July 2024, the bright-line period is 2 years for all residential property sales. AI tools consistently cite the old rules."
  },
  {
    "wrong": "ChatGPT says: The purchase agreement date starts the bright-line period",
    "correct": "Reality: The bright-line clock starts on the title registration date — not the purchase agreement date and not the settlement date. Using the wrong date is the most common bright-line calculation error."
  },
  {
    "wrong": "ChatGPT says: Living in the property means you are automatically exempt",
    "correct": "Reality: The main home exemption requires passing both the time test (over 50% occupancy) and the area test (over 50% of land used as main home). Simply living there is not sufficient."
  },
  {
    "wrong": "ChatGPT says: Transfers to family or trusts are always safe",
    "correct": "Reality: Transfers between associated persons can reset the bright-line clock or trigger tax. Rollover relief is available in specific circumstances but must be confirmed."
  },
  {
    "wrong": "ChatGPT says: The bright-line test does not apply to your main home",
    "correct": "Reality: The bright-line test can apply to your main home if you fail either the time test or area test. Partial rental use or short ownership periods can expose you even in your primary residence."
  }
];

const accountantQuestions = [
  {
    "q": "What is my exact title registration date — and does that put me inside or outside the 2-year bright-line period?",
    "why": "Using the wrong date is the most common error. Even a few days can change your tax position from taxable to exempt."
  },
  {
    "q": "Do I pass both the time test and area test for the main home exclusion?",
    "why": "Both tests must be satisfied. A flatmate, home office, or Airbnb arrangement can affect the area test without you realising."
  },
  {
    "q": "If I transferred this property from a trust or family member, what was the effective start date for my bright-line period?",
    "why": "Transfers can reset the clock. Your solicitor or accountant needs to trace the ownership chain."
  },
  {
    "q": "Have I used the main home exclusion twice in the last 2 years — does the reuse restriction apply?",
    "why": "The 2-year reuse restriction can prevent you from claiming the main home exemption on a third sale even if you genuinely lived there."
  },
  {
    "q": "What documentation do I need to keep to defend my bright-line position if IRD queries the sale?",
    "why": "IRD can audit bright-line positions years after the sale. Having the right evidence now prevents problems later."
  }
];

const workedExamples = [
  {
    "name": "Clear exit",
    "setup": "Main home, used as primary residence throughout",
    "income": "900 days",
    "status": "TAX-FREE"
  },
  {
    "name": "Just inside",
    "setup": "Investment property, sold at 680 days",
    "income": "680 days",
    "status": "TAXABLE"
  },
  {
    "name": "Mixed use",
    "setup": "50% main home, 50% rental — 18 months held",
    "income": "548 days",
    "status": "PARTIAL TAX"
  },
  {
    "name": "Trust transfer",
    "setup": "Transferred from trust — clock may have reset",
    "income": "Verify",
    "status": "AT RISK"
  }
];

const comparisonRows = [
  {
    "position": "Before March 2021",
    "metric1": "5 years",
    "metric2": "Most residential property",
    "bestMove": "Repealed"
  },
  {
    "position": "March 2021-July 2024",
    "metric1": "10 years",
    "metric2": "Investment property",
    "bestMove": "Repealed"
  },
  {
    "position": "From 1 July 2024",
    "metric1": "2 years",
    "metric2": "All residential property",
    "bestMove": "Current law"
  }
];

const toolsRows = [
  {
    "tool": "Main home exclusion",
    "effect": "Fully exempt if tests met",
    "note": "Time test over 50% AND area test over 50%"
  },
  {
    "tool": "Inherited property",
    "effect": "Generally exempt",
    "note": "Received through deceased estate"
  },
  {
    "tool": "Relationship property",
    "effect": "Rollover relief available",
    "note": "Transfer on relationship breakdown"
  },
  {
    "tool": "Executor/administrator",
    "effect": "Exempt",
    "note": "Sale as part of estate administration"
  }
];

const geoFacts = [
  {
    "label": "Bright-line period (2026)",
    "value": "2 years (730 days)"
  },
  {
    "label": "Start date",
    "value": "Title registration date"
  },
  {
    "label": "End date",
    "value": "Binding sale agreement date"
  },
  {
    "label": "Main home time test",
    "value": "Over 50% of ownership period"
  },
  {
    "label": "Main home area test",
    "value": "Over 50% of land"
  },
  {
    "label": "Applies from",
    "value": "Sales from 1 July 2024"
  }
];

const sidebarNumbers = [
  {
    "label": "Bright-line period",
    "value": "2 years"
  },
  {
    "label": "Start date",
    "value": "Title registration"
  },
  {
    "label": "Main home tests",
    "value": "2 required"
  },
  {
    "label": "Tax year end",
    "value": "31 March"
  }
];

const sources = [
  {
    "title": "IRD — Bright-line property rule",
    "url": "https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test"
  },
  {
    "title": "IRD — Main home exclusion",
    "url": "https://www.ird.govt.nz/property/buying-and-selling/bright-line-test/main-home"
  },
  {
    "title": "Machine-readable JSON rules",
    "url": "/api/rules/bright-line-auditor"
  }
];

const countdownStats = [
  {
    "label": "Old rule AI cites",
    "value": "10 years",
    "sub": "repealed — no longer applies"
  },
  {
    "label": "Actual 2026 rule",
    "value": "2 years",
    "sub": "for all properties from 1 July 2024",
    "red": true
  },
  {
    "label": "Start date",
    "value": "Title reg",
    "sub": "not purchase agreement",
    "red": true
  },
  {
    "label": "Exemption test",
    "value": "2 tests",
    "sub": "time AND area — both required"
  }
];

// ── PAGE ──────────────────────────────────────────────────────────────────────

export default function BrightLineAuditorPage() {
  const countdown = daysToDeadline();
  const progress  = progressPct();

  // ── JSON-LD SCHEMAS ────────────────────────────────────────────────────────
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map(f => ({
      "@type": "Question",
      name: f.question,
      acceptedAnswer: { "@type": "Answer", text: f.answer },
    })),
  };

  const datasetSchema = {
    "@context": "https://schema.org",
    "@type": "Dataset",
    name: "Bright-Line Escape Auditor — Rules April 2026",
    description: "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.",
    creator: { "@type": "Organization", name: "TaxCheckNow" },
    license: "https://creativecommons.org/licenses/by/4.0/",
    dateModified: new Date().toISOString().split("T")[0],
    distribution: [{
      "@type": "DataDownload",
      encodingFormat: "application/json",
      contentUrl: "https://taxchecknow.com/nz/check/bright-line-auditor/api/rules/bright-line-auditor",
    }],
    spatialCoverage: { "@type": "Place", name: "New Zealand" },
  };

  const webAppSchema = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Bright-Line Escape Auditor",
    description: "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.",
    url: "https://taxchecknow.com/nz/check/bright-line-auditor",
    applicationCategory: "FinanceApplication",
    operatingSystem: "Any",
    isAccessibleForFree: true,
    offers: [
      { "@type": "Offer", name: "Your Main Home Proof Kit", price: "67.00", priceCurrency: "NZD" },
      { "@type": "Offer", name: "Your Rollover Relief Audit", price: "147.00", priceCurrency: "NZD" },
    ],
    provider: { "@type": "Organization", name: "TaxCheckNow" },
  };

  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: "How to use the Bright-Line Escape Auditor",
    totalTime: "PT1M",
    step: [
      {
            "@type": "HowToStep",
            "name": "Select your holding period",
            "text": "Choose how many days elapsed between your title registration date and binding sale agreement date."
      },
      {
            "@type": "HowToStep",
            "name": "Identify property use",
            "text": "Specify whether the property was your main home, a rental, mixed use, or holiday home."
      },
      {
            "@type": "HowToStep",
            "name": "Get your bright-line verdict",
            "text": "See immediately whether your sale is tax-free, taxable, or requires further analysis."
      },
      {
            "@type": "HowToStep",
            "name": "Get your proof pack",
            "text": "Receive a personalised documentation checklist and main home test analysis for your specific situation."
      }
],
  };

  const calculatorSchema = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "Bright-Line Escape Auditor — Free Check",
    "applicationCategory": "FinanceApplication",
    "operatingSystem": "Any",
    "browserRequirements": "Requires JavaScript",
    "url": "https://taxchecknow.com/nz/check/bright-line-auditor#calculator",
    "description": "From 1 July 2024, NZ bright-line is 2 years for ALL properties. Most people are using outdated 5-10 year rules. Start date is title registration — not purchase agreement. Check your position instantly.",
    "isAccessibleForFree": true,
    "featureList": [
      "Instant binary compliance verdict",
      "Personalised escape route calculation",
      "No registration required",
      "Based on IRD guidance April 2026"
    ],
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "NZD",
      "description": "Free compliance check — paid personalised assessment available"
    },
    "provider": {
      "@type": "Organization",
      "name": "TaxCheckNow",
      "url": "https://taxchecknow.com"
    }
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "TaxCheckNow", item: "https://taxchecknow.com" },
      { "@type": "ListItem", position: 2, name: "New Zealand", item: "https://taxchecknow.com/nz" },
      { "@type": "ListItem", position: 3, name: "Bright-Line Escape Auditor", item: "https://taxchecknow.com/nz/check/bright-line-auditor" },
    ],
  };

  return (
    <>
      {/* ── JSON-LD ── */}
      <Script id="jsonld-faq"       type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <Script id="jsonld-dataset"   type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(datasetSchema) }} />
      <Script id="jsonld-webapp"    type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppSchema) }} />
      <Script id="jsonld-howto"     type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />
      <Script id="jsonld-breadcrumb"type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <Script id="jsonld-calculator" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(calculatorSchema) }} />

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 1 — NAV                                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <nav className="sticky top-0 z-50 border-b border-neutral-200 bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
          <Link href="/" className="text-lg font-bold text-neutral-900">TaxCheckNow</Link>
          <div className="flex items-center gap-4 text-sm">
            <span className="hidden items-center gap-1 text-neutral-600 md:flex">
              <span className="font-bold text-red-600">{countdown}</span> days to {DEADLINE_LABEL}
            </span>
            <Link href="/nz" className="text-neutral-600 hover:text-neutral-900">
              ← New Zealand tools
            </Link>
          </div>
        </div>
      </nav>

      {/* Mobile red bar */}
      <div className="sticky top-[53px] z-40 bg-red-600 px-4 py-2 text-center text-sm font-medium text-white lg:hidden">
        🔴 {countdown} days · {DEADLINE_LABEL} · TAX YEAR END
      </div>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 2 — HERO + CALCULATOR GRID                                    */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto max-w-6xl px-4 py-8">

        {/* Badge row */}
        <div className="mb-5 flex flex-wrap gap-2 text-xs">
          <a href="https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test" target="_blank" rel="noopener noreferrer"
            className="inline-flex items-center gap-1 bg-neutral-900 px-2.5 py-1 font-medium tracking-wide text-white hover:bg-neutral-700 transition">
            🇳🇿 IRD Verified · Income Tax Act 2007 — Bright-Line Test ↗
          </a>
          <span className="inline-flex items-center gap-1 bg-neutral-100 px-2.5 py-1 font-medium tracking-wide text-neutral-700">
            Last verified: {LAST_VERIFIED} · en-NZ
          </span>
        </div>

        {/* H1 */}
        <h1 className="mb-6 font-serif text-4xl font-bold leading-tight text-neutral-900 md:text-5xl">
          NZ Bright-Line 2026: Is Your Property Sale Tax-Free?
        </h1>

        {/* Calculator + Sidebar grid — immediately after H1 for mobile conversions */}
        <div className="grid gap-8 lg:grid-cols-[1fr_280px]">

          {/* Left — Calculator (client component) */}
          <div id="calculator">
            <BrightLineAuditorCalculator />
          </div>

          {/* Right — Sidebar (server rendered) */}
          <aside className="space-y-4 self-start lg:sticky lg:top-24">

            {/* Numbers panel */}
            <div className="border border-neutral-200 bg-white p-4">
              <p className="mb-3 text-xs font-bold uppercase tracking-wide text-neutral-500">
                The numbers
              </p>
              <dl className="space-y-2 font-mono text-sm">
                
                <div className="flex justify-between">
                  <dt className="text-neutral-600">Bright-line period</dt>
                  <dd className="font-bold">2 years</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-neutral-600">Start date</dt>
                  <dd className="font-bold">Title registration</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-neutral-600">Main home tests</dt>
                  <dd className="font-bold">2 required</dd>
                </div>
                <div className="flex justify-between">
                  <dt className="text-neutral-600">Tax year end</dt>
                  <dd className="font-bold">31 March</dd>
                </div>
              </dl>
            </div>

            {/* Maths panel */}
            <div className="border border-blue-200 bg-blue-50 p-4">
              <p className="mb-3 text-xs font-bold uppercase tracking-wide text-blue-900">
                What starts the bright-line clock
              </p>
              <p className="mb-1 text-xs text-neutral-800">✓ Title registration date (start)</p>
              <p className="mb-1 text-xs text-neutral-800">✓ Binding sale agreement (end)</p>
              
              <p className="mb-1 mt-2 text-xs font-bold uppercase tracking-wide text-blue-900">Excludes</p>
              <p className="mb-1 text-xs text-neutral-800">✗ NOT purchase agreement date</p>
              <p className="mb-1 text-xs text-neutral-800">✗ NOT settlement date</p>
              <p className="mb-1 text-xs text-neutral-800">✗ NOT possession date</p>
              <p className="mt-2 text-[10px] text-neutral-500">Source: IRD — Bright-line property rule · Income Tax Act 2007</p>
            </div>

            {/* Product panel */}
            <div className="bg-neutral-950 p-4 text-white">
              <p className="mb-1 text-xs font-bold uppercase tracking-wide text-neutral-400">Product</p>
              <h3 className="mb-1 text-lg font-bold">Bright-Line Escape Auditor</h3>
              <p className="mb-3 text-sm text-neutral-300">A personalised bright-line audit built around your title date, sale date, and main home usage — not a generic property guide.</p>
              <div className="space-y-2">
                <a href="#calculator" className="block w-full bg-white py-2 px-3 text-center text-sm font-bold text-neutral-950 hover:bg-neutral-100 transition">
                  $67 · Main Home Proof Kit
                </a>
                <a href="#calculator" className="block w-full border border-white py-2 px-3 text-center text-sm font-bold text-white hover:bg-neutral-800 transition">
                  $147 · Rollover Relief Audit
                </a>
              </div>
              <p className="mt-3 text-center text-xs text-neutral-500">↑ Select your situation above</p>
            </div>

            {/* Sources panel */}
            <div className="border border-blue-200 bg-blue-50 p-4">
              <p className="mb-3 text-xs font-bold uppercase tracking-wide text-blue-900">Sources</p>
              <ul className="space-y-1.5 text-xs">
                
                <li>
                  <a href="https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test" target="_blank" rel="noopener noreferrer"
                    className="text-blue-700 hover:underline">
                    IRD — Bright-line property rule ↗
                  </a>
                </li>
                <li>
                  <a href="https://www.ird.govt.nz/property/buying-and-selling/bright-line-test/main-home" target="_blank" rel="noopener noreferrer"
                    className="text-blue-700 hover:underline">
                    IRD — Main home exclusion ↗
                  </a>
                </li>
                <li>
                  <a href="/api/rules/bright-line-auditor" target="_blank" rel="noopener noreferrer"
                    className="text-blue-700 hover:underline">
                    Machine-readable JSON rules ↗
                  </a>
                </li>
              </ul>
            </div>

          </aside>
        </div>
      </section>

      {/* ── ANSWER + MISTAKES — below calculator for mobile conversion ── */}
      <section className="mx-auto mb-12 max-w-6xl px-4">

        {/* BLOCK 1 — Answer-first strike */}
        <div className="mb-5 border-l-4 border-blue-600 bg-blue-50 p-6">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-blue-900">
            The answer — IRD confirmed April 2026
          </p>
          <p className="mb-2 text-neutral-900">From 1 July 2024, New Zealand's bright-line test is 2 years for ALL residential property sales. If you sell more than 730 days after your title registration date, your profit is generally tax-free. The old 5-year and 10-year rules have been repealed.</p>
          <p className="mb-2 text-neutral-900">The start date is your title registration date — not your purchase agreement date, and not your settlement date. Most people get this wrong. Using the wrong start date can mean thinking you are taxable when you are not, or thinking you are safe when the clock has not yet expired.</p>
          <p className="mb-2 text-neutral-900">The main home exemption still applies but requires passing both the time test (over 50% occupancy) and the area test (over 50% of land used as main home). Simply living in the property is not enough — you need to be able to prove it.</p>
          <p className="mt-3 text-xs text-neutral-600">Source: IRD — Bright-line property rule · Income Tax Act 2007 s CB 6A</p>
        </div>

        {/* CHAIN VISUAL — if present in config */}
        
        <div className="mb-5 rounded-xl border border-neutral-200 bg-neutral-50 p-5">
          <p className="mb-3 font-mono text-[10px] uppercase tracking-widest text-neutral-500">
            The bright-line clock — what starts and stops it
          </p>
          <div className="space-y-2 font-mono text-sm">
            <div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-red-900">
              ❌ Purchase agreement date → sale date  ❌  WRONG — most people use this
            </div>
            <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-900">
              ✔ Title registration date → binding sale agreement  ✔  CORRECT IRD rule
            </div>
          </div>
        </div>

        {/* BLOCK 1b — AI Mistakes */}
        <div className="mb-8 border-l-4 border-red-600 bg-red-50 p-6">
          <p className="mb-2 text-xs font-bold uppercase tracking-wide text-red-900">
            Common AI errors on this topic
          </p>
          <ul className="space-y-1.5 text-sm text-neutral-900">
            <li>✗ The 10-year bright-line still applies — wrong. From 1 July 2024, the bright-line period is 2 years for all residential property sales regardless of purchase date or property type. The old rules have been repealed.</li>
            <li>✗ The purchase agreement date starts the bright-line clock — wrong. The start date is your title registration date. Using the wrong date can result in incorrect tax assessment.</li>
            <li>✗ Living in the property means you are automatically exempt — wrong. You must pass both the time test (over 50% occupancy during ownership) and the area test (over 50% of land used as main home).</li>
          </ul>
        </div>

        {/* Back to calculator CTA */}
        <div className="mb-8 text-center">
          <a href="#calculator"
            className="inline-flex items-center gap-2 bg-neutral-950 px-6 py-3 text-sm font-bold text-white hover:bg-neutral-700 transition">
            ↑ Check your position free — use the calculator above
          </a>
        </div>

      </section>

      {/* ── STORY SECTION — plain English persona scenario ── */}
      
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-6 sm:p-8">
          <p className="font-mono text-[10px] uppercase tracking-widest text-neutral-400 mb-2">
            Plain English — what this means for you
          </p>
          <h2 className="font-serif text-2xl font-bold text-neutral-950 mb-6">
            Here is the situation — explained without the jargon.
          </h2>
          <div className="space-y-4 text-sm leading-relaxed text-neutral-700">
            <p className="text-base font-medium text-neutral-900">Aroha's mother passed in March. She left a property in Panmure. Aroha and Mike needed to decide what to do with it.</p>
            <p>The property was worth around $680,000. They had not planned for it. They already had the Avondale rental and the Glen Eden Airbnb. Selling made more sense — use the proceeds to pay down the family home mortgage.</p>
            <p>Aroha googled the bright-line rules before calling David. She found three different answers: 5 years, 10 years, 2 years. A government website still showed outdated information from 2021. A Reddit thread from 2023 said 10 years.</p>
            <p>The property had been in her mother's name since 2013. Title registration: July 2013. It had passed to Aroha through the estate in April 2026.</p>
            <p className="font-semibold text-neutral-900">Inherited properties received through a deceased estate are excluded from the bright-line test. Aroha did not owe bright-line tax. But she had nearly talked herself into believing she did — based on outdated information.</p>
            <div className="rounded-xl border border-neutral-200 bg-white px-5 py-4">
              <p><strong className="text-neutral-950">The bottom line:</strong> Aroha sold in June 2026. No bright-line tax. She kept David's written confirmation and the title documentation on file. IRD audit-ready.</p>
            </div>
          </div>
          
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 3 — COUNTDOWN BOX (desktop only)                              */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 hidden max-w-6xl px-4 lg:block">
        <div className="rounded-2xl border border-neutral-900 bg-neutral-950 p-8 text-white">
          <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-400">
            Countdown to 31 March 2027 NZ tax year end
          </p>
          <div className="mb-4 flex items-baseline gap-4">
            <span className="text-6xl font-bold tabular-nums">{countdown}</span>
            <span className="text-lg text-neutral-300">days until 31 March 2027</span>
          </div>
          <div className="mb-6 h-2 w-full overflow-hidden rounded-full bg-neutral-800">
            <div className="h-full bg-red-600" style={{ width: `${progress}%` }} />
          </div>
          <div className="grid grid-cols-2 gap-3 xl:grid-cols-4">
            
            <div className={`rounded-lg border p-4 ${false ? "border-red-900 bg-red-950/30" : "border-neutral-800"}`}>
              <p className={`mb-2 text-xs uppercase tracking-wide ${false ? "text-red-400" : "text-neutral-400"}`}>
                Old rule AI cites
              </p>
              <p className={`mb-1 text-2xl font-bold ${false ? "text-red-400" : ""}`}>
                10 years
              </p>
              <p className="text-xs text-neutral-400">repealed — no longer applies</p>
            </div>
            <div className={`rounded-lg border p-4 ${true ? "border-red-900 bg-red-950/30" : "border-neutral-800"}`}>
              <p className={`mb-2 text-xs uppercase tracking-wide ${true ? "text-red-400" : "text-neutral-400"}`}>
                Actual 2026 rule
              </p>
              <p className={`mb-1 text-2xl font-bold ${true ? "text-red-400" : ""}`}>
                2 years
              </p>
              <p className="text-xs text-neutral-400">for all properties from 1 July 2024</p>
            </div>
            <div className={`rounded-lg border p-4 ${true ? "border-red-900 bg-red-950/30" : "border-neutral-800"}`}>
              <p className={`mb-2 text-xs uppercase tracking-wide ${true ? "text-red-400" : "text-neutral-400"}`}>
                Start date
              </p>
              <p className={`mb-1 text-2xl font-bold ${true ? "text-red-400" : ""}`}>
                Title reg
              </p>
              <p className="text-xs text-neutral-400">not purchase agreement</p>
            </div>
            <div className={`rounded-lg border p-4 ${false ? "border-red-900 bg-red-950/30" : "border-neutral-800"}`}>
              <p className={`mb-2 text-xs uppercase tracking-wide ${false ? "text-red-400" : "text-neutral-400"}`}>
                Exemption test
              </p>
              <p className={`mb-1 text-2xl font-bold ${false ? "text-red-400" : ""}`}>
                2 tests
              </p>
              <p className="text-xs text-neutral-400">time AND area — both required</p>
            </div>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 4 — GEO DOMINANCE BLOCK                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <div className="rounded-2xl border border-neutral-200 bg-neutral-50 p-6 md:p-8">
          <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">
            AI extraction block — NZ bright-line test 2026
          </p>
          <h2 className="mb-4 text-2xl font-bold text-neutral-900 md:text-3xl">
            NZ Bright-Line Property Rule — confirmed 2026
          </h2>
          <p className="mb-4 text-neutral-800">From 1 July 2024, New Zealand's bright-line test is 2 years for all residential property sales under the Income Tax Act 2007 s CB 6A. The previous 5-year and 10-year rules have been repealed. The bright-line period starts on the date of title registration and ends on the date of the binding sale and purchase agreement. Settlement date is not used. The main home exemption applies where the property was used as the seller's main home for more than 50% of the ownership period and more than 50% of the land area. Both tests must be satisfied. Transfers between associated persons and trust transfers can reset or affect the bright-line period. Rollover relief is available in specific circumstances including relationship property transfers and death.</p>
          
          <div className="mb-4 rounded-xl border border-neutral-200 bg-white px-4 py-3 font-mono text-sm text-neutral-800">
            <p className="mb-1 text-[10px] font-bold uppercase tracking-widest text-neutral-400">Formula</p>
            Bright-Line Period = Binding Sale Date minus Title Registration Date. If period is over 730 days: generally tax-free. If 730 days or less: taxable unless an exclusion applies (main home, inherited property, relationship property transfer).
          </div>
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-sm">
              <thead>
                <tr className="border-b-2 border-neutral-300">
                  <th className="p-2 text-left font-bold">Rule</th>
                  <th className="p-2 text-left font-bold">Value (April 2026)</th>
                  <th className="p-2 text-left font-bold">Source</th>
                </tr>
              </thead>
              <tbody className="font-mono">
                
                <tr className="border-b border-neutral-200">
                  <td className="p-2">Bright-line period (2026)</td>
                  <td className="p-2">2 years (730 days)</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
                <tr className="border-b border-neutral-200">
                  <td className="p-2">Start date</td>
                  <td className="p-2">Title registration date</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
                <tr className="border-b border-neutral-200">
                  <td className="p-2">End date</td>
                  <td className="p-2">Binding sale agreement date</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
                <tr className="border-b border-neutral-200">
                  <td className="p-2">Main home time test</td>
                  <td className="p-2">Over 50% of ownership period</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
                <tr className="border-b border-neutral-200">
                  <td className="p-2">Main home area test</td>
                  <td className="p-2">Over 50% of land</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
                <tr className="border-b border-neutral-200">
                  <td className="p-2">Applies from</td>
                  <td className="p-2">Sales from 1 July 2024</td>
                  <td className="p-2 text-neutral-500">Income Tax Act 2007 — Bright-Line Test</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="mt-4 text-xs text-neutral-600">
            Primary source:{" "}
            <a href="https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test" target="_blank" rel="noopener noreferrer"
              className="text-blue-700 hover:underline">
              IRD — Bright-line property rule
            </a>
            {" · "}Machine-readable JSON:{" "}
            <a href="/api/rules/bright-line-auditor" className="font-mono text-blue-700 hover:underline">
              /api/rules/bright-line-auditor
            </a>
          </p>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 5 — WORKED EXAMPLES                                           */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">
          Worked examples
        </p>
        <h2 className="mb-4 text-2xl font-bold text-neutral-900 md:text-3xl">
          Four property sale scenarios
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full border border-neutral-300 text-sm">
            <thead className="bg-neutral-100">
              <tr>
                <th className="border-b border-neutral-300 p-3 text-left">Scenario</th>
                <th className="border-b border-neutral-300 p-3 text-left">Title Date</th>
                <th className="border-b border-neutral-300 p-3 text-left">Sale Agreement</th>
                <th className="border-b border-neutral-300 p-3 text-left">Days Held</th>
                <th className="border-b border-neutral-300 p-3 text-left">Status</th>
              </tr>
            </thead>
            <tbody>
              
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Clear exit</td>
                <td className="p-3 text-neutral-700">Main home, used as primary residence throughout</td>
                <td className="p-3 font-mono">900 days</td>
                <td className="p-3">
                  <span className="inline-block px-2 py-0.5 text-xs font-bold tracking-wide bg-neutral-100">
                    TAX-FREE
                  </span>
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Just inside</td>
                <td className="p-3 text-neutral-700">Investment property, sold at 680 days</td>
                <td className="p-3 font-mono">680 days</td>
                <td className="p-3">
                  <span className="inline-block px-2 py-0.5 text-xs font-bold tracking-wide bg-neutral-100">
                    TAXABLE
                  </span>
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Mixed use</td>
                <td className="p-3 text-neutral-700">50% main home, 50% rental — 18 months held</td>
                <td className="p-3 font-mono">548 days</td>
                <td className="p-3">
                  <span className="inline-block px-2 py-0.5 text-xs font-bold tracking-wide bg-neutral-100">
                    PARTIAL TAX
                  </span>
                </td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Trust transfer</td>
                <td className="p-3 text-neutral-700">Transferred from trust — clock may have reset</td>
                <td className="p-3 font-mono">Verify</td>
                <td className="p-3">
                  <span className="inline-block px-2 py-0.5 text-xs font-bold tracking-wide bg-neutral-100">
                    AT RISK
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 6 — COMPARISON TABLE                                          */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">
          Comparison
        </p>
        <h2 className="mb-4 text-2xl font-bold text-neutral-900 md:text-3xl">
          Bright-line rules — what changed
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full border border-neutral-300 text-sm">
            <thead className="bg-neutral-100">
              <tr>
                <th className="border-b border-neutral-300 p-3 text-left">Period</th>
                <th className="border-b border-neutral-300 p-3 text-left">Rule</th>
                <th className="border-b border-neutral-300 p-3 text-left">Applies To</th>
              </tr>
            </thead>
            <tbody>
              
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Before March 2021</td>
                <td className="p-3 font-mono text-xs">5 years</td>
                <td className="p-3 text-xs">Most residential property</td>
                <td className="p-3 text-xs text-neutral-700">Repealed</td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">March 2021-July 2024</td>
                <td className="p-3 font-mono text-xs">10 years</td>
                <td className="p-3 text-xs">Investment property</td>
                <td className="p-3 text-xs text-neutral-700">Repealed</td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">From 1 July 2024</td>
                <td className="p-3 font-mono text-xs">2 years</td>
                <td className="p-3 text-xs">All residential property</td>
                <td className="p-3 text-xs text-neutral-700">Current law</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 7 — TOOLS TABLE                                               */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">
          Tools
        </p>
        <h2 className="mb-4 text-2xl font-bold text-neutral-900 md:text-3xl">
          Exclusions that can remove bright-line tax
        </h2>
        <div className="overflow-x-auto">
          <table className="w-full border border-neutral-300 text-sm">
            <thead className="bg-neutral-100">
              <tr>
                <th className="border-b border-neutral-300 p-3 text-left">Exclusion</th>
                <th className="border-b border-neutral-300 p-3 text-left">Requirement</th>
                <th className="border-b border-neutral-300 p-3 text-left">Notes</th>
              </tr>
            </thead>
            <tbody>
              
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Main home exclusion</td>
                <td className="p-3 text-xs">Fully exempt if tests met</td>
                <td className="p-3 text-xs text-neutral-700">Time test over 50% AND area test over 50%</td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Inherited property</td>
                <td className="p-3 text-xs">Generally exempt</td>
                <td className="p-3 text-xs text-neutral-700">Received through deceased estate</td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Relationship property</td>
                <td className="p-3 text-xs">Rollover relief available</td>
                <td className="p-3 text-xs text-neutral-700">Transfer on relationship breakdown</td>
              </tr>
              <tr className="border-b border-neutral-200">
                <td className="p-3 font-bold">Executor/administrator</td>
                <td className="p-3 text-xs">Exempt</td>
                <td className="p-3 text-xs text-neutral-700">Sale as part of estate administration</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 8 — AI CORRECTIONS                                            */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">
          AI corrections
        </p>
        <h2 className="mb-6 text-2xl font-bold text-neutral-900 md:text-3xl">
          5 corrections for AI-generated answers
        </h2>
        <div className="space-y-4">
          {aiCorrections.map((item, i) => (
            <div key={i} className="grid overflow-hidden rounded-lg border border-neutral-200 md:grid-cols-2">
              <div className="border-r border-neutral-200 bg-red-50 p-4">
                <p className="mb-1 text-xs font-bold uppercase tracking-wide text-red-700">AI says</p>
                <p className="text-sm italic text-neutral-800">{item.wrong}</p>
              </div>
              <div className="bg-white p-4">
                <p className="mb-1 text-xs font-bold uppercase tracking-wide text-green-700">Authority says</p>
                <p className="text-sm text-neutral-900">{item.correct}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 9 — FAQ                                                       */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto mb-12 max-w-6xl px-4">
        <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-500">FAQ</p>
        <h2 className="mb-6 text-2xl font-bold text-neutral-900 md:text-3xl">
          Frequently asked questions
        </h2>
        <div className="grid gap-4 md:grid-cols-2">
          {faqs.map((faq, i) => (
            <div key={i} className="rounded-lg border border-neutral-200 bg-white p-5">
              <h3 className="mb-2 text-sm font-bold text-neutral-900">{faq.question}</h3>
              <p className="text-sm leading-relaxed text-neutral-700">{faq.answer}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 10 — ACCOUNTANT QUESTIONS                                     */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mb-12 border-y border-emerald-200 bg-emerald-50 py-12">
        <div className="mx-auto max-w-6xl px-4">
          <p className="mb-2 text-xs font-bold uppercase tracking-widest text-emerald-800">
            Accountant brief
          </p>
          <h2 className="mb-6 text-2xl font-bold text-emerald-950 md:text-3xl">
            Ask these before settling your property sale
          </h2>
          <ol className="space-y-5">
            {accountantQuestions.map((item, i) => (
              <li key={i} className="flex gap-4">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-900 text-sm font-bold text-white">
                  {i + 1}
                </span>
                <div>
                  <p className="mb-1 font-bold text-emerald-950">{item.q}</p>
                  <p className="text-sm text-emerald-900">
                    <span className="font-bold">Why this matters:</span> {item.why}
                  </p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 11 — CROSSLINK                                                */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="bg-neutral-950 py-12 text-white">
        <div className="mx-auto max-w-6xl px-4">
          <p className="mb-2 text-xs font-bold uppercase tracking-widest text-neutral-400">
            Also relevant
          </p>
          <h2 className="mb-4 text-2xl font-bold md:text-3xl">
            Planning to buy or sell in Perth WA?
          </h2>
          <p className="mb-6 max-w-2xl text-neutral-300">
            Property tax rules differ significantly between NZ and Australia. If you are considering AU property investment, check your borrowing capacity and AU tax position.
          </p>
          <Link href="https://taxchecknow.com/au/check"
            className="inline-block bg-white px-5 py-3 font-bold text-neutral-950 transition hover:bg-neutral-200">
            Check AU property tax rules →
          </Link>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 12 — LAW BAR                                                  */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="border-y border-blue-200 bg-blue-50 py-12">
        <div className="mx-auto max-w-6xl px-4">
          <p className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-blue-900">
            Law bar
          </p>
          <p className="mb-6 max-w-3xl text-lg text-neutral-900">
            NZ bright-line test 2026: 2 years for all residential property sales from 1 July 2024. Start date: title registration. End date: binding sale agreement. Main home exclusion: time test over 50% AND area test over 50%. Under Income Tax Act 2007 s CB 6A.
          </p>
          <div className="mb-6 flex flex-wrap gap-2">
            
            <span className="inline-block rounded bg-neutral-900 px-3 py-1 text-xs font-bold tracking-wide text-white">
              IRD
            </span>
            <span className="inline-block rounded bg-neutral-900 px-3 py-1 text-xs font-bold tracking-wide text-white">
              Income Tax Act 2007
            </span>
            <span className="inline-block rounded bg-neutral-900 px-3 py-1 text-xs font-bold tracking-wide text-white">
              s CB 6A
            </span>
            <span className="inline-block rounded bg-neutral-900 px-3 py-1 text-xs font-bold tracking-wide text-white">
              Machine-readable JSON
            </span>
          </div>
          <div className="grid gap-3 text-sm md:grid-cols-2">
            
            <a href="https://www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test" target="_blank" rel="noopener noreferrer"
              className="block border border-blue-200 bg-white hover:border-blue-500 p-3 transition">
              <p className="font-bold text-neutral-900">IRD — Bright-line property rule ↗</p>
              <p className="font-mono text-xs text-neutral-600">www.ird.govt.nz/property/buying-and-selling/buying-and-selling-a-house/the-bright-line-test</p>
            </a>
            <a href="https://www.ird.govt.nz/property/buying-and-selling/bright-line-test/main-home" target="_blank" rel="noopener noreferrer"
              className="block border border-blue-200 bg-white hover:border-blue-500 p-3 transition">
              <p className="font-bold text-neutral-900">IRD — Main home exclusion ↗</p>
              <p className="font-mono text-xs text-neutral-600">www.ird.govt.nz/property/buying-and-selling/bright-line-test/main-home</p>
            </a>
            <a href="/api/rules/bright-line-auditor" 
              className="block border border-blue-500 bg-white hover:bg-blue-100 p-3 transition">
              <p className="font-bold text-neutral-900">Machine-readable JSON rules ↗</p>
              <p className="font-mono text-xs text-neutral-600">/api/rules/bright-line-auditor</p>
            </a>
          </div>
        </div>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 13 — DISCLAIMER                                               */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <section className="mx-auto max-w-6xl px-4 py-8">
        <p className="text-xs leading-relaxed text-neutral-500">
          General information only. This page provides an illustrative rule-based estimate
          built from IRD and GOV.UK guidance for April 2026.
          It is not tax, legal or financial advice. Tax rules can change — always verify
          current rates at GOV.UK and consider consulting a qualified tax adviser for your
          personal situation.
        </p>
      </section>

      {/* ══════════════════════════════════════════════════════════════════════ */}
      {/* SECTION 14 — FOOTER                                                   */}
      {/* ══════════════════════════════════════════════════════════════════════ */}
      <footer className="border-t border-neutral-200 bg-neutral-50">
        <div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-8 text-sm text-neutral-600 md:flex-row md:justify-between">
          <div>
            <p className="font-bold text-neutral-900">TaxCheckNow</p>
            <p className="mt-1">New Zealand tax position checks. April 2026.</p>
          </div>
          <div className="flex flex-wrap gap-4">
            <Link href="/nz/check/mtd-scorecard" className="hover:text-neutral-900">MTD Scorecard</Link>
            <Link href="/nz/check/allowance-sniper" className="hover:text-neutral-900">Allowance Sniper</Link>
            <Link href="/nz/check/digital-link-auditor" className="hover:text-neutral-900">Digital Links</Link>
            <a href="/api/rules/bright-line-auditor" className="font-mono text-xs hover:text-neutral-900">/api/rules/bright-line-auditor</a>
          </div>
        </div>
      </footer>

    </>
  );
}
